export const leaders = [
  { id: 'faisal-orakzai', name: 'Faisal Orakzai', role: 'Founder & Chairman', image: '/leadership/faisal-orakzai.webp', imageAlt: 'Faisal Orakzai, Founder and Chairman of Shamim Forever', intro: 'Faisal Orakzai is the Founder and Chairman of Shamim Forever.', bio: ['His vision for the House is rooted in the belief that luxury should represent more than appearance. It should carry identity, meaning, craftsmanship, and a legacy designed to endure.', 'As an entrepreneur, technology-focused systems architect, researcher, and author, Faisal brings a multidisciplinary perspective to the development of Shamim Forever. His broader work explores technology, digital infrastructure, blockchain, artificial intelligence, and emerging systems.', 'At Shamim Forever, he leads the long-term strategic vision of the House, guiding its identity, direction, innovation, and future growth. His approach combines the traditions of luxury with modern systems that can support authenticity, provenance, digital identity, and the preservation of legacy.', 'His role is not merely to build a luxury brand, but to establish a House designed around permanence.'], quote: 'Luxury may be created in a moment, but legacy is built across generations.' },
  { id: 'asma-orakzai', name: 'Dr Asma Orakzai', role: 'Chief Executive Officer', image: '/leadership/asma-orakzai.webp', imageAlt: 'Dr Asma Orakzai, Chief Executive Officer of Shamim Forever', intro: 'Dr Asma Orakzai serves as the Chief Executive Officer of Shamim Forever, contributing to the executive direction and development of the House.', bio: ['Her role focuses on organizational leadership, strategic coordination, operational development, and supporting the long-term growth of Shamim Forever.', 'As CEO, she works to translate the vision of the House into structured execution, helping ensure that its ambitions are supported by thoughtful planning, consistency, and sustainable development.', "Her leadership represents an important part of Shamim Forever's commitment to building a House with both creative ambition and operational discipline."], quote: 'A lasting House is built not only through vision, but through the discipline to bring that vision to life.' },
  { id: 'laiba-faisal-orakzai', name: 'Dr Laiba Faisal Orakzai', role: 'Director', image: '/leadership/laiba-faisal-orakzai.webp', imageAlt: 'Dr Laiba Faisal Orakzai, Director of Shamim Forever', intro: 'Dr Laiba Faisal Orakzai serves as a Director of Shamim Forever, contributing to the strategic development and long-term direction of the House.', bio: ['Her role supports the broader vision of Shamim Forever through leadership, strategic perspective, and participation in the evolution of the brand.', "As the House develops, her involvement reflects Shamim Forever's commitment to building a leadership structure capable of supporting growth while preserving the identity, standards, and long-term philosophy of the brand."], quote: 'Legacy requires continuity. What we build today should carry meaning for those who come after us.' },
]

export const principles = [
  ['Legacy', 'We think beyond the immediate moment and build with long-term purpose.'],
  ['Craft', 'We believe that quality, attention, and discipline are essential to meaningful luxury.'],
  ['Identity', 'Every creation should carry a clear sense of origin, character, and belonging.'],
  ['Innovation', 'We explore new ideas and emerging technologies without losing respect for enduring craftsmanship.'],
  ['Stewardship', 'A luxury house must protect its standards, heritage, and identity for the future.'],
]
