import type { Metadata } from "next"
    import Link from "next/link"

    export const metadata: Metadata = {
    title: "Investor Relations | Capital in Service of Legacy",
    description: "Institutional information about Shamim Forever's long-term value thesis, capital philosophy, governance, risk disclosure, strategic roadmap, and investor communication principles.",
    keywords: ["Shamim Forever investor relations", "long-term value", "capital stewardship", "luxury house governance", "strategic investors"],
    alternates: { canonical: "https://www.shamimforever.com/investor-relations" },
    openGraph: { title: "Investor Relations | Capital in Service of Legacy | Shamim Forever", description: "Building long-term value beyond the present through disciplined capital, responsible governance, and enduring institutional direction.", url: "https://www.shamimforever.com/investor-relations", type: "website" },
    }

    type Status = "ESTABLISHED" | "CURRENT" | "IN DEVELOPMENT" | "PLANNED" | "SUBJECT TO APPROVAL" | "FORWARD-LOOKING"

    const valueDimensions = [
    ["I", "Brand Equity", "Building a distinctive and enduring luxury identity that can earn memory beyond individual transactions."],
    ["II", "Intellectual Capital", "Developing proprietary knowledge, design systems, research, creative frameworks, and institutional documentation."],
    ["III", "Craft & Cultural Value", "Supporting craftsmanship, heritage, authenticity, and long-term cultural relevance."],
    ["IV", "Infrastructure", "Developing systems, technology, and operational capabilities capable of supporting long-term growth."],
    ["V", "Strategic Expansion", "Exploring carefully selected categories, markets, partnerships, and opportunities when aligned with capacity."],
    ["VI", "Legacy Value", "Creating assets, systems, and institutions designed to remain relevant beyond short-term market cycles."],
    ]
    const allocationPriorities = [
    ["01", "Preserve the foundation", "Protect core integrity, infrastructure, intellectual property, and operational stability."],
    ["02", "Build capability", "Invest in systems, talent, technology, and expertise that increase institutional capacity."],
    ["03", "Create strategic assets", "Develop assets capable of contributing long-term value rather than disposable growth."],
    ["04", "Pursue selective growth", "Expand only where opportunity aligns with strategy, readiness, and available capacity."],
    ["05", "Maintain resilience", "Preserve sufficient flexibility to respond to uncertainty and changing market conditions."],
    ]
    const risks = [
    ["Market risk", "Economic conditions, consumer behavior, interest rates, currency markets, and broader market environments may change."],
    ["Execution risk", "Strategic initiatives may take longer, cost more, or achieve different results than anticipated."],
    ["Brand risk", "Reputational damage, inconsistent positioning, or weak decisions may affect long-term brand equity."],
    ["Operational risk", "Supply chain, technology, infrastructure, personnel, and process disruption may affect operations."],
    ["Regulatory risk", "Laws, licensing, reporting, compliance, and regulatory requirements may change."],
    ["Technology & cyber risk", "Security vulnerabilities, infrastructure failure, data loss, and emerging threats may occur."],
    ["Capital risk", "The availability, cost, and efficient deployment of capital may constrain development."],
    ["Expansion risk", "New markets, categories, partnerships, and ventures may not perform as expected."],
    ["Forward-looking risk", "Plans, targets, and strategic expectations may differ materially from future outcomes."],
    ]
    const roadmap = [
    ["Phase I", "Foundation", "Corporate architecture · Brand foundation · Governance systems · Intellectual property · Digital infrastructure · Documentation", "CURRENT"],
    ["Phase II", "Development", "Capability development · Strategic partnerships · Product and service architecture · Operational systems · Institutional processes", "IN DEVELOPMENT"],
    ["Phase III", "Expansion", "Selective market development · New strategic opportunities · Infrastructure expansion · International positioning, where appropriate", "PLANNED"],
    ["Phase IV", "Maturity", "Institutional resilience · Long-term asset development · Heritage preservation · Multi-generational continuity", "FORWARD-LOOKING"],
    ]
    const library = [
    ["Corporate documents", ["Corporate Overview", "Company Profile", "Strategic Framework", "Governance Framework"]],
    ["Financial materials", ["Annual Reports", "Interim Reports", "Financial Statements", "Auditor Reports"]],
    ["Investment materials", ["Investor Presentation", "Capital Strategy", "Approved Offering Documents", "Investment Memoranda, where applicable"]],
    ["Governance", ["Board Charter", "Governance Principles", "Risk Framework", "Code of Conduct"]],
    ["Legal", ["Disclosures", "Terms", "Policies", "Regulatory Notices"]],
    ["Research", ["White Papers", "Strategic Research", "Industry Analysis", "Institutional Publications"]],
    ]
    const faqs = [
    ["Is Shamim Forever currently accepting investment?", "Investment availability should only be communicated through officially authorized materials and applicable legal processes. This page is not an offer, solicitation, or commitment to accept capital."],
    ["Is the information on this page investment advice?", "No. Website content is for informational purposes only and does not constitute investment, legal, tax, accounting, or financial advice."],
    ["Are future returns guaranteed?", "No. Investment return should never be represented as guaranteed unless supported by a legally enforceable and appropriately regulated structure."],
    ["Where can official investor documents be accessed?", "Eligible documents will be made available through the Investor Materials section or authorized communication channels when verified and approved for publication."],
    ["Who can contact Investor Relations?", "Institutional investors, strategic investors, family offices, authorized representatives, and other eligible capital stakeholders may contact the Investor Relations function through the official channel below."],
    ]
    const statusClasses: Record<Status, string> = { ESTABLISHED: "border-[#4b3a1c] text-[#c9a054]", CURRENT: "border-[#4b3a1c] text-[#c9a054]", "IN DEVELOPMENT": "border-[#252525] text-zinc-400", PLANNED: "border-[#252525] text-zinc-500", "SUBJECT TO APPROVAL": "border-[#252525] text-zinc-500", "FORWARD-LOOKING": "border-[#252525] text-zinc-600" }
    function StatusPill({ status }: { status: Status }) { return <span className={"inline-flex border px-2.5 py-1 text-[8px] tracking-[0.28em] uppercase " + statusClasses[status]}>{status}</span> }
    function Heading({ eyebrow, title, copy }: { eyebrow: string; title: string; copy?: string }) { return <div><p className="text-[9px] uppercase tracking-[0.5em] text-[#c9a054]">{eyebrow}</p><h2 className="mt-5 text-3xl font-light leading-tight md:text-5xl">{title}</h2>{copy && <p className="mt-5 max-w-md text-sm leading-7 text-zinc-600">{copy}</p>}</div> }

    const jsonLd = {
    "@context": "https://schema.org",
    "@graph": [
      { "@type": "WebPage", "@id": "https://www.shamimforever.com/investor-relations#webpage", url: "https://www.shamimforever.com/investor-relations", name: "Investor Relations | Capital in Service of Legacy | Shamim Forever", description: "Institutional information about Shamim Forever's long-term value thesis, capital philosophy, governance, risk disclosure, strategic roadmap, and investor communication principles.", about: { "@id": "https://www.shamimforever.com/#organization" } },
      { "@type": "Organization", "@id": "https://www.shamimforever.com/#organization", name: "Shamim Forever", url: "https://www.shamimforever.com", description: "Sovereign Luxury House.", email: "relations@shamimforever.com", contactPoint: { "@type": "ContactPoint", contactType: "Investor Relations", email: "relations@shamimforever.com" } },
      { "@type": "DefinedTermSet", name: "Shamim Forever Investor Relations Framework", url: "https://www.shamimforever.com/investor-relations", hasDefinedTerm: [{ "@type": "DefinedTerm", name: "Capital Stewardship", description: "The disciplined use of capital to preserve foundations, build capability, create strategic assets, pursue selective growth, and maintain resilience." }, { "@type": "DefinedTerm", name: "Long-Term Value", description: "Institutional value considered across brand equity, intellectual capital, craft, infrastructure, strategic expansion, and legacy." }, { "@type": "DefinedTerm", name: "Transparency Before Promotion", description: "The principle that aspiration must remain distinct from established performance and verified disclosure." }] },
      { "@type": "FAQPage", mainEntity: faqs.map(([question, answer]) => ({ "@type": "Question", name: question, acceptedAnswer: { "@type": "Answer", text: answer } })) },
      { "@type": "BreadcrumbList", itemListElement: [{ "@type": "ListItem", position: 1, name: "Home", item: "https://www.shamimforever.com/" }, { "@type": "ListItem", position: 2, name: "Corporate", item: "https://www.shamimforever.com/corporate" }, { "@type": "ListItem", position: 3, name: "Investor Relations", item: "https://www.shamimforever.com/investor-relations" }] },
    ],
    }

    export default function InvestorRelationsPage() {
    return <>
      <main className="min-h-screen bg-[#050505] text-zinc-200">
        <section className="px-5 pb-20 pt-32 md:px-12 md:pb-28 lg:px-20 lg:pt-40"><div className="mx-auto max-w-[1180px]"><p className="mb-5 text-[9px] uppercase tracking-[0.5em] text-[#c9a054]">Corporate · Capital · Disclosure</p><div className="grid gap-12 lg:grid-cols-[1.3fr_0.7fr] lg:items-end"><div><p className="mb-5 font-serif text-2xl italic text-[#c9a054] md:text-3xl">Investor Relations</p><h1 className="max-w-4xl text-5xl font-light leading-[0.98] tracking-[-0.04em] text-zinc-100 md:text-7xl lg:text-[92px]">Capital in Service of <span className="font-serif italic text-[#c9a054]">Legacy.</span></h1><p className="mt-10 max-w-2xl text-xl font-light leading-relaxed text-zinc-300 md:text-2xl">Building long-term value beyond the present.</p></div><div className="border-l border-[#2a2112] pl-6 text-sm leading-7 text-zinc-500 md:pl-8"><p>Shamim Forever is built around a long-term vision of luxury, permanence, innovation, craftsmanship, infrastructure, and enduring value.</p><p className="mt-5 text-zinc-400">Build deliberately. Govern responsibly. Think beyond the immediate.</p></div></div><div className="mt-16 flex flex-wrap gap-x-7 gap-y-4 border-y border-[#171717] py-5">{["Overview", "Value Thesis", "Governance", "Risk", "Materials", "Roadmap"].map((item, index) => <a key={String(item)} href={["#overview", "#value-thesis", "#governance", "#risk", "#materials", "#roadmap"][index]} className="text-[9px] uppercase tracking-[0.3em] text-zinc-600 transition-colors hover:text-[#c9a054]"><span className="mr-2 text-[#c9a054]">0{index + 1}</span>{item}</a>)}</div></div></section>

        <section id="overview" className="border-t border-[#111] px-5 py-20 md:px-12 md:py-28 lg:px-20"><div className="mx-auto max-w-[1180px]"><div className="grid gap-12 lg:grid-cols-[0.55fr_1fr]"><Heading eyebrow="01 — The purpose of Investor Relations" title="Transparency before promotion."/><div className="max-w-3xl space-y-6 text-base leading-8 text-zinc-400"><p>Investor Relations exists to establish a disciplined relationship between the Company and its capital stakeholders. It is not a marketing brochure, a promise of returns, or an attempt to manufacture valuation through aggressive language.</p><p>It provides a structured environment for eligible investors, strategic partners, and institutional stakeholders to understand the Company's direction, governance architecture, strategic priorities, disclosures, risk philosophy, and long-term value framework.</p><div className="grid gap-3 pt-4 sm:grid-cols-2"><div className="border border-[#1b1b1b] bg-[#080808] p-5"><p className="mb-3 text-[9px] uppercase tracking-[0.35em] text-[#c9a054]">Investor communication includes</p><ul className="space-y-2 text-sm text-zinc-500"><li>Strategic direction</li><li>Corporate structure</li><li>Business model and capital requirements</li><li>Governance and material risks</li><li>Financial information, where applicable</li><li>Relevant disclosures and developments</li></ul></div><div className="border border-[#1b1b1b] bg-[#080808] p-5"><p className="mb-3 text-[9px] uppercase tracking-[0.35em] text-[#c9a054]">Every statement is classified</p><div className="flex flex-wrap gap-2">{(["ESTABLISHED", "CURRENT", "IN DEVELOPMENT", "PLANNED", "SUBJECT TO APPROVAL", "FORWARD-LOOKING"] as Status[]).map(status => <StatusPill key={status} status={status} />)}</div></div></div></div></div></div></section>

        <section id="value-thesis" className="border-t border-[#111] px-5 py-20 md:px-12 md:py-28 lg:px-20"><div className="mx-auto max-w-[1180px]"><div className="mb-12 flex flex-col justify-between gap-5 md:flex-row md:items-end"><Heading eyebrow="02 — The long-term value thesis" title="Six dimensions of enduring value."/><p className="max-w-sm text-sm leading-7 text-zinc-600">The Company's long-term value philosophy is broader than short-term expansion or a single seasonal offering.</p></div><div className="grid gap-px bg-[#1a1a1a] md:grid-cols-2 lg:grid-cols-3">{valueDimensions.map(([number, title, text]) => <article key={String(title)} className="bg-[#070707] p-7 md:p-9"><p className="font-serif text-3xl italic text-[#c9a054]">{number}</p><h3 className="mt-8 text-xl font-light text-zinc-100">{title}</h3><p className="mt-4 text-sm leading-7 text-zinc-500">{text}</p></article>)}</div></div></section>

        <section className="border-t border-[#111] bg-[#070707] px-5 py-20 md:px-12 md:py-28 lg:px-20"><div className="mx-auto max-w-[1180px]"><div className="grid gap-12 lg:grid-cols-[0.55fr_1fr]"><Heading eyebrow="03 — Investment philosophy" title="Long-term capital for long-term creation."/><div className="max-w-3xl space-y-6 text-base leading-8 text-zinc-400"><p>Shamim Forever does not define success exclusively through short-term expansion. Institutional value may require patience, careful sequencing, and a willingness to protect the underlying House before accelerating its reach.</p><p>Capital allocation considers strategic necessity, long-term durability, brand integrity, operational capability, risk exposure, legal and regulatory requirements, capital efficiency, potential return, opportunity cost, and alignment with the House's long-term direction.</p><p className="font-serif text-2xl italic leading-relaxed text-zinc-200">The question is not simply, “Can we grow faster?” It is also, “Should we grow this way?”</p></div></div></div></section>

        <section className="border-t border-[#111] px-5 py-20 md:px-12 md:py-28 lg:px-20"><div className="mx-auto max-w-[1180px]"><div className="grid gap-12 lg:grid-cols-[0.55fr_1fr]"><Heading eyebrow="04 — Investor overview" title="The House at a glance."/><div className="border-y border-[#1a1a1a]">{[["Company", "Shamim Forever"], ["Positioning", "Sovereign Luxury House"], ["Core philosophy", "Built From Love. Forged Into Legacy."], ["Focus", "Luxury, heritage, craftsmanship, innovation, long-term value, and sovereign infrastructure"], ["Investor Relations function", "Strategic communication and disclosure for eligible investors and capital stakeholders"]].map(([label, value]) => <div key={String(label)} className="grid gap-2 border-b border-[#141414] py-5 last:border-0 md:grid-cols-[0.38fr_0.62fr]"><p className="text-[9px] uppercase tracking-[0.35em] text-[#c9a054]">{label}</p><p className="text-sm leading-7 text-zinc-300">{value}</p></div>)}</div></div><div className="mt-10 border border-[#3a2c17] bg-[#100d08] p-6 text-sm leading-7 text-zinc-400"><span className="mr-2 text-[#c9a054]">Disclosure discipline:</span> Financial figures, valuation, revenue, assets under management, investment rounds, ownership percentages, and performance metrics will only appear after verified documentation exists. No numbers are invented to fill an empty dashboard.</div></div></section>

        <section className="border-t border-[#111] bg-[#070707] px-5 py-20 md:px-12 md:py-28 lg:px-20"><div className="mx-auto max-w-[1180px]"><div className="grid gap-12 lg:grid-cols-[0.55fr_1fr]"><Heading eyebrow="05 — Why Shamim Forever" title="A long-term institution, not a seasonal promise."/><div className="grid gap-px bg-[#1a1a1a] sm:grid-cols-2">{[["A distinctive long-term vision", "The House is being developed around an institutional philosophy rather than a single product or seasonal offering."], ["Brand as a long-term asset", "A coherent luxury identity can create value beyond individual transactions when it is protected with discipline."], ["Integrated intellectual architecture", "Brand philosophy, design, technology, documentation, infrastructure, and strategic thinking operate as connected assets."], ["Multi-dimensional development", "Future development may extend across selected experiences, products, services, technology, and infrastructure, subject to planning and approval."], ["Emphasis on permanence", "Durability, heritage, and long-term relevance are prioritized over disposable growth."], ["Evidence before performance claims", "Aspiration remains visibly separate from current, established, verified, or approved activity."]].map(([title, text]) => <article key={String(title)} className="bg-[#080808] p-7"><h3 className="text-lg font-light text-zinc-100">{title}</h3><p className="mt-3 text-sm leading-7 text-zinc-500">{text}</p></article>)}</div></div></div></section>

        <section className="border-t border-[#111] px-5 py-20 md:px-12 md:py-28 lg:px-20"><div className="mx-auto max-w-[1180px]"><div className="grid gap-12 lg:grid-cols-[0.55fr_1fr]"><Heading eyebrow="06 — Corporate structure" title="Brand architecture is not legal architecture."/><div className="space-y-7"><div className="border border-[#1a1a1a] bg-[#080808] p-7 text-center"><p className="text-[9px] uppercase tracking-[0.4em] text-[#c9a054]">Shamim Forever</p><p className="mt-3 text-xs uppercase tracking-[0.3em] text-zinc-500">Holding / parent concept</p><div className="mx-auto my-5 h-8 w-px bg-[#c9a054]"/><div className="grid gap-2 text-xs uppercase tracking-[0.2em] text-zinc-400 sm:grid-cols-3"><span className="border border-[#242424] p-4">The House · Luxury · Our World</span><span className="border border-[#242424] p-4">Authenticity · Innovation</span><span className="border border-[#242424] p-4">Sovereign Infrastructure</span></div></div><p className="text-sm leading-7 text-zinc-500">This is a brand and strategic architecture, not a representation of verified legal entities, subsidiaries, ownership, or securities. The actual legal entity structure should only be published once legally established and verified.</p><Link href="/corporate-information" className="inline-block text-xs uppercase tracking-[0.25em] text-[#c9a054]">Corporate information →</Link></div></div></div></section>

        <section className="border-t border-[#111] bg-[#070707] px-5 py-20 md:px-12 md:py-28 lg:px-20"><div className="mx-auto max-w-[1180px]"><div className="grid gap-12 lg:grid-cols-[0.55fr_1fr]"><Heading eyebrow="07 — Capital allocation philosophy" title="Protect first. Build with intention."/><div className="grid gap-3">{allocationPriorities.map(([number, title, text]) => <div key={String(number)} className="flex gap-6 border-b border-[#1a1a1a] py-5"><span className="font-serif text-2xl italic text-[#c9a054]">{number}</span><div><h3 className="text-lg font-light text-zinc-100">{title}</h3><p className="mt-2 text-sm leading-7 text-zinc-500">{text}</p></div></div>)}</div></div></div></section>

        <section id="governance" className="border-t border-[#111] px-5 py-20 md:px-12 md:py-28 lg:px-20"><div className="mx-auto max-w-[1180px]"><div className="grid gap-12 lg:grid-cols-[0.55fr_1fr]"><Heading eyebrow="08 — Governance for investors" title="Capital deserves accountable stewardship."/><div><p className="max-w-3xl text-base leading-8 text-zinc-400">Investor Relations summarizes the parts of the governance system most relevant to capital stakeholders. It does not replace the complete Leadership &amp; Governance framework.</p><div className="mt-8 grid gap-3 sm:grid-cols-2">{["Board oversight", "Management accountability", "Capital allocation oversight", "Risk management", "Internal controls", "Material decision-making", "Disclosure governance", "Conflicts of interest", "Investor communication protocols"].map(item => <div key={String(item)} className="border border-[#1a1a1a] bg-[#080808] p-5 text-sm text-zinc-400"><span className="mr-3 text-[#c9a054]">—</span>{item}</div>)}</div><Link href="/corporate/leadership-governance" className="mt-8 inline-block text-xs uppercase tracking-[0.25em] text-[#c9a054]">Learn more: Leadership &amp; Governance →</Link></div></div></div></section>

        <section id="risk" className="border-t border-[#111] bg-[#070707] px-5 py-20 md:px-12 md:py-28 lg:px-20"><div className="mx-auto max-w-[1180px]"><div className="mb-12 flex flex-col justify-between gap-5 md:flex-row md:items-end"><Heading eyebrow="09 — Risk disclosure" title="Serious capital conversations acknowledge risk."/><p className="max-w-md text-sm leading-7 text-zinc-600">The following categories are a framework for disclosure, not a promise that every risk can be predicted or eliminated.</p></div><div className="grid gap-px bg-[#1a1a1a] md:grid-cols-2 lg:grid-cols-3">{risks.map(([title, text]) => <article key={String(title)} className="bg-[#080808] p-7"><h3 className="text-lg font-light text-zinc-100">{title}</h3><p className="mt-3 text-sm leading-7 text-zinc-500">{text}</p></article>)}</div><div className="mt-10 border border-[#3a2c17] bg-[#100d08] p-7 text-sm leading-8 text-zinc-400"><span className="font-serif text-xl italic text-[#c9a054]">Required risk statement.</span><br/>Investment involves risk. Past performance, where applicable, is not necessarily indicative of future results. No content on this website should be interpreted as a guarantee of financial performance or investment return.</div></div></section>

        <section id="materials" className="border-t border-[#111] px-5 py-20 md:px-12 md:py-28 lg:px-20"><div className="mx-auto max-w-[1180px]"><div className="mb-12 flex flex-col justify-between gap-5 md:flex-row md:items-end"><Heading eyebrow="10 — Investor materials" title="The Investor Library."/><p className="max-w-md text-sm leading-7 text-zinc-600">A document library is only useful when documents are approved, current, and actually available. Unpublished materials are shown as a framework, not as downloadable fiction.</p></div><div className="grid gap-3 md:grid-cols-2 lg:grid-cols-3">{library.map(([title, items]) => <article key={String(title)} className="border border-[#1a1a1a] bg-[#080808] p-7"><div className="flex items-start justify-between gap-3"><h3 className="text-lg font-light text-zinc-100">{title}</h3><StatusPill status="PLANNED" /></div><ul className="mt-6 space-y-3">{(items as string[]).map(item => <li key={String(item)} className="flex gap-3 text-sm text-zinc-500"><span className="text-[#c9a054]">—</span>{item}</li>)}</ul></article>)}</div><div className="mt-10 grid gap-4 md:grid-cols-3"><Link href="/whitepapers" className="border border-[#1a1a1a] p-6 transition-colors hover:border-[#c9a054]/50"><p className="text-[9px] uppercase tracking-[0.35em] text-[#c9a054]">Research &amp; intellectual work</p><p className="mt-3 text-sm text-zinc-400">White Papers →</p></Link><Link href="/guides" className="border border-[#1a1a1a] p-6 transition-colors hover:border-[#c9a054]/50"><p className="text-[9px] uppercase tracking-[0.35em] text-[#c9a054]">Education &amp; comprehensive knowledge</p><p className="mt-3 text-sm text-zinc-400">Guides →</p></Link><Link href="/sustainability" className="border border-[#1a1a1a] p-6 transition-colors hover:border-[#c9a054]/50"><p className="text-[9px] uppercase tracking-[0.35em] text-[#c9a054]">Responsibility &amp; stewardship</p><p className="mt-3 text-sm text-zinc-400">Sustainability →</p></Link></div></div></section>

        <section id="roadmap" className="border-t border-[#111] bg-[#070707] px-5 py-20 md:px-12 md:py-28 lg:px-20"><div className="mx-auto max-w-[1180px]"><div className="mb-12"><Heading eyebrow="11 — Strategic roadmap" title="A sequence, not a fictional calendar." copy="Roadmap language deliberately uses Completed, Current, In Development, Planned, and Forward-Looking. No future date is presented as if the paperwork has already been signed."/></div><div className="grid gap-3 lg:grid-cols-4">{roadmap.map(([phase, title, text, status]) => <article key={String(phase)} className="border border-[#1a1a1a] bg-[#080808] p-6"><div className="flex items-center justify-between gap-3"><p className="text-[9px] uppercase tracking-[0.35em] text-[#c9a054]">{phase}</p><StatusPill status={status as Status} /></div><h3 className="mt-8 text-2xl font-light text-zinc-100">{title}</h3><p className="mt-4 text-sm leading-7 text-zinc-500">{text}</p></article>)}</div></div></section>

        <section className="border-t border-[#111] px-5 py-20 md:px-12 md:py-28 lg:px-20"><div className="mx-auto max-w-[1180px]"><div className="grid gap-12 lg:grid-cols-[0.55fr_1fr]"><Heading eyebrow="12 — Investor newsroom" title="Official developments, clearly classified."/><div><p className="max-w-3xl text-base leading-8 text-zinc-400">When an investor newsroom is populated, each announcement should display a date, category, status, and official source. Until verified announcements exist, no placeholder news is presented as corporate performance.</p><div className="mt-8 flex flex-wrap gap-2">{["Corporate Developments", "Strategic Announcements", "Governance Updates", "Financial Disclosures", "Partnerships", "Research & Publications", "Investor Notices"].map(item => <span key={String(item)} className="border border-[#1a1a1a] px-4 py-3 text-[9px] uppercase tracking-[0.22em] text-zinc-500">{item}</span>)}</div><Link href="/newsroom" className="mt-8 inline-block text-xs uppercase tracking-[0.25em] text-[#c9a054]">Visit the Newsroom →</Link></div></div></div></section>

        <section className="border-t border-[#111] bg-[#070707] px-5 py-20 md:px-12 md:py-28 lg:px-20"><div className="mx-auto max-w-[1180px]"><div className="mb-12"><Heading eyebrow="13 — Investor Relations Master Book" title="The page is the index. The framework is the institution." copy="The complete 100,000+ word Investor Relations Framework should live as a structured master library, not as one exhausting wall of text. Its future chapters can be expanded with verified documentation as the institution develops."/></div><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{["Capital & Long-Term Value", "The Business", "Corporate Structure", "Governance", "Capital Strategy", "Performance & Measurement", "Risk", "Investor Communication", "Strategic Development", "Legal & Compliance", "Future", "Appendices"].map((part, index) => <div key={String(part)} className="border border-[#1a1a1a] bg-[#080808] p-6"><p className="font-serif text-2xl italic text-[#c9a054]">{String(index + 1).padStart(2, "0")}</p><p className="mt-5 text-sm uppercase tracking-[0.18em] text-zinc-300">{part}</p><p className="mt-3 text-[9px] uppercase tracking-[0.25em] text-zinc-700">Framework index</p></div>)}</div></div></section>

        <section className="border-t border-[#111] px-5 py-20 md:px-12 md:py-28 lg:px-20"><div className="mx-auto max-w-[900px]"><Heading eyebrow="14 — Investor FAQ" title="Clear answers for serious enquiries."/><div className="mt-10 divide-y divide-[#1a1a1a] border-y border-[#1a1a1a]">{faqs.map(([question, answer]) => <details key={String(question)} className="group py-6"><summary className="flex cursor-pointer list-none items-center justify-between gap-6 text-lg font-light text-zinc-200"><span>{question}</span><span className="font-serif text-2xl text-[#c9a054] transition-transform group-open:rotate-45">+</span></summary><p className="max-w-3xl pt-4 text-sm leading-7 text-zinc-500">{answer}</p></details>)}</div></div></section>

        <section className="border-t border-[#111] bg-[#070707] px-5 py-20 md:px-12 md:py-28 lg:px-20"><div className="mx-auto max-w-[1180px]"><div className="grid gap-12 lg:grid-cols-[0.7fr_1.3fr] lg:items-end"><div><p className="text-[9px] uppercase tracking-[0.5em] text-[#c9a054]">15 — Investor contact</p><h2 className="mt-5 text-4xl font-light leading-tight md:text-6xl">Invest in what is built to endure.</h2></div><div className="border-l border-[#2a2112] pl-6 text-sm leading-8 text-zinc-500 md:pl-8"><p>Capital can accelerate growth. Growth alone does not create permanence.</p><p className="mt-5">Our Investor Relations approach is grounded in transparency, strategic communication, and a commitment to distinguishing ambition from achievement.</p><p className="mt-5 font-serif text-xl italic text-zinc-300">The future cannot be guaranteed. But it can be approached with greater discipline.</p></div></div><div className="mt-14 grid gap-3 md:grid-cols-3"><a href="mailto:relations@shamimforever.com" className="border border-[#3a2c17] bg-[#100d08] p-7 transition-colors hover:border-[#c9a054]"><p className="text-[9px] uppercase tracking-[0.35em] text-[#c9a054]">Investor Relations</p><p className="mt-4 text-lg text-zinc-200">relations@shamimforever.com</p><p className="mt-3 text-xs leading-6 text-zinc-600">For institutional and strategic capital enquiries through the established official relations channel.</p></a><Link href="/corporate/leadership-governance" className="border border-[#1a1a1a] p-7 transition-colors hover:border-[#c9a054]/50"><p className="text-[9px] uppercase tracking-[0.35em] text-[#c9a054]">Governance</p><p className="mt-4 text-lg text-zinc-200">Leadership &amp; Governance →</p><p className="mt-3 text-xs leading-6 text-zinc-600">The complete governance, accountability, ethics, and stewardship framework.</p></Link><Link href="/corporate-information" className="border border-[#1a1a1a] p-7 transition-colors hover:border-[#c9a054]/50"><p className="text-[9px] uppercase tracking-[0.35em] text-[#c9a054]">Corporate</p><p className="mt-4 text-lg text-zinc-200">Corporate Information →</p><p className="mt-3 text-xs leading-6 text-zinc-600">Public corporate information and the distinction between verified structure and future concepts.</p></Link></div></div></section>

        <section className="border-t border-[#111] px-5 py-16 md:px-12 lg:px-20"><div className="mx-auto max-w-[1180px] text-center"><p className="font-serif text-3xl italic text-[#c9a054] md:text-4xl">Shamim Forever</p><p className="mt-4 text-[9px] uppercase tracking-[0.45em] text-zinc-600">Built From Love. Forged Into Legacy.</p><p className="mx-auto mt-8 max-w-2xl text-xs leading-7 text-zinc-700">This Investor Relations page is informational. It is not an offer to sell securities, a solicitation of investment, investment advice, or a guarantee of financial performance or return.</p></div></section>
      </main>
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }} />
    </>
    }
    