import type { Metadata } from 'next'
import SeoJsonLd from '@/components/SeoJsonLd'
import InnovationHub from '@/components/InnovationHub'
import { pillars, faqs } from '@/lib/innovation-content'
const url='https://www.shamimforever.com/learn/innovation'
const description='Explore how Shamim Forever approaches innovation through craftsmanship, intelligent systems, digital identity, sustainable thinking, private client technology, and the future of sovereign luxury.'
export const metadata:Metadata={title:'Innovation in Luxury | The Future Architecture of Shamim Forever',description,keywords:['Shamim Forever innovation','innovation in luxury','future of luxury','luxury technology','intelligent luxury','digital house','material innovation','future craftsmanship','private client technology'],alternates:{canonical:url},robots:{index:true,follow:true},openGraph:{type:'article',url,title:'Innovation in Luxury | The Future Architecture of Shamim Forever',description,siteName:'Shamim Forever',images:[{url:'https://www.shamimforever.com/og-heirloom.jpg',width:1200,height:630,alt:'Shamim Forever innovation and future luxury'}]},twitter:{card:'summary_large_image',title:'Innovation in Luxury | Shamim Forever',description,images:['https://www.shamimforever.com/og-heirloom.jpg']}}
const schema=[{'@context':'https://schema.org','@type':'Article','@id':url+'#article',headline:'Innovation in Luxury | The Future Architecture of Shamim Forever',description,url,mainEntityOfPage:{'@id':url},author:{'@type':'Organization',name:'Shamim Forever',url:'https://www.shamimforever.com'},publisher:{'@type':'Organization',name:'Shamim Forever',url:'https://www.shamimforever.com'},datePublished:'2026-09-07',dateModified:'2026-09-07',inLanguage:'en',about:['innovation in luxury','artificial intelligence','digital infrastructure','material innovation','future craftsmanship']},{'@context':'https://schema.org','@type':'ItemList','@id':url+'#pillars',name:'Shamim Forever Innovation pillars',itemListElement:pillars.map((p,i)=>({'@type':'ListItem',position:i+1,name:p[1],url:url+'/'+p[0]}))},{'@context':'https://schema.org','@type':'FAQPage','@id':url+'#faq',mainEntity:faqs.map(f=>({'@type':'Question',name:f[0],acceptedAnswer:{'@type':'Answer',text:f[1]}}))},{'@context':'https://schema.org','@type':'BreadcrumbList',itemListElement:[{'@type':'ListItem',position:1,name:'Learn',item:'https://www.shamimforever.com/learn'},{'@type':'ListItem',position:2,name:'Innovation',item:url}]}]
export default function InnovationPage(){return <SeoJsonLd schemas={schema}><InnovationHub/></SeoJsonLd>}
