import type { Metadata } from 'next'
import { chapters, faqs } from '@/lib/authenticity-content'
import AuthenticityHub from '@/components/AuthenticityHub'
import SeoJsonLd from '@/components/SeoJsonLd'
const url='https://www.shamimforever.com/learn/authenticity'
const description='Explore the Shamim Forever Authenticity Standard, including provenance, product identity, craftsmanship records, authentication principles, heritage documentation, and Sovereign verification infrastructure.'
export const metadata:Metadata={title:'Authenticity | The Sovereign Standard of Provenance | Shamim Forever',description,keywords:['Shamim Forever Authenticity','luxury authentication','luxury product provenance','authentic luxury','luxury verification','product identity','craftsmanship authentication','heritage documentation'],alternates:{canonical:url},robots:{index:true,follow:true},openGraph:{type:'article',url,title:'Authenticity | The Sovereign Standard of Provenance | Shamim Forever',description,siteName:'Shamim Forever',images:[{url:'https://www.shamimforever.com/og-heirloom.jpg',width:1200,height:630,alt:'Shamim Forever authenticity and heritage'}]},twitter:{card:'summary_large_image',title:'Authenticity | Shamim Forever',description,images:['https://www.shamimforever.com/og-heirloom.jpg']}}
const schema=[{'@context':'https://schema.org','@type':'Article','@id':url+'#article',headline:'Authenticity | The Sovereign Standard of Provenance',description,url,mainEntityOfPage:{'@id':url},author:{'@type':'Organization',name:'Shamim Forever',url:'https://www.shamimforever.com'},publisher:{'@type':'Organization',name:'Shamim Forever',url:'https://www.shamimforever.com'},datePublished:'2026-09-07',dateModified:'2026-09-07',inLanguage:'en',about:['luxury authentication','provenance','object identity','heritage documentation']},{'@context':'https://schema.org','@type':'ItemList','@id':url+'#chapters',name:'Shamim Forever Authenticity Knowledge System',itemListElement:chapters.map((c,i)=>({'@type':'ListItem',position:i+1,name:c[1],url:url+'/'+c[0]}))},{'@context':'https://schema.org','@type':'FAQPage','@id':url+'#faq',mainEntity:faqs.map(f=>({'@type':'Question',name:f[0],acceptedAnswer:{'@type':'Answer',text:f[1]}}))},{'@context':'https://schema.org','@type':'BreadcrumbList',itemListElement:[{'@type':'ListItem',position:1,name:'Learn',item:'https://www.shamimforever.com/learn'},{'@type':'ListItem',position:2,name:'Authenticity',item:url}]}]
export default function AuthenticityPage(){return <><SeoJsonLd schemas={schema}><AuthenticityHub/></SeoJsonLd></>}
