import { NextRequest, NextResponse } from 'next/server'
import { createClient } from '@supabase/supabase-js'

export const dynamic = 'force-dynamic'
export const maxDuration = 60

function db() {
  return createClient(
    process.env.NEXT_PUBLIC_SUPABASE_URL!,
    process.env.SUPABASE_SERVICE_ROLE_KEY ?? process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!,
    { auth: { persistSession: false } }
  )
}

const PLACEHOLDER_IMG = 'https://uvgtgeauhjbdatrmmaob.supabase.co/storage/v1/object/public/products/perfumes/oud-sovereign-new.png'
const PERF_M = 'https://uvgtgeauhjbdatrmmaob.supabase.co/storage/v1/object/public/products/perfumes/himalayan-snow-musk.png'
const PERF_F = 'https://uvgtgeauhjbdatrmmaob.supabase.co/storage/v1/object/public/products/perfumes/midnight-iris-royale.png'
const PERF_U = 'https://uvgtgeauhjbdatrmmaob.supabase.co/storage/v1/object/public/products/perfumes/vanilla-absolute.png'

function storyJSON(tagline: string, olfactory: string, top: string, heart: string, base: string, volume: string, price: string) {
  return JSON.stringify({
    tagline, olfactory,
    scentPyramid: { top, heart, base },
    specs: {
      volume, concentration: 'Extrait de Parfum', sillage: 'Imperial / Commanding', longevity: '12–18 Hours', batch: 'Limited Reserve Batch', price
    }
  })
}

function cosStory(tagline: string, desc: string, benefits: string[], howTo: string) {
  return JSON.stringify({ tagline, description: desc, benefits, howTo })
}

function jewStory(tagline: string, material: string, desc: string, care: string) {
  return JSON.stringify({ tagline, material, description: desc, care })
}

export async function GET(req: NextRequest) {
  const secret = req.nextUrl.searchParams.get('secret')
  if (secret !== 'shamim-seed-all-2026') {
    return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })
  }

  const supabase = db()

  // ── Get category IDs ────────────────────────────────────────────────────────
  const { data: cats } = await supabase.from('main_categories').select('id, slug')
  const perfumeId = cats?.find(c => c.slug === 'perfume')?.id
  const cosmeticsId = cats?.find(c => c.slug === 'cosmetics')?.id
  const jewelryId = cats?.find(c => c.slug === 'jewelry')?.id

  if (!perfumeId || !cosmeticsId || !jewelryId) {
    return NextResponse.json({ error: 'Categories not found. Run /api/seed-products first.' }, { status: 400 })
  }

  // ── Get sub-category IDs ───────────────────────────────────────────────────
  const { data: subcats } = await supabase.from('sub_categories').select('id, name, slug')
  const maleId = subcats?.find(s => s.name?.toLowerCase().includes('him') || s.slug?.includes('him') || s.name?.toLowerCase().includes('male'))?.id || null
  const femaleId = subcats?.find(s => s.name?.toLowerCase().includes('her') || s.slug?.includes('her') || s.name?.toLowerCase().includes('female'))?.id || null
  const unisexId = subcats?.find(s => s.name?.toLowerCase().includes('unisex') || s.slug?.includes('unisex'))?.id || null

  // ── PERFUMES ─────────────────────────────────────────────────────────────────
  const perfumeMale = [
    { name: 'Dark Oud Intense', slug: 'dark-oud-intense', description: 'Heavily concentrated dark oud layered with smoky leather, black pepper, and vetiver. A masculine power statement.', story: storyJSON('Dark Oud Intense — The Absolute Authority', 'A dense, dark oud from Assam meets Indian leather and Moroccan spice in an unprecedented masculine declaration.', 'Black Pepper, Smoked Cardamom', 'Rare Assamese Oud, Dark Leather Accord', 'Vetiver Root, Ambergris, Musk', '100ML EDP', 'Rs 22,500 / $79'), price_pkr: 22500, price_usd: 79 },
    { name: 'Sovereign Cedar Noir', slug: 'sovereign-cedar-noir', description: 'Crisp Himalayan cedar combined with dry incense and smoky vetiver. Masculine, architectural, commanding.', story: storyJSON('Sovereign Cedar Noir', 'Cedar has been the wood of kings. Ours is sourced from Himalayan forests and blended with a dry incense that commands any room.', 'Bergamot, Juniper Berry', 'Himalayan Cedar, Cypress, Dry Incense', 'Vetiver, Grey Amber, Musk', '100ML EDP', 'Rs 19,500 / $69'), price_pkr: 19500, price_usd: 69 },
    { name: 'Black Saffron Reserve', slug: 'black-saffron-reserve', description: 'Golden saffron threads steeped in dark leather and molasses amber. The imperial scent of the sovereign merchant.', story: storyJSON('Black Saffron Reserve', 'Saffron was worth its weight in gold on the ancient spice routes. We have captured the deepest, darkest side of this legendary ingredient.', 'Persian Saffron, Black Cardamom', 'Dark Leather, Tobacco Leaf', 'Amber Resin, Benzoin, Vetiver', '100ML EDP', 'Rs 21,000 / $74'), price_pkr: 21000, price_usd: 74 },
    { name: 'Imperial Tobacco & Bourbon', slug: 'imperial-tobacco-bourbon', description: 'Aged Kentucky bourbon fused with Virginia tobacco, dark cherry, and smooth vanillic woods. Masculine luxury redefined.', story: storyJSON('Imperial Tobacco & Bourbon', 'The members\'s lounge of a sovereign institution. Aged leather chairs, Kentucky bourbon, the finest tobacco. Bottled.', 'Dark Cherry, Bergamot, Tobacco Flower', 'Kentucky Bourbon Accord, Birchwood Smoke', 'Tonka Bean, Dark Vanilla, Atlas Cedar', '100ML EDP', 'Rs 23,000 / $82'), price_pkr: 23000, price_usd: 82 },
    { name: 'Alpha Marine Intense', slug: 'alpha-marine-intense', description: 'The modern sovereign in his natural habitat — the open sea. Sea salt, driftwood, and bergamot with an iron-dry base.', story: storyJSON('Alpha Marine Intense', 'Not the casual aquatic of the boardwalk — this is the captain\'s maritime accord. Powerful, clean, and commanding.', 'Sea Salt, Bergamot, Green Petitgrain', 'Ambergris, Driftwood, Sage', 'Iron Cedar, Grey Amber, Musk', '100ML EDP', 'Rs 17,500 / $62'), price_pkr: 17500, price_usd: 62 },
    { name: 'Knight Vetiver', slug: 'knight-vetiver', description: 'Raw, earthy Haitian vetiver paired with smoked woods and crushed black pepper. For those who need no armour.', story: storyJSON('Knight Vetiver', 'Vetiver is the warrior\'s root. We use only the finest Haitian vetiver, smoked over open flame and blended with a crushed peppercorn accord.', 'Black Pepper, Grapefruit', 'Haitian Vetiver, Cypriol Oil', 'Smoked Birch, Grey Ambergris, Musks', '100ML EDP', 'Rs 18,000 / $64'), price_pkr: 18000, price_usd: 64 },
    { name: 'Dark Rose & Oud', slug: 'dark-rose-oud-him', description: 'The masculine interpretation of the immortal rose — deep, thorned, and dark. Turkish rose oil tempered with oud and leather.', story: storyJSON('Dark Rose & Oud', 'In the ancient East, rose and oud were never considered feminine. This is rose at its darkest, most powerful expression.', 'Turkish Rose Otto, Black Pepper', 'Aged Cambodian Oud, Dark Rose Absolute', 'Leather, Sandalwood, Iso E Super', '100ML EDP', 'Rs 24,500 / $87'), price_pkr: 24500, price_usd: 87 },
    { name: 'Conqueror Spice', slug: 'conqueror-spice', description: 'A bold spice cabinet of cinnamon, clove, and saffron over a rich benzoin base. The scent of ancient conquest.', story: storyJSON('Conqueror Spice', 'The Silk Road carried spices that altered the course of civilisation. We\'ve captured the summit of this trade in a single sovereign accord.', 'Cinnamon, Clove, Saffron', 'Elemi Resin, Frankincense', 'Benzoin, Amber, Sandalwood', '100ML EDP', 'Rs 19,000 / $67'), price_pkr: 19000, price_usd: 67 },
    { name: 'Heritage Leather', slug: 'heritage-leather', description: 'Full-bodied Russian leather accord with birch tar, black coffee, and dry birchwood. The scent of earned authority.', story: storyJSON('Heritage Leather', 'Russian leather — historically the most prized leather on earth — has been the scent of aristocrats for three centuries. We\'ve rebuilt this legend.', 'Birch Tar, Black Coffee', 'Russian Leather Accord, Guaiac Wood', 'Dry Birchwood, Tobacco, Musk', '100ML EDP', 'Rs 20,500 / $73'), price_pkr: 20500, price_usd: 73 },
    { name: 'Smoky Incense Noir', slug: 'smoky-incense-noir', description: 'Sacred Omani frankincense smoked over charcoal, with deep myrrh and sacred resins. A meditative masculine.', story: storyJSON('Smoky Incense Noir', 'The great temples of antiquity burned frankincense to commune with the divine. This is that sacred smoke, distilled.', 'Smoked Frankincense, Bergamot', 'Omani Frankincense, Myrrh, Black Benzoin', 'Dark Amber, Sandalwood, Labdanum', '100ML EDP', 'Rs 18,500 / $65'), price_pkr: 18500, price_usd: 65 },
    { name: 'Jungle Oud', slug: 'jungle-oud', description: 'Wild, animalic Borneo oud with green vetiver and earthy patchouli. Raw nature, sovereign in intensity.', story: storyJSON('Jungle Oud', 'Deep in the Borneo rainforest, oud trees infected by the Aquilaria mold produce the rarest, most animalic oud on earth. We\'ve captured it.', 'Green Vetiver, Galbanum', 'Borneo Oud, Cypriol, Patchouli', 'Animalic Musks, Sandalwood, Amber', '100ML EDP', 'Rs 26,000 / $92'), price_pkr: 26000, price_usd: 92 },
    { name: 'Steel & Sandalwood', slug: 'steel-sandalwood', description: 'Industrial cold metal accord with creamy Mysore sandalwood and clean white musks. Strength wrapped in elegance.', story: storyJSON('Steel & Sandalwood', 'The duality of the modern sovereign — hard as steel in the boardroom, smooth as sandalwood in the private hour.', 'Cold Metal Accord, Bergamot, Iso E Super', 'Mysore Sandalwood, Cashmere Wood', 'White Musk, Ambroxan, Amber', '100ML EDP', 'Rs 16,500 / $58'), price_pkr: 16500, price_usd: 58 },
    { name: 'Frontier Accord', slug: 'frontier-accord', description: 'Bold fougère of lavender, coumarin, and dry woods. The classic masculine elevated to sovereign luxury.', story: storyJSON('Frontier Accord', 'The fougère is the original masculine accord — lavender, coumarin, and oakmoss. We\'ve reconstructed this with the finest modern ingredients.', 'Bergamot, Lavender, Geranium', 'Coumarin, Oakmoss, Vetiver', 'Tonka Bean, Dry Woods, White Musk', '100ML EDP', 'Rs 15,500 / $55'), price_pkr: 15500, price_usd: 55 },
    { name: 'Noble Amber Reserve', slug: 'noble-amber-reserve', description: 'A rich, deep amber accord with warm benzoin, labdanum, and a hint of oud smoke. Opulent, warm, sovereign.', story: storyJSON('Noble Amber Reserve', 'Amber is the colour of sovereignty. This is its olfactory equivalent — golden, warm, and absolutely dominant.', 'Bergamot, Pink Pepper', 'Amber Resin, Labdanum, Benzoin', 'Oud Smoke, Sandalwood, Vanilla Musk', '100ML EDP', 'Rs 20,000 / $71'), price_pkr: 20000, price_usd: 71 },
    { name: 'Black Pepper Emperor', slug: 'black-pepper-emperor', description: 'Sharp black peppercorn with a bold smoky heart of oud and an earthy vetiver base. Assertive, modern, sovereign.', story: storyJSON('Black Pepper Emperor', 'In ancient trade, black pepper was so valuable it was used as currency. The Emperor\'s accord — sharp, powerful, non-negotiable.', 'Black Pepper, Pink Grapefruit', 'Oud Absolute, Guaiac Wood', 'Vetiver, Ambergris, Musks', '100ML EDP', 'Rs 17,000 / $60'), price_pkr: 17000, price_usd: 60 },
  ]

  const perfumeFemale = [
    { name: 'Rose Absolue Royale', slug: 'rose-absolue-royale', description: 'Pure rose absolute from Grasse combined with lychee and pink pepper. The feminine sovereign in full bloom.', story: storyJSON('Rose Absolue Royale', 'The most prized ingredient in all of perfumery — rose absolute from Grasse — is the centrepiece of this feminine declaration.', 'Lychee, Pink Pepper, Bergamot', 'Rose Absolute (Grasse), Peony, Jasmine', 'White Musk, Sandalwood, Amber', '100ML EDP', 'Rs 21,000 / $74'), price_pkr: 21000, price_usd: 74 },
    { name: 'Sakura Blossom', slug: 'sakura-blossom', description: 'Japanese cherry blossom and pink magnolia over a soft musk. Pure femininity, softly sovereign.', story: storyJSON('Sakura Blossom', 'For three weeks each spring, Japan transforms into a sea of pink. We\'ve captured that fleeting, perfect moment.', 'Cherry Blossom, Yuzu, Green Apple', 'Pink Magnolia, Lily, Rose Petals', 'White Musk, Sandalwood, Vanilla', '100ML EDP', 'Rs 16,500 / $58'), price_pkr: 16500, price_usd: 58 },
    { name: 'Velvet Peony Intense', slug: 'velvet-peony-intense', description: 'Lush Chinese peony over velvety musks and warm cedarwood. Feminine strength, sovereignly expressed.', story: storyJSON('Velvet Peony Intense', 'The peony is the flower of prosperity and royalty in Eastern culture. We\'ve built our interpretation around a lush peony absolute.', 'Bergamot, Pear, Pomegranate', 'Peony Absolute, Rose, Jasmine', 'Cashmere Wood, White Musk, Amber', '100ML EDP', 'Rs 17,500 / $62'), price_pkr: 17500, price_usd: 62 },
    { name: 'Jasmine Nocturne', slug: 'jasmine-nocturne', description: 'Indolic jasmine absolute from Grasse, deepened with dark tuberose and warm amber at midnight.', story: storyJSON('Jasmine Nocturne', 'Jasmine releases its most intoxicating scent at night. This is our night-blooming jasmine accord — deep, indolic, and utterly captivating.', 'Neroli, Pink Pepper, Bergamot', 'Jasmine Absolute, Tuberose, Ylang', 'Amber, Musk, Sandalwood', '100ML EDP', 'Rs 20,000 / $71'), price_pkr: 20000, price_usd: 71 },
    { name: 'Crystal Iris', slug: 'crystal-iris', description: 'Pale powdery iris root (orris butter) with violet leaves and soft suede. Cool, aristocratic, timeless.', story: storyJSON('Crystal Iris', 'Orris butter is one of the rarest and most expensive ingredients in perfumery. A single kilo costs more than gold. This is pure iris.', 'Violet Leaf, Bergamot, Aldehydes', 'Iris Root (Orris Butter), Violet, Powder', 'Suede, White Musk, Ambrette', '100ML EDP', 'Rs 22,500 / $79'), price_pkr: 22500, price_usd: 79 },
    { name: 'Evening Orchid', slug: 'evening-orchid', description: 'Black orchid essence with dark cherry, amber, and a sandalwood heart. Mysterious, deep feminine luxury.', story: storyJSON('Evening Orchid', 'The black orchid grows only in the deepest rainforests. We\'ve combined it with dark cherry and sandalwood for the most luxurious feminine accord.', 'Black Orchid, Dark Cherry, Bergamot', 'Black Rose, Ylang Ylang, Jasmine', 'Patchouli, Amber, Sandalwood', '100ML EDP', 'Rs 23,500 / $83'), price_pkr: 23500, price_usd: 83 },
    { name: 'Sweet Magnolia', slug: 'sweet-magnolia', description: 'Southern magnolia blossom with creamy coconut, vanilla, and pink pepper. Feminine warmth, sovereign charm.', story: storyJSON('Sweet Magnolia', 'The magnolia was the first flowering plant to appear on earth — 95 million years ago. This is nature\'s original sovereignty.', 'Pink Pepper, Green Apple, Bergamot', 'Magnolia, Peach Blossom, Coconut', 'Vanilla, Musk, Sandalwood', '100ML EDP', 'Rs 15,500 / $55'), price_pkr: 15500, price_usd: 55 },
    { name: 'Precious Lily of the Valley', slug: 'lily-of-the-valley', description: 'Fresh, dewy lily of the valley (muguet) with green iris and soft violet. A classic feminine freshness, sovereignly rendered.', story: storyJSON('Precious Lily of the Valley', 'Muguet — lily of the valley — is so rare it cannot be extracted naturally. Every drop is a masterpiece of reconstruction. We\'ve used the finest available.', 'Green Notes, Bergamot, Lemon', 'Muguet Absolute, Iris, Violet', 'White Musk, Sandalwood, Cedarwood', '100ML EDP', 'Rs 18,000 / $64'), price_pkr: 18000, price_usd: 64 },
    { name: 'Amber Rose Fusion', slug: 'amber-rose-fusion', description: 'Warm amber resin enveloping Turkish rose oil and soft sandalwood. The essence of luxurious femininity.', story: storyJSON('Amber Rose Fusion', 'Amber and rose — two of the most prized elements in the history of luxury — fused in a single, unforgettable accord.', 'Bergamot, Rose Otto, Pink Pepper', 'Amber Rose, Ylang Ylang', 'Benzoin, Labdanum, Vanilla Musk', '100ML EDP', 'Rs 19,500 / $69'), price_pkr: 19500, price_usd: 69 },
    { name: 'Berry Bloom Royale', slug: 'berry-bloom-royale', description: 'Wild blackberry and raspberry blossom over a heart of pink rose and creamy musks. Young luxury with sovereign elegance.', story: storyJSON('Berry Bloom Royale', 'The wild berries of the Himalayan hillside — raspberries, blackberries — captured at peak ripeness and woven into a sovereign feminine accord.', 'Raspberry, Blackberry, Pink Grapefruit', 'Rose Petals, Peony, Freesia', 'Creamy Musk, Cashmere, White Woods', '100ML EDP', 'Rs 15,000 / $53'), price_pkr: 15000, price_usd: 53 },
    { name: 'Gardenia Opulence', slug: 'gardenia-opulence', description: 'Creamy white gardenia blossom with honeyed tuberose and warm vanilla base. Feminine, indulgent, and sovereignly rich.', story: storyJSON('Gardenia Opulence', 'Gardenia — cream-white, intoxicating, nocturnal. This is femininity distilled to its purest, most opulent expression.', 'White Gardenia, Neroli, Green Leaves', 'Tuberose, Jasmine, Ylang', 'Vanilla, Sandalwood, White Musk', '100ML EDP', 'Rs 20,500 / $73'), price_pkr: 20500, price_usd: 73 },
    { name: 'Enchanting Violet', slug: 'enchanting-violet', description: 'Deep purple violet absolute with powdery iris and a hint of raspberry. Feminine mystery, sovereign allure.', story: storyJSON('Enchanting Violet', 'Violets were the favourite flower of Napoleon\'s Josephine. We honour this royal obsession with our deepest violet accord.', 'Violet, Raspberry, Bergamot', 'Iris, Violet Absolute, Powder', 'White Musk, Vanilla, Cedarwood', '100ML EDP', 'Rs 16,000 / $57'), price_pkr: 16000, price_usd: 57 },
    { name: 'Silken Oud Feminine', slug: 'silken-oud-feminine', description: 'Feminine oud — rose-soaked, smooth, and velvety — with saffron and creamy sandalwood. The queen\'s private accord.', story: storyJSON('Silken Oud Feminine', 'Oud is not exclusively masculine — when blended with rose and saffron, it transforms into the most opulent feminine accord imaginable.', 'Saffron, Persian Rose, Bergamot', 'Rose Oud Accord, Jasmine', 'Creamy Sandalwood, Vanilla, Musks', '100ML EDP', 'Rs 24,000 / $85'), price_pkr: 24000, price_usd: 85 },
    { name: 'Gold Freesia', slug: 'gold-freesia', description: 'Light, airy freesia blossom with citrus accord and warm soft musks. Fresh, elegant, effortlessly feminine.', story: storyJSON('Gold Freesia', 'Freesia — the freshest floral — elevated from a garden flower to a sovereign luxury statement. Bright, light, and utterly unforgettable.', 'Freesia, Lemon, Green Bergamot', 'White Floral Accord, Lily, Muguet', 'Skin Musk, Cedar, Ambrette', '100ML EDP', 'Rs 14,500 / $51'), price_pkr: 14500, price_usd: 51 },
    { name: 'Soft Powder Elegance', slug: 'soft-powder-elegance', description: 'Ultra-feminine powdery accord of aldehydes, iris, and white musks. Classic luxury, timelessly sovereign.', story: storyJSON('Soft Powder Elegance', 'The powdery accord was the hallmark of old Hollywood glamour. We\'ve reimagined it for the modern sovereign woman — softer, deeper, more intimate.', 'Bergamot, Aldehydes, Citrus', 'Iris, Violet, Rose', 'White Musk, Vanilla, Sandalwood', '100ML EDP', 'Rs 17,000 / $60'), price_pkr: 17000, price_usd: 60 },
  ]

  const perfumeUnisex = [
    { name: 'Clean Skin Musk', slug: 'clean-skin-musk', description: 'The purest expression of clean — skin-close musk with a hint of warm ambrette. Invisible sovereignty.', story: storyJSON('Clean Skin Musk', 'The most intimate fragrance we make. It smells of clean, warm skin — amplified, perfected, and made immortal.', 'Bergamot, Clean Aldehydes', 'Ambrette, White Musk', 'Sandalwood, Skin Musk, Ambroxan', '100ML EDP', 'Rs 14,000 / $49'), price_pkr: 14000, price_usd: 49 },
    { name: 'Warm Amber Accord', slug: 'warm-amber-accord', description: 'Warm, resinous amber with labdanum, benzoin, and a sandalwood core. A sovereign comfort scent.', story: storyJSON('Warm Amber Accord', 'Amber is the warmth of the sun crystallised. This is our definitive amber accord — rich, warm, and universally elegant.', 'Bergamot, Orange Zest', 'Amber Resin, Benzoin, Labdanum', 'Sandalwood, Tonka, Vanilla Musk', '100ML EDP', 'Rs 16,000 / $57'), price_pkr: 16000, price_usd: 57 },
    { name: 'Sea Salt & Cedar', slug: 'sea-salt-cedar', description: 'Mediterranean sea salt and driftwood with green bergamot and a clean musk. Elemental and sovereign.', story: storyJSON('Sea Salt & Cedar', 'The meeting point of the Mediterranean — salt air, bleached driftwood, bergamot trees. Pure elemental luxury.', 'Sea Salt, Bergamot, Citrus', 'Driftwood, Cypress, Ambergris', 'Atlas Cedar, Musk, Iso E Super', '100ML EDP', 'Rs 15,500 / $55'), price_pkr: 15500, price_usd: 55 },
    { name: 'Green Tea Reserve', slug: 'green-tea-reserve', description: 'Rare Japanese matcha green tea absolute with fresh bergamot and a white musk. Calm, focused, sovereign.', story: storyJSON('Green Tea Reserve', 'The Japanese tea ceremony is an act of sovereign focus — complete mindfulness. This fragrance is its olfactory companion.', 'Green Tea Absolute, Bergamot, Lemon', 'Matcha, White Flowers, Iris', 'White Musk, Sandalwood, Cedar', '100ML EDP', 'Rs 13,500 / $48'), price_pkr: 13500, price_usd: 48 },
    { name: 'White Sandalwood Absolute', slug: 'white-sandalwood-absolute', description: 'Pure Mysore sandalwood absolute — milky, smooth, and timeless. Unisex sovereignty at its most refined.', story: storyJSON('White Sandalwood Absolute', 'Mysore sandalwood is the most prized wood in Indian culture — the material of gods and kings. This is its purest expression.', 'Bergamot, Cardamom', 'Mysore Sandalwood Absolute, Iris', 'Creamy Musk, Ambroxan, Cashmeran', '100ML EDP', 'Rs 19,000 / $67'), price_pkr: 19000, price_usd: 67 },
    { name: 'Black Vanilla Patchouli', slug: 'black-vanilla-patchouli', description: 'Dark patchouli absolute with Tahitian vanilla and warm rum accord. Sensual, deep, and sovereignly intoxicating.', story: storyJSON('Black Vanilla Patchouli', 'Patchouli and vanilla — the most universally beloved pairing in perfumery. This is the darkest, deepest interpretation of this iconic duo.', 'Rum Accord, Dark Bergamot', 'Patchouli Absolute, Dark Vanilla, Tonka', 'Amber, Sandalwood, Musks', '100ML EDP', 'Rs 17,500 / $62'), price_pkr: 17500, price_usd: 62 },
    { name: 'Crisp Iris Blanc', slug: 'crisp-iris-blanc', description: 'Pale, powdery orris root with violet leaves and a clean white musk. The most refined unisex statement.', story: storyJSON('Crisp Iris Blanc', 'Iris is neither masculine nor feminine — it transcends gender. This is its most refined, crystalline expression.', 'Violet Leaf, Bergamot, Aldehydes', 'Iris Root, Orris Butter, Powder', 'White Musk, Cashmere, Cedar', '100ML EDP', 'Rs 21,000 / $74'), price_pkr: 21000, price_usd: 74 },
    { name: 'Cedar & Vetiver Forest', slug: 'cedar-vetiver-forest', description: 'Deep forest accord of Haitian vetiver, Atlas cedar, and crisp fir needle. Nature, sovereignly refined.', story: storyJSON('Cedar & Vetiver Forest', 'The ancient forest — vetiver roots, cedar bark, fir needles. We\'ve bottled the most pristine landscape on earth.', 'Fir Needle, Petitgrain, Green Galbanum', 'Atlas Cedar, Haitian Vetiver', 'Oakmoss, Dry Amber, Musk', '100ML EDP', 'Rs 16,500 / $58'), price_pkr: 16500, price_usd: 58 },
    { name: 'Oud & Citrus Light', slug: 'oud-citrus-light', description: 'Light, approachable oud tempered by Sicilian bergamot and lemon verbena. Luxury made accessible, unisex sovereignty.', story: storyJSON('Oud & Citrus Light', 'Oud does not have to be dark and heavy. In its lightest form, oud is a clean, warm wood that elevates everything around it.', 'Bergamot, Lemon Verbena, Green Mandarin', 'Light Oud, Cedarwood, Amber', 'White Musk, Sandalwood, Clean Amber', '100ML EDP', 'Rs 18,500 / $65'), price_pkr: 18500, price_usd: 65 },
    { name: 'Sacred Frankincense', slug: 'sacred-frankincense', description: 'Pure Omani Hojari frankincense — the finest in the world — with lemon and myrrh. Spiritual, clean, sovereign.', story: storyJSON('Sacred Frankincense', 'Hojari frankincense from Oman — the most prized resin on earth. It was the currency of ancient trade and the sacrifice of kings.', 'Lemon, Bergamot, Incense Smoke', 'Frankincense (Hojari), Myrrh, Elemi', 'Sandalwood, Amber, Labdanum', '100ML EDP', 'Rs 17,000 / $60'), price_pkr: 17000, price_usd: 60 },
    { name: 'Desert Rose Accord', slug: 'desert-rose-accord', description: 'Arid rose petals dried by the Saharan wind, with amber and sand accord. Ancient, elemental, sovereign.', story: storyJSON('Desert Rose Accord', 'In the desert, the rose that survives is the most powerful rose of all. This is that rose — sun-dried, amber-dusted, impossible to ignore.', 'Dry Rose, Saffron, Pink Pepper', 'Amber Rose, Desert Accord, Oud', 'Sand Amber, Vetiver, Musks', '100ML EDP', 'Rs 19,500 / $69'), price_pkr: 19500, price_usd: 69 },
    { name: 'Midnight Jasmine Absolute', slug: 'midnight-jasmine-absolute', description: 'Nocturnal jasmine absolute from Grasse, deepened with tuberose and warm amber. The sovereign night garden.', story: storyJSON('Midnight Jasmine Absolute', 'Jasmine at midnight — at the peak of its bloom — is the most seductive ingredient in all of perfumery. This is that moment, preserved.', 'Bergamot, Neroli, Pink Pepper', 'Jasmine Absolute, Tuberose, Ylang', 'Amber, Sandalwood, Musks', '100ML EDP', 'Rs 22,000 / $78'), price_pkr: 22000, price_usd: 78 },
    { name: 'Transparent Musk Signature', slug: 'transparent-musk-signature', description: 'An almost invisible musk accord — clean, warm, and deeply intimate. The sovereign signature that stays with you.', story: storyJSON('Transparent Musk Signature', 'The most personal fragrance we make — a transparent musk that merges with your skin chemistry to create something uniquely yours.', 'Bergamot, Light Aldehydes', 'Ambrette, Cashmeran, Clean Musks', 'Sandalwood, Ambroxan, White Musk', '100ML EDP', 'Rs 12,500 / $44'), price_pkr: 12500, price_usd: 44 },
    { name: 'Saffron & Gold', slug: 'saffron-gold', description: 'Pure Persian saffron with aged oud and warm golden amber. A unisex masterpiece of Eastern luxury.', story: storyJSON('Saffron & Gold', 'Saffron and gold — the two most coveted substances in the ancient world — fused into a single sovereign accord of impossible luxury.', 'Persian Saffron, Rose Petals', 'Aged Oud, Mellow Amber, Iris', 'Gold Accord, Sandalwood, Musk', '100ML EDP', 'Rs 25,500 / $90'), price_pkr: 25500, price_usd: 90 },
    { name: 'Rain on Dry Earth', slug: 'rain-dry-earth', description: 'The petrichor accord — rain on warm dry earth — with vetiver and woody amber. Nature bottled as luxury.', story: storyJSON('Rain on Dry Earth', 'Petrichor — the scent of rain on dry earth — is universally beloved. We\'ve captured this elemental phenomenon in its most refined form.', 'Petrichor Accord, Rain Water, Bergamot', 'Vetiver, Earth Accord, Geosmin', 'Woody Amber, Musk, Sandalwood', '100ML EDP', 'Rs 14,500 / $51'), price_pkr: 14500, price_usd: 51 },
  ]

  // ── COSMETICS ──────────────────────────────────────────────────────────────
  const cosmeticsMale = [
    { name: 'Charcoal Deep Cleanse', slug: 'charcoal-deep-cleanse', description: 'Premium activated charcoal face wash — removes pollution, excess oil, and impurities without stripping skin. Luxury barber grade.', story: cosStory('Charcoal Deep Cleanse', 'Premium activated charcoal from bamboo, combined with tea tree and aloe vera for a deep clean that leaves skin balanced.', ['Removes pollution & excess oil', 'Unclogs pores', 'Controls shine', 'pH balanced'], 'Wet face, apply small amount, massage 60 seconds, rinse with cool water.'), price_pkr: 3500, price_usd: 12 },
    { name: 'Ultra Hydrating Balm', slug: 'ultra-hydrating-balm', description: 'Non-greasy luxury moisturizer with hyaluronic acid and peptides. Repairs, hydrates, and strengthens the masculine skin barrier.', story: cosStory('Ultra Hydrating Balm', 'Formulated with 5 molecular weights of hyaluronic acid, this balm delivers hydration at every layer of the skin.', ['Repairs dry, tired skin', 'Non-greasy formula', 'Reduces fine lines', '48-hour hydration'], 'Apply morning and evening to clean skin. Pat gently — do not rub.'), price_pkr: 5500, price_usd: 20 },
    { name: 'Vitamin C Brightening Serum', slug: 'vitamin-c-serum-him', description: 'High-potency 20% vitamin C serum that eliminates dark spots, evens skin tone, and delivers an instant sovereign glow.', story: cosStory('Vitamin C Brightening Serum', '20% L-ascorbic acid combined with vitamin E and ferulic acid — the gold standard brightening combination.', ['Fades dark spots', 'Evens skin tone', 'Antioxidant protection', 'Brightens complexion'], 'Apply 3-4 drops to clean skin every morning before moisturizer and SPF.'), price_pkr: 7200, price_usd: 25 },
    { name: 'Anti-Fatigue Eye Rescue', slug: 'anti-fatigue-eye-him', description: 'Specialized eye cream that eliminates dark circles, puffiness, and fine lines. Premium formula for the sovereign executive.', story: cosStory('Anti-Fatigue Eye Rescue', 'Caffeine, retinol, and peptides combined to de-puff, brighten, and firm the delicate eye area overnight.', ['Eliminates dark circles', 'Reduces puffiness', 'Firms eye area', 'Hydrates deeply'], 'Apply pea-sized amount to eye area morning and evening. Tap gently with ring finger.'), price_pkr: 6500, price_usd: 23 },
    { name: 'Matte Shield SPF 50', slug: 'matte-shield-spf50', description: 'Zero-shine, zero-residue premium sunscreen with SPF 50+. Invisible protection for the sovereign man.', story: cosStory('Matte Shield SPF 50', 'Mineral and chemical hybrid sunscreen that dries completely matte. No white cast, no shine — just protected, sovereign skin.', ['SPF 50+ protection', 'Zero white cast', 'Matte finish', 'Lightweight fluid'], 'Apply 2 pumps 15 minutes before sun exposure. Reapply every 2 hours.'), price_pkr: 4800, price_usd: 17 },
    { name: 'Luxury Exfoliating Scrub', slug: 'exfoliating-scrub-him', description: 'Premium physical exfoliant with walnut shell powder and salicylic acid. Removes dead skin and blackheads twice weekly.', story: cosStory('Luxury Exfoliating Scrub', 'Walnut shell powder (finely milled), 2% salicylic acid, and kaolin clay for the deepest pore cleanse.', ['Removes dead skin', 'Unclogs blackheads', 'Smooths texture', 'Controls oil'], 'Apply to wet skin 2x per week. Massage for 90 seconds, rinse thoroughly.'), price_pkr: 4200, price_usd: 15 },
    { name: 'Pre-Shave Luxury Oil', slug: 'pre-shave-oil', description: 'Premium pre-shave oil with argan, castor, and vitamin E. Softens stubble and protects skin from razor burn.', story: cosStory('Pre-Shave Luxury Oil', 'Argan, jojoba, and castor oil — the holy trinity of shave oils — blended with vitamin E and cedarwood for the perfect glide.', ['Softens stubble', 'Prevents razor burn', 'Reduces ingrowns', 'Deeply conditions'], 'Apply 4-5 drops to wet face before shaving cream. Massage in circular motions.'), price_pkr: 3800, price_usd: 13 },
    { name: 'Triple Cushion Shave Cream', slug: 'triple-cushion-shave-cream', description: 'Rich, cushioning shaving cream that creates a dense lather for the closest, most comfortable sovereign shave.', story: cosStory('Triple Cushion Shave Cream', 'Triple the cushioning agents of a standard shaving cream — glycerin, aloe vera, and shea butter — for a razor-smooth shave.', ['Maximum razor glide', 'Prevents nicks', 'Hydrates while shaving', 'Rich dense lather'], 'Apply to wet face with brush or hands. Build lather before shaving.'), price_pkr: 3200, price_usd: 11 },
    { name: 'Calming Aftershave Balm', slug: 'aftershave-balm', description: 'Alcohol-free aftershave balm with aloe vera, chamomile, and allantoin. Instantly calms, repairs, and restores post-shave skin.', story: cosStory('Calming Aftershave Balm', 'Our alcohol-free formula uses aloe vera, chamomile extract, and allantoin to repair the skin barrier immediately after shaving.', ['Calms razor burn', 'Reduces redness', 'Alcohol-free formula', 'Speeds skin recovery'], 'Apply generously to freshly shaved skin. No need to rinse.'), price_pkr: 3600, price_usd: 13 },
    { name: 'Beard Growth Shine Oil', slug: 'beard-growth-shine-oil', description: 'Sovereign beard oil with castor, jojoba, and argan oil. Promotes growth, softens beard hair, and nourishes the skin beneath.', story: cosStory('Beard Growth Shine Oil', 'Black seed (nigella sativa), castor, argan, and jojoba oils — scientifically proven to promote beard growth and thickness.', ['Promotes beard growth', 'Softens beard hair', 'Nourishes skin beneath', 'Adds healthy shine'], 'Warm 3-5 drops between palms, apply to beard and massage into skin. Style as desired.'), price_pkr: 4500, price_usd: 16 },
    { name: 'Anti-Hairfall Caffeine Shampoo', slug: 'caffeine-shampoo', description: 'Clinically proven caffeine shampoo that strengthens hair roots and reduces hairfall by up to 60%. Luxury salon quality.', story: cosStory('Anti-Hairfall Caffeine Shampoo', 'Caffeine blocks DHT (the primary cause of hair loss) at the follicle level. Our formula also includes biotin and niacinamide.', ['Reduces hairfall 60%', 'Strengthens roots', 'Stimulates growth', 'Sulfate-free'], 'Apply to wet hair, massage into scalp for 2 minutes. Leave for 3 minutes, rinse.'), price_pkr: 5200, price_usd: 18 },
    { name: 'Matte Clay Styling', slug: 'matte-clay-styling', description: 'Premium salon-grade matte clay with medium-to-strong hold. All-day natural texture without any stickiness.', story: cosStory('Matte Clay Styling', 'Kaolin clay, beeswax, and lanolin combine to give professional hold with a completely natural matte finish.', ['Medium-strong hold', 'Zero stickiness', 'All-day texture', 'Water soluble'], 'Warm small amount between fingers, work through dry or damp hair. Style as desired.'), price_pkr: 3900, price_usd: 14 },
    { name: "Men's Concealer Stick", slug: 'mens-concealer-stick', description: 'Sweat-proof, skin-toned concealer stick for men. Instantly covers blemishes, dark circles, and redness. Undetectable.', story: cosStory("Men's Concealer Stick", 'Ultra-light formula with silica microspheres that blur imperfections while feeling weightless. Available in 12 sovereign shades.', ['Covers blemishes instantly', 'Sweat-proof formula', 'Undetectable finish', '12 shades available'], 'Apply directly to blemish or dark area. Blend with fingertip.'), price_pkr: 4100, price_usd: 15 },
    { name: 'Tinted Moisturizer Men', slug: 'tinted-moisturizer-men', description: 'Lightweight BB cream for men with SPF 20. Evens skin tone, hydrates, and provides invisible coverage. Sovereign grooming.', story: cosStory('Tinted Moisturizer Men', 'Our male-specific BB cream is 40% lighter than standard BB creams. Tinted with iron oxides for a natural skin match.', ['Evens skin tone', 'SPF 20 protection', 'Hydrates all day', 'Invisible coverage'], 'Apply evenly to face after skincare. Blend with fingertips or sponge.'), price_pkr: 4600, price_usd: 16 },
    { name: 'Hydrating Matte Lip Balm', slug: 'hydrating-matte-lip-balm', description: 'Non-shiny luxury lip balm with shea butter, beeswax, and vitamin E. Heals dry, chapped lips without any glossy finish.', story: cosStory('Hydrating Matte Lip Balm', 'Shea butter, beeswax, and castor oil in a matte formula. No shine, no stickiness — just deeply hydrated, sovereign lips.', ['Heals dry lips', 'Zero shine formula', 'Long-lasting moisture', 'Natural ingredients'], 'Apply as needed throughout the day. Best applied at bedtime for overnight repair.'), price_pkr: 2800, price_usd: 10 },
  ]

  const cosmeticsFemale = [
    { name: 'Hyaluronic Plump Serum', slug: 'hyaluronic-plump-serum', description: 'Multi-molecular hyaluronic acid serum that hydrates, plumps, and fills fine lines from within. Luxury skincare essentials.', story: cosStory('Hyaluronic Plump Serum', '5 molecular weights of hyaluronic acid deliver moisture at every skin layer — from the deepest dermis to the outermost surface.', ['Plumps and hydrates', 'Fills fine lines', 'Instant glow', 'Lightweight formula'], 'Apply 3-4 drops to damp skin morning and evening before moisturizer.'), price_pkr: 7800, price_usd: 28 },
    { name: 'Gentle Foaming Cleanser', slug: 'gentle-foaming-cleanser', description: 'A cloud-soft foaming cleanser that removes makeup, SPF, and impurities while preserving the skin\'s natural moisture barrier.', story: cosStory('Gentle Foaming Cleanser', 'Amino acid surfactants — the gentlest cleansing agents — combined with ceramides to clean without disrupting the skin barrier.', ['Removes all makeup', 'Preserves moisture barrier', 'Suitable for all skin types', 'pH balanced'], 'Dispense 2 pumps, massage onto wet face, rinse thoroughly with lukewarm water.'), price_pkr: 4200, price_usd: 15 },
    { name: 'Retinol Night Royale', slug: 'retinol-night-royale', description: 'Encapsulated retinol anti-aging night cream that reduces wrinkles, refines texture, and keeps skin youthfully sovereign.', story: cosStory('Retinol Night Royale', 'Encapsulated retinol releases slowly overnight for maximum efficacy with minimum irritation. Paired with peptides and niacinamide.', ['Reduces wrinkles', 'Refines skin texture', 'Stimulates collagen', 'Overnight transformation'], 'Apply pea-sized amount to face every other evening. Always use SPF the next morning.'), price_pkr: 9500, price_usd: 34 },
    { name: 'Vitamin C Glow Serum', slug: 'vitamin-c-glow-serum-her', description: 'Brightening vitamin C serum that eliminates dark spots and delivers instant radiance. The sovereign glow secret.', story: cosStory('Vitamin C Glow Serum', '15% stable vitamin C derivative combined with alpha arbutin and niacinamide for triple-action brightening.', ['Fades dark spots', 'Instant radiance', 'Evens skin tone', 'Antioxidant shield'], 'Apply 4-5 drops every morning to clean skin before moisturizer.'), price_pkr: 7200, price_usd: 25 },
    { name: 'Invisible Sunscreen', slug: 'invisible-sunscreen-her', description: 'Zero white cast, ultralightweight sunscreen with SPF 50+. The perfect base under makeup for the sovereign woman.', story: cosStory('Invisible Sunscreen', 'Hybrid mineral-chemical formula with PPD 42 for UVA protection. Applies invisible, dries to a silky finish.', ['SPF 50+ protection', 'Zero white cast', 'Makeup-ready finish', 'UVA/UVB shield'], 'Apply 1/2 teaspoon to face and neck 15 minutes before sun exposure.'), price_pkr: 5500, price_usd: 20 },
    { name: 'Under-Eye Brightener', slug: 'under-eye-brightener', description: 'High-performance eye cream with vitamin K, caffeine, and gold peptides that banishes dark circles and brightens the sovereign gaze.', story: cosStory('Under-Eye Brightener', 'Vitamin K reduces dark pigmentation, caffeine constricts blood vessels, and gold peptides firm the eye area.', ['Banishes dark circles', 'Reduces fine lines', 'Firms eye area', 'Brightens instantly'], 'Apply morning and evening. Tap gently with ring finger — never drag.'), price_pkr: 7500, price_usd: 27 },
    { name: 'Luminous Liquid Foundation', slug: 'luminous-liquid-foundation', description: 'Skin-like foundation with hyaluronic acid and SPF 20. Natural glow, full coverage, 24-hour wear. 22 sovereign shades.', story: cosStory('Luminous Liquid Foundation', 'Hyaluronic acid micro-spheres swell with moisture through the day, keeping skin dewy and luminous from 9am to midnight.', ['Full coverage', 'Natural glow finish', '24-hour wear', '22 shades available'], 'Dot 5 points on face, blend with brush or sponge using pressing motions.'), price_pkr: 8900, price_usd: 32 },
    { name: 'Full-Coverage Concealer', slug: 'full-coverage-concealer', description: 'Creamy, full-coverage concealer with vitamin C and collagen. Covers circles, blemishes, and imperfections — flawlessly.', story: cosStory('Full-Coverage Concealer', 'Creamy emollients for coverage, vitamin C to brighten, and collagen-stimulating peptides to improve skin over time.', ['Full coverage', 'Stays crease-free', 'Brightening formula', '18 shades'], 'Apply under eyes and blemishes. Blend with damp sponge immediately.'), price_pkr: 5800, price_usd: 21 },
    { name: 'Translucent Setting Powder', slug: 'translucent-setting-powder', description: 'Ultra-fine silk powder that locks makeup for 12+ hours and controls oil. The sovereign secret to all-day perfection.', story: cosStory('Translucent Setting Powder', 'Silk amino acids and ultra-fine silica create an air-light powder that sets makeup without adding texture or weight.', ['12-hour makeup lock', 'Oil control', 'Weightless formula', 'Suitable all skin tones'], 'Dust lightly over foundation using a fluffy brush. Build up for more coverage.'), price_pkr: 5200, price_usd: 18 },
    { name: 'Liquid Blush Highlighter Duo', slug: 'liquid-blush-highlighter-duo', description: 'A buildable liquid blush and illuminating highlighter in one. Cheeks glowing and cheekbones sculpted, sovereignly.', story: cosStory('Liquid Blush Highlighter Duo', 'Two formulas in one wand — a water-based liquid blush and an illuminating highlighter — for a fresh, lit-from-within look.', ['Buildable coverage', 'Natural flush', 'Luminous highlight', 'Lasting formula'], 'Apply 1-2 drops to cheeks, blend immediately with fingers or brush.'), price_pkr: 6400, price_usd: 23 },
    { name: 'Volumizing Mascara Waterproof', slug: 'volumizing-mascara-waterproof', description: 'Smudge-proof, waterproof mascara that lengthens, lifts, and dramatically volumises lashes. The sovereign lash standard.', story: cosStory('Volumizing Mascara Waterproof', 'Microfiber-enriched formula with a dual-sided brush — thickening fibres for volume and a fine tip for separation.', ['Waterproof formula', 'Dramatic volume', 'Lifts and lengthens', 'Smudge-proof'], 'Apply from root to tip with a zigzag motion. Allow to dry between coats.'), price_pkr: 5500, price_usd: 20 },
    { name: 'Nude Eyeshadow Palette', slug: 'nude-eyeshadow-palette', description: '18 luxuriously pressed nude and warm-toned eyeshadows for every sovereign look — from day to evening.', story: cosStory('Nude Eyeshadow Palette', '18 shades spanning mattes, shimmers, and glitters in coordinated nude and warm-nude families. Zero fallout formula.', ['18 versatile shades', 'Zero fallout formula', 'Day to evening looks', 'Pressed pigment'], 'Apply matte shades to lid, shimmer to centre, dark shade to crease.'), price_pkr: 9800, price_usd: 35 },
    { name: 'Precision Liquid Eyeliner', slug: 'precision-liquid-eyeliner', description: 'Ultra-fine 0.1mm tip liquid eyeliner with jet-black pigment. Perfect wings every time, all day, sovereign precision.', story: cosStory('Precision Liquid Eyeliner', 'Flexible micro-brush tip mirrors a calligraphy pen for the most precise line. Carbon-black pigment lasts 24 hours.', ['0.1mm precision tip', '24-hour formula', 'Jet-black pigment', 'Smudge-proof'], 'Shake gently. Draw from inner to outer corner with one smooth stroke.'), price_pkr: 4200, price_usd: 15 },
    { name: 'Velvet Matte Lipstick', slug: 'velvet-matte-lipstick', description: 'Long-wearing velvet matte lipstick that stays all day without drying. 20 sovereign shades from nude to deep red.', story: cosStory('Velvet Matte Lipstick', 'Hyaluronic acid and vitamin E in a matte formula — the impossible combination that delivers full-day wear without cracking.', ['All-day wear', 'Velvet matte finish', 'Non-drying formula', '20 sovereign shades'], 'Outline lips first with liner, apply from centre outward. Press lips together.'), price_pkr: 4600, price_usd: 16 },
    { name: 'Lip Glow Oil', slug: 'lip-glow-oil', description: 'High-shine, plumping lip oil with rosehip, jojoba, and vitamin E. Nourishes deeply while delivering a sovereign gloss.', story: cosStory('Lip Glow Oil', 'Rosehip oil (clinical-grade) combined with plumping peptides and colour-reactive pigments that enhance your natural lip tone.', ['Deep nourishment', 'High-shine finish', 'Natural plumping', 'Colour-reactive formula'], 'Apply as desired throughout the day. Layer over matte lipstick for a glazed look.'), price_pkr: 3800, price_usd: 14 },
  ]

  // ── JEWELRY ────────────────────────────────────────────────────────────────────
  const jewelryMale = [
    { name: 'Sovereign Signet Ring', slug: 'sovereign-signet-ring', description: 'Premium sterling silver signet ring with custom-engravable flat surface. Institutional elegance, sovereign statement.', story: jewStory('Sovereign Signet Ring', 'Sterling Silver 925 / 18K Gold Option', 'Flat-top design with bevelled edges. Available in sizes 8–14. Each ring can be personalized with initials or house crest.', 'Clean with soft polishing cloth. Store in provided sovereign pouch.'), price_pkr: 18500, price_usd: 65 },
    { name: 'Minimalist Band Ring', slug: 'minimalist-band-ring', description: 'Sleek, brushed stainless steel band for everyday sovereign wear. Indestructible, timeless, and effortlessly masculine.', story: jewStory('Minimalist Band Ring', 'Medical-grade Stainless Steel 316L', 'Width: 6mm / 8mm. Available in silver, black, and gold PVD finish. Comfort-fit internal curvature.', 'Rinse under warm water when needed. Polish with microfibre cloth.'), price_pkr: 8500, price_usd: 30 },
    { name: 'Aqeeq Gemstone Ring', slug: 'aqeeq-gemstone-ring', description: 'Natural aqeeq (agate) stone set in 925 silver. Traditional craftsmanship meets modern sovereign design.', story: jewStory('Aqeeq Gemstone Ring', '925 Sterling Silver with Natural Aqeeq Stone', 'Natural aqeeq from Yemen — each stone unique in pattern. Available with black, red, and green aqeeq variants.', 'Avoid chemicals and water. Clean stone with dry soft cloth only.'), price_pkr: 14500, price_usd: 51 },
    { name: 'Cuban Link Chain', slug: 'cuban-link-chain', description: 'Premium 18K gold-plated Cuban link chain with box clasp. 24-inch, 10mm width. The sovereign statement chain.', story: jewStory('Cuban Link Chain', '18K Gold Plated Stainless Steel 316L', '10mm width, 24-inch length. Box clasp with double safety lock. Tarnish-resistant plating (3-micron gold layer).', 'Keep away from water, perfume, and chemicals. Polish with provided cloth.'), price_pkr: 28000, price_usd: 99 },
    { name: 'Box Chain Fine', slug: 'box-chain-fine', description: 'Sleek 2mm box chain in sterling silver or gold. Wears alone as a statement or holds your sovereign pendant.', story: jewStory('Box Chain Fine', '925 Sterling Silver or 18K Gold Plated', '2mm width, available in 20/22/24 inch. Lobster clasp. Classic square link construction.', 'Store separately to prevent tangling. Polish with silver cloth monthly.'), price_pkr: 16500, price_usd: 58 },
    { name: 'Sovereign Dog Tag Pendant', slug: 'sovereign-dog-tag-pendant', description: 'Military-inspired dog tag pendant in stainless steel. Custom-engravable, waterproof, and sovereignly masculine.', story: jewStory('Sovereign Dog Tag Pendant', 'Stainless Steel 316L with Box Chain', '40mm × 25mm pendant. Engrave up to 3 lines of text. Comes with 24-inch box chain. Waterproof.', 'Waterproof — can be worn daily. Polish with microfibre cloth.'), price_pkr: 12500, price_usd: 44 },
    { name: 'Cuff Bracelet Steel', slug: 'cuff-bracelet-steel', description: 'Open-ended steel cuff bracelet, hand-hammered finish. Modern sovereign wristwear that commands respect.', story: jewStory('Cuff Bracelet Steel', 'Stainless Steel 316L', 'Width: 10mm. Hand-hammered texture. Available in silver and gunmetal. One size fits most (adjustable opening).', 'Wipe with dry cloth after wear. Avoid harsh chemicals.'), price_pkr: 9500, price_usd: 34 },
    { name: 'Premium Leather Bracelet', slug: 'premium-leather-bracelet', description: 'Hand-braided genuine leather bracelet with magnetic stainless steel clasp. Masculine luxury for the sovereign wrist.', story: jewStory('Premium Leather Bracelet', 'Full-Grain Leather with Stainless Steel Clasp', '8mm width, adjustable length 17-21cm. Magnetic clasp with safety lock. Available in black, cognac, and dark brown.', 'Condition leather every 3 months with leather balm. Keep dry.'), price_pkr: 7800, price_usd: 28 },
    { name: 'Black Onyx Bead Bracelet', slug: 'black-onyx-bead-bracelet', description: 'Natural black onyx beads on elastic cord with sterling silver spacers. Raw masculine energy, sovereign energy.', story: jewStory('Black Onyx Bead Bracelet', 'Natural Black Onyx with 925 Silver Spacers', '10mm natural onyx beads. Elastic cord, stretch fit. Available with gold or silver spacers. Can be stacked.', 'Clean beads with damp cloth. Avoid prolonged sun exposure.'), price_pkr: 11500, price_usd: 41 },
    { name: 'Statement Timepiece', slug: 'statement-timepiece', description: 'Stainless steel luxury dress watch with mineral crystal and sapphire-coated dial. The sovereign wrist statement.', story: jewStory('Statement Timepiece', 'Stainless Steel 316L Case with Mineral Crystal', '42mm case, 10ATM water resistance. Quartz movement. Available with mesh, link, or leather strap.', 'Service every 2 years. Avoid extreme magnets. Clean case with soft cloth.'), price_pkr: 45000, price_usd: 159 },
    { name: 'Mesh Watch Strap', slug: 'mesh-watch-strap', description: 'Premium stainless steel mesh watch strap — the most versatile, elegant strap upgrade for any sovereign timepiece.', story: jewStory('Mesh Watch Strap', 'Stainless Steel 316L Milanese Mesh', '20mm or 22mm lug width. Butterfly clasp with micro-adjust. Available in silver, gold, and rose gold.', 'Rinse under water if needed. Dry thoroughly. Polish with cloth.'), price_pkr: 5500, price_usd: 20 },
    { name: 'Premium Cufflinks', slug: 'premium-cufflinks', description: 'Silver or gold cufflinks with black enamel inlay. The finishing touch for the sovereign formal ensemble.', story: jewStory('Premium Cufflinks', '925 Sterling Silver with Enamel Inlay', 'Bullet-back closure. Diameter 15mm. Available in: plain silver, gold, black enamel, and navy enamel.', 'Polish with silver cloth. Store in provided pouch. Do not submerge in water.'), price_pkr: 9800, price_usd: 35 },
    { name: 'Gold Tie Clip', slug: 'gold-tie-clip', description: 'Slim gold-tone tie bar with a spring-loaded clamp. Keeps the sovereign\'s tie in perfect position all day.', story: jewStory('Gold Tie Clip', 'Brass with 18K Gold Plating', '57mm length. Spring-clip mechanism. Available in silver and gold. Fits ties 6-10cm wide.', 'Do not submerge in water. Polish with microfibre cloth.'), price_pkr: 6500, price_usd: 23 },
    { name: 'Sovereign Lapel Pin', slug: 'sovereign-lapel-pin', description: 'Premium gold-tone lapel pin with the Shamim Forever house crest. The sovereign mark on every suit.', story: jewStory('Sovereign Lapel Pin', 'Brass with 18K Gold Plating', '15mm diameter. Butterfly clutch back. Polished gold finish with fine detail engraving of the house crest.', 'Pin through lapel buttonhole or attach to collar. Polish with dry cloth.'), price_pkr: 4200, price_usd: 15 },
    { name: 'Collar Stays Premium', slug: 'collar-stays-premium', description: 'Solid brass collar stays in a set of 3 pairs. Keeps the sovereign collar crisp, sharp, and commanding.', story: jewStory('Collar Stays Premium', 'Solid Brass (Silver / Gold Finish)', 'Set of 3 pairs in sizes 50mm, 57mm, 65mm. Slide-in design fits standard collar channel. Comes in sovereign leather pouch.', 'Wipe clean with dry cloth. Store in provided pouch.'), price_pkr: 3800, price_usd: 14 },
  ]

  const jewelryFemale = [
    { name: 'Solitaire Diamond Pendant', slug: 'solitaire-diamond-pendant', description: 'Single VS1 diamond (0.25ct) pendant on an 18K white gold chain. Timeless, sovereign, unforgettable.', story: jewStory('Solitaire Diamond Pendant', '18K White Gold with VS1 Diamond', '0.25ct round brilliant diamond. GIA-certified. 18-inch box chain included. Perfect for layering.', 'Clean with soft brush and warm soapy water. Store separately.'), price_pkr: 95000, price_usd: 339 },
    { name: 'Layered Chain Set', slug: 'layered-chain-set', description: 'Three delicate gold chains in graduating lengths — a sovereign layered look, effortlessly perfect.', story: jewStory('Layered Chain Set', '18K Gold Plated 925 Silver', 'Three chains: 16", 18", 20". Box, cable, and rope chain styles. Lobster clasps. Can be worn separately.', 'Store in anti-tarnish pouch. Avoid water and perfume.'), price_pkr: 22000, price_usd: 78 },
    { name: 'Pearl Choker Necklace', slug: 'pearl-choker-necklace', description: 'Freshwater pearl choker on a white gold chain. A sovereign piece that has graced royal necks for centuries.', story: jewStory('Pearl Choker Necklace', 'Freshwater Pearls with 18K White Gold Chain', 'AAA-grade freshwater pearls, 7-8mm diameter. 14-inch choker length. Lobster clasp. Available in white and champagne.', 'Wipe pearls with soft damp cloth. Apply makeup/perfume before wearing.'), price_pkr: 45000, price_usd: 159 },
    { name: 'Statement Gem Neckpiece', slug: 'statement-gem-neckpiece', description: 'Heavy statement necklace with Swarovski crystals and gold-tone setting. Made for weddings, galas, and sovereign events.', story: jewStory('Statement Gem Neckpiece', 'Brass Base with 18K Gold Plating and Swarovski Crystals', 'Adjustable length 16-20 inches. Three rows of crystals. Weight 85g. Gift-boxed.', 'Store flat to prevent tangling. Clean crystals with dry soft cloth.'), price_pkr: 38000, price_usd: 135 },
    { name: 'Classic Diamond Studs', slug: 'classic-diamond-studs', description: 'Timeless 0.1ct diamond stud earrings in 18K white gold. The sovereign woman\'s essential daily piece.', story: jewStory('Classic Diamond Studs', '18K White Gold with Diamond', '0.10ct total weight. Push-back closure. Diameter 4mm. GIA certified. Available in yellow and rose gold.', 'Clean with soft brush and soapy water monthly. Store in padded box.'), price_pkr: 58000, price_usd: 205 },
    { name: 'Gold Hoop Earrings', slug: 'gold-hoop-earrings', description: 'Classic 18K gold hoop earrings in three sizes — small, medium, and large. The most versatile piece in any sovereign wardrobe.', story: jewStory('Gold Hoop Earrings', '18K Gold Plated 925 Sterling Silver', 'Diameters: 20mm, 35mm, 50mm. Post-and-click closure. Hinged for easy wearing.', 'Avoid water and chemicals. Polish with gold cloth.'), price_pkr: 16500, price_usd: 58 },
    { name: 'Pearl Drop Earrings', slug: 'pearl-drop-earrings', description: 'South Sea pearl drops on 18K yellow gold ear wires. Luxury craftsmanship for the sovereign woman.', story: jewStory('Pearl Drop Earrings', '18K Gold with South Sea Pearls', '10-11mm South Sea pearls, AAA grade. Total drop length 25mm. French wire closure.', 'Wipe with soft cloth. Apply perfume before wearing. Store separately.'), price_pkr: 75000, price_usd: 265 },
    { name: 'Crystal Ear Cuff Set', slug: 'crystal-ear-cuff-set', description: 'Set of three gold-tone ear cuffs with pavé crystals. No piercing required — the sovereign statement for any outfit.', story: jewStory('Crystal Ear Cuff Set', '18K Gold Plated Brass with Cubic Zirconia', 'Set of 3 cuffs in small, medium, and large. Fits 2-5mm ear cartilage. Adjustable.', 'Slide onto ear cartilage — no piercing needed. Clean with dry cloth.'), price_pkr: 12500, price_usd: 44 },
    { name: 'Diamond Eternity Band', slug: 'diamond-eternity-band', description: 'Full eternity band with 1.5ct of round brilliant diamonds in 18K white gold. The circle of sovereign love.', story: jewStory('Diamond Eternity Band', '18K White Gold with 1.5ct Diamonds', 'Full eternity: 30 diamonds, 0.05ct each, VS2, F-G colour. Available in yellow and rose gold.', 'Professional clean every 6 months. Insure before wearing daily.'), price_pkr: 185000, price_usd: 655 },
    { name: 'Stackable Ring Set', slug: 'stackable-ring-set', description: 'Set of four ultra-thin stackable bands in gold and rose gold. Mix and match for your sovereign expression.', story: jewStory('Stackable Ring Set', '18K Gold Plated 925 Sterling Silver', 'Set of 4 rings: 1.5mm width each. Two gold, two rose gold. Available in sizes 4-10.', 'Stack on any finger. Polish with gold cloth. Avoid chlorine.'), price_pkr: 18500, price_usd: 65 },
    { name: 'Cocktail Statement Ring', slug: 'cocktail-statement-ring', description: 'Oversized emerald-cut CZ cocktail ring in 18K gold. The sovereign centrepiece for any occasion.', story: jewStory('Cocktail Statement Ring', '18K Gold Plated Brass with Emerald-cut CZ', '15mm × 20mm emerald-cut cubic zirconia, 8ct equivalent. Sovereign prong setting. Sizes 5-10.', 'Remove before washing hands. Store in box provided.'), price_pkr: 22000, price_usd: 78 },
    { name: 'Tennis Bracelet', slug: 'tennis-bracelet', description: 'A continuous line of prong-set cubic zirconia in 18K white gold. The sovereign essential bracelet for every wrist.', story: jewStory('Tennis Bracelet', '18K White Gold Plated Silver with Cubic Zirconia', '4mm round CZ, 7 inches. Box clasp with safety. Available in yellow and rose gold.', 'Keep away from chlorine. Clean with soft brush and lukewarm water.'), price_pkr: 35000, price_usd: 124 },
    { name: 'Charm Bracelet Sovereign', slug: 'charm-bracelet-sovereign', description: 'Gold chain bracelet with five pre-loaded luxury charms — customizable with additional sovereign charms.', story: jewStory('Charm Bracelet Sovereign', '18K Gold Plated 925 Silver', '7.5 inch chain, lobster clasp. Five charms included: crown, star, key, heart, and SF initial. Add more charms sold separately.', 'Clean with soft cloth. Add new charms using a charm tool.'), price_pkr: 19500, price_usd: 69 },
    { name: 'Open Bangle Cuff Gold', slug: 'open-bangle-cuff-gold', description: 'Sleek open-ended gold cuff bangle. Hammered texture for artisan feel. The sovereign minimalist\'s essential bracelet.', story: jewStory('Open Bangle Cuff Gold', '18K Gold Plated Brass', 'Width: 8mm. Open-ended, one size fits most. Hammered finish. Available in silver and rose gold.', 'Avoid water. Buff with gold cloth when needed.'), price_pkr: 8500, price_usd: 30 },
    { name: 'Minimalist Pearl Anklet', slug: 'pearl-anklet', description: 'Delicate gold anklet with freshwater pearl stations. Subtle sovereign elegance for the ankle.', story: jewStory('Minimalist Pearl Anklet', '18K Gold Plated Silver with Freshwater Pearls', '9-11 inch adjustable length. 5mm freshwater pearls. Lobster clasp. Can be worn in water.', 'Rinse with fresh water after salt water exposure. Store dry.'), price_pkr: 9800, price_usd: 35 },
  ]

  // ── Map products with category IDs and insert ─────────────────────────────
  function mapProducts(products: any[], mainCatId: string, subCatId: string | null, imgBase: string) {
    return products.map(p => ({
      ...p,
      main_category_id: mainCatId,
      sub_category_id: subCatId,
      images: [imgBase],
      is_featured: Math.random() > 0.6,
      is_active: true,
      inventory: Math.floor(Math.random() * 80) + 20,
    }))
  }

  const allProducts = [
    ...mapProducts(perfumeMale, perfumeId, maleId, PERF_M),
    ...mapProducts(perfumeFemale, perfumeId, femaleId, PERF_F),
    ...mapProducts(perfumeUnisex, perfumeId, unisexId, PERF_U),
    ...mapProducts(cosmeticsMale, cosmeticsId, maleId, PLACEHOLDER_IMG),
    ...mapProducts(cosmeticsFemale, cosmeticsId, femaleId, PLACEHOLDER_IMG),
    ...mapProducts(jewelryMale, jewelryId, maleId, PLACEHOLDER_IMG),
    ...mapProducts(jewelryFemale, jewelryId, femaleId, PLACEHOLDER_IMG),
  ]

  // Insert in batches of 20
  let inserted = 0
  let errors: string[] = []

  for (let i = 0; i < allProducts.length; i += 20) {
    const batch = allProducts.slice(i, i + 20)
    const { data, error } = await supabase.from('products').upsert(batch, { onConflict: 'slug', ignoreDuplicates: false }).select('id')
    if (error) errors.push(error.message)
    else inserted += data?.length ?? 0
  }

  return NextResponse.json({
    success: errors.length === 0,
    inserted,
    total: allProducts.length,
    breakdown: {
      perfumes: { male: perfumeMale.length, female: perfumeFemale.length, unisex: perfumeUnisex.length },
      cosmetics: { male: cosmeticsMale.length, female: cosmeticsFemale.length },
      jewelry: { male: jewelryMale.length, female: jewelryFemale.length },
    },
    errors: errors.length > 0 ? errors : undefined,
    sub_categories_found: { maleId, femaleId, unisexId },
  })
}
