import Link from 'next/link'
import { HOUSE_CHAPTERS } from '@/lib/the-house-content'
import HouseChapter from './HouseChapter'

export default function TheHousePage() {
  return (
    <main className="bg-[#050505] text-zinc-200">
      <header className="relative overflow-hidden border-b border-[#15120f] px-5 py-28 md:px-12 md:py-40"><div className="pointer-events-none absolute left-1/2 top-1/2 h-[440px] w-[440px] -translate-x-1/2 -translate-y-1/2 rounded-full bg-[#c9a054]/[0.06] blur-[120px]" /><div className="relative mx-auto max-w-[1100px]"><p className="text-[9px] uppercase tracking-[0.5em] text-[#c9a054]">LEARN · THE HOUSE</p><h1 className="mt-7 max-w-4xl font-serif text-5xl font-light leading-[0.95] text-[#f3efe7] md:text-8xl">The architecture<br /><span className="text-[#c9a054]">behind the name.</span></h1><p className="mt-8 max-w-2xl text-base leading-8 text-zinc-400 md:text-lg">Understanding the institution behind Shamim Forever — its founding philosophy, sovereign luxury architecture, leadership, craftsmanship, global presence, private client culture, heritage, innovation, and long-term vision.</p><div className="mt-10 flex flex-wrap gap-3 text-[9px] uppercase tracking-[0.28em] text-zinc-600"><span className="border border-[#211b14] px-3 py-2">35 chapters</span><span className="border border-[#211b14] px-3 py-2">The House pillar</span><span className="border border-[#211b14] px-3 py-2">Built for continuity</span></div></div></header>
      <div className="mx-auto grid max-w-[1280px] gap-14 px-5 py-16 md:px-12 md:py-24 lg:grid-cols-[220px_1fr] lg:gap-20">
        <aside className="lg:sticky lg:top-24 lg:h-fit"><p className="text-[9px] uppercase tracking-[0.4em] text-[#c9a054]">Contents</p><nav className="mt-5 grid grid-cols-2 gap-x-5 gap-y-3 lg:grid-cols-1">{HOUSE_CHAPTERS.map((chapter) => <a key={chapter.slug} href={'#' + chapter.slug} className="text-[9px] uppercase tracking-[0.16em] text-zinc-600 transition-colors hover:text-[#c9a054]"><span className="mr-2 text-[#c9a054]/70">{chapter.number}</span>{chapter.title}</a>)}</nav></aside>
        <section><div className="max-w-3xl border-b border-[#1b1814] pb-12"><p className="text-[9px] uppercase tracking-[0.42em] text-[#c9a054]">The House, in continuity</p><h2 className="mt-4 font-serif text-3xl font-light leading-tight text-[#f3efe7] md:text-5xl">More than products. A living institution.</h2><p className="mt-6 text-sm leading-8 text-zinc-400">Shamim Forever is not intended to be understood merely as a collection of products, boutiques, services, or luxury experiences. The House is the system behind them: the people, standards, rituals, infrastructure, and long-term vision through which the institution operates.</p><p className="mt-5 text-sm leading-8 text-zinc-500">Read this page as a map. Each chapter is a foundation for a deeper knowledge path that can grow with the House.</p></div>{HOUSE_CHAPTERS.map((chapter) => <HouseChapter key={chapter.slug} chapter={chapter} />)}<div className="border-t border-[#1b1814] py-16"><p className="text-[9px] uppercase tracking-[0.42em] text-[#c9a054]">Shamim Forever</p><h2 className="mt-4 max-w-2xl font-serif text-3xl font-light leading-tight text-[#f3efe7] md:text-5xl">Built From Love.<br /><span className="text-[#c9a054]">Forged Into Legacy.</span></h2><p className="mt-6 max-w-2xl text-sm leading-8 text-zinc-500">The House exists to create objects with meaning, experiences with intention, relationships with trust, infrastructure with continuity, and a legacy capable of outliving the present.</p><div className="mt-9 flex flex-wrap gap-3"><Link href="/learn" className="bg-[#c9a054] px-5 py-3 text-[9px] uppercase tracking-[0.24em] text-[#050505]">Back to Learn</Link><Link href="/founder-leadership" className="border border-[#c9a054]/50 px-5 py-3 text-[9px] uppercase tracking-[0.24em] text-[#c9a054]">Meet the leadership</Link><Link href="/atelier" className="border border-[#262019] px-5 py-3 text-[9px] uppercase tracking-[0.24em] text-zinc-500">Enter the Atelier</Link></div></div></section>
      </div>
    </main>
  )
}
