export type Article = { title: string; eyebrow: string; intro: string; sections: { heading: string; body: string }[] }
export const articles: Record<string, Article> = {
'what-is-authenticity': { title:'What Is Authenticity?', eyebrow:'01 · Foundations', intro:'Authenticity is the relationship between an object and the evidence supporting its origin, identity, provenance, integrity, and continuity.', sections:[
 {heading:'Authenticity is evidence',body:'A name can be copied. A logo can be reproduced. Packaging can be imitated, and a document can be separated from the object it describes. Authenticity is therefore a reasoned assessment of whether available evidence forms a coherent relationship with the physical object.'},
 {heading:'The object and its documentary form',body:'Every object has a physical form: what can be seen, touched, measured, and examined. It also has a documentary form: identity, creation record, provenance, service history, and other connected information. The challenge is keeping these forms connected over time.'},
 {heading:'Why certainty needs discipline',body:'Records are not always complete. Ownership may be private, archives may contain gaps, and evidence may conflict or be unavailable. A responsible framework distinguishes verified, consistent, under review, insufficient evidence, and discrepancy identified.'},
 {heading:'A working principle',body:'The more precisely an object is described, and the more independently its identity and history can be examined, the stronger the basis for an assessment. Technology can preserve evidence; it cannot make an unsupported claim true.'}]},
'provenance': { title:'Luxury Product Provenance', eyebrow:'02 · History', intro:'Provenance is the documented history and journey of an object from creation through the stages that can be responsibly recorded.', sections:[
 {heading:'A chain, not a single receipt',body:'A provenance chain may include creation, House registration, atelier records, boutique allocation, acquisition, authorized transfer, service, restoration, and heritage preservation. Not every object contains every stage; the value is understanding which links exist and how confidently they connect.'},
 {heading:'Gaps are not automatic proof',body:'Records can be lost, private, or never created. An absent document does not automatically prove that an object is inauthentic. It changes how much historical evidence is available and should be stated plainly.'},
 {heading:'Public, authorized, and private',body:'Public evidence can explain a House or collection. Authorized evidence can be available to verified parties. Private evidence can remain protected while still contributing to an internal record.'},
 {heading:'Preserving a story',body:'The purpose of provenance is to preserve a defensible relationship between an object and its documented story so future care, service, restoration, and inheritance can be handled with more intelligence.'}]},
'object-identity': { title:'Object Identity in Luxury', eyebrow:'03 · Identity', intro:'A generic description is weak evidence. A precise identity gives an object something specific to examine.', sections:[
 {heading:'From category to identity',body:'Luxury handbag, rare fragrance, couture object, or jewellery piece is a category—not a complete identity. A stronger description includes collection, design reference, materials, construction, craftsmanship, creation period, and authorized identifiers.'},
 {heading:'Identity must remain connected',body:'A number by itself is not identity. A serial or reference can be copied, duplicated, or fabricated. It becomes more useful when connected to physical characteristics, creation record, House identity, and authorized history.'},
 {heading:'Time changes design',body:'Collections evolve. Materials, proportions, finishes, and production methods change. A responsible examination asks whether claimed characteristics existed during the claimed period: identity understood within time.'},
 {heading:'The identity record',body:'A mature identity record connects object, identifier, attributes, records, and verification. The goal is to make description specific enough that evidence can be compared rather than imagined.'}]},
'materials': { title:'Materials and Craftsmanship as Evidence', eyebrow:'04 · Making', intro:'Material and the hand of the maker can provide evidence, but neither should become mythology or a standalone verdict.', sections:[
 {heading:'Materials tell part of the story',body:'Composition, construction, texture, aging, wear, manufacturing characteristics, and consistency can be relevant. Yet an imitation may use similar materials. Material examination is one part of a larger system.'},
 {heading:'The hand leaves information',body:'Depending on the object, examination may consider construction, stitching, assembly, finishing, proportions, material handling, and design consistency. Not every handmade variation proves authenticity, and not every perfect finish proves originality.'},
 {heading:'Context is the multiplier',body:'A material observation becomes more useful when it agrees with the claimed collection, period, construction method, and provenance. Independent signals pointing in the same direction are stronger than one convincing detail.'},
 {heading:'Document, do not romanticize',body:'The language of luxury can be beautiful without becoming vague. A serious record describes what was observed, what it supports, what remains unknown, and which evidence would improve the assessment.'}]},
'digital-authenticity': { title:'Digital Authenticity and Provenance', eyebrow:'05 · Infrastructure', intro:'Digital information can preserve a relationship between an object and its record, but digital does not automatically mean secure or true.', sections:[
 {heading:'A record needs governance',body:'A digital record requires integrity, access control, security, traceability, and governance. It should be possible to understand when it was created, how it changed, who can access it, and what evidence was attached.'},
 {heading:'A QR code is only a doorway',body:'A QR code directs someone to information and can be copied. The question is what exists behind it: controlled destination, specific identity, authorized access, and a continuing connection to the physical object.'},
 {heading:'Blockchain has a defined role',body:'Blockchain may help with record integrity, timestamping, and traceability. It cannot establish that physical information entered into a record was true. Recording false information immutably does not make it true.'},
 {heading:'The physical-to-digital trust problem',body:'Every digital authenticity architecture has an oracle problem: who confirmed the original physical information? Technology can improve how trust is documented; it cannot eliminate accountable examination.'}]},
'authentication-guide': { title:'A Responsible Luxury Authentication Guide', eyebrow:'06 · Practice', intro:'Responsible authentication examines the relationship between identity, provenance, and evidence instead of searching for one theatrical detail.', sections:[
 {heading:'Step 01 · Identify the object',body:'Describe category, collection, reference, materials, construction, claimed period, and authorized identifiers. Avoid conclusions before identity is specific.'},
 {heading:'Step 02 · Review what exists',body:'Gather records, documentation, images, service history, and provenance. Separate confirmed information from statements not independently supported.'},
 {heading:'Step 03 · Compare signals',body:'Examine identity, materials, construction, craftsmanship, design consistency, and chronology. Look for agreement across independent signals.'},
 {heading:'Step 04 · State the limit',body:'Document uncertainty. An outcome may be verified, consistent, under review, insufficient evidence, or discrepancy identified. The conclusion should reflect evidence available.'}]},
}
