export type ForHimPerfumeDefinition = {
  code: string
  reference: string
  name: string
  slug: string
  referenceConcentration: string
  priceUsd: number
  family: string
  gender: string
  top: string[]
  heart: string[]
  base: string[]
  creation: string
  identity: string
  opening: string
  development: string
  dryDown: string
  whenToWear: string
}

const disclaimer =
  'An original Shamim Forever fragrance inspired by the olfactory profile named in the reference field. It is not made by, affiliated with, endorsed by, licensed by, or authorized by that reference brand.'

export const FOR_HIM_PERFUME_CATALOG: ForHimPerfumeDefinition[] = [
  {
    code: 'SF-FM-001',
    reference: 'Dior Sauvage',
    name: 'SF Sovereign Sauvage',
    slug: 'sf-sovereign-sauvage',
    referenceConcentration: 'EDT reference profile',
    priceUsd: 178,
    family: 'Fresh aromatic woody',
    gender: 'Masculine-leaning profile',
    top: ['Calabrian bergamot accord', 'cracked pepper', 'cool grapefruit'],
    heart: ['lavender', 'geranium leaf', 'mineral sage'],
    base: ['ambroxan accord', 'dry cedar', 'labdanum'],
    creation: 'A bright, wind-cut composition built for the first step into a room: clean citrus lifted by a mineral aromatic core and a dry, persistent trail.',
    identity: 'SF Sovereign Sauvage interprets the fresh aromatic power profile through a Shamim Forever lens, with a polished mineral texture rather than a copied formula.',
    opening: 'Bergamot and pepper arrive with a brisk, open-air clarity.',
    development: 'Lavender, geranium, and sage give the middle a cool tailored shape.',
    dryDown: 'Ambroxan, cedar, and labdanum settle close to the skin with a clean ambered edge.',
    whenToWear: 'Daytime leadership, travel, warm weather, and occasions that call for confident freshness.',
  },
  {
    code: 'SF-FM-002',
    reference: 'Dior Sauvage Elixir',
    name: 'SF Sauvage Elixir Noir',
    slug: 'sf-sauvage-elixir-noir',
    referenceConcentration: 'Parfum reference profile',
    priceUsd: 218,
    family: 'Spiced aromatic amber',
    gender: 'Masculine-leaning profile',
    top: ['cinnamon bark', 'grapefruit peel', 'cardamom'],
    heart: ['lavender absolute', 'nutmeg', 'licorice root'],
    base: ['rich woods', 'amber resin', 'patchouli'],
    creation: 'A darker interpretation of aromatic command, composed around warm spice, dense lavender, and a restrained resinous foundation.',
    identity: 'This Shamim Forever original takes the reference profile as a direction for intensity, not as a claim of identical ingredients or construction.',
    opening: 'Cinnamon and grapefruit create a vivid, dark-gold spark.',
    development: 'Lavender absolute and nutmeg deepen the structure without losing lift.',
    dryDown: 'Rich woods and amber resin leave a measured, nocturnal signature.',
    whenToWear: 'Cool evenings, formal dinners, and close-set occasions where depth matters.',
  },
  {
    code: 'SF-FM-003',
    reference: 'Dior Homme Intense',
    name: 'SF Homme Intense',
    slug: 'sf-homme-intense',
    referenceConcentration: 'EDP reference profile',
    priceUsd: 198,
    family: 'Woody powdery amber',
    gender: 'Masculine-leaning profile',
    top: ['pear skin', 'lavender', 'bergamot'],
    heart: ['iris accord', 'ambrette seed', 'violet'],
    base: ['cedarwood', 'vetiver', 'soft amber'],
    creation: 'An urban iris study with a soft tailored opening, a cool floral heart, and a smooth wood finish that never becomes sugary.',
    identity: 'SF Homme Intense is an original Shamim Forever interpretation of the elegant woody-iris profile associated with the reference fragrance.',
    opening: 'Pear skin and bergamot give the first impression a polished, almost satin-like lift.',
    development: 'Iris and ambrette form a cool, powdery center with quiet authority.',
    dryDown: 'Cedar, vetiver, and soft amber keep the finish dry, elegant, and wearable.',
    whenToWear: 'Black-tie evenings, gallery visits, and composed autumn or winter dressing.',
  },
  {
    code: 'SF-FM-004',
    reference: 'Bleu de Chanel',
    name: 'SF Bleu Sovereign',
    slug: 'sf-bleu-sovereign',
    referenceConcentration: 'EDT reference profile',
    priceUsd: 175,
    family: 'Citrus aromatic woody',
    gender: 'Masculine-leaning profile',
    top: ['grapefruit', 'lemon zest', 'mint leaf'],
    heart: ['ginger', 'incense', 'cedar leaf'],
    base: ['sandalwood', 'dry amber', 'white musk'],
    creation: 'A clean architectural blue fragrance where citrus, incense, and woods are balanced for an uninterrupted daily signature.',
    identity: 'The Shamim Forever interpretation preserves the reference profile’s poised versatility while using original editorial language and construction.',
    opening: 'Grapefruit, lemon, and mint cut through with a crisp tailored brightness.',
    development: 'Ginger and incense add lift and a subtle smoky line through the center.',
    dryDown: 'Sandalwood and dry amber create a calm, understated base.',
    whenToWear: 'Office hours, daytime ceremonies, and year-round signature wear.',
  },
  {
    code: 'SF-FM-005',
    reference: 'Bleu de Chanel Parfum',
    name: 'SF Bleu Sovereign Parfum',
    slug: 'sf-bleu-sovereign-parfum',
    referenceConcentration: 'Parfum reference profile',
    priceUsd: 205,
    family: 'Woody aromatic',
    gender: 'Masculine-leaning profile',
    top: ['lemon peel', 'bergamot', 'lavender'],
    heart: ['green woods', 'geranium', 'cedar'],
    base: ['sandalwood', 'amberwood', 'tonka'],
    creation: 'A denser blue composition shaped around the quiet confidence of polished woods and a measured citrus opening.',
    identity: 'SF Bleu Sovereign Parfum is a Shamim Forever original with a smoother, more intimate reading of the reference profile.',
    opening: 'Citrus peel flashes cleanly before the composition settles into green woods.',
    development: 'Geranium and cedar make the heart feel precise and quietly formal.',
    dryDown: 'Sandalwood, amberwood, and tonka leave a warm, refined contour.',
    whenToWear: 'Evening tailoring, client dinners, and cooler months when a smooth trail is preferred.',
  },
  {
    code: 'SF-FM-006',
    reference: 'Creed Aventus',
    name: 'SF Aventus Sovereign',
    slug: 'sf-aventus-sovereign',
    referenceConcentration: 'EDP reference profile',
    priceUsd: 220,
    family: 'Fruity smoky chypre',
    gender: 'Masculine-leaning profile',
    top: ['pineapple leaf', 'blackcurrant', 'apple peel'],
    heart: ['birch smoke', 'jasmine', 'rose pepper'],
    base: ['oakmoss', 'musk', 'dry vanilla'],
    creation: 'A confident fruit-and-smoke composition that moves from bright orchard air into a polished, mossy trail.',
    identity: 'This original SF interpretation uses the reference profile’s contrast of fruit and smoke without suggesting the same formula or maker.',
    opening: 'Pineapple leaf and blackcurrant create a bright, textured first impression.',
    development: 'Birch smoke gives the heart an elegant charred edge softened by jasmine.',
    dryDown: 'Oakmoss, musk, and dry vanilla build a long, quietly assertive finish.',
    whenToWear: 'Milestones, presentations, evening receptions, and transitional seasons.',
  },
  {
    code: 'SF-FM-007',
    reference: 'Creed Green Irish Tweed',
    name: 'SF Irish Sovereign',
    slug: 'sf-irish-sovereign',
    referenceConcentration: 'EDP reference profile',
    priceUsd: 192,
    family: 'Green aromatic fougère',
    gender: 'Masculine-leaning profile',
    top: ['lemon verbena', 'peppermint', 'fresh violet leaf'],
    heart: ['iris', 'geranium', 'clover'],
    base: ['sandalwood', 'ambergris accord', 'moss'],
    creation: 'A green tailored fragrance designed around rain-washed fields, cool herbs, and a soft cream of woods.',
    identity: 'SF Irish Sovereign is a Shamim Forever original interpretation of the reference profile’s green, clean, gentlemanly character.',
    opening: 'Lemon verbena and mint feel bright, wet, and freshly pressed.',
    development: 'Iris and geranium bring a soft floral polish to the green heart.',
    dryDown: 'Sandalwood and moss settle into a calm, natural trail.',
    whenToWear: 'Daytime country settings, spring ceremonies, and understated business wear.',
  },
  {
    code: 'SF-FM-008',
    reference: 'Giorgio Armani Acqua di Giò',
    name: 'SF Aqua Sovereign',
    slug: 'sf-aqua-sovereign',
    referenceConcentration: 'EDT reference profile',
    priceUsd: 168,
    family: 'Aquatic citrus aromatic',
    gender: 'Masculine-leaning profile',
    top: ['marine air', 'bergamot', 'green mandarin'],
    heart: ['rosemary', 'persimmon', 'neroli'],
    base: ['cedar', 'patchouli', 'clean musk'],
    creation: 'A transparent marine composition with a sunlit citrus opening and a cedar backbone made for movement.',
    identity: 'The Shamim Forever version is original editorial work inspired by a Mediterranean aquatic reference profile.',
    opening: 'Marine air and green mandarin arrive with a clear, salt-bright lift.',
    development: 'Rosemary, persimmon, and neroli keep the center airy and aromatic.',
    dryDown: 'Cedar, patchouli, and clean musk provide a dry, dependable close.',
    whenToWear: 'Summer days, seaside travel, casual tailoring, and active afternoons.',
  },
  {
    code: 'SF-FM-009',
    reference: 'Acqua di Giò Parfum',
    name: 'SF Aqua Sovereign Parfum',
    slug: 'sf-aqua-sovereign-parfum',
    referenceConcentration: 'Parfum reference profile',
    priceUsd: 198,
    family: 'Marine woody aromatic',
    gender: 'Masculine-leaning profile',
    top: ['sea mist', 'bergamot', 'rosemary'],
    heart: ['cypress', 'clary sage', 'geranium'],
    base: ['mineral woods', 'patchouli', 'incense'],
    creation: 'A deeper marine study where oceanic clarity is anchored by cypress, sage, and a restrained line of incense.',
    identity: 'SF Aqua Sovereign Parfum is an original Shamim Forever fragrance guided by the reference profile’s marine-woody balance.',
    opening: 'Sea mist and bergamot open with a cool, mineral clarity.',
    development: 'Cypress and sage give the heart a green, sculptural quality.',
    dryDown: 'Mineral woods, patchouli, and incense hold the finish close and composed.',
    whenToWear: 'Warm evenings, resort dressing, and formal occasions near the water.',
  },
  {
    code: 'SF-FM-010',
    reference: 'Yves Saint Laurent Y Eau de Parfum',
    name: 'SF Y Sovereign',
    slug: 'sf-y-sovereign',
    referenceConcentration: 'EDP reference profile',
    priceUsd: 182,
    family: 'Aromatic fruity woody',
    gender: 'Masculine-leaning profile',
    top: ['apple skin', 'ginger', 'bergamot'],
    heart: ['sage', 'juniper', 'geranium'],
    base: ['fir balsam', 'cedarwood', 'tonka'],
    creation: 'A modern aromatic built around crisp fruit, green herbs, and a clean forested base with an easy evening transition.',
    identity: 'SF Y Sovereign is an original Shamim Forever composition inspired by the reference profile’s bright, contemporary confidence.',
    opening: 'Apple and ginger give the first spray a bright, energetic snap.',
    development: 'Sage and juniper add a cool green middle with tailored edges.',
    dryDown: 'Fir balsam, cedar, and tonka make the finish smooth without heaviness.',
    whenToWear: 'Workdays, city nights, and versatile year-round rotation.',
  },
  {
    code: 'SF-FM-011',
    reference: 'Yves Saint Laurent La Nuit de L’Homme',
    name: 'SF Nuit Royale',
    slug: 'sf-nuit-royale',
    referenceConcentration: 'EDT reference profile',
    priceUsd: 176,
    family: 'Spiced woody aromatic',
    gender: 'Masculine-leaning profile',
    top: ['cardamom', 'bergamot', 'black pepper'],
    heart: ['lavender', 'cedar', 'violet leaf'],
    base: ['vetiver', 'coumarin', 'amberwood'],
    creation: 'A night-focused cardamom composition with a soft pulse, dark woods, and a close conversational trail.',
    identity: 'This Shamim Forever original follows the reference profile’s intimate evening mood without claiming its formula or affiliation.',
    opening: 'Cardamom and bergamot create a cool, spicy invitation.',
    development: 'Lavender and cedar keep the heart smooth, clean, and quietly magnetic.',
    dryDown: 'Vetiver and amberwood leave a warm, discreetly smoky finish.',
    whenToWear: 'Date nights, candlelit dinners, and intimate evening gatherings.',
  },
  {
    code: 'SF-FM-012',
    reference: 'Jean Paul Gaultier Le Male',
    name: 'SF Homme Royale',
    slug: 'sf-homme-royale',
    referenceConcentration: 'EDT reference profile',
    priceUsd: 170,
    family: 'Aromatic fougère amber',
    gender: 'Masculine-leaning profile',
    top: ['mint leaf', 'lavender', 'bergamot'],
    heart: ['cinnamon', 'orange blossom', 'sage'],
    base: ['vanilla', 'tonka bean', 'sandalwood'],
    creation: 'A familiar fougère silhouette recast with a smooth mint opening, a floral-spiced center, and a creamy amber finish.',
    identity: 'SF Homme Royale is an original Shamim Forever interpretation of a classic fresh-to-sweet masculine profile.',
    opening: 'Mint and lavender create a cool, immediate freshness.',
    development: 'Cinnamon and orange blossom bring warmth and a gentle floral tension.',
    dryDown: 'Vanilla, tonka, and sandalwood leave a soft, inviting aura.',
    whenToWear: 'Evening social occasions, cooler days, and relaxed formal dressing.',
  },
  {
    code: 'SF-FM-013',
    reference: 'Jean Paul Gaultier Le Male Elixir',
    name: 'SF Homme Elixir',
    slug: 'sf-homme-elixir',
    referenceConcentration: 'Parfum reference profile',
    priceUsd: 205,
    family: 'Amber aromatic gourmand',
    gender: 'Masculine-leaning profile',
    top: ['lavender honey', 'mint', 'tonka'],
    heart: ['benzoin', 'orange blossom', 'tobacco leaf'],
    base: ['vanilla', 'amberwood', 'musk'],
    creation: 'A richer night composition that layers honeyed lavender over tobacco warmth and a rounded vanilla base.',
    identity: 'The Shamim Forever interpretation is original, using the reference profile only as an olfactory direction.',
    opening: 'Honeyed lavender opens with a smooth glow rather than a sharp burst.',
    development: 'Orange blossom and tobacco leaf add a warm, resinous center.',
    dryDown: 'Vanilla and amberwood create a plush, lasting close with clean musk.',
    whenToWear: 'Winter evenings, celebratory dinners, and after-dark gatherings.',
  },
  {
    code: 'SF-FM-014',
    reference: 'Versace Eros',
    name: 'SF Eros Royale',
    slug: 'sf-eros-royale',
    referenceConcentration: 'EDT reference profile',
    priceUsd: 172,
    family: 'Fresh aromatic gourmand',
    gender: 'Masculine-leaning profile',
    top: ['mint', 'green apple', 'lemon'],
    heart: ['geranium', 'ambroxan', 'tonka'],
    base: ['vanilla', 'cedar', 'oakmoss'],
    creation: 'A vivid blue-green fragrance with a bright fruit opening, a clean aromatic heart, and a confident sweet-wood close.',
    identity: 'SF Eros Royale is an original Shamim Forever creation inspired by a bold, youthful reference profile.',
    opening: 'Mint, green apple, and lemon produce a lively first impression.',
    development: 'Geranium and ambroxan add cool volume and a polished heart.',
    dryDown: 'Vanilla, cedar, and oakmoss balance sweetness with structure.',
    whenToWear: 'Social evenings, celebrations, and expressive casual tailoring.',
  },
  {
    code: 'SF-FM-015',
    reference: 'Versace Dylan Blue',
    name: 'SF Dylan Noir',
    slug: 'sf-dylan-noir',
    referenceConcentration: 'EDT reference profile',
    priceUsd: 174,
    family: 'Aromatic aquatic woody',
    gender: 'Masculine-leaning profile',
    top: ['bergamot', 'fig leaf', 'grapefruit'],
    heart: ['black pepper', 'ambroxan', 'violet leaf'],
    base: ['incense', 'patchouli', 'musk'],
    creation: 'A darker blue fragrance with an aromatic opening and a mineral, incense-touched trail made for confident movement.',
    identity: 'SF Dylan Noir is a Shamim Forever original interpretation, not an official or affiliated product.',
    opening: 'Bergamot and fig leaf create a green, textured freshness.',
    development: 'Black pepper and violet leaf sharpen the aromatic center.',
    dryDown: 'Incense, patchouli, and musk bring a cool midnight finish.',
    whenToWear: 'City evenings, smart-casual dressing, and transitional weather.',
  },
  {
    code: 'SF-FM-016',
    reference: 'Paco Rabanne 1 Million',
    name: 'SF Million Royale',
    slug: 'sf-million-royale',
    referenceConcentration: 'EDT reference profile',
    priceUsd: 180,
    family: 'Spiced leather amber',
    gender: 'Masculine-leaning profile',
    top: ['blood orange', 'grapefruit', 'mint'],
    heart: ['cinnamon', 'rose', 'saffron'],
    base: ['leather accord', 'amber', 'patchouli'],
    creation: 'A high-contrast amber built around sparkling citrus, warm spice, and a polished leather backbone.',
    identity: 'This Shamim Forever original is inspired by the reference profile’s opulent, attention-ready character without copying official copy or identity.',
    opening: 'Blood orange and mint make the opening bright and unmistakable.',
    development: 'Cinnamon, rose, and saffron create a glowing central accord.',
    dryDown: 'Leather, amber, and patchouli leave a smooth, confident trail.',
    whenToWear: 'Nightlife, festive occasions, and bold winter styling.',
  },
  {
    code: 'SF-FM-017',
    reference: 'Rabanne Phantom',
    name: 'SF Phantom Noir',
    slug: 'sf-phantom-noir',
    referenceConcentration: 'EDT reference profile',
    priceUsd: 178,
    family: 'Aromatic woody gourmand',
    gender: 'Masculine-leaning profile',
    top: ['lavender', 'lemon peel', 'elemi'],
    heart: ['apple accord', 'earthy patchouli', 'smoky violet'],
    base: ['vanilla', 'tonka', 'vetiver'],
    creation: 'A nocturnal aromatic with a digital-clean opening, roasted woods, and a soft gourmand base.',
    identity: 'SF Phantom Noir translates the reference mood into an original Shamim Forever archive piece.',
    opening: 'Lavender and lemon peel create a cool, luminous entrance.',
    development: 'Apple and patchouli add contrast between crispness and shadow.',
    dryDown: 'Vanilla, tonka, and vetiver provide a smooth, darkly playful finish.',
    whenToWear: 'Late dinners, creative spaces, and informal night events.',
  },
  {
    code: 'SF-FM-018',
    reference: 'Tom Ford Oud Wood',
    name: 'SF Oud Sovereign',
    slug: 'sf-oud-sovereign',
    referenceConcentration: 'EDP reference profile',
    priceUsd: 215,
    family: 'Woody spicy amber',
    gender: 'Unisex / shared fragrance profile',
    top: ['cardamom', 'rosewood', 'pepper'],
    heart: ['oud accord', 'sandalwood', 'vetiver'],
    base: ['amber', 'tonka bean', 'vanilla'],
    creation: 'A quiet wood study where spice, polished oud, and soft amber create an intimate architecture rather than a loud statement.',
    identity: 'SF Oud Sovereign is an original Shamim Forever shared fragrance profile inspired by the reference’s refined woods.',
    opening: 'Cardamom and rosewood introduce a cool, dry spice.',
    development: 'Oud, sandalwood, and vetiver form a smooth, linear center.',
    dryDown: 'Amber, tonka, and vanilla soften the woods into a long skin-close finish.',
    whenToWear: 'Private dinners, gallery nights, and year-round understated luxury.',
  },
  {
    code: 'SF-FM-019',
    reference: 'Tom Ford Tobacco Vanille',
    name: 'SF Tobacco Vanille Royale',
    slug: 'sf-tobacco-vanille-royale',
    referenceConcentration: 'EDP reference profile',
    priceUsd: 218,
    family: 'Spiced tobacco gourmand',
    gender: 'Unisex / shared fragrance profile',
    top: ['tobacco leaf', 'spiced ginger', 'coriander'],
    heart: ['cacao', 'vanilla', 'clove'],
    base: ['dried fruits', 'amber', 'dark woods'],
    creation: 'A warm shared fragrance built like a velvet library: tobacco, spice, cacao, and vanilla moving through dark woods.',
    identity: 'This original Shamim Forever interpretation is inspired by the reference profile and carries no official association with its maker.',
    opening: 'Tobacco leaf and ginger create a rich, dry-spiced first impression.',
    development: 'Cacao, vanilla, and clove add a dense, softly gourmand heart.',
    dryDown: 'Dried fruit, amber, and dark woods linger with winter warmth.',
    whenToWear: 'Cold weather, festive evenings, and slow, formal gatherings.',
  },
  {
    code: 'SF-FM-020',
    reference: 'Tom Ford Noir Extreme',
    name: 'SF Noir Extreme Sovereign',
    slug: 'sf-noir-extreme-sovereign',
    referenceConcentration: 'EDP reference profile',
    priceUsd: 210,
    family: 'Amber woody gourmand',
    gender: 'Masculine-leaning profile',
    top: ['mandarin', 'cardamom', 'nutmeg'],
    heart: ['kulfi accord', 'rose', 'orange blossom'],
    base: ['amber', 'sandalwood', 'vanilla'],
    creation: 'A plush evening amber that balances citrus spice with a creamy heart and a polished sandalwood base.',
    identity: 'SF Noir Extreme Sovereign is an original Shamim Forever reading of the reference profile’s decadent evening character.',
    opening: 'Mandarin and cardamom open with a luminous, spiced lift.',
    development: 'A creamy kulfi-inspired accord brings the center its distinctive softness.',
    dryDown: 'Amber and sandalwood carry vanilla into a rich but controlled finish.',
    whenToWear: 'Formal evenings, winter celebrations, and intimate dining.',
  },
  {
    code: 'SF-FM-021',
    reference: 'Parfums de Marly Layton',
    name: 'SF Layton Royale',
    slug: 'sf-layton-royale',
    referenceConcentration: 'EDP reference profile',
    priceUsd: 208,
    family: 'Fruity spicy woody',
    gender: 'Unisex / shared fragrance profile',
    top: ['apple', 'bergamot', 'lavender'],
    heart: ['jasmine', 'violet', 'geranium'],
    base: ['vanilla', 'peppery woods', 'patchouli'],
    creation: 'A polished shared profile that places crisp apple and cool florals over a warm, lightly spiced wood frame.',
    identity: 'SF Layton Royale is an original Shamim Forever interpretation, with the reference used only for scent-profile context.',
    opening: 'Apple and bergamot give the first moments a clear, juicy lift.',
    development: 'Lavender, jasmine, and violet make the heart soft but structured.',
    dryDown: 'Vanilla and peppery woods create an elegant, lingering close.',
    whenToWear: 'Autumn afternoons, evening receptions, and elevated everyday wear.',
  },
  {
    code: 'SF-FM-022',
    reference: 'Parfums de Marly Percival',
    name: 'SF Percival Sovereign',
    slug: 'sf-percival-sovereign',
    referenceConcentration: 'EDP reference profile',
    priceUsd: 196,
    family: 'Fresh aromatic woody',
    gender: 'Masculine-leaning profile',
    top: ['bergamot', 'mandarin', 'lavender'],
    heart: ['jasmine', 'violet leaf', 'coriander'],
    base: ['ambroxan', 'fir balsam', 'musk'],
    creation: 'A clean, expansive aromatic with citrus brightness, transparent florals, and a soft modern amber trail.',
    identity: 'SF Percival Sovereign is a Shamim Forever original inspired by a fresh polished reference profile, not a licensed reproduction.',
    opening: 'Bergamot and mandarin create a bright, easy-moving entrance.',
    development: 'Lavender and violet leaf keep the center airy and tailored.',
    dryDown: 'Ambroxan, fir balsam, and musk provide lift with a clean finish.',
    whenToWear: 'Daytime travel, spring and summer meetings, and open-air occasions.',
  },
  {
    code: 'SF-FM-023',
    reference: 'Maison Francis Kurkdjian Baccarat Rouge 540',
    name: 'SF Crystal Rouge Sovereign',
    slug: 'sf-crystal-rouge-sovereign',
    referenceConcentration: 'EDP reference profile',
    priceUsd: 220,
    family: 'Amber woody floral',
    gender: 'Unisex / shared fragrance profile',
    top: ['saffron', 'bitter almond', 'pear blossom'],
    heart: ['jasmine', 'mineral amber', 'cedar'],
    base: ['dry woods', 'musk', 'resinous amber'],
    creation: 'A radiant shared fragrance shaped around mineral amber, airy florals, and a crystalline woody trail.',
    identity: 'SF Crystal Rouge Sovereign is an original Shamim Forever interpretation of a luminous amber-wood profile; it is not an official product.',
    opening: 'Saffron and bitter almond give the opening a warm, transparent glow.',
    development: 'Jasmine and mineral amber create an airy, almost weightless center.',
    dryDown: 'Dry woods and musk leave a radiant trail that sits close and travels well.',
    whenToWear: 'Celebrations, evening receptions, and signature wear across seasons.',
  },
  {
    code: 'SF-FM-024',
    reference: 'Terre d’Hermès',
    name: 'SF Terre Royale',
    slug: 'sf-terre-royale',
    referenceConcentration: 'EDT reference profile',
    priceUsd: 184,
    family: 'Citrus woody vetiver',
    gender: 'Masculine-leaning profile',
    top: ['orange peel', 'grapefruit', 'pepper'],
    heart: ['flint accord', 'geranium', 'pepper leaf'],
    base: ['vetiver', 'cedar', 'benzoin'],
    creation: 'An earthy citrus composition with a dry mineral center and a grounded vetiver finish.',
    identity: 'SF Terre Royale is an original Shamim Forever fragrance inspired by the reference profile’s relationship between earth, citrus, and wood.',
    opening: 'Orange and grapefruit arrive with a dry, sparkling bitterness.',
    development: 'A mineral flint accord and geranium create a tactile middle.',
    dryDown: 'Vetiver, cedar, and benzoin settle into a firm, earthy foundation.',
    whenToWear: 'Daytime tailoring, outdoor lunches, and crisp autumn weather.',
  },
  {
    code: 'SF-FM-025',
    reference: 'Prada Luna Rossa Carbon',
    name: 'SF Luna Carbon',
    slug: 'sf-luna-carbon',
    referenceConcentration: 'EDT reference profile',
    priceUsd: 176,
    family: 'Mineral aromatic fougère',
    gender: 'Masculine-leaning profile',
    top: ['bergamot', 'pepper', 'lavender'],
    heart: ['coal accord', 'patchouli', 'metallic geranium'],
    base: ['ambroxan', 'dry earth', 'clean musk'],
    creation: 'A cool mineral aromatic designed around pepper, lavender, and an urban carbon-like texture.',
    identity: 'SF Luna Carbon is an original Shamim Forever interpretation of the reference profile’s clean metallic freshness.',
    opening: 'Bergamot and pepper create a bright, mineral snap.',
    development: 'Lavender, patchouli, and geranium build a cool, modern center.',
    dryDown: 'Ambroxan and clean musk leave a smooth dry-urban trail.',
    whenToWear: 'Daily commute, active afternoons, and modern office dressing.',
  },
  {
    code: 'SF-FM-026',
    reference: 'Azzaro The Most Wanted',
    name: 'SF Most Wanted Noir',
    slug: 'sf-most-wanted-noir',
    referenceConcentration: 'EDP Intense reference profile',
    priceUsd: 202,
    family: 'Spiced amber gourmand',
    gender: 'Masculine-leaning profile',
    top: ['cardamom', 'mandarin', 'pink pepper'],
    heart: ['toffee accord', 'cinnamon', 'lavender'],
    base: ['amberwood', 'benzoin', 'vanilla'],
    creation: 'A magnetic night amber where bright spice melts into toasted sweetness and polished woods.',
    identity: 'SF Most Wanted Noir is an original Shamim Forever interpretation, inspired by the reference profile but independent in identity and formula.',
    opening: 'Cardamom and mandarin create a bright, spicy invitation.',
    development: 'Toffee and cinnamon bring a warm, toasted center.',
    dryDown: 'Amberwood, benzoin, and vanilla create a dense, polished finish.',
    whenToWear: 'After-dark occasions, winter parties, and confident evening dressing.',
  },
  {
    code: 'SF-FM-027',
    reference: 'Givenchy Gentleman',
    name: 'SF Gentleman Royale',
    slug: 'sf-gentleman-royale',
    referenceConcentration: 'EDP reference profile',
    priceUsd: 190,
    family: 'Woody aromatic iris',
    gender: 'Masculine-leaning profile',
    top: ['black pepper', 'lavender', 'bergamot'],
    heart: ['iris', 'cacao', 'orris'],
    base: ['patchouli', 'vanilla', 'tol balsam'],
    creation: 'A dressed iris composition with peppered freshness, a cocoa-softened center, and a dark refined base.',
    identity: 'SF Gentleman Royale is an original Shamim Forever fragrance inspired by the reference profile’s modern gentleman character.',
    opening: 'Black pepper and lavender create a precise, tailored start.',
    development: 'Iris and cacao give the heart a cool, velvety dimension.',
    dryDown: 'Patchouli and vanilla create a smooth, quietly dramatic close.',
    whenToWear: 'Formal workdays, dinners, and polished evening occasions.',
  },
  {
    code: 'SF-FM-028',
    reference: 'Montblanc Explorer',
    name: 'SF Explorer Sovereign',
    slug: 'sf-explorer-sovereign',
    referenceConcentration: 'EDP reference profile',
    priceUsd: 179,
    family: 'Woody aromatic leather',
    gender: 'Masculine-leaning profile',
    top: ['bergamot', 'pink pepper', 'clary sage'],
    heart: ['vetiver', 'leather accord', 'patchouli'],
    base: ['ambroxan', 'cacao wood', 'akigalawood'],
    creation: 'A travel-ready woody composition that moves from bright citrus into vetiver, leather, and dry modern woods.',
    identity: 'SF Explorer Sovereign is an original Shamim Forever interpretation of an adventurous woody reference profile.',
    opening: 'Bergamot and pink pepper open with clear momentum.',
    development: 'Vetiver and leather add a dry, tactile center.',
    dryDown: 'Ambroxan and cacao wood form a warm, contemporary trail.',
    whenToWear: 'Travel, weekend tailoring, and daytime exploration.',
  },
  {
    code: 'SF-FM-029',
    reference: 'Narciso Rodriguez Bleu Noir',
    name: 'SF Bleu Noir Sovereign',
    slug: 'sf-bleu-noir-sovereign',
    referenceConcentration: 'EDP reference profile',
    priceUsd: 186,
    family: 'Woody musky aromatic',
    gender: 'Masculine-leaning profile',
    top: ['cardamom', 'nutmeg', 'citrus peel'],
    heart: ['musk', 'iris', 'suede accord'],
    base: ['cedar', 'ebony wood', 'vetiver'],
    creation: 'A close, dark musk study with cool spice, soft iris, and a clean architectural wood finish.',
    identity: 'SF Bleu Noir Sovereign is an original Shamim Forever fragrance guided by the reference profile’s restrained nocturnal character.',
    opening: 'Cardamom and nutmeg create a quiet, cool-spiced entry.',
    development: 'Musk, iris, and suede make the center intimate and tactile.',
    dryDown: 'Cedar, ebony, and vetiver keep the finish dry and composed.',
    whenToWear: 'Close quarters, evening commutes, and understated formal wear.',
  },
  {
    code: 'SF-FM-030',
    reference: 'Valentino Uomo Born In Roma Intense',
    name: 'SF Uomo Roma Intense',
    slug: 'sf-uomo-roma-intense',
    referenceConcentration: 'EDP Intense reference profile',
    priceUsd: 204,
    family: 'Amber aromatic vanilla',
    gender: 'Masculine-leaning profile',
    top: ['lavender', 'ginger', 'violet leaf'],
    heart: ['nutmeg', 'sage', 'orris'],
    base: ['vanilla', 'benzoin', 'smoky woods'],
    creation: 'A modern Roman amber with aromatic lavender, warm spice, and a dark vanilla base built for evening presence.',
    identity: 'SF Uomo Roma Intense is an original Shamim Forever interpretation of the reference profile, with no official brand relationship.',
    opening: 'Lavender and ginger open with a cool, confident lift.',
    development: 'Nutmeg and sage bring warmth and aromatic shape to the heart.',
    dryDown: 'Vanilla, benzoin, and smoky woods create a rich, elegant finish.',
    whenToWear: 'Night events, winter evenings, and formal modern tailoring.',
  },
]

export function buildForHimPerfumeStory(definition: ForHimPerfumeDefinition) {
  const referenceLabel = `Reference profile: ${definition.reference}.`
  return JSON.stringify({
    tagline: `${definition.name} — Original Shamim Forever Interpretation`,
    referenceProfile: referenceLabel,
    positioning: `${disclaimer} ${referenceLabel} This fragrance is placed in the For Him collection; its gender positioning is ${definition.gender.toLowerCase()}.`,
    olfactory: {
      top: definition.top,
      heart: definition.heart,
      base: definition.base,
      top_description: 'Opening Veil — the first luminous impression.',
      heart_description: 'Sovereign Core — the central character as the fragrance develops.',
      base_description: 'Eternal Foundation — the lasting structure on skin.',
    },
    specs: {
      classification: definition.family,
      concentration: 'EDP — Shamim Forever house interpretation',
      volume: '100ML',
      gender: definition.gender,
      wearing_environment: definition.whenToWear,
      allocation: definition.code,
      reference_concentration: definition.referenceConcentration,
      reference_price_status: 'Not verified in the current 2026 publish record; do not quote a reference price.',
      media_status: 'Product video and bespoke product imagery not supplied; media slot intentionally unassigned.',
      blockchain: 'Not issued — no verified blockchain record supplied.',
    },
    dossier: {
      creation: definition.creation,
      olfactiveIdentity: definition.identity,
      opening: definition.opening,
      development: definition.development,
      dryDown: definition.dryDown,
      whenToWear: definition.whenToWear,
      applicationAndCare: 'Spray onto pulse points from a short distance. Do not rub. Store upright in a cool, dry place away from direct sunlight and heat.',
      archiveObject: 'A Shamim Forever fragrance allocation presented as an original house interpretation. Bottle and campaign media remain pending the correct supplied assets.',
      authentication: 'No authentication record has been issued for this product. Verify only through an official Shamim Forever channel when a physical record is supplied.',
      walletSafety: 'Shamim Forever will never request a seed phrase, private key, recovery phrase, or wallet password.',
    },
    faqs: [
      { question: 'What is this fragrance?', answer: `${definition.name} is an original Shamim Forever ${definition.family.toLowerCase()} fragrance in the For Him collection.` },
      { question: 'What inspired this fragrance?', answer: `Its reference profile is ${definition.reference}; the Shamim Forever interpretation is independently written and presented.` },
      { question: 'Is it an original Shamim Forever fragrance?', answer: 'Yes. It is an original Shamim Forever product and is not an official, affiliated, endorsed, licensed, or authorized product of the reference brand.' },
      { question: 'What are the main scent notes?', answer: `Opening: ${definition.top.join(', ')}. Heart: ${definition.heart.join(', ')}. Base: ${definition.base.join(', ')}.` },
      { question: 'When should it be worn?', answer: definition.whenToWear },
      { question: 'How can it be authenticated?', answer: 'No authentication record is currently issued. Use the official Shamim Forever verification process when a verified record accompanies the physical product.' },
      { question: 'What is the Digital Sovereign Passport?', answer: 'It is Shamim Forever’s digital product-record system. No passport, NFT, wallet, token, or transaction data is issued for this product at publish time.' },
    ],
    verification: {
      blockchain: false,
      passport: false,
      provenance: false,
      authentication: false,
      holderPrivileges: false,
    },
    productCode: definition.code,
    sku: definition.slug,
  })
}
