const PERFUME_CATEGORY_ID = 'c513e298-7cb4-4c94-8288-19c6a12eed9b'
const FOR_HER_SUBCATEGORY_ID = 'ab8df629-e022-41d9-a6de-fac63d5680e8'

type ForHerDefinition = {
  name: string
  slug: string
  code: string
  reference: string
  referenceFamily: string
  referenceSource: string
  priceUsd: number
  positioning: string
  legacy: string
  opening: string
  development: string
  dryDown: string
  whenToWear: string
  top: string[]
  heart: string[]
  base: string[]
}

const definitions: ForHerDefinition[] = [
  {
    name: 'Velvet Command No. 01',
    slug: 'sf-good-girl',
    code: 'SF-FH-011',
    reference: 'Carolina Herrera Good Girl',
    referenceFamily: 'Amber floral',
    referenceSource: 'https://www.carolinaherrera.com/us/en/p-fragrance/good-girl-eau-de-parfum',
    priceUsd: 198,
    positioning: 'A polished amber floral built around contrast: luminous white flowers above a dark, cocoa-toned foundation.',
    legacy: 'Velvet Command is for the woman who can hold softness and authority in the same gesture.',
    opening: 'Almond and bergamot open with a roasted coffee accent, giving the first impression a clean flash of confidence.',
    development: 'Tuberose, jasmine sambac and orange blossom move the composition into a creamy white-floral heart.',
    dryDown: 'Tonka, cocoa, vanilla and sandalwood leave a warm, tailored trail with a quiet gourmand depth.',
    whenToWear: 'Evening appointments, black-tie rooms, intimate dinners and any moment that calls for composed presence.',
    top: ['Almond', 'Bergamot', 'Coffee accord'],
    heart: ['Tuberose', 'Jasmine sambac', 'Orange blossom'],
    base: ['Tonka bean', 'Cocoa', 'Vanilla', 'Sandalwood'],
  },
  {
    name: 'Scarlet Poise No. 02',
    slug: 'sf-very-good-girl',
    code: 'SF-FH-012',
    reference: 'Carolina Herrera Very Good Girl',
    referenceFamily: 'Fruity floral amber',
    referenceSource: 'https://www.carolinaherrera.com/ae/en/p-fragrance/very-good-girl',
    priceUsd: 202,
    positioning: 'A bright rose composition with a vivid fruit opening and a softly grounded vanilla-vetiver finish.',
    legacy: 'Scarlet Poise turns optimism into a form of self-possession: bright, direct and never apologetic.',
    opening: 'Lychee and red currant create a vivid, sparkling entrance with a tart red-fruit lift.',
    development: 'Rose absolute becomes the central line, carrying a petal-soft richness without losing its clarity.',
    dryDown: 'Vanilla and vetiver settle close to skin, balancing sweetness with a dry, elegant finish.',
    whenToWear: 'Day-to-evening transitions, celebrations, gallery openings and warm-weather city nights.',
    top: ['Lychee', 'Red currant', 'Bright citrus'],
    heart: ['Rose absolute', 'Freesia', 'Soft peony'],
    base: ['Vanilla', 'Vetiver', 'Clean woods'],
  },
  {
    name: 'Prismatic Paradox No. 03',
    slug: 'sf-paradoxe',
    code: 'SF-FH-013',
    reference: 'Prada Paradoxe',
    referenceFamily: 'Floral amber',
    referenceSource: 'https://www.prada-beauty.com/fragrance/womens-fragrances/paradoxe-eau-de-parfum/',
    priceUsd: 195,
    positioning: 'A contemporary floral amber that moves from transparent citrus to a radiant orange-blossom core.',
    legacy: 'Prismatic Paradox is the House study of a woman who refuses a single definition.',
    opening: 'Pear, bergamot and mandarin bring a cool, translucent brightness to the first spray.',
    development: 'Orange blossom, neroli and jasmine sambac give the heart a clean, solar floral volume.',
    dryDown: 'White musk, vanilla, benzoin and amber woods create a smooth, modern skin finish.',
    whenToWear: 'Daily signatures, creative workdays, travel and occasions where polish must remain effortless.',
    top: ['Pear accord', 'Bergamot', 'Mandarin'],
    heart: ['Orange blossom', 'Neroli', 'Jasmine sambac'],
    base: ['White musk', 'Vanilla', 'Benzoin', 'Amber woods'],
  },
  {
    name: 'Roma Afterglow No. 04',
    slug: 'sf-born-in-roma',
    code: 'SF-FH-014',
    reference: 'Valentino Donna Born In Roma',
    referenceFamily: 'Floral amber woody',
    referenceSource: 'https://www.valentino-beauty.us/fragrance/womens-fragrance/donna-born-in-roma-eau-de-parfum',
    priceUsd: 208,
    positioning: 'A modern floral with a cool, peppered opening and a luxurious bourbon-vanilla architecture.',
    legacy: 'Roma Afterglow carries the confidence of a woman who treats heritage as material, not a boundary.',
    opening: 'Blackcurrant, bergamot and pink pepper set a crisp, lightly spiced first impression.',
    development: 'Jasmine sambac opens into a luminous floral heart with a distinctly urban clarity.',
    dryDown: 'Bourbon vanilla, cashmeran and guaiac wood build a warm, textured trail with depth.',
    whenToWear: 'Autumn evenings, tailored daywear, dinners and after-dark cultural occasions.',
    top: ['Blackcurrant', 'Bergamot', 'Pink pepper'],
    heart: ['Jasmine sambac', 'Solar floral accord'],
    base: ['Bourbon vanilla', 'Cashmeran', 'Guaiac wood'],
  },
  {
    name: 'Gilded Goddess No. 05',
    slug: 'sf-goddess',
    code: 'SF-FH-015',
    reference: 'Burberry Goddess',
    referenceFamily: 'Aromatic vanilla',
    referenceSource: 'https://us.burberry.com/goddess-eau-de-parfum-100ml-p40822071',
    priceUsd: 198,
    positioning: 'An enveloping vanilla study in which aromatic lavender gives the sweetness a composed, contemporary edge.',
    legacy: 'Gilded Goddess is a portrait of inner radiance: calm power, warm light and deliberate grace.',
    opening: 'Lavender brings a clean aromatic lift before the vanilla structure starts to unfold.',
    development: 'Vanilla infusion and vanilla caviar create a layered, creamy heart rather than a single sweet note.',
    dryDown: 'Soft woods and ambered warmth leave a smooth, reassuring finish that stays close and elegant.',
    whenToWear: 'Quiet mornings, refined daytime rituals, winter evenings and intimate celebrations.',
    top: ['Lavender', 'Aromatic herbs', 'Bergamot'],
    heart: ['Vanilla caviar', 'Vanilla infusion', 'Jasmine veil'],
    base: ['Vanilla absolute', 'Soft woods', 'Warm amber'],
  },
  {
    name: 'Sovereign Yes No. 06',
    slug: 'sf-si',
    code: 'SF-FH-016',
    reference: 'Giorgio Armani Sì',
    referenceFamily: 'Chypre fruity',
    referenceSource: 'https://www.giorgioarmanibeauty-usa.com/fragrances/womens-fragrances/si-eau-de-parfum',
    priceUsd: 192,
    positioning: 'A poised cassis-led floral that turns a decisive fruit opening into a velvety, modern base.',
    legacy: 'Sovereign Yes is a fragrance for the woman who makes a decision and then gives it room to become a life.',
    opening: 'Blackcurrant nectar and a pear-like brightness create a crisp, expressive entrance.',
    development: 'Rose, freesia and transparent florals soften the fruit without making it fragile.',
    dryDown: 'Vanilla, patchouli and amber woods give the final impression a polished chypre silhouette.',
    whenToWear: 'Boardroom mornings, signature daily wear, formal lunches and elegant transitions into evening.',
    top: ['Blackcurrant nectar', 'Pear accord', 'Bergamot'],
    heart: ['Rose', 'Freesia', 'Transparent floral accord'],
    base: ['Vanilla', 'Patchouli', 'Amber woods'],
  },
  {
    name: 'Solar Amethyst No. 07',
    slug: 'sf-alien',
    code: 'SF-FH-017',
    reference: 'Mugler Alien',
    referenceFamily: 'Amber floral',
    referenceSource: 'https://www.muglerusa.com/fragrance/womens-fragrance/alien-eau-de-parfum',
    priceUsd: 210,
    positioning: 'A concentrated solar floral that places luminous jasmine against a distinctive cashmeran and amber foundation.',
    legacy: 'Solar Amethyst is the House interpretation of presence that arrives before explanation.',
    opening: 'A bright floral radiance rises immediately, shaped by a clean, almost electric lift.',
    development: 'Jasmine sambac forms the heart: creamy, solar and intentionally unmistakable.',
    dryDown: 'Cashmeran wood and white amber create a warm, mineral finish with a long, sculpted impression.',
    whenToWear: 'Night events, winter dressing, signature wear and moments that reward a memorable trail.',
    top: ['Solar floral lift', 'Bergamot', 'Fresh green facets'],
    heart: ['Jasmine sambac', 'White floral absolute'],
    base: ['Cashmeran wood', 'White amber', 'Soft musk'],
  },
  {
    name: 'Botanical Sovereignty No. 08',
    slug: 'sf-bloom',
    code: 'SF-FH-018',
    reference: 'Gucci Bloom',
    referenceFamily: 'White floral',
    referenceSource: 'https://www.gucci.com/us/en/pr/beauty/fragrances/womens-fragrances/gucci-bloom-eau-de-parfum-p-408020042200',
    priceUsd: 188,
    positioning: 'A full white-floral composition that treats garden abundance as a structured, wearable form of luxury.',
    legacy: 'Botanical Sovereignty is not a bouquet; it is a private garden with its own entrance and its own rules.',
    opening: 'A fresh green veil prepares the skin for an opulent, natural-feeling floral expansion.',
    development: 'Jasmine bud and tuberose build the central bloom with creamy volume and soft diffusion.',
    dryDown: 'Rangoon creeper and clean woods keep the floral signature rounded, modern and enduring.',
    whenToWear: 'Spring ceremonies, daytime elegance, garden settings and warm-weather signature wear.',
    top: ['Green leaf accord', 'Pear blossom', 'Fresh citrus'],
    heart: ['Jasmine bud', 'Tuberose', 'Rangoon creeper'],
    base: ['Soft woods', 'White musk', 'Creamy floral resin'],
  },
  {
    name: 'Petal Voltage No. 09',
    slug: 'sf-flowerbomb',
    code: 'SF-FH-019',
    reference: 'Viktor & Rolf Flowerbomb',
    referenceFamily: 'Amber floral',
    referenceSource: 'https://www.viktor-rolf.com/products/flowerbomb-eau-de-parfum-50ml',
    priceUsd: 205,
    positioning: 'A high-impact floral built around contrast: fresh petals at the start, an opulent bouquet in the heart and warm vanilla below.',
    legacy: 'Petal Voltage gives the floral bouquet a pulse: generous, kinetic and impossible to mistake for background.',
    opening: 'Tea, bergamot and freesia create a lifted, sparkling entrance.',
    development: 'Centifolia rose, jasmine and orchid accords form a dense, couture-like floral heart.',
    dryDown: 'Patchouli, vanilla and soft musk turn the bouquet into a warm amber floral trail.',
    whenToWear: 'Celebrations, evening plans, festive dressing and confident cold-weather wear.',
    top: ['Tea accord', 'Bergamot', 'Freesia'],
    heart: ['Centifolia rose', 'Jasmine', 'Orchid accord'],
    base: ['Patchouli', 'Vanilla bean', 'Soft musk'],
  },
  {
    name: 'Musc Veil No. 10',
    slug: 'sf-for-her',
    code: 'SF-FH-020',
    reference: 'Narciso Rodriguez For Her',
    referenceFamily: 'Musk floral woody',
    referenceSource: 'https://www.narcisorodriguezparfums.com/en/narciso-rodriguez-for-her/for-her-edp.html',
    priceUsd: 185,
    positioning: 'A skin-close musk composition with pink florals and peach softness, shaped for intimacy rather than spectacle.',
    legacy: 'Musc Veil is the House study of personal magnetism: the trace left after the room has moved on.',
    opening: 'Peach pulp and a soft pink-fruit brightness introduce the signature musk with gentle warmth.',
    development: 'Rose and pink florals give the heart a clean, tactile character.',
    dryDown: 'Musk, soft amber, patchouli and sandalwood settle into a smooth second-skin finish.',
    whenToWear: 'Close conversations, daily rituals, understated elegance and layered fragrance wardrobes.',
    top: ['Peach pulp', 'Pink fruit accord', 'Soft citrus'],
    heart: ['Rose', 'Pink floral accord', 'Musk'],
    base: ['Soft amber', 'Patchouli', 'Sandalwood'],
  },
]

function buildFaq(definition: ForHerDefinition) {
  return [
    {
      question: `What is ${definition.name}?`,
      answer: `${definition.name} is an original Shamim Forever Eau de Parfum in the For Her collection, composed as a ${definition.referenceFamily} interpretation with its own House identity.`,
    },
    {
      question: `What inspired ${definition.name}?`,
      answer: `Its reference profile is ${definition.reference}. The reference is disclosed for olfactory orientation only; ${definition.name} is not an official, licensed or affiliated product of that brand.`,
    },
    {
      question: `Is ${definition.name} an original Shamim Forever fragrance?`,
      answer: `Yes. The name, editorial concept, product presentation and Shamim Forever interpretation are original to the House. The reference profile is not presented as a copied formula.`,
    },
    {
      question: 'What are the main scent notes?',
      answer: `The opening carries ${definition.top.join(', ')}. The heart develops through ${definition.heart.join(', ')}, and the foundation rests on ${definition.base.join(', ')}.`,
    },
    {
      question: `When should ${definition.name} be worn?`,
      answer: definition.whenToWear,
    },
    {
      question: 'How can the product be authenticated?',
      answer: 'Keep the House order record and product details together. Authentication is handled through the existing Shamim Forever product and order workflow; no unverified blockchain claim is made for this new allocation.',
    },
    {
      question: 'What is the Digital Sovereign Passport?',
      answer: 'It is the House record used to connect a physical product with its verified product information. A blockchain token, contract or wallet record is shown only when a real product-specific record exists.',
    },
  ]
}

function buildStory(definition: ForHerDefinition) {
  return JSON.stringify({
    tagline: `${definition.name} — an original For Her Eau de Parfum`,
    reference_profile: `Inspired by the olfactory profile of ${definition.reference}. Reference family: ${definition.referenceFamily}.`,
    positioning: definition.positioning,
    legacy_statement: definition.legacy,
    atmospheric_presence: 'A considered House composition for a woman whose presence is felt before it is explained.',
    olfactory: {
      top: definition.top,
      heart: definition.heart,
      base: definition.base,
      top_description: definition.opening,
      heart_description: definition.development,
      base_description: definition.dryDown,
    },
    specs: {
      code: definition.code,
      collection: 'For Her',
      classification: 'Original Shamim Forever fragrance',
      product_type: 'Eau de Parfum',
      concentration: 'Eau de Parfum',
      volume: '100 mL',
      scent_family: definition.referenceFamily,
      longevity: 'Performance varies with skin, climate and application.',
      projection: 'Measured, visible presence with a refined trail.',
      sillage: 'Moderate to pronounced depending on application.',
      batch: 'House For Her allocation',
      gender: 'For Her',
      production: 'Presented as an original Shamim Forever interpretation.',
      wearing_environment: definition.whenToWear,
      reference_price: 'Reference pricing varies by market, size and retailer; verify against the official source before comparison.',
      reference_source: definition.referenceSource,
    },
    dossier: {
      creation: `The House created ${definition.name} as a new interpretation rather than a replica. ${definition.positioning}`,
      olfactive_identity: definition.referenceFamily,
      opening: definition.opening,
      development: definition.development,
      dry_down: definition.dryDown,
      when_to_wear: definition.whenToWear,
      application_care: 'Apply to pulse points from a short distance. Store upright, away from direct sun, heat and rapid temperature changes. Do not spray on delicate fabrics without testing first.',
      archive_object: 'The physical flacon and its House product record are kept together as the archive object.',
      authentication: 'Use the published Shamim Forever URL, order record and product code when requesting assistance. Never rely on an unofficial wallet message or a copied listing.',
      wallet_safety: 'The House will never request a seed phrase, private key, recovery phrase or wallet password.',
    },
    faq: buildFaq(definition),
    seo: {
      title: `${definition.name} | Shamim Forever For Her Eau de Parfum`,
      description: `${definition.name} is an original Shamim Forever For Her Eau de Parfum with a ${definition.referenceFamily} profile inspired by ${definition.reference}.`,
      og_title: `${definition.name} — Shamim Forever`,
      og_description: `Discover ${definition.name}, an original House interpretation in the Shamim Forever For Her fragrance collection.`,
      twitter_title: `${definition.name} — Shamim Forever For Her`,
      twitter_description: `An original Shamim Forever ${definition.referenceFamily} Eau de Parfum interpretation.`,
      image_alt: `Shamim Forever ${definition.name} luxury women's Eau de Parfum`,
      keywords: [
        `Shamim Forever ${definition.name}`,
        'Shamim Forever perfume',
        'luxury perfume for women',
        "women's Eau de Parfum",
        'luxury fragrance',
        'premium women’s fragrance',
        'For Her perfume',
        'Shamim Forever For Her',
        `${definition.reference} inspired perfume`,
      ],
    },
  })
}

export const FOR_HER_10_PRODUCTS = definitions.map((definition) => ({
  name: definition.name,
  slug: definition.slug,
  description: `${definition.positioning} Reference profile: ${definition.reference}.`,
  story: buildStory(definition),
  price_pkr: definition.priceUsd * 280,
  price_usd: definition.priceUsd,
  inventory: 20,
  images: [`/products/${definition.slug}/poster.jpg`],
  main_category_id: PERFUME_CATEGORY_ID,
  sub_category_id: FOR_HER_SUBCATEGORY_ID,
  collection_id: null,
  is_featured: false,
  is_active: true,
}))

export const FOR_HER_PRODUCT_DEFINITIONS = definitions