export type GlossaryTerm = {
  slug: string
  term: string
  pronunciation: string
  category: string
  shortDefinition: string
  definition: string
  houseContext: string
  whyItMatters: string
  relatedSlugs: string[]
  misunderstandings: string
  resources: Array<{ label: string; href: string }>
  lastReviewed: string
}

export const glossaryCategories = [
  { slug: 'the-house', title: 'The House', description: 'The language of maison, identity, governance, and institutional memory.' },
  { slug: 'luxury', title: 'Luxury', description: 'Words for quality, rarity, experience, exclusivity, and enduring value.' },
  { slug: 'craftsmanship', title: 'Craftsmanship', description: 'The intelligence of materials, hands, precision, and finishing.' },
  { slug: 'bespoke', title: 'Bespoke', description: 'The vocabulary of commissions shaped around one client.' },
  { slug: 'couture-fashion', title: 'Couture & Fashion', description: 'Silhouette, tailoring, textile, and garment construction.' },
  { slug: 'heritage', title: 'Heritage', description: 'Cultural memory, archives, provenance, preservation, and restoration.' },
  { slug: 'authenticity', title: 'Authenticity', description: 'Evidence, verification, identity, and trust.' },
  { slug: 'private-client', title: 'Private Client', description: 'Discretion, access, relationships, and personal service.' },
  { slug: 'concierge', title: 'Concierge', description: 'White-glove assistance before, during, and after a creation.' },
  { slug: 'boutiques-locations', title: 'Boutiques & Locations', description: 'Places where a house becomes a lived experience.' },
  { slug: 'materials', title: 'Materials', description: 'Material integrity, sourcing, and the story of physical matter.' },
  { slug: 'jewellery', title: 'Jewellery', description: 'Gemstones, precious metals, setting, hallmark, and heirloom.' },
  { slug: 'fragrance', title: 'Fragrance', description: 'The vocabulary of accords, notes, and olfactory identity.' },
  { slug: 'identity', title: 'Identity', description: 'The signatures and codes that make a House recognisable.' },
  { slug: 'innovation', title: 'Innovation', description: 'Research, experimentation, emerging technology, and future craft.' },
  { slug: 'digital-authenticity', title: 'Digital Authenticity', description: 'Digital certificates, cryptography, ledgers, and provenance.' },
  { slug: 'sovereign-infrastructure', title: 'Sovereign Infrastructure', description: 'Resilient systems for continuity, security, and trust.' },
  { slug: 'sustainability', title: 'Sustainability', description: 'Longevity, repair, circularity, and responsible production.' },
  { slug: 'time-archive', title: 'Time & Archive', description: 'Chronology, documentation, collections, and memory.' },
  { slug: 'sovereign-philosophy', title: 'Sovereign Philosophy', description: 'Independence, integrity, stewardship, and long-term thinking.' },
]

const term = (
  details: Omit<GlossaryTerm, 'resources' | 'lastReviewed'> & { resources?: GlossaryTerm['resources']; lastReviewed?: string },
): GlossaryTerm => ({
  resources: [],
  lastReviewed: 'September 2026',
  ...details,
})

export const glossaryTerms: GlossaryTerm[] = [
  term({
    slug: 'authenticity',
    term: 'Authenticity',
    pronunciation: 'aw·then·TIS·uh·tee',
    category: 'Authenticity',
    shortDefinition: 'The condition of being genuine, verifiable, and faithful to an object’s origin, identity, or documented history.',
    definition: 'Authenticity is not established by appearance alone. It is a reasoned conclusion drawn from evidence: materials, construction, records, provenance, identifiers, and the credibility of the verification process.',
    houseContext: 'Within Shamim Forever, authenticity is treated as a relationship between a creation and the identity the House records around it. Physical quality and responsible documentation work together.',
    whyItMatters: 'Authenticity protects trust, preserves cultural and creative value, and gives an owner confidence that the story attached to a creation is supported by evidence.',
    relatedSlugs: ['provenance', 'verification', 'digital-identity', 'traceability', 'identity'],
    misunderstandings: 'Authenticity is not the same as luxury, price, rarity, or a single certificate. One signal can support a conclusion, but it should not be mistaken for the whole chain of evidence.',
    resources: [{ label: 'Read the Authenticity guide', href: '/learn/authenticity' }, { label: 'Explore digital authenticity', href: '/learn/authenticity/digital-authenticity' }],
  }),
  term({
    slug: 'atelier',
    term: 'Atelier',
    pronunciation: 'uh·tuh·LYAY',
    category: 'Craftsmanship',
    shortDefinition: 'A workshop or studio where design direction, material knowledge, skilled making, and refinement come together.',
    definition: 'An atelier is both a place and a practice. It is where a concept becomes a material decision, a material decision becomes a prototype, and patient iteration becomes a finished creation.',
    houseContext: 'The Shamim Forever atelier represents the human and technical centre of a creation: a place for specialist collaboration, review, finishing, and the quiet standards that cannot be reduced to a checklist.',
    whyItMatters: 'The atelier makes authorship, accountability, and refinement visible. It is where the values of a House become tangible in the hands of makers.',
    relatedSlugs: ['craftsmanship', 'bespoke', 'materiality', 'couture', 'heritage'],
    misunderstandings: 'Atelier does not simply mean a retail showroom or a fashionable synonym for workshop. Its meaning comes from the quality of practice and the relationship between people, materials, and decisions.',
    resources: [{ label: 'Enter the Atelier', href: '/atelier' }, { label: 'Explore the craft guide', href: '/guides#craft-atelier' }],
  }),
  term({
    slug: 'archive',
    term: 'Archive',
    pronunciation: 'AR·kive',
    category: 'Time & Archive',
    shortDefinition: 'A deliberately preserved body of records, objects, images, materials, and knowledge that documents continuity.',
    definition: 'An archive is more than storage. It is a structured memory system with enough context to explain what a creation was, where it came from, how it was made, and why it matters.',
    houseContext: 'A House archive may hold sketches, material references, production notes, provenance, client permissions, campaign history, and the stories that allow future generations to understand a creation.',
    whyItMatters: 'Without archives, institutions lose the evidence and nuance needed to preserve identity, learn from the past, and make responsible claims about heritage.',
    relatedSlugs: ['heritage', 'provenance', 'legacy', 'heirloom', 'institutional-memory'],
    misunderstandings: 'An archive is not a miscellaneous folder of old files. It requires selection, description, preservation, access rules, and ongoing stewardship.',
    resources: [{ label: 'Explore Heritage', href: '/our-story' }, { label: 'Explore the Time Archive', href: '/time-archive' }],
  }),
  term({
    slug: 'bespoke',
    term: 'Bespoke',
    pronunciation: 'bih·SPOHK',
    category: 'Bespoke',
    shortDefinition: 'Created specifically around the requirements, preferences, measurements, or identity of an individual client.',
    definition: 'Bespoke describes a creation shaped through a personal process rather than selected as a finished standard. It can involve consultation, material selection, design development, fitting, review, and careful refinement.',
    houseContext: 'At Shamim Forever, bespoke is a philosophy of individual consideration. The client’s needs inform the brief, while the atelier protects the integrity of the material and the craft.',
    whyItMatters: 'Bespoke makes room for individuality, meaning, fit, and long-term personal significance. It turns a transaction into a considered relationship with the creation.',
    relatedSlugs: ['custom-commission', 'made-to-measure', 'atelier', 'craftsmanship', 'private-client'],
    misunderstandings: 'Bespoke is not simply adding initials or choosing from a menu of options. Personalisation can be part of a bespoke process, but it does not define the whole process.',
    resources: [{ label: 'Visit Bespoke', href: '/bespoke' }, { label: 'Read the bespoke guide', href: '/guides#craft-atelier' }],
  }),
  term({
    slug: 'boutique',
    term: 'Boutique',
    pronunciation: 'boo·TEEK',
    category: 'Boutiques & Locations',
    shortDefinition: 'A focused environment where a House presents creations, service, and its way of receiving people.',
    definition: 'A boutique is not only a point of sale. It is a physical expression of a House: a place where a visitor encounters its objects, language, hospitality, standards, and pace.',
    houseContext: 'Shamim Forever boutiques are intended to connect discovery with relationship. The environment should help a client understand a creation rather than simply move toward a purchase.',
    whyItMatters: 'A well-considered location gives intangible values a physical address and creates a setting for trust, privacy, and memory.',
    relatedSlugs: ['maison', 'private-client', 'concierge', 'atelier', 'house'],
    misunderstandings: 'A boutique is not defined by its size or price point. Its meaning depends on the quality of the experience and its connection to the House.',
    resources: [{ label: 'Discover Boutiques', href: '/boutiques' }, { label: 'Explore locations', href: '/guides#the-house' }],
  }),
  term({
    slug: 'craftsmanship',
    term: 'Craftsmanship',
    pronunciation: 'KRAFTS·mən·ship',
    category: 'Craftsmanship',
    shortDefinition: 'The knowledge, skill, precision, patience, and judgement applied to making something well.',
    definition: 'Craftsmanship includes technique, but it is broader than manual skill. It includes material reading, proportion, construction, finishing, problem-solving, and the discipline to improve a piece before it is released.',
    houseContext: 'The House uses craftsmanship to describe the full chain of thoughtful making, from the first material decision to the final inspection and the care offered after ownership.',
    whyItMatters: 'Craftsmanship creates quality that can be experienced, examined, repaired, and respected over time.',
    relatedSlugs: ['atelier', 'materiality', 'hand-finished', 'heritage', 'bespoke'],
    misunderstandings: 'Handmade does not automatically mean well-made, and machine-assisted work is not automatically without craft. Judgement and integrity matter at every stage.',
    resources: [{ label: 'Explore the Atelier', href: '/atelier' }, { label: 'Enter Craft & Atelier', href: '/guides#craft-atelier' }],
  }),
  term({
    slug: 'concierge',
    term: 'Concierge',
    pronunciation: 'kon·see·AIRZH',
    category: 'Concierge',
    shortDefinition: 'A dedicated service relationship that helps a client navigate discovery, purchase, care, access, and follow-through.',
    definition: 'Concierge work is anticipatory and personal. It reduces friction while protecting the client’s time, privacy, preferences, and sense of welcome.',
    houseContext: 'At Shamim Forever, concierge is a human bridge between the House and the client. It may include appointments, product guidance, private access, aftercare, and thoughtful coordination.',
    whyItMatters: 'Exceptional creations need an equally considered relationship around them. Concierge turns service into continuity rather than a single moment.',
    relatedSlugs: ['private-client', 'white-glove-service', 'appointment', 'aftercare', 'client-journey'],
    misunderstandings: 'Concierge is not merely a receptionist or a promise of unlimited availability. It is a defined service practice grounded in discretion and competence.',
    resources: [{ label: 'Meet the Concierge', href: '/concierge' }, { label: 'Explore Concierge & Care', href: '/care' }],
  }),
  term({
    slug: 'couture',
    term: 'Couture',
    pronunciation: 'koo·TOOR',
    category: 'Couture & Fashion',
    shortDefinition: 'A mode of fashion creation centred on exceptional construction, skilled technique, and a highly considered relationship to the wearer.',
    definition: 'Couture is associated with making that gives unusual attention to construction, fit, detail, and finish. In a wider House vocabulary, it can also describe an attitude of precision and personal consideration.',
    houseContext: 'Shamim Forever uses couture as a reference for care, not as an unsupported legal or industry accreditation claim. The relevant question is always what was made, by whom, and to what standard.',
    whyItMatters: 'Couture reminds us that the value of a garment or object can live in its construction, intelligence, and relationship with a person.',
    relatedSlugs: ['bespoke', 'made-to-measure', 'craftsmanship', 'atelier', 'materiality'],
    misunderstandings: 'Couture is not a decorative label that automatically means bespoke, handmade, or superior. Those claims need their own evidence.',
    resources: [{ label: 'Explore Craft & Atelier', href: '/guides#craft-atelier' }, { label: 'Visit the Atelier', href: '/atelier' }],
  }),
  term({
    slug: 'digital-identity',
    term: 'Digital Identity',
    pronunciation: 'DIJ·uh·təl eye·DEN·tuh·tee',
    category: 'Digital Authenticity',
    shortDefinition: 'A persistent digital record that helps identify, verify, and care for a physical creation or relationship.',
    definition: 'Digital identity connects a real-world subject to information held in a digital system. Depending on the design, that information may include identifiers, provenance, ownership events, care history, or permissions.',
    houseContext: 'For the House, digital identity is a proposed support layer for product identity and responsible ownership. It should complement physical examination and clear governance, not replace them.',
    whyItMatters: 'A well-designed digital identity can make care, verification, transfer, and long-term records more accessible.',
    relatedSlugs: ['identity', 'authenticity', 'traceability', 'verification', 'digital-provenance'],
    misunderstandings: 'A QR code or token alone is not proof of authenticity. The reliability of the issuer, the data, the controls, and the chain behind it all matter.',
    resources: [{ label: 'Explore Digital Authenticity', href: '/learn/authenticity/digital-authenticity' }, { label: 'Read White Papers', href: '/whitepapers' }],
  }),
  term({
    slug: 'exclusivity',
    term: 'Exclusivity',
    pronunciation: 'ek·skloo·SIV·uh·tee',
    category: 'Luxury',
    shortDefinition: 'A controlled sense of limited access, availability, or participation that protects attention and meaning.',
    definition: 'Exclusivity can arise from limited production, private access, specialised service, geography, timing, or a relationship with a House. It is a design decision, not a substitute for quality.',
    houseContext: 'Shamim Forever treats exclusivity as a responsibility: access should feel considered, never needlessly humiliating, and should protect the integrity of an experience or creation.',
    whyItMatters: 'When used with integrity, exclusivity protects scarcity, privacy, and the conditions needed for thoughtful attention.',
    relatedSlugs: ['rarity', 'scarcity', 'private-client', 'private-access', 'luxury'],
    misunderstandings: 'Exclusivity is not the same as arrogance, high price, or indiscriminate restriction. It has meaning only when it serves a clear experience or standard.',
    resources: [{ label: 'Explore Luxury', href: '/learn/luxury' }, { label: 'Enter the Inner Circle', href: '/inner-circle' }],
  }),
  term({
    slug: 'heritage',
    term: 'Heritage',
    pronunciation: 'HER·uh·tij',
    category: 'Heritage',
    shortDefinition: 'The cultural, historical, and creative inheritance that connects past knowledge with future continuity.',
    definition: 'Heritage is living rather than frozen. It includes objects, techniques, stories, places, values, and practices that are preserved, interpreted, and responsibly carried forward.',
    houseContext: 'Shamim Forever’s heritage language is intended to honour memory without inventing history. Claims about origins, traditions, and cultural influence should remain supported and specific.',
    whyItMatters: 'Heritage gives creations context and helps a House develop continuity without confusing nostalgia with meaning.',
    relatedSlugs: ['archive', 'provenance', 'legacy', 'preservation', 'restoration'],
    misunderstandings: 'Heritage is not automatically old, inherited, or prestigious. A young institution can begin building heritage through consistent practice and responsible memory.',
    resources: [{ label: 'Explore Our Story', href: '/our-story' }, { label: 'Enter Heritage', href: '/guides#heritage' }],
  }),
  term({
    slug: 'heirloom',
    term: 'Heirloom',
    pronunciation: 'AIR·loom',
    category: 'Jewellery',
    shortDefinition: 'A meaningful object preserved and passed through generations.',
    definition: 'An heirloom carries more than material value. Its significance may come from the people connected to it, the events it has witnessed, the craft it represents, and the care invested in its preservation.',
    houseContext: 'Within the House vocabulary, heirloom is an aspiration of continuity rather than a guarantee. A creation becomes heirloom-worthy through quality, meaning, documentation, and care over time.',
    whyItMatters: 'Thinking in heirlooms changes the horizon from immediate consumption to stewardship and intergenerational value.',
    relatedSlugs: ['legacy', 'heritage', 'archive', 'provenance', 'stewardship'],
    misunderstandings: 'An heirloom is not defined only by age, monetary value, or family bloodline. Meaning and responsible continuity are equally important.',
    resources: [{ label: 'Explore the Heirloom Vault', href: '/heirloom-vault' }, { label: 'Read Ownership & Stewardship', href: '/guides#ownership-stewardship' }],
  }),
  term({
    slug: 'identity',
    term: 'Identity',
    pronunciation: 'eye·DEN·tuh·tee',
    category: 'Identity',
    shortDefinition: 'The distinctive qualities and records through which a person, creation, or House can be recognised.',
    definition: 'Identity is made from signals that persist: name, form, materials, marks, stories, records, relationships, and behaviours. It is both expressive and evidentiary.',
    houseContext: 'A House identity should be recognisable without becoming repetitive. Product identity, founder identity, client identity, and digital identity need clear boundaries and respectful governance.',
    whyItMatters: 'Clear identity supports recognition, authenticity, belonging, and continuity across physical and digital experiences.',
    relatedSlugs: ['digital-identity', 'house', 'signature', 'authenticity', 'distinctiveness'],
    misunderstandings: 'Identity is not just a logo or visual style. Those are signals within a larger system of meaning and conduct.',
    resources: [{ label: 'Explore DNA Identity', href: '/dna-identity' }, { label: 'Read Authenticity', href: '/learn/authenticity' }],
  }),
  term({
    slug: 'innovation',
    term: 'Innovation',
    pronunciation: 'in·uh·VAY·shən',
    category: 'Innovation',
    shortDefinition: 'A meaningful new method, idea, material, system, or experience that improves what can be made or understood.',
    definition: 'Innovation is not novelty for its own sake. It is disciplined experimentation that creates a useful difference while respecting quality, responsibility, and the people affected by the change.',
    houseContext: 'Shamim Forever explores innovation at the intersection of craft, technology, digital provenance, private experience, and future infrastructure.',
    whyItMatters: 'Innovation keeps a House capable of adapting without abandoning its standards or its memory.',
    relatedSlugs: ['digital-identity', 'sovereign-infrastructure', 'future-craft', 'research', 'authenticity'],
    misunderstandings: 'New does not automatically mean innovative, and traditional does not automatically mean obsolete. The value is in the outcome and the integrity of the process.',
    resources: [{ label: 'Explore Innovation', href: '/learn/innovation' }, { label: 'Visit the Guides', href: '/guides#innovation' }],
  }),
  term({
    slug: 'legacy',
    term: 'Legacy',
    pronunciation: 'LEG·uh·see',
    category: 'Sovereign Philosophy',
    shortDefinition: 'The influence, knowledge, objects, relationships, and values intentionally carried forward into the future.',
    definition: 'Legacy is not only what remains after someone is gone. It is the result of present decisions about what to preserve, how to behave, what to teach, and what future people may inherit.',
    houseContext: '“Forged into legacy” describes a direction for the House: to make creations and systems that can outlive the moment without claiming a future that has not yet been earned.',
    whyItMatters: 'Legacy gives long-term thinking a human and cultural dimension. It asks whether today’s work will still be meaningful when context changes.',
    relatedSlugs: ['heritage', 'heirloom', 'stewardship', 'permanence', 'continuity'],
    misunderstandings: 'Legacy is not the same as fame, scale, or age. It can be intimate, local, technical, cultural, or institutional.',
    resources: [{ label: 'Read Our Story', href: '/our-story' }, { label: 'Explore the House', href: '/learn/the-house' }],
  }),
  term({
    slug: 'luxury',
    term: 'Luxury',
    pronunciation: 'LUK·shuh·ree',
    category: 'Luxury',
    shortDefinition: 'A combination of exceptional quality, craftsmanship, rarity, experience, cultural meaning, and long-term value.',
    definition: 'Luxury cannot be reduced to price alone. A high price may reflect rarity or expensive materials, but meaningful luxury also depends on quality, integrity, personal relevance, service, time, and the experience around a creation.',
    houseContext: 'Shamim Forever understands luxury as a system of meaning and responsibility: how a creation is imagined, made, identified, experienced, cared for, and remembered.',
    whyItMatters: 'A broader definition helps people distinguish durable value from temporary status signals and make more conscious choices.',
    relatedSlugs: ['craftsmanship', 'heritage', 'bespoke', 'exclusivity', 'rarity', 'legacy'],
    misunderstandings: 'Luxury and expensive can overlap, but they are not identical. Luxury does not always mean the highest price or the loudest display.',
    resources: [{ label: 'Explore the Luxury guide', href: '/learn/luxury' }, { label: 'Start with Guides', href: '/guides#luxury' }],
  }),
  term({
    slug: 'maison',
    term: 'Maison',
    pronunciation: 'may·ZOHN',
    category: 'The House',
    shortDefinition: 'A house or institution whose identity is expressed through its creations, people, standards, and continuity.',
    definition: 'In luxury language, maison can refer to more than a physical building. It suggests a living structure of creative direction, craft, service, archives, and relationships.',
    houseContext: 'Shamim Forever uses “House” and “maison” to describe an evolving institution rather than a claim of historical status. The identity is built through practice over time.',
    whyItMatters: 'The concept of a maison helps connect products and experiences to the deeper systems that give them meaning.',
    relatedSlugs: ['house', 'atelier', 'heritage', 'house-identity', 'legacy'],
    misunderstandings: 'Maison is not a guarantee of age, prestige, or quality. The word should be supported by what the institution actually does.',
    resources: [{ label: 'Explore The House', href: '/learn/the-house' }, { label: 'Read the brand book', href: '/whitepapers' }],
  }),
  term({
    slug: 'private-client',
    term: 'Private Client',
    pronunciation: 'PRY·vit KLY·ənt',
    category: 'Private Client',
    shortDefinition: 'A client who works with a House through a personal, discreet, and relationship-led experience.',
    definition: 'Private client describes a mode of relationship rather than a status label. It may involve tailored consultation, confidential communication, private access, and continuing care.',
    houseContext: 'At Shamim Forever, a private client relationship should be built on consent, clarity, discretion, and service quality—not on exaggerated promises or assumptions about wealth.',
    whyItMatters: 'The relationship model makes space for trust and careful decision-making when a creation or commission deserves more time.',
    relatedSlugs: ['concierge', 'private-access', 'bespoke', 'confidentiality', 'client-journey'],
    misunderstandings: 'Private client is not a synonym for VIP, celebrity, or unlimited access. It should describe an actual service relationship.',
    resources: [{ label: 'Contact the Concierge', href: '/concierge' }, { label: 'Explore Private Client infrastructure', href: '/learn/sovereign-infrastructure/private-client-infrastructure' }],
  }),
  term({
    slug: 'provenance',
    term: 'Provenance',
    pronunciation: 'PROV·uh·nəns',
    category: 'Heritage',
    shortDefinition: 'The documented history of an object’s origin, ownership, movement, or development.',
    definition: 'Provenance provides context around a creation. It can include records of origin, materials, makers, commissions, custody, exhibitions, repairs, and ownership events, with the quality of each record clearly understood.',
    houseContext: 'The House treats provenance as a record that must be built carefully and maintained over time. Privacy and consent are part of responsible provenance design.',
    whyItMatters: 'Good provenance supports authenticity, cultural understanding, care, valuation context, and a more honest relationship between an owner and a creation.',
    relatedSlugs: ['authenticity', 'traceability', 'archive', 'chain-of-custody', 'digital-identity'],
    misunderstandings: 'Provenance is not a decorative story, an unverified anecdote, or a guarantee of value. It is only as strong as its evidence and custody controls.',
    resources: [{ label: 'Read the Provenance guide', href: '/learn/authenticity/provenance' }, { label: 'Explore Authenticity', href: '/learn/authenticity' }],
  }),
  term({
    slug: 'rarity',
    term: 'Rarity',
    pronunciation: 'RAIR·uh·tee',
    category: 'Luxury',
    shortDefinition: 'The relative uncommonness of a creation, material, experience, circumstance, or combination of qualities.',
    definition: 'Rarity can be natural, produced, historical, geographic, technical, or experiential. It becomes meaningful when its origin and limits are understood rather than simply announced.',
    houseContext: 'Shamim Forever distinguishes rarity from scarcity theatre. A limited creation should have a clear reason for its limit and an honest record of what that limit means.',
    whyItMatters: 'Understanding rarity helps people assess what is genuinely uncommon and what is merely marketed as such.',
    relatedSlugs: ['scarcity', 'exclusivity', 'luxury', 'provenance', 'limited-creation'],
    misunderstandings: 'Rare does not always mean desirable, valuable, or well-made. Rarity needs relevance and context.',
    resources: [{ label: 'Explore Luxury', href: '/learn/luxury' }, { label: 'Read the Guides', href: '/guides#luxury' }],
  }),
  term({
    slug: 'sovereignty',
    term: 'Sovereignty',
    pronunciation: 'SOV·rən·tee',
    category: 'Sovereign Philosophy',
    shortDefinition: 'The capacity for independent authority, identity, control, and continuity.',
    definition: 'Sovereignty is context-dependent. For a person, House, or system it may involve the ability to make decisions, protect identity, govern resources, and continue with resilience.',
    houseContext: 'Shamim Forever uses sovereignty as a conceptual framework, not an absolute claim. Any technical, legal, or operational assertion must be supported by evidence and carefully scoped.',
    whyItMatters: 'The concept prompts institutions to ask who controls their identity, data, standards, dependencies, and future decisions.',
    relatedSlugs: ['sovereign-infrastructure', 'digital-identity', 'integrity', 'continuity', 'stewardship'],
    misunderstandings: 'Sovereignty does not mean isolation or total control. No system should be called “fully sovereign” without clear technical and legal proof.',
    resources: [{ label: 'Explore Sovereign Infrastructure', href: '/learn/sovereign-infrastructure' }, { label: 'Read the White Paper library', href: '/whitepapers' }],
  }),
  term({
    slug: 'sovereign-infrastructure',
    term: 'Sovereign Infrastructure',
    pronunciation: 'SOV·rən IN·fruh·struk·cher',
    category: 'Sovereign Infrastructure',
    shortDefinition: 'The resilient organisational, digital, physical, and governance systems that support identity and continuity.',
    definition: 'Sovereign infrastructure describes the architecture behind an institution: secure systems, data stewardship, operational resilience, governance, interoperability, archives, and the ability to protect its standards.',
    houseContext: 'It is one of Shamim Forever’s emerging knowledge areas. The term names a direction of research and design, not a claim that any system is independent of every external dependency.',
    whyItMatters: 'A beautiful front end cannot preserve a House without reliable systems behind it. Infrastructure gives continuity practical form.',
    relatedSlugs: ['sovereignty', 'digital-identity', 'resilience', 'digital-authenticity', 'governance'],
    misunderstandings: 'Sovereign infrastructure is not simply blockchain, a private server, or a security product. It is a whole-system question about control, resilience, and responsibility.',
    resources: [{ label: 'Read the Infrastructure guide', href: '/learn/sovereign-infrastructure' }, { label: 'Explore White Papers', href: '/whitepapers' }],
  }),
  term({
    slug: 'traceability',
    term: 'Traceability',
    pronunciation: 'TRAYS·uh·BIL·uh·tee',
    category: 'Digital Authenticity',
    shortDefinition: 'The ability to follow a material, creation, transaction, or record through defined stages using evidence.',
    definition: 'Traceability links events and records across a chain: sourcing, making, inspection, custody, delivery, care, repair, or transfer. It is a process property, not a visual badge.',
    houseContext: 'For the House, traceability can support authenticity and responsible sourcing when the records, permissions, and limits of the system are clear.',
    whyItMatters: 'Traceability improves accountability and makes it easier to investigate, care for, and explain a creation over time.',
    relatedSlugs: ['provenance', 'chain-of-custody', 'verification', 'digital-identity', 'authenticity'],
    misunderstandings: 'Traceability does not mean that every fact is public, perfect, or immutable. It means the relevant journey can be followed to an appropriate degree.',
    resources: [{ label: 'Explore Authenticity', href: '/learn/authenticity' }, { label: 'Read about digital systems', href: '/learn/sovereign-infrastructure/data-architecture' }],
  }),
  term({
    slug: 'verification',
    term: 'Verification',
    pronunciation: 'ver·uh·fuh·KAY·shən',
    category: 'Authenticity',
    shortDefinition: 'The process of checking a claim, record, identity, or creation against relevant evidence.',
    definition: 'Verification asks whether available evidence supports a stated fact. The method should be proportionate to the claim, transparent about its limits, and capable of being reviewed.',
    houseContext: 'Shamim Forever treats verification as a layered practice that may include physical examination, records, serialisation, expert judgement, and digital systems.',
    whyItMatters: 'Clear verification turns trust from a feeling into a process that can be explained and improved.',
    relatedSlugs: ['authentication', 'authenticity', 'provenance', 'digital-identity', 'traceability'],
    misunderstandings: 'Verification is not the same as certainty, and a verified record is not automatically a guarantee of every quality or future event.',
    resources: [{ label: 'Read What Is Authenticity?', href: '/learn/authenticity/what-is-authenticity' }, { label: 'Explore the Guides', href: '/guides#authenticity' }],
  }),
  term({
    slug: 'white-glove-service',
    term: 'White-Glove Service',
    pronunciation: 'WYTE GLUV SUR·vis',
    category: 'Concierge',
    shortDefinition: 'A highly attentive service experience designed around care, discretion, precision, and the client’s circumstances.',
    definition: 'White-glove service is a standard of attention rather than a costume or phrase. It may include careful handling, private coordination, proactive communication, delivery, installation, and aftercare.',
    houseContext: 'At Shamim Forever, the phrase should be earned through what the client actually experiences: clarity, respect, responsiveness, and care for the creation.',
    whyItMatters: 'Service becomes part of the creation’s meaning when it protects a client’s time and preserves the object’s condition.',
    relatedSlugs: ['concierge', 'private-client', 'aftercare', 'private-access', 'bespoke'],
    misunderstandings: 'White-glove service is not merely expensive packaging, formality, or a promise of instant availability.',
    resources: [{ label: 'Meet the Concierge', href: '/concierge' }, { label: 'Explore Care', href: '/care' }],
  }),
  term({
    slug: 'house',
    term: 'House',
    pronunciation: 'HOWS',
    category: 'The House',
    shortDefinition: 'A living institution expressed through its philosophy, creations, people, standards, relationships, and memory.',
    definition: 'A House is the system behind the visible product. It holds a point of view, a way of making decisions, a relationship with clients, and a responsibility to the future.',
    houseContext: 'Shamim Forever is developing as a House of luxury, craft, technology, service, and stewardship. Its institutional identity should be judged by consistent practice over time.',
    whyItMatters: 'Thinking as a House connects individual creations to the standards and relationships that make them meaningful.',
    relatedSlugs: ['maison', 'house-identity', 'heritage', 'atelier', 'legacy'],
    misunderstandings: 'A House is not simply a logo, company name, or catalogue of products.',
    resources: [{ label: 'Read The House', href: '/learn/the-house' }, { label: 'Explore the brand book', href: '/whitepapers' }],
  }),
  term({
    slug: 'quiet-luxury',
    term: 'Quiet Luxury',
    pronunciation: 'KWY·ət LUK·shuh·ree',
    category: 'Luxury',
    shortDefinition: 'A mode of luxury that communicates quality, restraint, and discernment without relying on conspicuous display.',
    definition: 'Quiet luxury is a cultural description, not a universal quality guarantee. It often values subtle materials, construction, fit, provenance, and a lower volume of visible branding.',
    houseContext: 'The House values restraint when it helps attention move toward material, craft, service, and meaning. Quietness should not become a substitute for substance.',
    whyItMatters: 'The concept helps distinguish personal value and enduring design from the pressure to perform status publicly.',
    relatedSlugs: ['luxury', 'craftsmanship', 'exclusivity', 'heritage', 'timeless-luxury'],
    misunderstandings: 'Quiet does not always mean better, more ethical, or more expensive. It is an aesthetic and cultural tendency, not proof.',
    resources: [{ label: 'Explore Luxury', href: '/learn/luxury' }, { label: 'Read Guides', href: '/guides#luxury' }],
  }),
  term({
    slug: 'materiality',
    term: 'Materiality',
    pronunciation: 'muh·TEER·ee·AL·uh·tee',
    category: 'Materials',
    shortDefinition: 'The physical character, behaviour, origin, and meaning of the materials used in a creation.',
    definition: 'Materiality considers what a material feels like, how it performs, how it changes, where it comes from, and what its use communicates. It joins sensory experience with technical and ethical judgement.',
    houseContext: 'The atelier uses materiality to guide selection, construction, finishing, care, and the stories the House can honestly tell about a creation.',
    whyItMatters: 'Respect for material leads to better design, longer life, more honest sourcing, and deeper appreciation of craft.',
    relatedSlugs: ['craftsmanship', 'atelier', 'sustainability', 'provenance', 'hand-finished'],
    misunderstandings: 'A costly or natural material is not automatically responsible, durable, or beautiful. Performance and context matter.',
    resources: [{ label: 'Explore Craft & Atelier', href: '/guides#craft-atelier' }, { label: 'Read Sustainability', href: '/sustainability' }],
  }),
  term({
    slug: 'stewardship',
    term: 'Stewardship',
    pronunciation: 'STOO·ərd·ship',
    category: 'Sovereign Philosophy',
    shortDefinition: 'The responsibility to care for, document, preserve, and thoughtfully carry something of value into the future.',
    definition: 'Stewardship is active responsibility. It includes maintenance, ethical decision-making, records, repair, education, and the willingness to leave a creation or system stronger for its next chapter.',
    houseContext: 'The House uses stewardship to describe the relationship between making and aftercare, between ownership and preservation, and between present ambition and future consequence.',
    whyItMatters: 'Stewardship turns value into a practice rather than a claim.',
    relatedSlugs: ['legacy', 'heirloom', 'heritage', 'preservation', 'sovereignty'],
    misunderstandings: 'Stewardship is not passive possession, indefinite control, or perfection. It is a continuing duty shaped by context.',
    resources: [{ label: 'Explore Ownership & Stewardship', href: '/guides#ownership-stewardship' }, { label: 'Visit the Heirloom Vault', href: '/heirloom-vault' }],
  }),
]

export function getGlossaryTerm(slug: string) {
  return glossaryTerms.find((entry) => entry.slug === slug)
}