export interface GuestCurationConfig {
    slug: string
    archiveCode: string
    archiveLabel: string
    collectionName: string
    classification: string
    size: string
    globalRetailUsd: number
    signatureNotes: string[]
    whyCurated: string[]
    curatorPositioning: string[]
    image?: string
  }

  const CONFIGS: GuestCurationConfig[] = [
    // ── FEMALE SERIES ──────────────────────────────────────────
    {
      slug: 'delina-exclusif',
      archiveCode: 'G-I',
      archiveLabel: 'Curated Female Allocation — Archive G-I',
      collectionName: 'The Sovereign Rose Archive',
      classification: 'Luxury Niche Feminine Masterpiece',
      size: '75ml',
      globalRetailUsd: 430,
      signatureNotes: ['Turkish Rose', 'Lychee', 'Incense', 'Oud', 'Vanilla'],
      whyCurated: [
        'Delina Exclusif represents the meeting point between aristocratic floral craftsmanship and modern luxury architecture.',
        'Its Turkish Rose core carries extraordinary richness. Its incense foundation creates permanence. Its oud structure delivers authority.',
        'The House selected Delina Exclusif because it demonstrates a philosophy we deeply respect: Beauty strengthened by discipline.',
        'This fragrance belongs inside every sovereign feminine archive.',
      ],
      curatorPositioning: ['Not merely a floral perfume.', 'A modern rose monument.', 'A luxury standard.', 'A permanent feminine signature.'],
    },
    {
      slug: 'amouage-guidance',
      archiveCode: 'G-II',
      archiveLabel: 'Curated Female Allocation — Archive G-II',
      collectionName: 'The Sovereign Harmony Archive',
      classification: 'Ultra-Luxury Niche Feminine Composition',
      size: '100ml',
      globalRetailUsd: 395,
      signatureNotes: ['Pear', 'Hazelnut', 'Frankincense', 'Osmanthus', 'Rose', 'Sandalwood'],
      whyCurated: [
        'Guidance represents emotional intelligence translated into fragrance.',
        'Its Omani Frankincense foundation reflects structure. Its creamy woods create depth. Its floral architecture creates sophistication.',
        'The House allocated Guidance because true luxury whispers rather than shouts. This fragrance rewards attention.',
        'And reveals new dimensions over time.',
      ],
      curatorPositioning: ['Not a trend.', 'A sensory symphony.', 'An intelligent luxury asset.'],
    },
    {
      slug: 'baccarat-rouge-540-extrait',
      archiveCode: 'G-III',
      archiveLabel: 'Curated Female Allocation — Archive G-III',
      collectionName: 'The Crystal Empire Archive',
      classification: 'Luxury Amber-Wood Extrait',
      size: '70ml',
      globalRetailUsd: 465,
      signatureNotes: ['Saffron', 'Bitter Almond', 'Egyptian Jasmine', 'Ambergris', 'Cedarwood'],
      whyCurated: [
        'Few fragrances have achieved modern legendary status. Baccarat Rouge 540 Extrait is one of them.',
        'Its saffron brilliance. Its ambergris structure. Its crystalline projection.',
        "Together create one of contemporary perfumery's most recognized luxury signatures.",
        'The House includes it as an archive-worthy benchmark of modern excellence.',
      ],
      curatorPositioning: ['A fragrance icon.', 'A global luxury reference point.', 'A crystal monument in liquid form.'],
    },
    {
      slug: 'xerjoff-casamorati-lira',
      archiveCode: 'G-IV',
      archiveLabel: 'Curated Female Allocation — Archive G-IV',
      collectionName: 'The Golden Theatre Archive',
      classification: 'Luxury Gourmand Masterpiece',
      size: '100ml',
      globalRetailUsd: 315,
      signatureNotes: ['Blood Orange', 'Bergamot', 'Lavender', 'Cinnamon', 'Licorice', 'Caramel Vanilla'],
      whyCurated: [
        'Lira preserves old-world Italian romance. Rich sweetness. Vintage elegance. Theatrical beauty.',
        'Its gourmand architecture demonstrates how luxury can feel emotional without sacrificing sophistication.',
      ],
      curatorPositioning: ['A heritage gourmand.', "A collector's dessert.", 'A preserved piece of olfactory history.'],
    },
    {
      slug: 'initio-atomic-rose',
      archiveCode: 'G-V',
      archiveLabel: 'Curated Female Allocation — Archive G-V',
      collectionName: 'The Sovereign Power Rose',
      classification: 'Luxury High-Impact Floral',
      size: '90ml',
      globalRetailUsd: 360,
      signatureNotes: ['Italian Bergamot', 'Bulgarian Rose', 'Turkish Rose', 'Egyptian Jasmine', 'Madagascar Vanilla'],
      whyCurated: [
        'Atomic Rose transforms the rose from ornament into authority. Powerful. Bold. Unapologetic.',
        'The House selected this masterpiece because it demonstrates how a classic floral note can become a commanding statement.',
      ],
      curatorPositioning: ['Not a flower.', 'A declaration.', 'A rose engineered for influence.'],
    },
    {
      slug: 'chanel-coco-mademoiselle-intense',
      archiveCode: 'G-VI',
      archiveLabel: 'Curated Female Allocation — Archive G-VI',
      collectionName: 'The Executive Elegance Archive',
      classification: 'Luxury Corporate Feminine Signature',
      size: '100ml',
      globalRetailUsd: 190,
      signatureNotes: ['Patchouli', 'Sicilian Orange', 'Calabrian Bergamot', 'Amber', 'Tonka Bean'],
      whyCurated: [
        'Modern feminine professionalism has few universal references. Coco Mademoiselle Intense remains one of them.',
        'The House recognizes its ability to balance elegance, confidence, and maturity with effortless authority.',
      ],
      curatorPositioning: ['Boardroom luxury.', 'Executive sophistication.', 'Timeless feminine structure.'],
    },
    {
      slug: 'dior-jadore-lor',
      archiveCode: 'G-VII',
      archiveLabel: 'Curated Female Allocation — Archive G-VII',
      collectionName: 'The Liquid Gold Archive',
      classification: 'Luxury Floral Essence',
      size: '50ml',
      globalRetailUsd: 170,
      signatureNotes: ['Orange Blossom Absolute', 'Jasmine Grandiflorum', 'Centifolia Rose'],
      whyCurated: [
        "J'adore L'Or feels like concentrated precious metal. Rich. Radiant. Refined.",
        'The House selected this composition because it embodies purity elevated to luxury.',
      ],
      curatorPositioning: ['Liquid gold.', 'Floral wealth.', 'Pure feminine refinement.'],
    },
    {
      slug: 'tom-ford-velvet-orchid',
      archiveCode: 'G-VIII',
      archiveLabel: 'Curated Female Allocation — Archive G-VIII',
      collectionName: 'The Midnight Society Archive',
      classification: 'Dark Oriental Floral',
      size: '100ml',
      globalRetailUsd: 235,
      signatureNotes: ['Black Orchid', 'Velvet Orchid', 'Rum', 'Honey', 'Mandarin', 'Myrrh'],
      whyCurated: [
        "Mystery remains one of luxury's most powerful currencies. Velvet Orchid operates within shadows.",
        'Its honey. Its rum. Its dark floral architecture. Together create an atmosphere of private luxury.',
      ],
      curatorPositioning: ['Not attention.', 'Intrigue.', 'Not visibility.', 'Presence.'],
    },
    {
      slug: 'ysl-libre-le-parfum',
      archiveCode: 'G-IX',
      archiveLabel: 'Curated Female Allocation — Archive G-IX',
      collectionName: 'The Sovereign Freedom Archive',
      classification: 'Luxury Floral Amber',
      size: '90ml',
      globalRetailUsd: 195,
      signatureNotes: ['French Lavender', 'Moroccan Orange Blossom', 'Ginger', 'Saffron'],
      whyCurated: [
        'Libre Le Parfum embodies self-determination. Its lavender structure. Its saffron warmth. Its amber foundation.',
        'Create a fragrance that feels modern yet authoritative.',
      ],
      curatorPositioning: ['Freedom with structure.', 'Elegance with power.', 'Modern sovereignty in liquid form.'],
    },
    {
      slug: 'kilian-angels-share',
      archiveCode: 'G-X',
      archiveLabel: 'Curated Female Allocation — Archive G-X',
      collectionName: 'The Heritage Cognac Archive',
      classification: 'Luxury Gourmand Amber',
      size: '50ml',
      globalRetailUsd: 245,
      signatureNotes: ['Cognac Accord', 'Cinnamon', 'Tonka Bean', 'Praline', 'Vanilla', 'Oak'],
      whyCurated: [
        "Some fragrances transcend categories. Angels' Share is one of them. Warm. Addictive. Sophisticated.",
        'The House includes it because it captures the emotional richness of celebration, memory, and legacy.',
      ],
      curatorPositioning: ["A bottle of heritage.", "A vault of memories.", 'A luxury masterpiece worthy of preservation.'],
    },

    // ── MALE SERIES — SF GUEST CURATION ──────────────────────
    {
      slug: 'creed-aventus',
      archiveCode: 'M-I',
      archiveLabel: 'Curated Masculine Allocation — Archive M-I',
      collectionName: 'The Empire Benchmark Archive',
      classification: 'Luxury Masculine Icon',
      size: '100ML',
      globalRetailUsd: 565,
      image: '/guest-curation/male/creed-aventus.jpg',
      signatureNotes: ['Pineapple', 'Bergamot', 'Birch Wood', 'Patchouli', 'Ambergris'],
      whyCurated: [
        'Few fragrances have influenced modern masculine perfumery like Aventus.',
        'Its fusion of bright pineapple and dry birch smoke created an entirely new luxury category.',
        'The House allocated Aventus because it represents leadership through identity rather than imitation.',
      ],
      curatorPositioning: ['A global masculine benchmark.', 'A symbol of success.', 'An empire captured in glass.'],
    },
    {
      slug: 'roja-elysium-pour-homme',
      archiveCode: 'M-II',
      archiveLabel: 'Curated Masculine Allocation — Archive M-II',
      collectionName: 'The Sovereign Freshness Archive',
      classification: 'Ultra-Luxury Fresh Masculine',
      size: '100ML',
      globalRetailUsd: 385,
      image: '/guest-curation/male/roja-elysium.jpg',
      signatureNotes: ['Grapefruit', 'Lime', 'Lavender', 'Vetiver', 'Ambergris', 'Leather'],
      whyCurated: [
        'Fresh fragrances rarely achieve true luxury status.',
        'Elysium succeeds through extraordinary refinement and balance.',
        'Its citrus brilliance and ambergris structure embody discipline over noise.',
      ],
      curatorPositioning: ['Freshness elevated to sovereignty.', 'Precision luxury.', 'Silent authority.'],
    },
    {
      slug: 'tom-ford-oud-wood',
      archiveCode: 'M-III',
      archiveLabel: 'Curated Masculine Allocation — Archive M-III',
      collectionName: 'The Executive Sanctuary Archive',
      classification: 'Luxury Clean Oud Masterpiece',
      size: '100ML',
      globalRetailUsd: 365,
      image: '/guest-curation/male/tom-ford-oud-wood.jpg',
      signatureNotes: ['Rare Oud', 'Sandalwood', 'Chinese Pepper', 'Rosewood', 'Vanilla', 'Amber'],
      whyCurated: [
        'Oud Wood transformed oud into modern sophistication.',
        'Its creamy architecture appeals to leaders, founders, and visionaries who value refinement over excess.',
      ],
      curatorPositioning: ['Corporate luxury.', 'Modern wealth.', 'Private confidence.'],
    },
    {
      slug: 'parfums-de-marly-layton',
      archiveCode: 'M-IV',
      archiveLabel: 'Curated Masculine Allocation — Archive M-IV',
      collectionName: 'The Aristocratic Legacy Archive',
      classification: 'Luxury Modern Gentleman Signature',
      size: '125ML',
      globalRetailUsd: 435,
      image: '/guest-curation/male/layton.webp',
      signatureNotes: ['Apple', 'Lavender', 'Bergamot', 'Violet', 'Vanilla', 'Guaiac Wood'],
      whyCurated: [
        'Layton represents timeless masculine elegance.',
        "Its balance of freshness, spice, and creamy woods creates one of modern perfumery's most admired signatures.",
      ],
      curatorPositioning: ['Modern royalty.', 'French aristocratic luxury.', 'A legacy preserved through scent.'],
    },
    {
      slug: 'amouage-interlude-man',
      archiveCode: 'M-V',
      archiveLabel: 'Curated Masculine Allocation — Archive M-V',
      collectionName: 'The Fortress Archive',
      classification: 'Ultra-Luxury Dark Oriental',
      size: '100ML',
      globalRetailUsd: 485,
      image: '/guest-curation/male/amouage-interlude.webp',
      signatureNotes: ['Oregano', 'Pimento Berry', 'Frankincense', 'Amber', 'Myrrh', 'Leather'],
      whyCurated: [
        'Known globally as the Blue Beast, Interlude Man represents uncompromising strength.',
        'Its fortress-like structure aligns perfectly with the House philosophy of permanence and authority.',
      ],
      curatorPositioning: ['Not a fragrance.', 'A sensory fortress.', 'Smoke forged into power.'],
    },
    {
      slug: 'kilian-angels-share-homme',
      archiveCode: 'M-VI',
      archiveLabel: 'Curated Masculine Allocation — Archive M-VI',
      collectionName: 'The Heritage Cognac Archive',
      classification: 'Luxury Gourmand Amber',
      size: '50ML',
      globalRetailUsd: 315,
      image: '/guest-curation/male/kilian-angels-share.webp',
      signatureNotes: ['Cognac Oil', 'Oak', 'Cinnamon', 'Tonka Bean', 'Praline', 'Sandalwood'],
      whyCurated: [
        "Angels' Share captures celebration, heritage, and luxury in its purest form.",
        'Its cognac architecture creates one of the most addictive modern compositions.',
      ],
      curatorPositioning: ['A bottle of heritage.', 'A vault of memories.', 'Liquid prosperity.'],
    },
    {
      slug: 'xerjoff-naxos',
      archiveCode: 'M-VII',
      archiveLabel: 'Curated Masculine Allocation — Archive M-VII',
      collectionName: 'The Golden Tobacco Archive',
      classification: 'Luxury Honey Tobacco Masterpiece',
      size: '100ML',
      globalRetailUsd: 355,
      image: '/guest-curation/male/xerjoff-naxos.webp',
      signatureNotes: ['Honey', 'Tobacco', 'Lavender', 'Bergamot', 'Cinnamon', 'Vanilla'],
      whyCurated: [
        'Naxos embodies warmth, sophistication, and comfort without sacrificing luxury.',
        'Its tobacco-honey structure feels regal and timeless.',
      ],
      curatorPositioning: ['Golden luxury.', 'Refined success.', "An aristocrat's signature."],
    },
    {
      slug: 'lv-ombre-nomade',
      archiveCode: 'M-VIII',
      archiveLabel: 'Curated Masculine Allocation — Archive M-VIII',
      collectionName: 'The Dark Empire Archive',
      classification: 'Ultra-Luxury Oud Monument',
      size: '100ML',
      globalRetailUsd: 495,
      image: '/guest-curation/male/lv-ombre-nomade.jpg',
      signatureNotes: ['Oud Wood', 'Incense', 'Benzoin', 'Raspberry'],
      whyCurated: [
        'Ombre Nomade is one of the most powerful oud creations ever released.',
        'Dense. Dark. Authoritative.',
        "Its architecture mirrors the philosophy behind the House's own archive creations.",
      ],
      curatorPositioning: ['A dark empire.', 'An uncompromising presence.', 'A monument of oud.'],
    },
    {
      slug: 'mfk-grand-soir',
      archiveCode: 'M-IX',
      archiveLabel: 'Curated Masculine Allocation — Archive M-IX',
      collectionName: 'The Golden Midnight Archive',
      classification: 'Luxury Amber Masterpiece',
      size: '70ML',
      globalRetailUsd: 355,
      image: '/guest-curation/male/mfk-grand-soir.jpg',
      signatureNotes: ['Labdanum', 'Benzoin', 'Tonka Bean', 'Amber', 'Vanilla'],
      whyCurated: [
        'Grand Soir transforms warmth into art.',
        'Its luminous amber structure feels like golden light preserved within crystal.',
      ],
      curatorPositioning: ['Parisian luxury.', 'Golden sophistication.', 'Timeless warmth.'],
    },
    {
      slug: 'penhaligons-lord-george',
      archiveCode: 'M-X',
      archiveLabel: 'Curated Masculine Allocation — Archive M-X',
      collectionName: 'The Aristocratic Gentleman Archive',
      classification: 'Luxury British Heritage Signature',
      size: '75ML',
      globalRetailUsd: 395,
      image: '/guest-curation/male/penhaligons-lord-george.webp',
      signatureNotes: ['Brandy', 'Shaving Soap', 'Amber', 'Tonka Bean'],
      whyCurated: [
        'Lord George represents traditional masculine refinement.',
        'Its elegant British character reflects discipline, structure, and institutional stature.',
      ],
      curatorPositioning: ['Old-world authority.', 'Heritage craftsmanship.', 'A gentleman preserved in time.'],
    },

    // ── SF ESSENTIAL ARCHIVE FOR HIM ─────────────────────────
    {
      slug: 'bleu-de-chanel-essential',
      archiveCode: 'E-I',
      archiveLabel: 'SF Essential Archive For Him — Allocation E-I',
      collectionName: 'The Executive Archive',
      classification: 'Luxury Fresh Woody Signature',
      size: '50ML EDT',
      globalRetailUsd: 129,
      image: '/images/products/bleu-de-chanel.png',
      signatureNotes: ['Grapefruit', 'Mint', 'Ginger', 'Incense', 'Cedarwood', 'Sandalwood'],
      whyCurated: [
        'Few fragrances have influenced modern masculine luxury more than Bleu de Chanel.',
        'Its balance of freshness, sophistication, and executive presence has made it a universal benchmark.',
        'The House selected it as a foundational allocation because it performs flawlessly in every environment — boardroom, meeting, event, or private gathering.',
        'This is not a fragrance you discover. It is a fragrance you inherit.',
      ],
      curatorPositioning: [
        'Corporate luxury.',
        'Executive authority.',
        'A modern leadership standard.',
        'The scent worn by men who have already arrived.',
      ],
    },
    {
      slug: 'dior-sauvage-essential',
      archiveCode: 'E-II',
      archiveLabel: 'SF Essential Archive For Him — Allocation E-II',
      collectionName: 'The Frontier Archive',
      classification: 'Fresh Aromatic Powerhouse',
      size: '60ML EDT',
      globalRetailUsd: 129,
      image: '/images/products/dior-sauvage.png',
      signatureNotes: ['Calabrian Bergamot', 'Sichuan Pepper', 'Lavender', 'Pink Pepper', 'Patchouli', 'Ambroxan'],
      whyCurated: [
        'Sauvage transformed contemporary masculine perfumery through its explosive freshness and unmistakable projection.',
        'It became the world\'s best-selling masculine fragrance not through trend — but through universal magnetic appeal.',
        'The House allocated Sauvage because its Ambroxan signature creates an almost supernatural skin chemistry with the wearer.',
        'It adapts. It projects. It stays. A fragrance that becomes part of your identity.',
      ],
      curatorPositioning: [
        'Raw confidence.',
        'Modern influence.',
        'A global masculine icon.',
        'Worn by leaders who move without hesitation.',
      ],
    },
    {
      slug: 'acqua-di-gio-essential',
      archiveCode: 'E-III',
      archiveLabel: 'SF Essential Archive For Him — Allocation E-III',
      collectionName: 'The Oceanic Archive',
      classification: 'Marine Citrus Classic',
      size: '50ML EDT',
      globalRetailUsd: 119,
      image: '/images/products/acqua-di-gio.png',
      signatureNotes: ['Sea Notes', 'Bergamot', 'Neroli', 'Jasmine', 'Rosemary', 'Cedarwood', 'Patchouli'],
      whyCurated: [
        'One of the most recognizable fresh fragrances ever created. Acqua di Giò captures clarity, calmness, and effortless sophistication.',
        'For over three decades it has defined what a clean, Mediterranean masculine fragrance should feel like.',
        'The House selected it because timelessness is itself a form of luxury.',
        'It belongs in every essential masculine archive — not because it is modern, but because it never ages.',
      ],
      curatorPositioning: [
        'Mediterranean elegance.',
        'Timeless freshness.',
        'Pure refinement.',
        'The fragrance of a man at peace with his own power.',
      ],
    },
    {
      slug: 'ysl-la-nuit-essential',
      archiveCode: 'E-IV',
      archiveLabel: 'SF Essential Archive For Him — Allocation E-IV',
      collectionName: 'The Midnight Archive',
      classification: 'Spicy Evening Signature',
      size: '60ML EDT',
      globalRetailUsd: 125,
      image: '/images/products/ysl-la-nuit.png',
      signatureNotes: ['Cardamom', 'Lavender', 'Virginia Cedar', 'Coumarin', 'White Musk'],
      whyCurated: [
        'La Nuit de L\'Homme remains one of the most respected evening fragrances in modern luxury.',
        'Its cardamom-lavender accord created a new standard for masculine sophistication in night settings.',
        'The House allocated La Nuit because there are moments that require an elevated presence — and this fragrance delivers it consistently.',
        'Smooth. Magnetic. Unforgettable.',
      ],
      curatorPositioning: [
        'Sophisticated mystery.',
        'Nighttime authority.',
        'Refined charisma.',
        'The scent of a man who controls the room without trying.',
      ],
    },
    {
      slug: 'versace-eros-essential',
      archiveCode: 'E-V',
      archiveLabel: 'SF Essential Archive For Him — Allocation E-V',
      collectionName: 'The Conquest Archive',
      classification: 'Fresh Amber Power Fragrance',
      size: '50ML EDP',
      globalRetailUsd: 129,
      image: '/images/products/versace-eros.png',
      signatureNotes: ['Mint', 'Italian Lemon', 'Green Apple', 'Tonka Bean', 'Amber', 'Vetiver', 'Atlas Cedarwood'],
      whyCurated: [
        'Eros represents ambition, energy, and unapologetic confidence.',
        'Its bold mint-citrus opening creates an immediate impression — vibrant, masculine, undeniable.',
        'The House selected Eros because it captures the spirit of achievement without arrogance.',
        'It wears like a declaration. Every spray is an affirmation of intent.',
      ],
      curatorPositioning: [
        'Passion.',
        'Power.',
        'Modern conquest.',
        'The scent of a man who pursues excellence without apology.',
      ],
    },
    {
      slug: 'terre-dhermes-essential',
      archiveCode: 'E-VI',
      archiveLabel: 'SF Essential Archive For Him — Allocation E-VI',
      collectionName: 'The Earth Archive',
      classification: 'Mineral Woody Luxury',
      size: '50ML EDT',
      globalRetailUsd: 135,
      image: '/images/products/terre-dhermes.png',
      signatureNotes: ['Orange', 'Pink Pepper', 'Flint', 'Vetiver', 'Cedarwood', 'Benzoin', 'Grapefruit'],
      whyCurated: [
        'Terre d\'Hermès remains one of the most sophisticated woody fragrances ever created by a major house.',
        'Its flint-mineral signature is unlike anything else in the genre — grounded, intellectual, and completely self-assured.',
        'The House allocated it because it reflects discipline, structure, and a quiet maturity that commands deep respect.',
        'This is the fragrance of a man who builds — not follows.',
      ],
      curatorPositioning: [
        'Grounded authority.',
        'Quiet confidence.',
        'Intellectual luxury.',
        'The scent of a man who knows exactly who he is.',
      ],
    },
    {
      slug: 'tom-ford-noir-anthracite-essential',
      archiveCode: 'E-VII',
      archiveLabel: 'SF Essential Archive For Him — Allocation E-VII',
      collectionName: 'The Shadow Archive',
      classification: 'Dark Woody Spice',
      size: '30ML Travel Allocation',
      globalRetailUsd: 125,
      image: '/images/products/tom-ford-noir.png',
      signatureNotes: ['Sichuan Pepper', 'Ginger', 'Galbanum', 'Cedarwood', 'Ebony Wood', 'Vetiver'],
      whyCurated: [
        'Dark. Architectural. Uncompromising.',
        'Noir Anthracite represents power concealed behind discipline — the signature of men who operate at the highest levels.',
        'The House selected it as a travel allocation because its compact format delivers maximum impact in any situation.',
        'Wear it when presence is the only strategy that matters.',
      ],
      curatorPositioning: [
        'The scent of strategic silence.',
        'Dark sophistication.',
        'Power without announcement.',
        'Architecture in fragrance form.',
      ],
    },
    {
      slug: 'prada-lhomme-essential',
      archiveCode: 'E-VIII',
      archiveLabel: 'SF Essential Archive For Him — Allocation E-VIII',
      collectionName: 'The Precision Archive',
      classification: 'Luxury Clean Iris Signature',
      size: '50ML EDT',
      globalRetailUsd: 125,
      image: '/images/products/prada-lhomme.png',
      signatureNotes: ['Iris', 'Amber', 'Neroli', 'Geranium', 'Patchouli', 'Vetiver'],
      whyCurated: [
        'Prada L\'Homme exemplifies modern professionalism through immaculate cleanliness and refined structure.',
        'Its iris-forward composition signals sophistication without effort — the hallmark of genuine luxury.',
        'The House allocated it because it performs flawlessly in professional environments where precision matters.',
        'Clean without being cold. Structured without being rigid. Perfect without being obvious.',
      ],
      curatorPositioning: [
        'Professional perfection.',
        'Corporate sophistication.',
        'Everyday prestige.',
        'The scent of a man whose standards never drop.',
      ],
    },
    {
      slug: 'jpg-le-male-essential',
      archiveCode: 'E-IX',
      archiveLabel: 'SF Essential Archive For Him — Allocation E-IX',
      collectionName: "The Captain's Archive",
      classification: 'Oriental Amber Signature',
      size: '75ML EDP',
      globalRetailUsd: 129,
      image: '/images/products/jpg-le-male.png',
      signatureNotes: ['Cardamom', 'Lavender', 'Iris', 'Vanilla', 'Vetiver', 'Sandalwood', 'Oriental Woods'],
      whyCurated: [
        'A modern evolution of one of history\'s most iconic masculine lineages.',
        'Le Parfum intensifies the original into something denser, smoother, and remarkably refined.',
        'The House allocated Le Male Le Parfum because it carries weight — the kind that commands respect without demanding it.',
        'Dense enough for winter. Smooth enough for evenings. Powerful enough to remember.',
      ],
      curatorPositioning: [
        'Command presence.',
        'Timeless masculinity.',
        'Modern aristocracy.',
        'A fragrance that has earned its place in history.',
      ],
    },
    {
      slug: 'giorgio-armani-code-essential',
      archiveCode: 'E-X',
      archiveLabel: 'SF Essential Archive For Him — Allocation E-X',
      collectionName: 'The Enigma Archive',
      classification: 'Elegant Amber Aromatic',
      size: '50ML EDT',
      globalRetailUsd: 119,
      signatureNotes: ['Green Mandarin', 'Bergamot', 'Lavender', 'Guaiac Wood', 'Tonka Bean', 'Cedarwood', 'Olive Blossom'],
      whyCurated: [
        'Armani Code remains one of the most respected evening signatures in luxury fragrance history.',
        'Its elegance has survived generations of trends, remaining a benchmark of masculine refinement.',
        'The House selected it to complete the essential archive because every collection needs a piece of enduring legacy.',
        'Not loud. Not obvious. Simply perfect — year after year, decade after decade.',
      ],
      curatorPositioning: [
        'Structured mystery.',
        'Quiet power.',
        'Enduring sophistication.',
        'The fragrance of a man whose reputation precedes him.',
      ],
    },

    // ── UNISEX SERIES — SF GUEST CURATION ──────────────────────
    {
      slug: 'byredo-gypsy-water',
      archiveCode: 'U-I',
      archiveLabel: 'Curated Unisex Allocation — Archive U-I',
      collectionName: 'The Sovereign Freedom Archive',
      classification: 'Luxury Woody Aromatic Unisex Signature',
      size: '50ML',
      globalRetailUsd: 245,
      image: '/guest-curation/unisex/byredo-gypsy-water.jpg',
      signatureNotes: ['Juniper', 'Lemon', 'Bergamot', 'Pine Needles', 'Incense', 'Sandalwood', 'Vanilla'],
      whyCurated: [
        'Gypsy Water represents artistic independence without boundaries.',
        'Its fresh juniper opening.',
        'Its smoky incense heart.',
        'Its smooth sandalwood foundation.',
        'Together create a fragrance that feels weightless yet memorable.',
        'The House selected Gypsy Water because it captures freedom in its most refined form.',
      ],
      curatorPositioning: ['Not a destination.', 'A journey.', 'A luxury escape preserved in glass.'],
    },
    {
      slug: 'le-labo-santal-33',
      archiveCode: 'U-II',
      archiveLabel: 'Curated Unisex Allocation — Archive U-II',
      collectionName: 'The Identity Archive',
      classification: 'Luxury Smoky Sandalwood Icon',
      size: '100ML',
      globalRetailUsd: 385,
      image: '/guest-curation/unisex/le-labo-santal-33.jpg',
      signatureNotes: ['Cardamom', 'Iris', 'Violet', 'Ambrox', 'Sandalwood', 'Papyrus', 'Cedarwood'],
      whyCurated: [
        'Santal 33 became a global benchmark because it refuses imitation.',
        'Its dry sandalwood.',
        'Its leathery structure.',
        'Its architectural simplicity.',
        'Reflect the House philosophy:',
        'Identity over imitation.',
      ],
      curatorPositioning: ['A cultural icon.', 'A global reference point.', 'A monument of individuality.'],
    },
    {
      slug: 'creed-silver-mountain-water',
      archiveCode: 'U-III',
      archiveLabel: 'Curated Unisex Allocation — Archive U-III',
      collectionName: 'The Crystal Summit Archive',
      classification: 'Luxury Alpine Fresh Masterpiece',
      size: '100ML',
      globalRetailUsd: 565,
      image: '/guest-curation/unisex/creed-silver-mountain-water.jpg',
      signatureNotes: ['Bergamot', 'Mandarin', 'Green Tea', 'Blackcurrant', 'Musk', 'Petitgrain', 'Sandalwood'],
      whyCurated: [
        'Silver Mountain Water represents luxury clarity.',
        'Its green tea freshness.',
        'Its metallic musk signature.',
        'Its alpine purity.',
        'Create one of the most refined fresh compositions ever produced.',
      ],
      curatorPositioning: ['Mountain air.', 'Crystal water.', 'Liquid precision.'],
    },
    {
      slug: 'diptyque-philosykos',
      archiveCode: 'U-IV',
      archiveLabel: 'Curated Unisex Allocation — Archive U-IV',
      collectionName: 'The Mediterranean Archive',
      classification: 'Luxury Fig Tree Masterpiece',
      size: '75ML',
      globalRetailUsd: 285,
      image: '/guest-curation/unisex/diptyque-philosykos.jpg',
      signatureNotes: ['Fig Leaf', 'Fig Fruit', 'Coconut', 'Green Notes', 'Cedar', 'Fig Tree Wood'],
      whyCurated: [
        'Philosykos preserves nature with remarkable authenticity.',
        'Every spray feels like walking beneath a Mediterranean fig tree.',
        'The House selected it because true luxury often begins with simplicity.',
      ],
      curatorPositioning: ['Nature refined.', 'Green luxury.', 'Mediterranean permanence.'],
    },
    {
      slug: 'tom-ford-soleil-blanc',
      archiveCode: 'U-V',
      archiveLabel: 'Curated Unisex Allocation — Archive U-V',
      collectionName: 'The Private Island Archive',
      classification: 'Luxury Solar Floral Masterpiece',
      size: '100ML',
      globalRetailUsd: 355,
      image: '/guest-curation/unisex/tom-ford-soleil-blanc.jpg',
      signatureNotes: ['Coconut', 'Ylang-Ylang', 'Bergamot', 'Cardamom', 'Pistachio', 'Amber', 'Tuberose'],
      whyCurated: [
        'Soleil Blanc transforms sunlight into luxury.',
        'Creamy.',
        'Warm.',
        'Sophisticated.',
        'A private resort preserved as a fragrance.',
      ],
      curatorPositioning: ['Sunlit opulence.', 'Endless summer.', 'Resort-level luxury.'],
    },
    {
      slug: 'nishane-hacivat',
      archiveCode: 'U-VI',
      archiveLabel: 'Curated Unisex Allocation — Archive U-VI',
      collectionName: 'The Legacy Archive',
      classification: 'Extrait de Parfum Luxury Signature',
      size: '100ML',
      globalRetailUsd: 365,
      image: '/guest-curation/unisex/nishane-hacivat.jpg',
      signatureNotes: ['Pineapple', 'Grapefruit', 'Bergamot', 'Oakmoss', 'Patchouli', 'Timberwood'],
      whyCurated: [
        'Hacivat represents permanence.',
        'Its extraordinary concentration.',
        'Its powerful longevity.',
        'Its oakmoss authority.',
        "Make it one of modern niche perfumery's strongest signatures.",
      ],
      curatorPositioning: ['Legacy over speed.', 'Power over trends.', 'A signature that refuses to fade.'],
    },
    {
      slug: 'parfums-de-marly-haltane',
      archiveCode: 'U-VII',
      archiveLabel: 'Curated Unisex Allocation — Archive U-VII',
      collectionName: 'The Prestige Archive',
      classification: 'Luxury Oud Prestige Signature',
      size: '125ML',
      globalRetailUsd: 425,
      image: '/guest-curation/unisex/parfums-de-marly-haltane.jpg',
      signatureNotes: ['Clary Sage', 'Lavender', 'Bergamot', 'Saffron', 'Praline', 'Oud Wood', 'Cedarwood'],
      whyCurated: [
        'Haltane balances strength and elegance.',
        'Natural oud meets modern sophistication.',
        'Authority meets refinement.',
        'The House selected it because prestige should never feel forced.',
      ],
      curatorPositioning: ['Modern aristocracy.', 'Velvet authority.', 'Prestige engineered to perfection.'],
    },
    {
      slug: 'frederic-malle-portrait-of-a-lady',
      archiveCode: 'U-VIII',
      archiveLabel: 'Curated Unisex Allocation — Archive U-VIII',
      collectionName: 'The Imperial Rose Archive',
      classification: 'Luxury Artistic Rose Masterpiece',
      size: '100ML',
      globalRetailUsd: 475,
      image: '/guest-curation/unisex/frederic-malle-portrait-of-a-lady.jpg',
      signatureNotes: ['Rose', 'Patchouli', 'Clove', 'Cinnamon', 'Incense', 'Amber', 'Sandalwood'],
      whyCurated: [
        'Portrait of a Lady is not merely fragrance.',
        'It is olfactory art.',
        'Its extraordinary rose concentration.',
        'Its dark incense structure.',
        'Its unmatched depth.',
        "Make it one of perfumery's greatest achievements.",
      ],
      curatorPositioning: ['A masterpiece.', 'A gallery piece.', 'A sovereign rose monument.'],
    },
    {
      slug: 'serge-lutens-ambre-sultan',
      archiveCode: 'U-IX',
      archiveLabel: 'Curated Unisex Allocation — Archive U-IX',
      collectionName: 'The Golden Resin Archive',
      classification: 'Luxury Amber Resin Signature',
      size: '50ML',
      globalRetailUsd: 210,
      image: '/guest-curation/unisex/serge-lutens-ambre-sultan.jpg',
      signatureNotes: ['Amber', 'Bay Leaf', 'Coriander', 'Oregano', 'Patchouli', 'Myrrh', 'Vanilla Resin'],
      whyCurated: [
        'Ambre Sultan respects raw materials.',
        'Its dry amber structure.',
        'Its herbal complexity.',
        'Its timeless warmth.',
        'Reflect the spirit of historical perfumery.',
      ],
      curatorPositioning: ['Ancient amber.', 'Modern elegance.', 'A preserved golden treasure.'],
    },
    {
      slug: 'jo-malone-wood-sage-sea-salt',
      archiveCode: 'U-X',
      archiveLabel: 'Curated Unisex Allocation — Archive U-X',
      collectionName: 'The Oceanic Archive',
      classification: 'Luxury Mineral Aquatic Signature',
      size: '100ML',
      globalRetailUsd: 215,
      image: '/guest-curation/unisex/jo-malone-wood-sage-sea-salt.jpg',
      signatureNotes: ['Ambrette Seeds', 'Sea Salt', 'Sage', 'Red Algae', 'Grapefruit'],
      whyCurated: [
        'Wood Sage & Sea Salt demonstrates restraint.',
        'Clean.',
        'Balanced.',
        'Effortlessly sophisticated.',
        'The House selected it because true luxury does not require excess.',
      ],
      curatorPositioning: ['Ocean air.', 'Coastal freedom.', 'Minimalist luxury perfected.'],
    },

      // ── UNISEX COSMETICS MASTERPIECES (Archive UC-I to UC-XV) ──────────────────
      {
        slug: 'la-mer-creme-de-la-mer-gc',
        archiveCode: 'UC-I',
        archiveLabel: 'SF Guest Curation · Global Unisex Cosmetics Masterpieces — Archive UC-I',
        collectionName: 'The Eternal Renewal Archive',
        classification: 'Ultra-Luxury Regenerative Moisturizer',
        size: '60ml',
        globalRetailUsd: 425,
        signatureNotes: ['Miracle Broth', 'Sea Kelp', 'Lime Tea', 'Eucalyptus', 'Wheat Germ', 'Alfalfa'],
        whyCurated: [
          'Crème de la Mer is not merely a moisturizer.',
          'It is the gold standard of global luxury skincare.',
          'Its Miracle Broth — born from 12 years of scientific research — represents one of the most celebrated formulation breakthroughs in modern skincare history.',
          'The House allocated Crème de la Mer as Archive UC-I because it embodies the philosophy we hold most deeply: true luxury is measured not by ornament, but by transformation.',
          'Timeless skin refinement. Legendary prestige. Eternal renewal.',
        ],
        curatorPositioning: ['The world's most iconic luxury cream.', 'Timeless skin refinement.', 'Legendary prestige.'],
      },
      {
        slug: 'augustinus-bader-the-cream',
        archiveCode: 'UC-II',
        archiveLabel: 'SF Guest Curation · Global Unisex Cosmetics Masterpieces — Archive UC-II',
        collectionName: 'The Future Technology Archive',
        classification: 'Advanced Regenerative Skincare',
        size: '50ml',
        globalRetailUsd: 325,
        signatureNotes: ['TFC8® Complex', 'Natural Moisturizing Factors', 'Hyaluronic Acid', 'Evening Primrose', 'Vitamins A & E', 'Argan Oil'],
        whyCurated: [
          'Augustinus Bader The Cream applies Nobel Prize-winning science to daily skincare.',
          'Its proprietary TFC8® complex was originally developed to heal severe burn injuries — a regenerative technology that once existed only in clinical medicine.',
          'The House allocated The Cream as Archive UC-II because it demonstrates that at their highest level, luxury and science are the same discipline.',
          'Modern excellence. Future-facing skincare.',
        ],
        curatorPositioning: ['Scientific luxury.', 'Modern excellence.', 'Future-facing skincare.'],
      },
      {
        slug: 'la-prairie-skin-caviar-luxe-cream',
        archiveCode: 'UC-III',
        archiveLabel: 'SF Guest Curation · Global Unisex Cosmetics Masterpieces — Archive UC-III',
        collectionName: 'The Billionaire Reserve Archive',
        classification: 'Ultra-Luxury Caviar Treatment',
        size: '100ml',
        globalRetailUsd: 895,
        signatureNotes: ['Caviar Extract', 'Swiss Cellular Complex', 'Caviar Beads', 'Golden Caviar', 'Peptide Complex', 'Lipid Replenishment'],
        whyCurated: [
          'La Prairie Skin Caviar Luxe Cream is the most prestigious skincare formulation available at open retail.',
          'Its caviar extract harvested from sustainably raised Swiss sturgeons.',
          'Its gold caviar beads suspended in a luxurious emulsion.',
          'Its Swiss cellular complex — the result of decades of biotechnology research.',
          'Together represent what the global ultra-wealthy have trusted for generations.',
          'The House allocated this masterpiece as Archive UC-III because collector-grade luxury demands collector-grade standards.',
        ],
        curatorPositioning: ['Elite skincare.', 'Global prestige.', 'Collector-grade luxury.'],
      },
      {
        slug: 'sisley-paris-black-rose-skin-infusion-cream',
        archiveCode: 'UC-IV',
        archiveLabel: 'SF Guest Curation · Global Unisex Cosmetics Masterpieces — Archive UC-IV',
        collectionName: 'The Parisian Excellence Archive',
        classification: 'Luxury Hydration Treatment',
        size: '50ml',
        globalRetailUsd: 245,
        signatureNotes: ['Black Rose Extract', 'Rose Hip Oil', 'Shea Butter', 'Sweet Almond Oil', 'Black Truffle', 'Hyaluronic Acid'],
        whyCurated: [
          'Sisley Paris carries a philosophy that French luxury has always honored: substance over spectacle.',
          'Black Rose Skin Infusion Cream is devastatingly effective — not because of its price, but because of the extraordinary concentration of black rose extract and its precision formulation.',
          'The House allocated this treasure as Archive UC-IV because it captures what Parisian elegance has always meant:',
          'Excellence that is visible without being declared.',
          'Visible radiance. Timeless elegance.',
        ],
        curatorPositioning: ['French sophistication.', 'Visible radiance.', 'Timeless elegance.'],
      },
      {
        slug: 'cle-de-peau-beaute-the-serum',
        archiveCode: 'UC-V',
        archiveLabel: 'SF Guest Curation · Global Unisex Cosmetics Masterpieces — Archive UC-V',
        collectionName: 'The Prestige Performance Archive',
        classification: 'Luxury Skin Activating Serum',
        size: '30ml',
        globalRetailUsd: 365,
        signatureNotes: ['Rare Royal Jelly Essence', 'Illuminating Complex EX', 'WS-TE®', 'Squalane', 'Japanese Camellia', 'Imperial Silk'],
        whyCurated: [
          'Clé de Peau Beauté The Serum activates the skin's own intelligence.',
          'Its Rare Royal Jelly Essence — harvested from a proprietary Japanese honeybee lineage — delivers nutrients with extraordinary bioavailability.',
          'Its Illuminating Complex EX bridges traditional Japanese beauty wisdom with modern dermatological science.',
          'The House allocated The Serum as Archive UC-V because the finest skincare does not impose transformation.',
          'It awakens it.',
          'Japanese precision. Luxury innovation. Exceptional refinement.',
        ],
        curatorPositioning: ['Japanese precision.', 'Luxury innovation.', 'Exceptional refinement.'],
      },
      {
        slug: 'chanel-sublimage-la-creme-gc',
        archiveCode: 'UC-VI',
        archiveLabel: 'SF Guest Curation · Global Unisex Cosmetics Masterpieces — Archive UC-VI',
        collectionName: 'The Haute Beauty Archive',
        classification: 'Ultimate Luxury Moisturizer',
        size: '50ml',
        globalRetailUsd: 495,
        signatureNotes: ['Vanilla Planifolia', 'Pure Concentrate', 'Regenerative Vanilla', 'Gold Elixir', 'Hyaluronic Acid', 'Sericin Silk Protein'],
        whyCurated: [
          'Chanel Sublimage La Crème represents over a century of luxury philosophy translated into a single daily ritual.',
          'Its vanilla planifolia pure concentrate — extracted via a proprietary supercritical CO2 process — represents one of the most technologically advanced botanical extractions in luxury skincare.',
          'The House allocated Sublimage as Archive UC-VI because Chanel represents a standard of excellence that requires no explanation.',
          'Haute couture skincare. Prestige without compromise. Pure elegance.',
        ],
        curatorPositioning: ['Haute couture skincare.', 'Prestige without compromise.', 'Pure elegance.'],
      },
      {
        slug: 'dior-prestige-la-micro-huile-de-rose',
        archiveCode: 'UC-VII',
        archiveLabel: 'SF Guest Curation · Global Unisex Cosmetics Masterpieces — Archive UC-VII',
        collectionName: 'The Golden Rose Archive',
        classification: 'Luxury Anti-Aging Serum',
        size: '30ml',
        globalRetailUsd: 315,
        signatureNotes: ['Micro-Granules of Rose', 'Granville Rose Wax', 'Rosewood', 'Retinol Alternative', 'Omega 3-6-9', 'Bio-Radiance Complex'],
        whyCurated: [
          'Dior Prestige La Micro-Huile de Rose harnesses a century of Dior rose expertise into a micro-emulsion of extraordinary radiance.',
          'The Granville rose — grown exclusively on the Norman coast of France — is the living signature of the Dior house, harvested at precise peak bloom and micro-encapsulated at the height of its potency.',
          'The House allocated this masterpiece as Archive UC-VII because Dior rose science represents one of the great ongoing achievements in luxury skincare history.',
          'Rose science. Luxury recovery. Radiant authority.',
        ],
        curatorPositioning: ['Rose science.', 'Luxury recovery.', 'Radiant authority.'],
      },
      {
        slug: 'tom-ford-research-serum-concentrate',
        archiveCode: 'UC-VIII',
        archiveLabel: 'SF Guest Curation · Global Unisex Cosmetics Masterpieces — Archive UC-VIII',
        collectionName: 'The Executive Luxury Archive',
        classification: 'Advanced Luxury Serum',
        size: '30ml',
        globalRetailUsd: 245,
        signatureNotes: ['Fermented Chaga Mushroom', 'Retinol', 'Niacinamide', 'Adenosine', 'Polyglutamic Acid', 'Palmitoyl Tripeptide-5'],
        whyCurated: [
          'Tom Ford Research Serum Concentrate applies the same uncompromising standard that built one of fashion's most authoritative houses to the domain of advanced skincare.',
          'Its fermented chaga mushroom — an adaptogenic superingredient — combined with clinical-grade retinol and peptide complexes creates a serum that performs at a level that justifies its placement in any luxury archive.',
          'The House allocated this serum as Archive UC-VIII because the Tom Ford philosophy is one we share:',
          'Excellence does not explain itself.',
          'Precision skincare. Executive grooming. Modern sophistication.',
        ],
        curatorPositioning: ['Precision skincare.', 'Executive grooming.', 'Modern sophistication.'],
      },
      {
        slug: 'valmont-prime-regenerating-pack',
        archiveCode: 'UC-IX',
        archiveLabel: 'SF Guest Curation · Global Unisex Cosmetics Masterpieces — Archive UC-IX',
        collectionName: 'The Swiss Heritage Archive',
        classification: 'Swiss Luxury Recovery Treatment',
        size: '75ml',
        globalRetailUsd: 295,
        signatureNotes: ['DNA & RNA Complex', 'Swiss Alpine Plant Stem Cells', 'Cellular Life Complex', 'Collagen', 'Elastin', 'Regenerative Peptides'],
        whyCurated: [
          'Valmont Prime Regenerating Pack carries the disciplined precision of Swiss alpine skincare science.',
          'Its DNA and RNA complex — a signature Valmont technology developed over decades of cellular research — delivers results that are visible, measurable, and immediate.',
          'Switzerland has always demanded that performance be earned through method, not marketing.',
          'The House allocated this masterpiece as Archive UC-IX because the Swiss standard is one that cannot be faked.',
          'Swiss excellence. Instant revitalization. High-performance skincare.',
        ],
        curatorPositioning: ['Swiss excellence.', 'Instant revitalization.', 'High-performance skincare.'],
      },
      {
        slug: 'dr-barbara-sturm-hyaluronic-serum',
        archiveCode: 'UC-X',
        archiveLabel: 'SF Guest Curation · Global Unisex Cosmetics Masterpieces — Archive UC-X',
        collectionName: 'The Modern Longevity Archive',
        classification: 'Luxury Hydration Serum',
        size: '30ml',
        globalRetailUsd: 285,
        signatureNotes: ['Low & High Molecular Hyaluronic Acid', 'Purslane', 'Upcycled Olive Squalane', 'Skullcap Extract', 'Anti-aging Peptides', 'Moisture-Lock Complex'],
        whyCurated: [
          'Dr. Barbara Sturm Hyaluronic Serum represents the intersection of clinical dermatology and modern luxury.',
          'Its dual-weight hyaluronic acid — working at two molecular levels to hydrate both surface and deep dermal layers simultaneously — reflects a dermatological precision that most luxury serums only approximate.',
          'Trusted by professional athletes, collectors, and cultural leaders who demand optimal performance from every tool they use.',
          'The House allocated this masterpiece as Archive UC-X because Dr. Sturm embodies the philosophy that longevity is the highest luxury.',
          'Clean luxury. Advanced hydration. Celebrity-grade performance.',
        ],
        curatorPositioning: ['Clean luxury.', 'Advanced hydration.', 'Celebrity-grade performance.'],
      },
      {
        slug: 'aesop-lucent-facial-concentrate',
        archiveCode: 'UC-XI',
        archiveLabel: 'SF Guest Curation · Global Unisex Cosmetics Masterpieces — Archive UC-XI',
        collectionName: 'The Intellectual Archive',
        classification: 'Luxury Vitamin-Rich Treatment',
        size: '25ml',
        globalRetailUsd: 135,
        signatureNotes: ['Vitamin C', 'Vitamin B', 'Vitamin E', 'Idebenone', 'Lactoferrin', 'Botanical Brightening Complex'],
        whyCurated: [
          'Aesop Lucent Facial Concentrate operates through botanical intelligence — a vitamin-rich formula that rewards patience and attention.',
          'Aesop has never chased trends. Its philosophy of rigorous formulation, minimal packaging, and earned reputation places it in a rare category of skincare that genuinely does not need to advertise.',
          'The House allocated this concentrate as Archive UC-XI because Aesop demonstrates a truth we hold essential:',
          'Luxury does not require performance. It requires philosophy.',
          'Minimalist prestige. Architectural simplicity. Modern elegance.',
        ],
        curatorPositioning: ['Minimalist prestige.', 'Architectural simplicity.', 'Modern elegance.'],
      },
      {
        slug: 'tatcha-the-dewy-skin-cream',
        archiveCode: 'UC-XII',
        archiveLabel: 'SF Guest Curation · Global Unisex Cosmetics Masterpieces — Archive UC-XII',
        collectionName: 'The Kyoto Archive',
        classification: 'Luxury Hydrating Cream',
        size: '50ml',
        globalRetailUsd: 115,
        signatureNotes: ['Hadasei-3™ Superfood Complex', 'Green Tea', 'Rice', 'Algae', 'Japanese Wild Rose', 'Hyaluronic Acid'],
        whyCurated: [
          'Tatcha The Dewy Skin Cream draws from centuries of Japanese beauty ritual.',
          'Its Hadasei-3™ complex — a trinity of Japanese superfoods including fermented green tea, rice, and Okinawan algae — nourishes skin the way Kyoto artisans have nourished theirs for generations.',
          'This is not cultural appropriation of Japanese beauty. It is cultural preservation.',
          'The House allocated this cream as Archive UC-XII because it carries genuine heritage within its formula — not as marketing, but as methodology.',
          'Japanese beauty heritage. Luminous skin. Refined simplicity.',
        ],
        curatorPositioning: ['Japanese beauty heritage.', 'Luminous skin.', 'Refined simplicity.'],
      },
      {
        slug: 'sulwhasoo-concentrated-ginseng-renewing-cream',
        archiveCode: 'UC-XIII',
        archiveLabel: 'SF Guest Curation · Global Unisex Cosmetics Masterpieces — Archive UC-XIII',
        collectionName: 'The Eastern Sovereign Archive',
        classification: 'Luxury Korean Skincare',
        size: '60ml',
        globalRetailUsd: 225,
        signatureNotes: ['6-Year-Old Korean Red Ginseng', 'Ginsenoside', 'Ginseng Berry', 'Ginseng Leaf', 'Ginseng Root Extract', 'JAUM Balancing Complex™'],
        whyCurated: [
          'Sulwhasoo Concentrated Ginseng Renewing Cream preserves a 5,000-year-old Korean understanding of ginseng as the root of longevity and refinement.',
          'Its 6-year-aged Korean red ginseng — the most potent grade, harvested only after half a decade of cultivation — delivers ginsenoside concentrations that validate what traditional Eastern medicine has known for millennia.',
          'Korean luxury skincare has emerged as one of the most scientifically rigorous and culturally rich categories in global beauty.',
          'The House allocated this cream as Archive UC-XIII because it carries a civilization's reverence for skin health.',
          'Ancient wisdom. Modern science. Generational beauty.',
        ],
        curatorPositioning: ['Ancient wisdom.', 'Modern science.', 'Generational beauty.'],
      },
      {
        slug: 'sk-ii-facial-treatment-essence',
        archiveCode: 'UC-XIV',
        archiveLabel: 'SF Guest Curation · Global Unisex Cosmetics Masterpieces — Archive UC-XIV',
        collectionName: 'The Crystal Skin Archive',
        classification: 'Luxury Skin Essence',
        size: '230ml',
        globalRetailUsd: 195,
        signatureNotes: ['Pitera™ (90%+ Galactomyces Ferment Filtrate)', 'Niacinamide', 'Panthenol', 'Sodium Acetylated Hyaluronate', 'Methylparaben', 'Butylene Glycol'],
        whyCurated: [
          'SK-II Facial Treatment Essence contains Pitera — discovered by scientists studying the hands of sake brewery workers, who possessed extraordinary skin well into old age despite their physical labor.',
          'That chance observation led to decades of research, yielding a bio-ingredient that remains one of the most studied fermentation filtrates in skincare science.',
          'The House allocated this essence as Archive UC-XIV because SK-II represents one of the great discovery stories in skincare history — proof that nature reveals its most profound secrets to those disciplined enough to observe them.',
          'Legendary clarity. Global recognition. Iconic skincare.',
        ],
        curatorPositioning: ['Legendary clarity.', 'Global recognition.', 'Iconic skincare.'],
      },
      {
        slug: 'guerlain-orchidee-imperiale-cream',
        archiveCode: 'UC-XV',
        archiveLabel: 'SF Guest Curation · Global Unisex Cosmetics Masterpieces — Archive UC-XV',
        collectionName: 'The Imperial Orchid Archive',
        classification: 'Ultra-Luxury Longevity Treatment',
        size: '50ml',
        globalRetailUsd: 465,
        signatureNotes: ['Imperial Orchid Molecular Extract', 'Orchidya Longevity Concentrate', 'Bio-Cellular Regeneration Complex', 'Gold-Charged Serum', 'Peptide Matrix', 'Guerlain Exclusive Fermentation'],
        whyCurated: [
          'Guerlain Orchidée Impériale Cream is sourced from the Imperial Orchid — a bloom cultivated exclusively for Guerlain, taking three years to mature, harvested only at precise peak potency.',
          'This orchid is not merely an ingredient. It is a symbol of the level of devotion Guerlain brings to its most prestigious formulation.',
          'The House allocated this masterpiece as Archive UC-XV — the final and most imperial entry in the Unisex Cosmetics Masterpieces Collection — because Guerlain represents the highest expression of French imperial luxury heritage.',
          'Imperial beauty. French luxury heritage. The pinnacle of skincare craftsmanship.',
        ],
        curatorPositioning: ['Imperial beauty.', 'French luxury heritage.', 'The pinnacle of skincare craftsmanship.'],
      },

      // ── ESSENTIAL UNISEX COSMETICS ARCHIVE (Archive UE-I to UE-XV) ─────────────
      {
        slug: 'cerave-moisturizing-lotion-unisex',
        archiveCode: 'UE-I',
        archiveLabel: 'SF Guest Curation · Essential Unisex Cosmetics Archive — Archive UE-I',
        collectionName: 'The Daily Foundation Archive',
        classification: 'Essential Daily Hydration',
        size: '237ml',
        globalRetailUsd: 22,
        signatureNotes: ['Ceramides 1, 3 & 6-II', 'Hyaluronic Acid', 'MVE Delivery Technology', 'Niacinamide', 'Glycerin', 'Dimethicone'],
        whyCurated: [
          'CeraVe Moisturizing Lotion was developed with dermatologists and carries the clinical validation of the American Academy of Dermatology.',
          'Its MVE Delivery Technology — a multi-vesicular emulsion system that releases ceramides gradually over 24 hours — is a genuine innovation in moisture retention that most expensive formulas have not replicated.',
          'The House allocated this essential as Archive UE-I because luxury is not always defined by price.',
          'Sometimes luxury is defined by consistency.',
          'Simple. Effective. Trusted worldwide.',
        ],
        curatorPositioning: ['Simple.', 'Effective.', 'Trusted worldwide.'],
      },
      {
        slug: 'the-ordinary-niacinamide-10-zinc-1',
        archiveCode: 'UE-II',
        archiveLabel: 'SF Guest Curation · Essential Unisex Cosmetics Archive — Archive UE-II',
        collectionName: 'The Intelligent Skincare Archive',
        classification: 'Daily Skin Refinement Serum',
        size: '30ml',
        globalRetailUsd: 15,
        signatureNotes: ['Niacinamide 10%', 'Zinc PCA 1%', 'Tamarindus Indica Seed Extract', 'Balances Sebum', 'Minimizes Pores', 'Brightens Complexion'],
        whyCurated: [
          'The Ordinary Niacinamide 10% + Zinc 1% changed the skincare industry.',
          'It made clinical-grade niacinamide — previously found only in dermatologist-recommended brands at far higher price points — available to everyone.',
          'The concentration is honest. The formulation is precise. The results are measurable.',
          'The House allocated this essential as Archive UE-II because intelligence in formulation is its own form of luxury.',
          'Science-driven care. Maximum value. Visible results.',
        ],
        curatorPositioning: ['Science-driven care.', 'Maximum value.', 'Visible results.'],
      },
      {
        slug: 'cetaphil-gentle-skin-cleanser',
        archiveCode: 'UE-III',
        archiveLabel: 'SF Guest Curation · Essential Unisex Cosmetics Archive — Archive UE-III',
        collectionName: 'The Sensitive Care Archive',
        classification: 'Daily Facial Cleanser',
        size: '250ml',
        globalRetailUsd: 18,
        signatureNotes: ['Niacinamide', 'Panthenol (Pro-Vitamin B5)', 'Glycerin', 'Allantoin', 'pH-Balanced Formula', 'Fragrance-Free'],
        whyCurated: [
          'Cetaphil Gentle Skin Cleanser has served as the foundational cleanser in clinical dermatology for over seven decades.',
          'Its formula has remained essentially unchanged since its introduction — not because innovation has stalled, but because the formula was correct from the beginning.',
          'In a market that rewards novelty over efficacy, Cetaphil has built its reputation on seven decades of clinical consistency.',
          'The House allocated this essential as Archive UE-III because perfection arrived early, and discipline preserved it.',
          'Clean simplicity. Dermatologist trusted. Everyday comfort.',
        ],
        curatorPositioning: ['Clean simplicity.', 'Dermatologist trusted.', 'Everyday comfort.'],
      },
      {
        slug: 'la-roche-posay-effaclar-purifying-gel',
        archiveCode: 'UE-IV',
        archiveLabel: 'SF Guest Curation · Essential Unisex Cosmetics Archive — Archive UE-IV',
        collectionName: 'The Clear Skin Archive',
        classification: 'Deep Cleansing Formula',
        size: '200ml',
        globalRetailUsd: 24,
        signatureNotes: ['La Roche-Posay Thermal Spring Water', 'Zinc Pidolate', 'Salicylic Acid', 'Glycerin', 'EDTA', 'pH-Balanced Purifying Complex'],
        whyCurated: [
          'La Roche-Posay was born from the thermal springs of La Roche-Posay, France — mineral-rich waters with a centuries-old history of dermatological healing.',
          'Effaclar Purifying Gel carries that heritage into a daily-use formulation that is trusted not only by consumers but by dermatologists who recommend it to their most sensitive patients.',
          'The House allocated Effaclar as Archive UE-IV because it delivers French pharmacy precision — a standard of clinical rigour — at a price accessible to daily discipline.',
          'French skincare expertise. Balanced performance. Daily clarity.',
        ],
        curatorPositioning: ['French skincare expertise.', 'Balanced performance.', 'Daily clarity.'],
      },
      {
        slug: 'bioderma-sensibio-h2o',
        archiveCode: 'UE-V',
        archiveLabel: 'SF Guest Curation · Essential Unisex Cosmetics Archive — Archive UE-V',
        collectionName: 'The Micellar Standard Archive',
        classification: 'Micellar Cleansing Water',
        size: '250ml',
        globalRetailUsd: 20,
        signatureNotes: ['Micelles', 'Cucumber Extract', 'Allantoin', 'EDTA', 'Fructooligosaccharides', 'Mannitol'],
        whyCurated: [
          'Bioderma Sensibio H2O invented the modern micellar water category.',
          'A format now copied by hundreds of brands — and surpassed by none.',
          'Its original micellar technology, developed with dermatologists specifically for reactive skin, has remained the clinical reference formula since its introduction.',
          'Makeup artists, dermatologists, and skincare editors return to it consistently — not for nostalgia, but for performance that subsequent iterations have not exceeded.',
          'The House allocated this essential as Archive UE-V because the original remains the standard.',
          'Gentle cleansing. Professional favorite. Global classic.',
        ],
        curatorPositioning: ['Gentle cleansing.', 'Professional favorite.', 'Global classic.'],
      },
      {
        slug: 'neutrogena-hydro-boost-water-gel',
        archiveCode: 'UE-VI',
        archiveLabel: 'SF Guest Curation · Essential Unisex Cosmetics Archive — Archive UE-VI',
        collectionName: 'The Hydration Archive',
        classification: 'Lightweight Moisturizer',
        size: '50ml',
        globalRetailUsd: 23,
        signatureNotes: ['Purified Hyaluronic Acid', 'Trehalose', 'Dimethicone', 'Glycerin', 'Olive Extract', 'Hydro-Gel Matrix'],
        whyCurated: [
          'Neutrogena Hydro Boost Water Gel popularized the water-gel moisturizer format that luxury brands subsequently elevated into premium lines.',
          'Its purified hyaluronic acid matrix delivers immediate, weightless hydration that the skin accepts without heaviness or residue.',
          'The House allocated this essential as Archive UE-VI because thoughtful formulation is a luxury available at every price level — and Hydro Boost demonstrates precisely that.',
          'Fresh hydration. Modern skincare. Daily protection.',
        ],
        curatorPositioning: ['Fresh hydration.', 'Modern skincare.', 'Daily protection.'],
      },
      {
        slug: 'simple-kind-to-skin-moisturizer',
        archiveCode: 'UE-VII',
        archiveLabel: 'SF Guest Curation · Essential Unisex Cosmetics Archive — Archive UE-VII',
        collectionName: 'The Everyday Comfort Archive',
        classification: 'Essential Moisturizing Care',
        size: '125ml',
        globalRetailUsd: 12,
        signatureNotes: ['Bisabolol', 'Allantoin', 'Vitamin E', 'Pro-Vitamin B5', 'Glycerin', 'No Artificial Perfume or Dyes'],
        whyCurated: [
          'Simple Kind to Skin Moisturizer lives up to its name.',
          'A formula built on the principle that what you remove from skincare can be as important as what you include.',
          'No artificial perfume. No harsh chemicals. No unnecessary complexity.',
          'Only what nourishes. Only what protects.',
          'The House allocated this essential as Archive UE-VII because simplicity, done with discipline, is its own form of excellence.',
          'Affordable excellence. Reliable performance. Clean hydration.',
        ],
        curatorPositioning: ['Affordable excellence.', 'Reliable performance.', 'Clean hydration.'],
      },
      {
        slug: 'thayers-witch-hazel-toner',
        archiveCode: 'UE-VIII',
        archiveLabel: 'SF Guest Curation · Essential Unisex Cosmetics Archive — Archive UE-VIII',
        collectionName: 'The Balance Archive',
        classification: 'Daily Toner',
        size: '355ml',
        globalRetailUsd: 16,
        signatureNotes: ['Aloe Vera', 'Witch Hazel (Hamamelis Virginiana)', 'Glycerin', 'Rose Water', 'Antioxidant Complex', 'Alcohol-Free Formula'],
        whyCurated: [
          'Thayers Witch Hazel Toner has been in production since 1847 — a formulation rooted in 19th-century herbal pharmacology and validated by 177 years of continuous daily use.',
          'Its alcohol-free witch hazel extract, combined with aloe vera and rose water, delivers skin balance without stripping — a distinction that many modern toners have failed to achieve.',
          'The House allocated this essential as Archive UE-VIII because longevity in skincare is its own form of proof.',
          'What lasts, works.',
          'Refreshing care. Natural balance. Skin discipline.',
        ],
        curatorPositioning: ['Refreshing care.', 'Natural balance.', 'Skin discipline.'],
      },
      {
        slug: 'aveeno-daily-moisturizing-lotion',
        archiveCode: 'UE-IX',
        archiveLabel: 'SF Guest Curation · Essential Unisex Cosmetics Archive — Archive UE-IX',
        collectionName: 'The Oat Reserve Archive',
        classification: 'Daily Body Care',
        size: '354ml',
        globalRetailUsd: 18,
        signatureNotes: ['Colloidal Oatmeal 1%', 'Dimethicone', 'Glycerin', 'Cetyl Alcohol', 'Natural Oat Extract', 'Skin-Barrier Reinforcement Complex'],
        whyCurated: [
          'Aveeno Daily Moisturizing Lotion is built around colloidal oatmeal — one of the most scientifically validated, FDA-recognized skin-soothing ingredients available.',
          'Used in clinical dermatology to treat eczema, psoriasis, and chronic dry skin, colloidal oatmeal's effectiveness has been documented in peer-reviewed literature across decades of research.',
          'The House allocated this essential as Archive UE-IX because comfort, delivered consistently over the long term, is a discipline as worthy of recognition as any other.',
          'Comfort. Protection. Trusted quality.',
        ],
        curatorPositioning: ['Comfort.', 'Protection.', 'Trusted quality.'],
      },
      {
        slug: 'vaseline-intensive-care-advanced-repair',
        archiveCode: 'UE-X',
        archiveLabel: 'SF Guest Curation · Essential Unisex Cosmetics Archive — Archive UE-X',
        collectionName: 'The Essential Protection Archive',
        classification: 'Body Moisturizer',
        size: '400ml',
        globalRetailUsd: 11,
        signatureNotes: ['Petroleum Jelly', 'Glycerin', 'Dimethicone', 'Stearic Acid', 'Micro-Droplet Technology', '150+ Years Barrier Science'],
        whyCurated: [
          'Vaseline has protected skin for over 150 years — a heritage of barrier science that no amount of marketing innovation has been able to replace or surpass.',
          'Its petroleum jelly base creates an occlusive barrier that is still considered the gold standard by dermatologists for protecting compromised skin — a standard that has not changed in a century and a half because it did not need to.',
          'The House allocated this essential as Archive UE-X because some formulas are classics not by label, but by proof.',
          'And 150 years of uninterrupted proof is unassailable.',
          'Practical luxury. Daily resilience. Long-term care.',
        ],
        curatorPositioning: ['Practical luxury.', 'Daily resilience.', 'Long-term care.'],
      },
      {
        slug: 'burts-bees-lip-balm',
        archiveCode: 'UE-XI',
        archiveLabel: 'SF Guest Curation · Essential Unisex Cosmetics Archive — Archive UE-XI',
        collectionName: 'The Everyday Essential Archive',
        classification: 'Lip Care',
        size: '4.25g',
        globalRetailUsd: 8,
        signatureNotes: ['Beeswax', 'Vitamin E', 'Peppermint Oil', 'Sunflower Seed Oil', 'Coconut Oil', 'Natural Origin Formula'],
        whyCurated: [
          'Burt's Bees Lip Balm carries beeswax, vitamin E, and peppermint oil in a natural formula trusted by over 50 million users globally.',
          'It is the most recognized natural lip care product in the world — not because of advertising, but because its formula has delivered visible, consistent relief to generations of users who returned to it willingly.',
          'The House allocated this essential as Archive UE-XI because daily refinement begins with the smallest disciplines.',
          'The lip is the most personal detail. The detail most often overlooked. The detail that reveals the most about the standard of care one maintains.',
          'Never neglect it.',
          'Small detail. Big impact. Daily refinement.',
        ],
        curatorPositioning: ['Small detail.', 'Big impact.', 'Daily refinement.'],
      },
      {
        slug: 'the-inkey-list-hyaluronic-acid-serum',
        archiveCode: 'UE-XII',
        archiveLabel: 'SF Guest Curation · Essential Unisex Cosmetics Archive — Archive UE-XII',
        collectionName: 'The Hydration Science Archive',
        classification: 'Moisture Boost Serum',
        size: '30ml',
        globalRetailUsd: 14,
        signatureNotes: ['Multi-Weight Hyaluronic Acid', 'Matrixyl 3000', 'Polyglutamic Acid', 'Arginine', 'Glycerin', 'Full Ingredient Transparency'],
        whyCurated: [
          'The Inkey List was built on a single principle: full transparency in formulation.',
          'Every ingredient listed. Every percentage disclosed. No concealment. No proprietary vagueness.',
          'Its Hyaluronic Acid Serum is that philosophy made liquid — multi-weight hyaluronic acid delivering moisture at multiple skin depths, with Matrixyl 3000 peptide complex supporting long-term collagen production.',
          'The House allocated this essential as Archive UE-XII because honesty in skincare is its own form of luxury.',
          'Modern skincare. Scientific simplicity. Reliable results.',
        ],
        curatorPositioning: ['Modern skincare.', 'Scientific simplicity.', 'Reliable results.'],
      },
      {
        slug: 'cosrx-advanced-snail-96-mucin-essence',
        archiveCode: 'UE-XIII',
        archiveLabel: 'SF Guest Curation · Essential Unisex Cosmetics Archive — Archive UE-XIII',
        collectionName: 'The Korean Innovation Archive',
        classification: 'Skin Recovery Essence',
        size: '96ml',
        globalRetailUsd: 22,
        signatureNotes: ['Snail Secretion Filtrate 96%', 'Sodium Hyaluronate', 'Betaine', 'Allantoin', 'Panthenol', 'K-Beauty BioFiltrate Technology'],
        whyCurated: [
          'COSRX Advanced Snail 96 Mucin Essence carries 96% snail secretion filtrate — a concentration that has made this one of the most studied and most-purchased Korean skincare products in global export history.',
          'Snail mucin contains hyaluronic acid, glycoprotein enzymes, antimicrobial peptides, and copper peptides — a naturally occurring cocktail that Korean dermatology has validated for wound healing, hydration, and skin renewal.',
          'The House allocated this essential as Archive UE-XIII because Korean innovation in skincare is a discipline that has earned the deepest global respect — and this product is its most iconic ambassador.',
          'K-Beauty excellence. Deep nourishment. Global favorite.',
        ],
        curatorPositioning: ['K-Beauty excellence.', 'Deep nourishment.', 'Global favorite.'],
      },
      {
        slug: 'elf-holy-hydration-face-cream',
        archiveCode: 'UE-XIV',
        archiveLabel: 'SF Guest Curation · Essential Unisex Cosmetics Archive — Archive UE-XIV',
        collectionName: 'The Modern Value Archive',
        classification: 'Daily Moisturizer',
        size: '50ml',
        globalRetailUsd: 15,
        signatureNotes: ['Hyaluronic Acid', 'Niacinamide', 'Peptide Complex', 'Vitamin E', 'Aloe Vera', 'Fragrance-Free Formula'],
        whyCurated: [
          'e.l.f. Holy Hydration Face Cream redefined what an entry-level moisturizer can deliver.',
          'Hyaluronic acid. Niacinamide. Peptide complex. Vitamin E. Ingredients that appear in luxury serums priced ten to thirty times higher.',
          'At $15, it removes every barrier to daily skincare discipline.',
          'The House allocated this essential as Archive UE-XIV because access to good skincare is a discipline, not a privilege — and this product makes that discipline available to everyone, without compromise.',
          'Affordable luxury. Consistent performance. Modern skincare.',
        ],
        curatorPositioning: ['Affordable luxury.', 'Consistent performance.', 'Modern skincare.'],
      },
      {
        slug: 'eucerin-advanced-repair-cream',
        archiveCode: 'UE-XV',
        archiveLabel: 'SF Guest Curation · Essential Unisex Cosmetics Archive — Archive UE-XV',
        collectionName: 'The Restoration Archive',
        classification: 'Deep Repair Treatment',
        size: '500ml',
        globalRetailUsd: 19,
        signatureNotes: ['Urea 5%', 'Ceramides', 'Natural Moisturizing Factors', 'Glycerin', 'Lactic Acid', 'German Dermatological Science'],
        whyCurated: [
          'Eucerin Advanced Repair Cream is formulated to the standards of German dermatological science — the most rigorous standard in global clinical skincare.',
          'Its 5% urea concentration — a keratolytic agent that softens and exfoliates at the cellular level while simultaneously binding moisture — is a clinical-grade intervention packaged in daily body care.',
          'Trusted in hospital dermatology departments and in homes worldwide for its ability to restore skin barriers that other formulations have failed to repair.',
          'The House allocated this essential as Archive UE-XV — the final entry in the Essential Unisex Cosmetics Archive — because restoration, done correctly, is the foundation of every lasting legacy.',
          'Dermatological excellence. Reliable hydration. Long-term protection.',
        ],
        curatorPositioning: ['Dermatological excellence.', 'Reliable hydration.', 'Long-term protection.'],
      },
    ]

  const CONFIG_MAP: Record<string, GuestCurationConfig> = {}
  for (const c of CONFIGS) CONFIG_MAP[c.slug] = c

  export function getGuestCurationConfig(slug: string): GuestCurationConfig | null {
    return CONFIG_MAP[slug] || null
  }

  export const GUEST_CURATION_SLUGS = CONFIGS.map(c => c.slug)
