export interface GuestCurationConfig {
    slug: string
    archiveCode: string
    archiveLabel: string
    collectionName: string
    classification: string
    size: string
    globalRetailUsd: number
    signatureNotes: string[]
    whyCurated: string[]
    curatorPositioning: string[]
    image?: string
  }

  const CONFIGS: GuestCurationConfig[] = [
    // ── FEMALE SERIES ──────────────────────────────────────────
    {
      slug: 'delina-exclusif',
      archiveCode: 'G-I',
      archiveLabel: 'Curated Female Allocation — Archive G-I',
      collectionName: 'The Sovereign Rose Archive',
      classification: 'Luxury Niche Feminine Masterpiece',
      size: '75ml',
      globalRetailUsd: 430,
      signatureNotes: ['Turkish Rose', 'Lychee', 'Incense', 'Oud', 'Vanilla'],
      whyCurated: [
        'Delina Exclusif represents the meeting point between aristocratic floral craftsmanship and modern luxury architecture.',
        'Its Turkish Rose core carries extraordinary richness. Its incense foundation creates permanence. Its oud structure delivers authority.',
        'The House selected Delina Exclusif because it demonstrates a philosophy we deeply respect: Beauty strengthened by discipline.',
        'This fragrance belongs inside every sovereign feminine archive.',
      ],
      curatorPositioning: ['Not merely a floral perfume.', 'A modern rose monument.', 'A luxury standard.', 'A permanent feminine signature.'],
    },
    {
      slug: 'amouage-guidance',
      archiveCode: 'G-II',
      archiveLabel: 'Curated Female Allocation — Archive G-II',
      collectionName: 'The Sovereign Harmony Archive',
      classification: 'Ultra-Luxury Niche Feminine Composition',
      size: '100ml',
      globalRetailUsd: 395,
      signatureNotes: ['Pear', 'Hazelnut', 'Frankincense', 'Osmanthus', 'Rose', 'Sandalwood'],
      whyCurated: [
        'Guidance represents emotional intelligence translated into fragrance.',
        'Its Omani Frankincense foundation reflects structure. Its creamy woods create depth. Its floral architecture creates sophistication.',
        'The House allocated Guidance because true luxury whispers rather than shouts. This fragrance rewards attention.',
        'And reveals new dimensions over time.',
      ],
      curatorPositioning: ['Not a trend.', 'A sensory symphony.', 'An intelligent luxury asset.'],
    },
    {
      slug: 'baccarat-rouge-540-extrait',
      archiveCode: 'G-III',
      archiveLabel: 'Curated Female Allocation — Archive G-III',
      collectionName: 'The Crystal Empire Archive',
      classification: 'Luxury Amber-Wood Extrait',
      size: '70ml',
      globalRetailUsd: 465,
      signatureNotes: ['Saffron', 'Bitter Almond', 'Egyptian Jasmine', 'Ambergris', 'Cedarwood'],
      whyCurated: [
        'Few fragrances have achieved modern legendary status. Baccarat Rouge 540 Extrait is one of them.',
        'Its saffron brilliance. Its ambergris structure. Its crystalline projection.',
        "Together create one of contemporary perfumery's most recognized luxury signatures.",
        'The House includes it as an archive-worthy benchmark of modern excellence.',
      ],
      curatorPositioning: ['A fragrance icon.', 'A global luxury reference point.', 'A crystal monument in liquid form.'],
    },
    {
      slug: 'xerjoff-casamorati-lira',
      archiveCode: 'G-IV',
      archiveLabel: 'Curated Female Allocation — Archive G-IV',
      collectionName: 'The Golden Theatre Archive',
      classification: 'Luxury Gourmand Masterpiece',
      size: '100ml',
      globalRetailUsd: 315,
      signatureNotes: ['Blood Orange', 'Bergamot', 'Lavender', 'Cinnamon', 'Licorice', 'Caramel Vanilla'],
      whyCurated: [
        'Lira preserves old-world Italian romance. Rich sweetness. Vintage elegance. Theatrical beauty.',
        'Its gourmand architecture demonstrates how luxury can feel emotional without sacrificing sophistication.',
      ],
      curatorPositioning: ['A heritage gourmand.', "A collector's dessert.", 'A preserved piece of olfactory history.'],
    },
    {
      slug: 'initio-atomic-rose',
      archiveCode: 'G-V',
      archiveLabel: 'Curated Female Allocation — Archive G-V',
      collectionName: 'The Sovereign Power Rose',
      classification: 'Luxury High-Impact Floral',
      size: '90ml',
      globalRetailUsd: 360,
      signatureNotes: ['Italian Bergamot', 'Bulgarian Rose', 'Turkish Rose', 'Egyptian Jasmine', 'Madagascar Vanilla'],
      whyCurated: [
        'Atomic Rose transforms the rose from ornament into authority. Powerful. Bold. Unapologetic.',
        'The House selected this masterpiece because it demonstrates how a classic floral note can become a commanding statement.',
      ],
      curatorPositioning: ['Not a flower.', 'A declaration.', 'A rose engineered for influence.'],
    },
    {
      slug: 'chanel-coco-mademoiselle-intense',
      archiveCode: 'G-VI',
      archiveLabel: 'Curated Female Allocation — Archive G-VI',
      collectionName: 'The Executive Elegance Archive',
      classification: 'Luxury Corporate Feminine Signature',
      size: '100ml',
      globalRetailUsd: 190,
      signatureNotes: ['Patchouli', 'Sicilian Orange', 'Calabrian Bergamot', 'Amber', 'Tonka Bean'],
      whyCurated: [
        'Modern feminine professionalism has few universal references. Coco Mademoiselle Intense remains one of them.',
        'The House recognizes its ability to balance elegance, confidence, and maturity with effortless authority.',
      ],
      curatorPositioning: ['Boardroom luxury.', 'Executive sophistication.', 'Timeless feminine structure.'],
    },
    {
      slug: 'dior-jadore-lor',
      archiveCode: 'G-VII',
      archiveLabel: 'Curated Female Allocation — Archive G-VII',
      collectionName: 'The Liquid Gold Archive',
      classification: 'Luxury Floral Essence',
      size: '50ml',
      globalRetailUsd: 170,
      signatureNotes: ['Orange Blossom Absolute', 'Jasmine Grandiflorum', 'Centifolia Rose'],
      whyCurated: [
        "J'adore L'Or feels like concentrated precious metal. Rich. Radiant. Refined.",
        'The House selected this composition because it embodies purity elevated to luxury.',
      ],
      curatorPositioning: ['Liquid gold.', 'Floral wealth.', 'Pure feminine refinement.'],
    },
    {
      slug: 'tom-ford-velvet-orchid',
      archiveCode: 'G-VIII',
      archiveLabel: 'Curated Female Allocation — Archive G-VIII',
      collectionName: 'The Midnight Society Archive',
      classification: 'Dark Oriental Floral',
      size: '100ml',
      globalRetailUsd: 235,
      signatureNotes: ['Black Orchid', 'Velvet Orchid', 'Rum', 'Honey', 'Mandarin', 'Myrrh'],
      whyCurated: [
        "Mystery remains one of luxury's most powerful currencies. Velvet Orchid operates within shadows.",
        'Its honey. Its rum. Its dark floral architecture. Together create an atmosphere of private luxury.',
      ],
      curatorPositioning: ['Not attention.', 'Intrigue.', 'Not visibility.', 'Presence.'],
    },
    {
      slug: 'ysl-libre-le-parfum',
      archiveCode: 'G-IX',
      archiveLabel: 'Curated Female Allocation — Archive G-IX',
      collectionName: 'The Sovereign Freedom Archive',
      classification: 'Luxury Floral Amber',
      size: '90ml',
      globalRetailUsd: 195,
      signatureNotes: ['French Lavender', 'Moroccan Orange Blossom', 'Ginger', 'Saffron'],
      whyCurated: [
        'Libre Le Parfum embodies self-determination. Its lavender structure. Its saffron warmth. Its amber foundation.',
        'Create a fragrance that feels modern yet authoritative.',
      ],
      curatorPositioning: ['Freedom with structure.', 'Elegance with power.', 'Modern sovereignty in liquid form.'],
    },
    {
      slug: 'kilian-angels-share',
      archiveCode: 'G-X',
      archiveLabel: 'Curated Female Allocation — Archive G-X',
      collectionName: 'The Heritage Cognac Archive',
      classification: 'Luxury Gourmand Amber',
      size: '50ml',
      globalRetailUsd: 245,
      signatureNotes: ['Cognac Accord', 'Cinnamon', 'Tonka Bean', 'Praline', 'Vanilla', 'Oak'],
      whyCurated: [
        "Some fragrances transcend categories. Angels' Share is one of them. Warm. Addictive. Sophisticated.",
        'The House includes it because it captures the emotional richness of celebration, memory, and legacy.',
      ],
      curatorPositioning: ["A bottle of heritage.", "A vault of memories.", 'A luxury masterpiece worthy of preservation.'],
    },

    // ── MALE SERIES — SF GUEST CURATION ──────────────────────
    {
      slug: 'creed-aventus',
      archiveCode: 'M-I',
      archiveLabel: 'Curated Masculine Allocation — Archive M-I',
      collectionName: 'The Empire Benchmark Archive',
      classification: 'Luxury Masculine Icon',
      size: '100ML',
      globalRetailUsd: 565,
      image: '/guest-curation/male/creed-aventus.jpg',
      signatureNotes: ['Pineapple', 'Bergamot', 'Birch Wood', 'Patchouli', 'Ambergris'],
      whyCurated: [
        'Few fragrances have influenced modern masculine perfumery like Aventus.',
        'Its fusion of bright pineapple and dry birch smoke created an entirely new luxury category.',
        'The House allocated Aventus because it represents leadership through identity rather than imitation.',
      ],
      curatorPositioning: ['A global masculine benchmark.', 'A symbol of success.', 'An empire captured in glass.'],
    },
    {
      slug: 'roja-elysium-pour-homme',
      archiveCode: 'M-II',
      archiveLabel: 'Curated Masculine Allocation — Archive M-II',
      collectionName: 'The Sovereign Freshness Archive',
      classification: 'Ultra-Luxury Fresh Masculine',
      size: '100ML',
      globalRetailUsd: 385,
      image: '/guest-curation/male/roja-elysium.jpg',
      signatureNotes: ['Grapefruit', 'Lime', 'Lavender', 'Vetiver', 'Ambergris', 'Leather'],
      whyCurated: [
        'Fresh fragrances rarely achieve true luxury status.',
        'Elysium succeeds through extraordinary refinement and balance.',
        'Its citrus brilliance and ambergris structure embody discipline over noise.',
      ],
      curatorPositioning: ['Freshness elevated to sovereignty.', 'Precision luxury.', 'Silent authority.'],
    },
    {
      slug: 'tom-ford-oud-wood',
      archiveCode: 'M-III',
      archiveLabel: 'Curated Masculine Allocation — Archive M-III',
      collectionName: 'The Executive Sanctuary Archive',
      classification: 'Luxury Clean Oud Masterpiece',
      size: '100ML',
      globalRetailUsd: 365,
      image: '/guest-curation/male/tom-ford-oud-wood.jpg',
      signatureNotes: ['Rare Oud', 'Sandalwood', 'Chinese Pepper', 'Rosewood', 'Vanilla', 'Amber'],
      whyCurated: [
        'Oud Wood transformed oud into modern sophistication.',
        'Its creamy architecture appeals to leaders, founders, and visionaries who value refinement over excess.',
      ],
      curatorPositioning: ['Corporate luxury.', 'Modern wealth.', 'Private confidence.'],
    },
    {
      slug: 'parfums-de-marly-layton',
      archiveCode: 'M-IV',
      archiveLabel: 'Curated Masculine Allocation — Archive M-IV',
      collectionName: 'The Aristocratic Legacy Archive',
      classification: 'Luxury Modern Gentleman Signature',
      size: '125ML',
      globalRetailUsd: 435,
      image: '/guest-curation/male/layton.webp',
      signatureNotes: ['Apple', 'Lavender', 'Bergamot', 'Violet', 'Vanilla', 'Guaiac Wood'],
      whyCurated: [
        'Layton represents timeless masculine elegance.',
        "Its balance of freshness, spice, and creamy woods creates one of modern perfumery's most admired signatures.",
      ],
      curatorPositioning: ['Modern royalty.', 'French aristocratic luxury.', 'A legacy preserved through scent.'],
    },
    {
      slug: 'amouage-interlude-man',
      archiveCode: 'M-V',
      archiveLabel: 'Curated Masculine Allocation — Archive M-V',
      collectionName: 'The Fortress Archive',
      classification: 'Ultra-Luxury Dark Oriental',
      size: '100ML',
      globalRetailUsd: 485,
      image: '/guest-curation/male/amouage-interlude.webp',
      signatureNotes: ['Oregano', 'Pimento Berry', 'Frankincense', 'Amber', 'Myrrh', 'Leather'],
      whyCurated: [
        'Known globally as the Blue Beast, Interlude Man represents uncompromising strength.',
        'Its fortress-like structure aligns perfectly with the House philosophy of permanence and authority.',
      ],
      curatorPositioning: ['Not a fragrance.', 'A sensory fortress.', 'Smoke forged into power.'],
    },
    {
      slug: 'kilian-angels-share-homme',
      archiveCode: 'M-VI',
      archiveLabel: 'Curated Masculine Allocation — Archive M-VI',
      collectionName: 'The Heritage Cognac Archive',
      classification: 'Luxury Gourmand Amber',
      size: '50ML',
      globalRetailUsd: 315,
      image: '/guest-curation/male/kilian-angels-share.webp',
      signatureNotes: ['Cognac Oil', 'Oak', 'Cinnamon', 'Tonka Bean', 'Praline', 'Sandalwood'],
      whyCurated: [
        "Angels' Share captures celebration, heritage, and luxury in its purest form.",
        'Its cognac architecture creates one of the most addictive modern compositions.',
      ],
      curatorPositioning: ['A bottle of heritage.', 'A vault of memories.', 'Liquid prosperity.'],
    },
    {
      slug: 'xerjoff-naxos',
      archiveCode: 'M-VII',
      archiveLabel: 'Curated Masculine Allocation — Archive M-VII',
      collectionName: 'The Golden Tobacco Archive',
      classification: 'Luxury Honey Tobacco Masterpiece',
      size: '100ML',
      globalRetailUsd: 355,
      image: '/guest-curation/male/xerjoff-naxos.webp',
      signatureNotes: ['Honey', 'Tobacco', 'Lavender', 'Bergamot', 'Cinnamon', 'Vanilla'],
      whyCurated: [
        'Naxos embodies warmth, sophistication, and comfort without sacrificing luxury.',
        'Its tobacco-honey structure feels regal and timeless.',
      ],
      curatorPositioning: ['Golden luxury.', 'Refined success.', "An aristocrat's signature."],
    },
    {
      slug: 'lv-ombre-nomade',
      archiveCode: 'M-VIII',
      archiveLabel: 'Curated Masculine Allocation — Archive M-VIII',
      collectionName: 'The Dark Empire Archive',
      classification: 'Ultra-Luxury Oud Monument',
      size: '100ML',
      globalRetailUsd: 495,
      image: '/guest-curation/male/lv-ombre-nomade.jpg',
      signatureNotes: ['Oud Wood', 'Incense', 'Benzoin', 'Raspberry'],
      whyCurated: [
        'Ombre Nomade is one of the most powerful oud creations ever released.',
        'Dense. Dark. Authoritative.',
        "Its architecture mirrors the philosophy behind the House's own archive creations.",
      ],
      curatorPositioning: ['A dark empire.', 'An uncompromising presence.', 'A monument of oud.'],
    },
    {
      slug: 'mfk-grand-soir',
      archiveCode: 'M-IX',
      archiveLabel: 'Curated Masculine Allocation — Archive M-IX',
      collectionName: 'The Golden Midnight Archive',
      classification: 'Luxury Amber Masterpiece',
      size: '70ML',
      globalRetailUsd: 355,
      image: '/guest-curation/male/mfk-grand-soir.jpg',
      signatureNotes: ['Labdanum', 'Benzoin', 'Tonka Bean', 'Amber', 'Vanilla'],
      whyCurated: [
        'Grand Soir transforms warmth into art.',
        'Its luminous amber structure feels like golden light preserved within crystal.',
      ],
      curatorPositioning: ['Parisian luxury.', 'Golden sophistication.', 'Timeless warmth.'],
    },
    {
      slug: 'penhaligons-lord-george',
      archiveCode: 'M-X',
      archiveLabel: 'Curated Masculine Allocation — Archive M-X',
      collectionName: 'The Aristocratic Gentleman Archive',
      classification: 'Luxury British Heritage Signature',
      size: '75ML',
      globalRetailUsd: 395,
      image: '/guest-curation/male/penhaligons-lord-george.webp',
      signatureNotes: ['Brandy', 'Shaving Soap', 'Amber', 'Tonka Bean'],
      whyCurated: [
        'Lord George represents traditional masculine refinement.',
        'Its elegant British character reflects discipline, structure, and institutional stature.',
      ],
      curatorPositioning: ['Old-world authority.', 'Heritage craftsmanship.', 'A gentleman preserved in time.'],
    },
  ]


      // ── UNISEX SERIES — SF GUEST CURATION ──────────────────────
      {
        slug: 'byredo-gypsy-water',
        archiveCode: 'U-I',
        archiveLabel: 'Curated Unisex Allocation — Archive U-I',
        collectionName: 'The Sovereign Freedom Archive',
        classification: 'Luxury Woody Aromatic Unisex Signature',
        size: '50ML',
        globalRetailUsd: 245,
        image: '/guest-curation/unisex/byredo-gypsy-water.jpg',
        signatureNotes: ['Juniper', 'Lemon', 'Bergamot', 'Pine Needles', 'Incense', 'Sandalwood', 'Vanilla'],
        whyCurated: [
          'Gypsy Water represents artistic independence without boundaries.',
          'Its fresh juniper opening.',
          'Its smoky incense heart.',
          'Its smooth sandalwood foundation.',
          'Together create a fragrance that feels weightless yet memorable.',
          'The House selected Gypsy Water because it captures freedom in its most refined form.',
        ],
        curatorPositioning: ['Not a destination.', 'A journey.', 'A luxury escape preserved in glass.'],
      },
      {
        slug: 'le-labo-santal-33',
        archiveCode: 'U-II',
        archiveLabel: 'Curated Unisex Allocation — Archive U-II',
        collectionName: 'The Identity Archive',
        classification: 'Luxury Smoky Sandalwood Icon',
        size: '100ML',
        globalRetailUsd: 385,
        image: '/guest-curation/unisex/le-labo-santal-33.jpg',
        signatureNotes: ['Cardamom', 'Iris', 'Violet', 'Ambrox', 'Sandalwood', 'Papyrus', 'Cedarwood'],
        whyCurated: [
          'Santal 33 became a global benchmark because it refuses imitation.',
          'Its dry sandalwood.',
          'Its leathery structure.',
          'Its architectural simplicity.',
          'Reflect the House philosophy:',
          'Identity over imitation.',
        ],
        curatorPositioning: ['A cultural icon.', 'A global reference point.', 'A monument of individuality.'],
      },
      {
        slug: 'creed-silver-mountain-water',
        archiveCode: 'U-III',
        archiveLabel: 'Curated Unisex Allocation — Archive U-III',
        collectionName: 'The Crystal Summit Archive',
        classification: 'Luxury Alpine Fresh Masterpiece',
        size: '100ML',
        globalRetailUsd: 565,
        image: '/guest-curation/unisex/creed-silver-mountain-water.jpg',
        signatureNotes: ['Bergamot', 'Mandarin', 'Green Tea', 'Blackcurrant', 'Musk', 'Petitgrain', 'Sandalwood'],
        whyCurated: [
          'Silver Mountain Water represents luxury clarity.',
          'Its green tea freshness.',
          'Its metallic musk signature.',
          'Its alpine purity.',
          'Create one of the most refined fresh compositions ever produced.',
        ],
        curatorPositioning: ['Mountain air.', 'Crystal water.', 'Liquid precision.'],
      },
      {
        slug: 'diptyque-philosykos',
        archiveCode: 'U-IV',
        archiveLabel: 'Curated Unisex Allocation — Archive U-IV',
        collectionName: 'The Mediterranean Archive',
        classification: 'Luxury Fig Tree Masterpiece',
        size: '75ML',
        globalRetailUsd: 285,
        image: '/guest-curation/unisex/diptyque-philosykos.jpg',
        signatureNotes: ['Fig Leaf', 'Fig Fruit', 'Coconut', 'Green Notes', 'Cedar', 'Fig Tree Wood'],
        whyCurated: [
          'Philosykos preserves nature with remarkable authenticity.',
          'Every spray feels like walking beneath a Mediterranean fig tree.',
          'The House selected it because true luxury often begins with simplicity.',
        ],
        curatorPositioning: ['Nature refined.', 'Green luxury.', 'Mediterranean permanence.'],
      },
      {
        slug: 'tom-ford-soleil-blanc',
        archiveCode: 'U-V',
        archiveLabel: 'Curated Unisex Allocation — Archive U-V',
        collectionName: 'The Private Island Archive',
        classification: 'Luxury Solar Floral Masterpiece',
        size: '100ML',
        globalRetailUsd: 355,
        image: '/guest-curation/unisex/tom-ford-soleil-blanc.jpg',
        signatureNotes: ['Coconut', 'Ylang-Ylang', 'Bergamot', 'Cardamom', 'Pistachio', 'Amber', 'Tuberose'],
        whyCurated: [
          'Soleil Blanc transforms sunlight into luxury.',
          'Creamy.',
          'Warm.',
          'Sophisticated.',
          'A private resort preserved as a fragrance.',
        ],
        curatorPositioning: ['Sunlit opulence.', 'Endless summer.', 'Resort-level luxury.'],
      },
      {
        slug: 'nishane-hacivat',
        archiveCode: 'U-VI',
        archiveLabel: 'Curated Unisex Allocation — Archive U-VI',
        collectionName: 'The Legacy Archive',
        classification: 'Extrait de Parfum Luxury Signature',
        size: '100ML',
        globalRetailUsd: 365,
        image: '/guest-curation/unisex/nishane-hacivat.jpg',
        signatureNotes: ['Pineapple', 'Grapefruit', 'Bergamot', 'Oakmoss', 'Patchouli', 'Timberwood'],
        whyCurated: [
          'Hacivat represents permanence.',
          'Its extraordinary concentration.',
          'Its powerful longevity.',
          'Its oakmoss authority.',
          'Make it one of modern niche perfumery's strongest signatures.',
        ],
        curatorPositioning: ['Legacy over speed.', 'Power over trends.', 'A signature that refuses to fade.'],
      },
      {
        slug: 'parfums-de-marly-haltane',
        archiveCode: 'U-VII',
        archiveLabel: 'Curated Unisex Allocation — Archive U-VII',
        collectionName: 'The Prestige Archive',
        classification: 'Luxury Oud Prestige Signature',
        size: '125ML',
        globalRetailUsd: 425,
        image: '/guest-curation/unisex/parfums-de-marly-haltane.jpg',
        signatureNotes: ['Clary Sage', 'Lavender', 'Bergamot', 'Saffron', 'Praline', 'Oud Wood', 'Cedarwood'],
        whyCurated: [
          'Haltane balances strength and elegance.',
          'Natural oud meets modern sophistication.',
          'Authority meets refinement.',
          'The House selected it because prestige should never feel forced.',
        ],
        curatorPositioning: ['Modern aristocracy.', 'Velvet authority.', 'Prestige engineered to perfection.'],
      },
      {
        slug: 'frederic-malle-portrait-of-a-lady',
        archiveCode: 'U-VIII',
        archiveLabel: 'Curated Unisex Allocation — Archive U-VIII',
        collectionName: 'The Imperial Rose Archive',
        classification: 'Luxury Artistic Rose Masterpiece',
        size: '100ML',
        globalRetailUsd: 475,
        image: '/guest-curation/unisex/frederic-malle-portrait-of-a-lady.jpg',
        signatureNotes: ['Rose', 'Patchouli', 'Clove', 'Cinnamon', 'Incense', 'Amber', 'Sandalwood'],
        whyCurated: [
          'Portrait of a Lady is not merely fragrance.',
          'It is olfactory art.',
          'Its extraordinary rose concentration.',
          'Its dark incense structure.',
          'Its unmatched depth.',
          'Make it one of perfumery's greatest achievements.',
        ],
        curatorPositioning: ['A masterpiece.', 'A gallery piece.', 'A sovereign rose monument.'],
      },
      {
        slug: 'serge-lutens-ambre-sultan',
        archiveCode: 'U-IX',
        archiveLabel: 'Curated Unisex Allocation — Archive U-IX',
        collectionName: 'The Golden Resin Archive',
        classification: 'Luxury Amber Resin Signature',
        size: '50ML',
        globalRetailUsd: 210,
        image: '/guest-curation/unisex/serge-lutens-ambre-sultan.jpg',
        signatureNotes: ['Amber', 'Bay Leaf', 'Coriander', 'Oregano', 'Patchouli', 'Myrrh', 'Vanilla Resin'],
        whyCurated: [
          'Ambre Sultan respects raw materials.',
          'Its dry amber structure.',
          'Its herbal complexity.',
          'Its timeless warmth.',
          'Reflect the spirit of historical perfumery.',
        ],
        curatorPositioning: ['Ancient amber.', 'Modern elegance.', 'A preserved golden treasure.'],
      },
      {
        slug: 'jo-malone-wood-sage-sea-salt',
        archiveCode: 'U-X',
        archiveLabel: 'Curated Unisex Allocation — Archive U-X',
        collectionName: 'The Oceanic Archive',
        classification: 'Luxury Mineral Aquatic Signature',
        size: '100ML',
        globalRetailUsd: 215,
        image: '/guest-curation/unisex/jo-malone-wood-sage-sea-salt.jpg',
        signatureNotes: ['Ambrette Seeds', 'Sea Salt', 'Sage', 'Red Algae', 'Grapefruit'],
        whyCurated: [
          'Wood Sage & Sea Salt demonstrates restraint.',
          'Clean.',
          'Balanced.',
          'Effortlessly sophisticated.',
          'The House selected it because true luxury does not require excess.',
        ],
        curatorPositioning: ['Ocean air.', 'Coastal freedom.', 'Minimalist luxury perfected.'],
      },

  const CONFIG_MAP: Record<string, GuestCurationConfig> = {}
  for (const c of CONFIGS) CONFIG_MAP[c.slug] = c

  export function getGuestCurationConfig(slug: string): GuestCurationConfig | null {
    return CONFIG_MAP[slug] || null
  }

  export const GUEST_CURATION_SLUGS = CONFIGS.map(c => c.slug)
  