export const PRODUCT_IMAGE_OVERRIDES: Record<string, string | string[]> = {
        'prada-candy': '/products/prada-candy/hero.png',
        'armani-si': '/products/armani-si/hero.png',
        'burberry-her': '/products/burberry-her/hero.png',
        'ysl-black-opium': '/products/ysl-black-opium/hero.png',
        'empress-sovereign-vault': [
          '/products/empress-sovereign-vault/hero.png',
          '/products/empress-sovereign-vault/packing.png',
        ],
        'queen-of-taif-crown-ring': '/products/queen-of-taif-crown-ring/ring-hero.png',
        // Sovereign perfumes — own-brand
        'eternal-empress': '/products/eternal-empress/empress-hero.png',
        'sovereign-genesis': '/products/sovereign-genesis/hero.png',
        'eternal-sovereign': '/products/eternal-sovereign/hero.png',
        'sovereign-oud-absolute': '/products/sovereign-oud-absolute/oud-bottle.png',
        'imperial-black-throne': '/products/imperial-black-throne/throne-bottle.png',
        'her-legacy-vault': '/products/her-legacy-vault/vault-hero.png',
        'midnight-iris-royale': '/products/midnight-iris-royale/mir-hero.png',
        'sapphire-blue-levant': '/products/sapphire-blue-levant/levant-bottle.png',
        'house-vault-no-001': '/products/house-vault-no-001/hero.png',
        'founders-eternal-archive': '/products/founders-eternal-archive/founder-hero.png',
        'founder-s-eternal-archive': '/products/founders-eternal-archive/founder-hero.png',
        'shamims-ghost': '/products/shamims-ghost/ghost-hero.png',
        'shamim-s-ghost-the-eternal-legacy': '/products/shamims-ghost/ghost-hero.png',
        'shamims-ghost-the-eternal-legacy': '/products/shamims-ghost/ghost-hero.png',
        'initio-atomic-rose': '/products/initio-atomic-rose/hero.png',
        'de-beers-enchanted-lotus-earrings': '/products/de-beers-enchanted-lotus/nft.avif',
        'coach-signature-crystal-studs': '/products/coach-signature-crystal-studs/hero.png',
        'pandora-sparkling-halo-ring': '/products/pandora-sparkling-halo-ring/hero.png',
          'chopard-happy-diamonds-necklace': '/products/chopard-happy-diamonds-necklace/hero.png',
          'monica-vinader-siren-gemstone-ring': '/products/monica-vinader-siren-gemstone-ring/hero.png',
          'van-cleef-alhambra-necklace': '/products/van-cleef-alhambra-necklace/hero.png',
          'michael-kors-pave-logo-bangle': '/products/michael-kors-pave-logo-bangle/hero.png',
          'buccellati-opera-tulle-bracelet': '/products/buccellati-opera-tulle-bracelet/hero.png',
          'bulgari-serpenti-viper-bracelet': '/products/bulgari-serpenti-viper-bracelet/hero.png',
          'chaumet-josephine-tiara-ring': '/products/chaumet-josephine-tiara-ring/hero.png',
          'mikimoto-south-sea-pearl-set': '/products/mikimoto-south-sea-pearl-set/hero.png',
          'cartier-panthere-ring': '/products/cartier-panthere-ring/hero.png',
          'harry-winston-cluster-diamond-ring': '/products/harry-winston-cluster-diamond-ring/hero.png',
          'graff-icon-diamond-necklace': [],
          'graff-butterfly-diamond-pendant': [],
          'swarovski-millenia-tennis-necklace': [],
          'jacob-co-astronomia-diamond-cuff': [],
          'graff-classic-diamond-mens-ring': [],
          'de-beers-talisman-diamond-pendant': [],
          'cartier-juste-un-clou-bracelet': [],
          'messika-move-titanium-bracelet': 'https://uvgtgeauhjbdatrmmaob.supabase.co/storage/v1/object/public/products/messika-move-titanium-bracelet/hero.png',
          'chaumet-liens-mens-bracelet': 'https://uvgtgeauhjbdatrmmaob.supabase.co/storage/v1/object/public/products/chaumet-liens-mens-bracelet/hero.png',
          'pandora-signature-mens-ring': 'https://uvgtgeauhjbdatrmmaob.supabase.co/storage/v1/object/public/products/pandora-signature-mens-ring/hero.png',
          'fossil-stainless-steel-chain': 'https://uvgtgeauhjbdatrmmaob.supabase.co/storage/v1/object/public/products/fossil-stainless-steel-chain/hero.png',
          'tommy-hilfiger-classic-bracelet': 'https://uvgtgeauhjbdatrmmaob.supabase.co/storage/v1/object/public/products/tommy-hilfiger-classic-bracelet/hero.png',
          'swarovski-mens-crystal-ring': 'https://uvgtgeauhjbdatrmmaob.supabase.co/storage/v1/object/public/products/swarovski-mens-crystal-ring/hero.png',
          'damiani-belle-epoque-cross-pendant': 'https://uvgtgeauhjbdatrmmaob.supabase.co/storage/v1/object/public/products/damiani-belle-epoque-cross-pendant/hero.png',
          'calvin-klein-minimalist-cuff': 'https://uvgtgeauhjbdatrmmaob.supabase.co/storage/v1/object/public/products/calvin-klein-minimalist-cuff/hero.png',
          'chopard-ice-cube-bracelet': 'https://uvgtgeauhjbdatrmmaob.supabase.co/storage/v1/object/public/products/chopard-ice-cube-bracelet/hero.png',
          'van-cleef-perlee-couples-ring': 'https://uvgtgeauhjbdatrmmaob.supabase.co/storage/v1/object/public/products/van-cleef-perlee-couples-ring/hero.png',
          'piaget-possession-mens-ring': 'https://uvgtgeauhjbdatrmmaob.supabase.co/storage/v1/object/public/products/piaget-possession-mens-ring/hero.png',
      }

      export const PRODUCT_VIDEO_OVERRIDES: Record<string, string> = {
        'messika-move-bracelet': '/products/messika-move-high-jewelry-bracelet/hero.mp4',
        'sovereign-amethyst': '/products/sovereign-amethyst/sovereign-amethyst-hero.mp4',
        'shamim-bloom-the-sovereign-grace': '/products/shamims-bloom/shamim-bloom-hero.mp4',
        'eternal-grace-sapphire-set': '/products/eternal-grace-sapphire-set/product-video.mp4',
        'de-beers-enchanted-lotus-earrings': '/products/de-beers-enchanted-lotus/hero.mp4',
          'graff-icon-diamond-necklace': '/products/graff-icon-diamond-necklace/hero.mp4',
          'graff-butterfly-diamond-pendant': '/products/graff-butterfly-diamond-pendant/hero.mp4',
          'swarovski-millenia-tennis-necklace': '/products/swarovski-millenia-tennis-necklace/hero.mp4',
        'swarovski-constella-bracelet': 'https://uvgtgeauhjbdatrmmaob.supabase.co/storage/v1/object/public/products/swarovski-constella-bracelet/hero.mp4',
        'cartier-juste-un-clou-bracelet': 'https://uvgtgeauhjbdatrmmaob.supabase.co/storage/v1/object/public/products/cartier-juste-un-clou-bracelet/hero.mp4',
        'de-beers-talisman-diamond-pendant': 'https://uvgtgeauhjbdatrmmaob.supabase.co/storage/v1/object/public/products/de-beers-talisman-diamond-pendant/hero.mp4',
        'graff-classic-diamond-mens-ring': 'https://uvgtgeauhjbdatrmmaob.supabase.co/storage/v1/object/public/products/graff-classic-diamond-mens-ring/hero.mp4',
        'jacob-co-astronomia-diamond-cuff': 'https://uvgtgeauhjbdatrmmaob.supabase.co/storage/v1/object/public/products/jacob-co-astronomia-diamond-cuff/hero.mp4',
        'bvlgari-bvlgari-ring': 'https://uvgtgeauhjbdatrmmaob.supabase.co/storage/v1/object/public/products/bvlgari-bvlgari-ring/hero.mp4',
      'boucheron-quatre-black-edition-ring': 'https://uvgtgeauhjbdatrmmaob.supabase.co/storage/v1/object/public/products/boucheron-quatre-black-edition-ring/hero.mp4',
    }
    