export type SovereignArticle={title:string;eyebrow:string;intro:string;sections:{heading:string;body:string}[]}
export const sovereignArticles:Record<string,SovereignArticle>={
'identity':{title:'Identity Infrastructure',eyebrow:'01 · Sovereign Architecture',intro:'Identity is the first requirement of a sovereign system. A House must distinguish itself, its objects, its places, its people, and its records through more than visual recognition.',sections:[
 {heading:'Many identities, one House',body:'Shamim Forever may need to distinguish the identity of the House, a boutique, an atelier, an object, a collection, a client relationship, and an authenticated record. These identities should connect without collapsing into one undifferentiated database.'},
 {heading:'Confidence through signals',body:'Names can be copied, images duplicated, documents altered, and websites imitated. Identity confidence is stronger when supported by multiple signals: verification, documentation, provenance, and historical continuity.'},
 {heading:'No magical proof',body:'The purpose is not to create one perfect token or certificate. It is to build a stronger system of evidence, with human review and appropriate context for the object or relationship being considered.'}]},
'authenticity-infrastructure':{title:'Authenticity Infrastructure',eyebrow:'02 · Trust Architecture',intro:'Authenticity should not depend on “trust us.” It should be supported by physical, documentary, historical, and digital layers that remain accountable over time.',sections:[
 {heading:'Physical identity',body:'Craft marks, serial references, material documentation, production records, and atelier information may contribute to the physical identity of an object. The relevant signals depend on the object category.'},
 {heading:'Documentary and historical identity',body:'Certificate information, creation date, collection, commission reference, authorized documentation, restoration history, and archive references connect an object to its story.'},
 {heading:'Digital evidence with limits',body:'Digital records can complement physical evidence. They should not automatically replace it, and a ledger cannot make unsupported physical information true.'}]},
'private-client-infrastructure':{title:'Private Client Infrastructure',eyebrow:'03 · Discreet Operations',intro:'A private client relationship requires a different philosophy from conventional digital commerce: minimum necessary information, maximum meaningful service.',sections:[
 {heading:'Discretion over scale',body:'Mass commerce often optimizes for scale. Private luxury often optimizes for discretion, continuity, and thoughtful attention. Collecting unnecessary information does not automatically improve service.'},
 {heading:'A controlled relationship layer',body:'Appointments, preferences, bespoke commissions, authorized communication, relationship history, and service continuity may be supported by an infrastructure governed by purpose and access.'},
 {heading:'Care without surveillance',body:'A relationship can remember what is relevant without turning a person into permanent data exhaust. Privacy must influence collection, access, retention, and deletion decisions.'}]},
'boutique-infrastructure':{title:'Boutique Infrastructure',eyebrow:'04 · Global House Nodes',intro:'A boutique is not simply a retail location. It is a physical node connecting local experience with House standards, client service, inventory, appointments, and institutional coherence.',sections:[
 {heading:'The boutique as a node',body:'A boutique can connect brand standards, client service, inventory, appointments, concierge, visual identity, and operational records. The infrastructure should support the experience without overwhelming it.'},
 {heading:'Global coordination, local character',body:'Global standards should create recognizable institutional coherence, not identical spaces everywhere. Local culture and human judgment remain part of the House.'},
 {heading:'Continuity across locations',body:'A client should experience care, integrity, and clear identity across regions while the individual boutique retains its own presence, knowledge, and responsibility.'}]},
'atelier-infrastructure':{title:'Bespoke Atelier Infrastructure',eyebrow:'05 · The Making System',intro:'Bespoke creation is a process. Infrastructure preserves continuity from consultation and concept through material selection, craft, quality review, delivery, and long-term care.',sections:[
 {heading:'The making chain',body:'Client, consultation, concept, material selection, design, craft, quality review, documentation, delivery, and care form a connected journey. Each stage can preserve the decisions that make the object meaningful.'},
 {heading:'Documenting without exposing',body:'Commission references, design development, material decisions, craft stages, and care recommendations may be important records. Not every detail should become public; bespoke infrastructure requires discretion.'},
 {heading:'Technology in service of the hand',body:'Digital measurements, archival records, and precision tools can reduce friction. They do not replace the artisan’s embodied knowledge or the human judgment behind the final object.'}]},
'digital-sovereignty':{title:'Digital Sovereignty',eyebrow:'06 · Strategic Independence',intro:'Digital sovereignty is not isolation. It is strategic awareness of who controls critical records, where information is maintained, whether it can migrate, and what happens when a platform disappears.',sections:[
 {heading:'Control the critical layer',body:'A sovereign digital architecture asks who controls critical records, whether backups exist, whether information can be migrated, and whether the House depends unnecessarily on one provider.'},
 {heading:'Interdependence with awareness',body:'The House can use external tools and global services while retaining clear boundaries around identity, records, access, export, recovery, and governance.'},
 {heading:'Technology changes faster than institutions',body:'Platforms evolve quickly. Institutional principles should move more carefully, so the House can adopt useful systems without allowing temporary technology to define its permanent identity.'}]},
'privacy':{title:'Privacy by Architecture',eyebrow:'07 · Private Systems',intro:'Privacy should not be a decorative policy page. It should influence how a system is designed, what it collects, who can access it, how long it retains information, and when it lets go.',sections:[
 {heading:'The necessary-information test',body:'Before collecting information, ask: do we need it, who requires access, for how long, how is access controlled, and what happens when it is no longer necessary?'},
 {heading:'Layered privacy',body:'High privacy requires multiple conditions: purposeful collection, least-privilege access, secure storage, transparent handling, appropriate retention, and responsible deletion. One password is not a privacy architecture.'},
 {heading:'Privacy as luxury',body:'Discretion is not an obstacle to service. It is part of service. The best private technology can feel like calm, relevance, simplicity, and trust rather than surveillance.'}]},
'security':{title:'Security Infrastructure',eyebrow:'08 · Protection and Recovery',intro:'Security is not a single wall. It is a layered architecture connecting identity, authentication, authorization, access control, monitoring, and recovery.',sections:[
 {heading:'The security sequence',body:'A resilient system distinguishes identity from authentication, authentication from authorization, authorization from access control, and access control from monitoring and recovery.'},
 {heading:'Failure is part of design',body:'A system with strong authentication but no recovery architecture may still fail. Security design should consider technical disruption, data corruption, communication interruption, physical disruption, and human error.'},
 {heading:'Protection without promises of perfection',body:'No infrastructure can guarantee that nothing will fail. The honest objective is to reduce unnecessary exposure, detect problems, recover responsibly, and learn from what happened.'}]},
'data-architecture':{title:'Data and Metadata Architecture',eyebrow:'09 · Meaningful Records',intro:'Information without structure becomes difficult to preserve. Data architecture gives records a place, a relationship, and enough context to remain useful through change.',sections:[
 {heading:'Structured and unstructured information',body:'Product records, boutique information, collection references, and operational metadata may sit beside images, documents, correspondence, and historical materials. The architecture should connect them without flattening their differences.'},
 {heading:'Metadata is context',body:'An archival object may need a name, collection, date, origin, material, creator, reference, and archive status. Meaningful metadata helps a future person understand what a record is and why it matters.'},
 {heading:'Less noise, more meaning',body:'More metadata is not automatically better. The objective is useful context, consistent naming, traceability, and the ability to migrate records without losing their relationships.'}]},
'heritage-architecture':{title:'Heritage Architecture',eyebrow:'10 · Institutional Memory',intro:'Luxury without memory becomes inventory. Heritage architecture preserves collection history, design evolution, founding records, milestones, atelier documentation, commissions, and cultural references.',sections:[
 {heading:'Heritage is active infrastructure',body:'An old document with no reliable context has limited institutional value. Heritage requires provenance, interpretation, continuity, and responsible stewardship.'},
 {heading:'The record of becoming',body:'The House can preserve not only finished objects but the decisions, references, people, materials, and moments that shaped them. This gives future designers and clients a way into the past.'},
 {heading:'Memory beyond decoration',body:'Institutional memory supports future decisions. It protects knowledge from disappearing when a person leaves, a platform closes, or a format becomes obsolete.'}]},
'time-archive':{title:'The Time Archive',eyebrow:'11 · Archival Continuity',intro:'The Time Archive is a long-term record environment designed to preserve information through technological change, not merely to store files in the present.',sections:[
 {heading:'Storage is not continuity',body:'A file format can become obsolete, a server architecture can disappear, and a platform can shut down. Archival continuity requires migration, documentation, integrity checks, and preserved historical context.'},
 {heading:'An evolving archive',body:'The archive must evolve while protecting the meaning of what came before. New systems should be able to carry old records forward without rewriting their history.'},
 {heading:'Future access',body:'The purpose of an archive is not accumulation. It is responsible future access: helping an authorized person find, understand, verify, and care for what the House chose to preserve.'}]},
'sovereign-vault':{title:'The Sovereign Vault',eyebrow:'12 · Controlled Records',intro:'The Sovereign Vault represents protected infrastructure for sensitive institutional records, strategic materials, governance records, and high-value historical information.',sections:[
 {heading:'Access is proportional to purpose',body:'A public journal is different from a private record. Access can be classified across open, restricted, private, confidential, and sovereign contexts according to legitimate purpose.'},
 {heading:'Protection with accountability',body:'A controlled environment should have clear authority, access decisions, monitoring, recovery, and a record of why a person or system was permitted to view something.'},
 {heading:'Not every record belongs in public',body:'Public education and institutional discretion can coexist. The House should publish what supports understanding while protecting what would compromise people, objects, operations, or trust.'}]},
'heirloom-vault':{title:'The Heirloom Vault',eyebrow:'13 · Object Continuity',intro:'The Heirloom Vault represents long-term continuity for significant objects and their historical context, extending luxury beyond the moment of acquisition.',sections:[
 {heading:'A life beyond acquisition',body:'An object may continue through care, restoration, stewardship, and future ownership. Its historical context should not disappear simply because the original transaction is complete.'},
 {heading:'The care record',body:'Object identity, care documentation, historical references, restoration history, and provenance information may form a meaningful continuity record where appropriate.'},
 {heading:'Responsible claims',body:'A vault is a concept unless it is operationally implemented. Shamim Forever should describe future infrastructure as an architecture under development rather than promise capabilities that do not yet exist.'}]},
'heritage-gallery':{title:'Heritage Gallery Infrastructure',eyebrow:'14 · Cultural Context',intro:'A Heritage Gallery is not simply a shop or an archive. It is a curated institutional environment that helps people understand cultural significance.',sections:[
 {heading:'Shop, archive, gallery',body:'A shop facilitates acquisition. An archive preserves information. A gallery contextualizes cultural significance. They may interact, but they should not be confused.'},
 {heading:'Curated meaning',body:'The Gallery can bring objects, images, design references, craft knowledge, and historical records into a coherent narrative without reducing them to inventory.'},
 {heading:'Access with stewardship',body:'Curation determines what is shared, how it is explained, and what context a future visitor needs. The goal is understanding, not spectacle.'}]},
'private-delivery':{title:'Private Delivery Infrastructure',eyebrow:'15 · Controlled Continuity',intro:'The delivery of a luxury object is part of the experience and a chain of responsibility. Continuity should be controlled from House to recipient.',sections:[
 {heading:'Beyond “package sent”',body:'A private delivery system may coordinate preparation, authorization, packaging, handoff, tracking, receipt, documentation, and care guidance according to the nature of the object.'},
 {heading:'Discretion at every handoff',body:'The delivery experience should protect identity, timing, address information, object context, and the dignity of the recipient. Operational detail should remain proportionate and private.'},
 {heading:'The relationship continues',body:'Delivery is not the end of the House relationship. It can connect naturally to care, restoration guidance, concierge, and future provenance.'}]},
'concierge-care':{title:'Concierge and Care Infrastructure',eyebrow:'16 · Relationship Continuity',intro:'Concierge is not simply customer support. Support reacts; concierge coordinates. Care continues after delivery.',sections:[
 {heading:'Coordination as service',body:'Private appointments, product guidance, bespoke coordination, boutique navigation, aftercare, restoration guidance, and client communications may form one continuous care layer.'},
 {heading:'After the transaction',body:'A relationship should not end automatically when a transaction ends. A House designed for permanence considers what the object and the person may need later.'},
 {heading:'Human care remains central',body:'Systems can help a team prepare and remember. The experience still depends on people who understand context, act with discretion, and take responsibility.'}]},
'governance':{title:'Governance Infrastructure',eyebrow:'17 · Authority and Accountability',intro:'Technology without governance can become uncontrolled. Governance establishes authority, responsibilities, standards, review processes, documentation, and accountability.',sections:[
 {heading:'Every critical process needs an owner',body:'A credible system should be able to answer: who is responsible, what is permitted, what is documented, who can review it, and what happens when something goes wrong.'},
 {heading:'Permanent principles, evolving methods',body:'Integrity, privacy, authenticity, and respect for heritage may be durable principles. Software, platforms, interfaces, and technical systems are operational methods that can evolve.'},
 {heading:'Governance protects evolution',body:'Standards create consistency without becoming rigidity. Good governance allows intelligent change while protecting the House’s identity and obligations.'}]},
'resilience':{title:'Resilience Architecture',eyebrow:'18 · Continuity Under Change',intro:'The relevant question is not only whether a system can operate. It is what happens when it cannot.',sections:[
 {heading:'Design for disruption',body:'Resilience considers technical disruption, data corruption, infrastructure failure, communication interruption, physical disruption, and the departure of key people.'},
 {heading:'Redundancy with judgment',body:'Critical systems should avoid unnecessary single points of failure. Redundancy does not mean duplicating everything; it means identifying what is critical and designing recovery around it.'},
 {heading:'Recovery is part of trust',body:'A resilient House reduces catastrophic dependence on failure-free conditions. It documents recovery paths, tests them responsibly, and learns when conditions change.'}]},
'interoperability':{title:'Interoperability',eyebrow:'19 · Open Continuity',intro:'Infrastructure should avoid becoming permanently trapped. The ability to move or exchange information may become essential as platforms and technologies change.',sections:[
 {heading:'Move without losing meaning',body:'Interoperability should preserve privacy, security, context, integrity, permissions, and provenance. Exporting a file is not enough if the relationships that explain it are lost.'},
 {heading:'Dependency awareness',body:'The House can use specialist systems while understanding the cost of lock-in, the availability of exports, the shape of backups, and the responsibility for migration.'},
 {heading:'Openness with boundaries',body:'Open exchange is not an excuse to expose private records. Interoperability must remain governed by legitimate purpose and controlled access.'}]},
'future-infrastructure':{title:'The Future of Sovereign Infrastructure',eyebrow:'20 · Principle-Led Evolution',intro:'The infrastructure of the future may include technologies that do not yet exist. The House should commit to principles rather than permanently attach its identity to a specific technology.',sections:[
 {heading:'Technology can change',body:'Future areas may include advanced digital identity, privacy-preserving systems, secure archival technologies, intelligent preservation, distributed records, and AI-assisted institutional knowledge.'},
 {heading:'Exploration is not deployment',body:'These are areas of exploration and development, not automatic promises of implementation. That distinction protects credibility and gives the House room to learn.'},
 {heading:'Designed to survive change',body:'Permanence should not mean that nothing changes. It should mean that the institution is designed to preserve what matters while adapting intelligently.'}]},
'ai-infrastructure':{title:'Artificial Intelligence Infrastructure',eyebrow:'21 · Human Authority',intro:'AI may assist institutional systems, but it should not automatically become the authority in heritage, authenticity, private relationships, or institutional records.',sections:[
 {heading:'A responsible sequence',body:'Data may be organised, AI may assist discovery or pattern recognition, a human may review the result, and an authorised person may make the decision. This protects accountability.'},
 {heading:'Useful applications',body:'Potential applications include archive discovery, knowledge organisation, internal operational assistance, pattern recognition, and client service support, subject to privacy and governance.'},
 {heading:'Human authority',body:'A system is not automatically intelligent because it contains software. Institutional intelligence emerges from people, knowledge, governance, and technology working with clear boundaries.'}]},
}
