export const HOUSE_PART_C = [
  { number: '25', slug: 'whitelist-access', title: 'Whitelist Access', kicker: 'A Controlled Access Pathway', paragraphs: ['Whitelist Access represents an initial controlled access pathway. It should remain distinct from Inner Circle membership.', 'Potential functions include early communication, private announcements, future experiences, appointment priority, and selected launches.'] },
  { number: '26', slug: 'sovereign-panel', title: 'The Sovereign Panel', kicker: 'The Secure Digital Interface', paragraphs: ['The Sovereign Panel can become the secure digital interface of the House, connecting private profiles, appointments, orders, preferences, authentication, digital records, and Concierge communication.', 'Its purpose is to give clients a clear, private way to navigate their relationship with the House.'] },
  { number: '27', slug: 'global-expansion', title: 'Global Expansion', kicker: 'Standards Before Location Count', paragraphs: ['Expansion should not be measured only through location count. Opening ten locations without maintaining standards does not necessarily strengthen a House.', 'The stronger measure is whether every new expression reinforces identity, quality, cultural intelligence, client trust, and continuity.'], formula: 'Expansion = Identity × Standards × Cultural Intelligence × Continuity' },
  { number: '28', slug: 'cultural-intelligence', title: 'Cultural Intelligence', kicker: 'Intelligent Integration', paragraphs: ['Luxury is interpreted differently around the world. A global House must understand European traditions, South Asian craftsmanship, Middle Eastern hospitality, Asian luxury culture, and local client behavior.', 'The goal is not to erase differences. The goal is intelligent integration: one identity that can listen, adapt, and remain itself.'] },
  { number: '29', slug: 'pakistan', title: 'Pakistan and The House', kicker: 'An Important Cultural Dimension', paragraphs: ['Pakistan represents an important cultural dimension within the broader story of Shamim Forever. It contains craft traditions, textile heritage, jewelry traditions, architectural diversity, regional cultures, and artisanal knowledge.', 'The House should approach this heritage with respect — not as decoration, but as knowledge.'] },
  { number: '30', slug: 'france', title: 'France and the Global House', kicker: 'Puteaux, Paris La Défense', paragraphs: ['France has an important position within global luxury history. The stated Global Headquarters in the Paris La Défense region connects the institution to an international business environment.', 'Influence is not identity. Shamim Forever must develop its own point of view while learning from the wider world of luxury.'] },
  { number: '31', slug: 'middle-east', title: 'The Middle East', kicker: 'A Significant Global Region', paragraphs: ['The Middle East represents an important global region for luxury, hospitality, design, private services, and international commerce.', 'Future House development should recognize cultural sophistication, private client expectations, hospitality standards, regional aesthetics, and global connectivity.'] },
  { number: '32', slug: 'future', title: 'The Future of The House', kicker: 'Across Generations', paragraphs: ['The House is not defined by a single decade. A long-term institution must think across generations and grow through deliberate phases.', 'The future is approached as a sequence: Foundation, Identity Development, Infrastructure, International Growth, Institutional Maturity, and Legacy.'], bullets: ['Phase I — Foundation', 'Phase II — Identity Development', 'Phase III — Infrastructure', 'Phase IV — International Growth', 'Phase V — Institutional Maturity', 'Phase VI — Legacy'] },
  { number: '33', slug: 'institutional-continuity', title: 'Institutional Continuity', kicker: 'Larger Than Any Individual', paragraphs: ['The most important question for a House is what happens when individuals change. Individuals are important, but the institution must eventually become larger than any individual.', 'Continuity is created through principles, records, standards, systems, and a culture capable of carrying the founding vision forward.'] },
  { number: '34', slug: 'house-standard', title: 'The House Standard', kicker: 'Questions Before Action', paragraphs: ['Every future initiative should pass through a set of questions before it becomes part of the House.'], bullets: ['Does it strengthen the identity?', 'Does it meet quality expectations?', 'Does it respect the client?', 'Does it create long-term value?', 'Does it belong to The House?'] },
  { number: '35', slug: 'living-institution', title: 'A Living Institution', kicker: 'The House Continues', paragraphs: ['Shamim Forever should not present itself as a completed institution. A House is never completely finished. It evolves, learns, expands, records its history, develops new standards, and preserves what matters.', 'The objective is not to create something that merely looks established. It is to build something capable of becoming established through time.'] },
]