export const HOUSE_PART_B = [
  { number: '13', slug: 'client-relationship', title: 'The Client Relationship', kicker: 'A Client Is Not a Transaction', paragraphs: ['The House should avoid treating every interaction as a single transaction. A long-term relationship is built from trust, continuity, and meaningful service.', 'The objective is not simply that a customer purchases a product. The objective is that the House understands the client relationship over time.'], formula: 'Relationship = Trust + Continuity + Meaningful Service' },
  { number: '14', slug: 'concierge', title: 'Concierge & Private Access', kicker: 'Privacy Is Part of Service', paragraphs: ['The Concierge represents a direct communication channel for private appointments, boutique visits, product inquiries, bespoke requests, client relations, and global assistance.', 'The service should remain discreet, informed, and human. Privacy is not an extra layer placed on top of service; it is part of the service itself.'] },
  { number: '15', slug: 'craftsmanship', title: 'Craftsmanship', kicker: 'The Discipline of Creation', paragraphs: ['Craftsmanship is not simply the use of expensive materials. It includes skill, precision, knowledge, process, repetition, patience, and quality control.', 'The House evaluates craftsmanship through the relationship between skill, precision, material understanding, and time.'], formula: 'Craft = Skill × Precision × Material Understanding × Time' },
  { number: '16', slug: 'atelier', title: 'The Atelier', kicker: 'Where Ideas Become Physical', paragraphs: ['The Atelier represents the creative and technical environment of the House. Depending on the category, it may involve design, prototyping, material selection, customization, craft development, and bespoke work.', 'The Atelier is also an intellectual environment. Creation requires thinking before it requires making.'] },
  { number: '17', slug: 'bespoke', title: 'Bespoke Creation', kicker: 'Personal Rather Than Mass', paragraphs: ['Bespoke creation recognizes that not every client requires the same experience. A bespoke path may move through discovery, consultation, development, review, and completion.', 'The purpose is not complexity for its own sake. It is to create the right relationship between the client, the idea, the material, and the finished work.'], bullets: ['Discovery — understanding the client’s requirements.', 'Consultation — exploring possible directions.', 'Development — creating the appropriate solution.', 'Review — evaluating the details.', 'Completion — delivering the final result.'] },
  { number: '18', slug: 'materials', title: 'Materials & Selection', kicker: 'Appropriate, Not Merely Expensive', paragraphs: ['Materials should not be selected simply because they are expensive. The House considers quality, durability, character, origin, suitability, and compatibility with the craft.', 'The best material is not automatically the rarest. It is the material appropriate to its purpose.'], bullets: ['Quality', 'Durability', 'Character', 'Origin', 'Suitability', 'Craft compatibility'] },
  { number: '19', slug: 'authenticity', title: 'Authenticity', kicker: 'Trust Must Be Designed', paragraphs: ['Authenticity is a major pillar of the House. Future systems may include product identification, documentation, digital records, certificates, ownership records, and authentication processes.', 'Technology should support trust, not replace it. Authenticity is both a record and a responsibility.'] },
  { number: '20', slug: 'heritage', title: 'Heritage', kicker: 'Heritage Is Not Just History', paragraphs: ['A new House does not need to pretend it is centuries old. Real heritage begins with honest history, documented development, consistent principles, and institutional memory.', 'Shamim Forever should build its heritage through real work: preserving what matters, recording what has been learned, and creating standards that can be carried forward.'] },
  { number: '21', slug: 'innovation', title: 'Innovation', kicker: 'Permanence Does Not Mean Stagnation', paragraphs: ['The House recognizes that permanence does not mean resisting change. Innovation can exist alongside heritage when it strengthens identity, improves trust, or enables a more meaningful client experience.', 'Innovation should be purposeful. The new matters when it serves the enduring.'] },
  { number: '22', slug: 'technology-infrastructure', title: 'Technology & Infrastructure', kicker: 'Purposeful Systems', paragraphs: ['Technology can support digital experiences, client relationships, authentication, global coordination, private access, archives, and data security.', 'The House should use technology with discipline. Not every shiny object needs blockchain attached to it; systems should be chosen for clarity, trust, usefulness, and long-term stewardship.'] },
  { number: '23', slug: 'privacy', title: 'Privacy', kicker: 'A Foundational Standard', paragraphs: ['Privacy is fundamental to the House. Personal information should be treated with responsibility across client information, communications, appointment details, private requests, and digital security.', 'A private client relationship is not a marketing claim. It is a standard that must be reflected in process, access, communication, and care.'] },
  { number: '24', slug: 'inner-circle', title: 'The Inner Circle', kicker: 'A Separate Private Program', paragraphs: ['The Inner Circle should remain a separate program within the House. It should not simply mean pay money and receive a badge.', 'It can represent a carefully structured private relationship environment with clear purpose, eligibility, invitations, experiences, privacy, governance, and member principles.'], bullets: ['Purpose', 'Eligibility', 'Invitations', 'Experiences', 'Privacy', 'Governance', 'Member principles'] },
]