import { NextRequest, NextResponse } from 'next/server'
import { createClient } from '@supabase/supabase-js'

export const dynamic = 'force-dynamic'
export const maxDuration = 60

function db() {
  return createClient(
    process.env.NEXT_PUBLIC_SUPABASE_URL!,
    process.env.SUPABASE_SERVICE_ROLE_KEY ?? process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!,
    { auth: { persistSession: false } }
  )
}

function s(tagline: string, top: string, heart: string, base: string, vol: string, price: string) {
  return JSON.stringify({ tagline, scentPyramid: { top, heart, base }, specs: { volume: vol, price, concentration: 'EDP', longevity: '10–16 Hours' } })
}
function c(tagline: string, benefits: string[], howTo: string) {
  return JSON.stringify({ tagline, benefits, howTo })
}
function j(tagline: string, material: string, desc: string) {
  return JSON.stringify({ tagline, material, description: desc, care: 'Clean with soft cloth. Store in provided pouch.' })
}

export async function GET(req: NextRequest) {
  const secret = req.nextUrl.searchParams.get('secret')
  if (secret !== 'shamim-seed-more-2026') {
    return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })
  }

  const supabase = db()

  // Get category IDs
  const { data: cats } = await supabase.from('main_categories').select('id, slug')
  const perfumeId = cats?.find(c => c.slug === 'perfume')?.id
  const cosmeticsId = cats?.find(c => c.slug === 'cosmetics')?.id
  const jewelryId = cats?.find(c => c.slug === 'jewelry')?.id
  if (!perfumeId || !cosmeticsId || !jewelryId) {
    return NextResponse.json({ error: 'Categories missing — run /api/seed-products first' }, { status: 400 })
  }

  // Get sub-category IDs
  const { data: subs } = await supabase.from('sub_categories').select('id, name, slug')
  const maleId   = subs?.find(s => s.name?.toLowerCase().includes('him') || s.slug?.includes('him'))?.id ?? null
  const femaleId = subs?.find(s => s.name?.toLowerCase().includes('her') || s.slug?.includes('her'))?.id ?? null
  const unisexId = subs?.find(s => s.name?.toLowerCase().includes('unisex'))?.id ?? null

  const IMG_PM = 'https://uvgtgeauhjbdatrmmaob.supabase.co/storage/v1/object/public/products/perfumes/himalayan-snow-musk.png'
  const IMG_PF = 'https://uvgtgeauhjbdatrmmaob.supabase.co/storage/v1/object/public/products/perfumes/midnight-iris-royale.png'
  const IMG_PU = 'https://uvgtgeauhjbdatrmmaob.supabase.co/storage/v1/object/public/products/perfumes/vanilla-absolute.png'
  const IMG_C  = 'https://uvgtgeauhjbdatrmmaob.supabase.co/storage/v1/object/public/products/perfumes/oud-sovereign-new.png'
  const IMG_J  = 'https://uvgtgeauhjbdatrmmaob.supabase.co/storage/v1/object/public/products/perfumes/oud-sovereign-new.png'

  // ── PERFUMES ───────────────────────────────────────────────────────────────

  // Male (15)
  const perfMale = [
    { name: 'AFNAN 9PM',                  slug: 'afnan-9pm',               description: 'Vibrant and bold EDP inspired by Parfums de Marly Herod. Crisp apple, lavender, cinnamon over vanilla and amber. A crowd-pleaser.',                               story: s('AFNAN 9PM — THE CROWD PLEASER','Crisp Apple, Bergamot, Wild Lavender, Cinnamon','Orange Blossom, Lily of the Valley','Vanilla, Tonka Bean, Patchouli, Amber','100ML','Rs 10,500 / $39'), price_pkr: 10500, price_usd: 39 },
    { name: 'J. FRAGRANCES SHER DIL',     slug: 'j-sher-dil',              description: 'A tribute to Pakistani heroes. Fresh citrus and green apple opening, floral-fruity heart, deep leather and amber base. National pride in a bottle.',              story: s('SHER DIL — EMBLEM OF VALOR','Fresh Citrus, Green Apple','Floral-Fruity, Black Pepper','Leather, Patchouli, Amber, Cedarwood','100ML','Rs 12,200 / $45'), price_pkr: 12200, price_usd: 45 },
    { name: 'LATTAFA ASAD',               slug: 'lattafa-asad',             description: 'Powerhouse amber-spicy EDP. Black pepper, pineapple, tobacco over coffee, patchouli, and dark vanilla. Dominance in a bottle.',                                   story: s('LATTAFA ASAD — EMBODIMENT OF DOMINANCE','Black Pepper, Pineapple, Tobacco','Coffee, Patchouli, Iris','Vanilla, Amber, Dry Woods, Benzoin','100ML','Rs 8,950 / $32'), price_pkr: 8950, price_usd: 32 },
    { name: 'RASASI HAWAS FOR HIM',        slug: 'rasasi-hawas-him',         description: 'Global best-seller aquatic beast-mode EDP. Explosive crisp apple, plum, bergamot, cinnamon over warm ambergris and driftwood.',                                   story: s('RASASI HAWAS FOR HIM — AQUATIC BEAST','Crisp Apple, Juicy Plum, Bergamot','Cinnamon, Cardamom','Warm Ambergris, Driftwood, Musk','100ML','Rs 11,900 / $42'), price_pkr: 11900, price_usd: 42 },
    { name: 'ARMAF CLUB DE NUIT INTENSE',  slug: 'armaf-cdni-man',           description: 'Legendary Creed Aventus dupe with even better performance. Lemon, bergamot, black currant, pineapple, birch, jasmine over musk and ambergris.',                   story: s('CDNI — THE LEGENDARY TRAILBLAZER','Lemon, Bergamot, Black Currant, Apple, Pineapple','Birch, Jasmine, Rose','Musk, Ambergris, Patchouli, Vanilla','200ML','Rs 13,500 / $49'), price_pkr: 13500, price_usd: 49 },
    { name: 'MONT BLANC LEGEND',           slug: 'mont-blanc-legend',        description: 'Iconic aromatic fougère. Fresh lavender, bergamot, neo-iris, coumarin over tonka bean and cedarwood. The timeless gentleman\'s signature.',                        story: s('MONT BLANC LEGEND — TIMELESS GENTLEMAN','Bergamot, Lavender, Pineapple','Neo Iris Accord, Geranium, Rose','Tonka Bean, Cedarwood, Oak Moss','100ML','Rs 14,500 / $52'), price_pkr: 14500, price_usd: 52 },
    { name: 'DIOR SAUVAGE DUPE INTENSE',   slug: 'sauvage-intense-dupe',     description: 'Premium Dior Sauvage inspired aromatic. Raw ambroxan, fresh pepper, bergamot from Calabria, lavender over sichuan pepper and earthy vetiver.',                    story: s('SAUVAGE INSPIRED — WILD AND NOBLE','Bergamot, Pink Pepper, Lavender, Geranium','Sichuan Pepper, Vetiver Accord','Ambroxan, Cedar, Labdanum, Patchouli','100ML','Rs 9,800 / $35'), price_pkr: 9800, price_usd: 35 },
    { name: 'CREED AVENTUS INSPIRED',      slug: 'creed-aventus-inspired',   description: 'Fresh fruity-smoky chypre inspired by the legendary Aventus. Bergamot, blackcurrant, apple, pineapple over birch smoke and oakmoss with musk.',                  story: s('AVENTUS INSPIRED — THE LEGACY','Bergamot, Black Currant, Apple, Pineapple','Birch, Jasmine, Rose, Dry Currant','Oak Moss, Musk, Ambergris, Vanilla','100ML','Rs 12,000 / $43'), price_pkr: 12000, price_usd: 43 },
    { name: 'ARABIAN NIGHTS OUD',          slug: 'arabian-nights-oud',       description: 'Deep Arabian oud with black saffron, rose and leather accord. The authentic Middle Eastern luxury experience for the discerning man.',                             story: s('ARABIAN NIGHTS OUD — THE EASTERN THRONE','Saffron, Cardamom, Black Pepper','Oud Absolute, Rose, Leather Accord','Amber, Sandalwood, Musk, Benzoin','100ML','Rs 16,500 / $58'), price_pkr: 16500, price_usd: 58 },
    { name: 'BLUE SEDUCTION INTENSE',      slug: 'blue-seduction-intense',   description: 'Premium blue aquatic aromatic. Ocean breeze, watery melon, mint over subtle woods and warm amber. Cool, clean, and magnetic.',                                   story: s('BLUE SEDUCTION — COOL COMMAND','Ocean Accord, Melon, Mint, Bergamot','Geranium, Violet, Lavender Accord','Amber, Musk, Driftwood, Cedar','100ML','Rs 8,500 / $30'), price_pkr: 8500, price_usd: 30 },
    { name: 'SPICE EMPEROR',               slug: 'spice-emperor-him',        description: 'Rich, warm spice accord of cinnamon, nutmeg, and cardamom over sandalwood and amber. Commanding depth for cold evenings.',                                         story: s('SPICE EMPEROR — WARM AUTHORITY','Cinnamon, Nutmeg, Cardamom, Clove','Amber Rose, Guaiac Wood','Sandalwood, Amber, Tonka, Musk','100ML','Rs 13,000 / $46'), price_pkr: 13000, price_usd: 46 },
    { name: 'PHANTOM OF NOIR',             slug: 'phantom-noir',             description: 'Dark, brooding aromatic leather. Lavender, violet leaf over dark leather, patchouli and smoky guaiac wood. Mysterious and compelling.',                           story: s('PHANTOM OF NOIR — DARK MYSTERY','Lavender, Violet Leaf, Dark Bergamot','Dark Leather, Patchouli, Tobacco','Guaiac Wood, Amber, Musk, Vetiver','100ML','Rs 11,000 / $39'), price_pkr: 11000, price_usd: 39 },
    { name: 'GOLDEN SAFFRON KING',         slug: 'golden-saffron-king',      description: 'Persian saffron with oud and warm amber. A rich, opulent signature for the man who lives boldly and commands every room.',                                        story: s('GOLDEN SAFFRON KING — PERSIAN ROYALTY','Saffron, Cardamom, Bergamot','Oud, Rose Absolute, Amberwood','Amber Resin, Sandalwood, Musk','100ML','Rs 17,500 / $62'), price_pkr: 17500, price_usd: 62 },
    { name: 'FRESH CITRUS SIGNATURE',      slug: 'fresh-citrus-signature',   description: 'Bright Sicilian lemon, bergamot, grapefruit over a white musk and cedarwood base. Clean daily signature for the modern sovereign man.',                          story: s('FRESH CITRUS SIGNATURE — VIBRANT ENERGY','Sicilian Lemon, Grapefruit, Bergamot','Petitgrain, Neroli, Green Tea','White Musk, Cedarwood, Vetiver','100ML','Rs 7,800 / $28'), price_pkr: 7800, price_usd: 28 },
    { name: 'DARK WOODS PRESTIGE',         slug: 'dark-woods-prestige',      description: 'Dense dark woods of oud, myrrh, and incense over a mossy labdanum base. Commanding, ancient, sovereign.',                                                        story: s('DARK WOODS PRESTIGE — ANCIENT COMMAND','Bergamot, Black Pepper, Galbanum','Oud, Myrrh Resin, Incense','Labdanum, Oakmoss, Amber, Musk','100ML','Rs 14,000 / $50'), price_pkr: 14000, price_usd: 50 },
  ]

  // Female (15)
  const perfFemale = [
    { name: 'RASASI HAWAS FOR HER',        slug: 'rasasi-hawas-her',         description: 'The feminine version of the Hawas beast. Citrusy bubbly opening, floral heart of rose and jasmine, warm musk and amber dry-down.',                               story: s('RASASI HAWAS FOR HER — FEMININE MAGNETISM','Pink Grapefruit, Orange, Bergamot','Rose, Jasmine, Lily','White Musk, Amber, Sandalwood','100ML','Rs 11,200 / $40'), price_pkr: 11200, price_usd: 40 },
    { name: 'LATTAFA YARA',                slug: 'lattafa-yara',             description: 'Incredibly popular feminine EDP — sweet, fruity, floral. Strawberry, pear, rose over white musk and sandalwood. An addictive crowd-pleaser.',                    story: s('LATTAFA YARA — FEMININE DELIGHT','Strawberry, Pear, Raspberry','Rose, Jasmine, Peony','White Musk, Sandalwood, Vanilla','100ML','Rs 7,500 / $27'), price_pkr: 7500, price_usd: 27 },
    { name: 'ARMAF CLUB DE NUIT WOMEN',    slug: 'armaf-cdnw',               description: 'Feminine version of the iconic Club de Nuit. Floral and fresh — bergamot, lemon, rose, jasmine over sandalwood and musks. Bright, elegant.',                    story: s('CDNW — FEMININE ICON','Bergamot, Lemon, Pink Pepper','Rose Absolute, Jasmine, Lily','Sandalwood, White Musk, Amber','200ML','Rs 11,500 / $41'), price_pkr: 11500, price_usd: 41 },
    { name: 'MISS DIOR INSPIRED',          slug: 'miss-dior-inspired',       description: 'Chic, modern floral chypre inspired by Miss Dior. Mandarin, bergamot, fresh-cut rose over patchouli and white musk. Parisian elegance.',                        story: s('MISS DIOR INSPIRED — PARISIAN ELEGANCE','Mandarin, Bergamot, Neroli','Rose Centifolia, Peony, Lily','Patchouli, White Musk, Sandalwood','100ML','Rs 9,500 / $34'), price_pkr: 9500, price_usd: 34 },
    { name: 'CHANEL NO.5 INSPIRED',        slug: 'chanel-no5-inspired',      description: 'Inspired by the world\'s most iconic fragrance. Classic powdery aldehydic floral — neroli, ylang, rose, jasmine over sandalwood and vanilla musk.',              story: s('NO.5 INSPIRED — TIMELESS ICONIC','Neroli, Aldehydes, Bergamot','Ylang Ylang, Rose, Jasmine','Sandalwood, Vanilla Musk, Amber','100ML','Rs 9,000 / $32'), price_pkr: 9000, price_usd: 32 },
    { name: 'LANCOME LA VIE EST BELLE INSPIRED', slug: 'la-vie-est-belle-inspired', description: 'Inspired by the best-selling sweet gourmand floral. Iris, patchouli, vanilla over praline and tonka bean. Joyful, warm, and feminine.',            story: s('LA VIE EST BELLE INSPIRED — SWEET JOY','Blackcurrant, Pear, Iris Pallida','Jasmine, Orange Blossom','Patchouli, Vanilla, Tonka Bean, Praline','100ML','Rs 9,800 / $35'), price_pkr: 9800, price_usd: 35 },
    { name: 'FLORAL BOUQUET ROYALE',       slug: 'floral-bouquet-royale',    description: 'Vibrant bouquet of Grasse rose, lily of the valley, and peony. Fresh, effervescent, and sovereignly feminine for every occasion.',                              story: s('FLORAL BOUQUET ROYALE — VIBRANT FEMININITY','Lemon, Bergamot, Green Apple','Rose de Grasse, Lily, Peony','White Musk, Sandalwood, Cedarwood','100ML','Rs 8,800 / $31'), price_pkr: 8800, price_usd: 31 },
    { name: 'SWEET GOURMAND PARFUM',       slug: 'sweet-gourmand-parfum',    description: 'Indulgent caramel, vanilla, and sandalwood EDP. Sweet yet sophisticated — a guilty pleasure elevated to luxury.',                                              story: s('SWEET GOURMAND PARFUM — GUILTY LUXURY','Caramel, Praline, Bergamot','Vanilla Orchid, Coconut, Rose','Sandalwood, Tonka Bean, Musks','100ML','Rs 8,200 / $29'), price_pkr: 8200, price_usd: 29 },
    { name: 'AZAR OUD FEMINITE',           slug: 'azar-oud-feminite',        description: 'Feminine oud accord with pink rose, saffron, and creamy vanilla. Eastern luxury reimagined for the modern sovereign woman.',                                    story: s('AZAR OUD FEMINITE — EASTERN LUXURY','Persian Rose, Saffron, Pink Pepper','Rose Oud, Jasmine, Iris','Creamy Vanilla, Sandalwood, Musks','100ML','Rs 14,000 / $50'), price_pkr: 14000, price_usd: 50 },
    { name: 'AQUA FLORALIS',               slug: 'aqua-floralis',            description: 'Fresh aquatic floral — sea breeze and bergamot open into a heart of transparent rose and jasmine over light woods and musk.',                                    story: s('AQUA FLORALIS — FRESH FEMININE','Sea Salt, Bergamot, Green Citrus','Rose, Jasmine, Transparent Floral','Light Musk, Cedarwood, Sandalwood','100ML','Rs 7,200 / $26'), price_pkr: 7200, price_usd: 26 },
    { name: 'TUBEROSE IMPERIALE',          slug: 'tuberose-imperiale',       description: 'Deep, heady tuberose absolute paired with jasmine and warm amber. Dramatically feminine, powerfully sovereign.',                                                 story: s('TUBEROSE IMPERIALE — DRAMATIC SOVEREIGNTY','Bergamot, Green Notes, Neroli','Tuberose Absolute, Jasmine, Gardenia','White Amber, Musk, Sandalwood','100ML','Rs 12,500 / $44'), price_pkr: 12500, price_usd: 44 },
    { name: 'PEARL OF THE EAST',           slug: 'pearl-of-the-east',        description: 'Delicate white musk with white florals and fresh coconut. Soft, clean, and endlessly feminine — inspired by South Sea pearls.',                                  story: s('PEARL OF THE EAST — DELICATE BEAUTY','Coconut Water, Bergamot, Aldehydes','White Rose, Lily, Muguet','White Musk, Vanilla, Sandalwood','100ML','Rs 9,200 / $33'), price_pkr: 9200, price_usd: 33 },
    { name: 'NOIR ROSE ABSOLUTE',          slug: 'noir-rose-absolute',       description: 'The darkest rose — velvety deep rose absolute over patchouli, dark amber, and oud. Feminine yet fierce, timeless yet modern.',                                   story: s('NOIR ROSE ABSOLUTE — FIERCE FEMININITY','Dark Rose, Saffron, Black Pepper','Deep Rose Absolute, Oud, Patchouli','Dark Amber, Sandalwood, Musks','100ML','Rs 13,800 / $49'), price_pkr: 13800, price_usd: 49 },
    { name: 'PINK SUGAR ROYALE',           slug: 'pink-sugar-royale',        description: 'Playful yet sophisticated — pink sugar, strawberry, and caramel over cotton candy musk and sandalwood. Young luxury at its sweetest.',                           story: s('PINK SUGAR ROYALE — SWEET SOVEREIGNTY','Strawberry, Bergamot, Fig','Pink Sugar, Raspberry, Rose','Cotton Candy Musk, Vanilla, Sandalwood','100ML','Rs 7,900 / $28'), price_pkr: 7900, price_usd: 28 },
    { name: 'MAGNOLIA STATEMENT',          slug: 'magnolia-statement',       description: 'Lush southern magnolia blossom with creamy coconut and warm woods. Feminine warmth with a sovereign confidence.',                                                 story: s('MAGNOLIA STATEMENT — SOVEREIGN WARMTH','Green Apple, Pink Pepper, Bergamot','Magnolia, White Rose, Coconut Cream','Vanilla, Cedarwood, White Musk','100ML','Rs 8,600 / $31'), price_pkr: 8600, price_usd: 31 },
  ]

  // Unisex (10)
  const perfUnisex = [
    { name: 'MAISON LOUIS MARIE NO.04',    slug: 'maison-lm-no04-inspired',  description: 'Inspired by the iconic Bois de Balincourt. Earthy cedar, sandalwood, and musk with a hint of vanilla. The ultimate clean unisex statement.',                    story: s('BOIS DE BALINCOURT INSPIRED — EARTHY CHIC','Bergamot, Pink Pepper, Geranium','Cypress, Sandalwood, Vetiver','Cedar, White Musk, Vanilla','100ML','Rs 13,500 / $48'), price_pkr: 13500, price_usd: 48 },
    { name: 'LE LABO SANTAL 33 INSPIRED',  slug: 'santal-33-inspired',       description: 'Inspired by the global cult favourite. Cardamom, iris, violet accord over sandalwood, cedarwood, leather and papyrus. Effortless unisex luxury.',                story: s('SANTAL 33 INSPIRED — CULT FAVOURITE','Cardamom, Iris, Violet Accord','Australian Sandalwood, Cedarwood, Leather','Ambrox, Papyrus, Musk','100ML','Rs 14,800 / $53'), price_pkr: 14800, price_usd: 53 },
    { name: 'TOBACCO HONEY',               slug: 'tobacco-honey',            description: 'Raw Virginian tobacco leaf steeped in honey and tonka bean over a dark amber base. Warm, seductive, and sovereignly unisex.',                                    story: s('TOBACCO HONEY — WARM SEDUCTION','Honey Accord, Bergamot, Citrus','Virginia Tobacco, Tonka Bean, Amber Rose','Dark Amber, Vanilla, Sandalwood','100ML','Rs 12,000 / $43'), price_pkr: 12000, price_usd: 43 },
    { name: 'NEROLI PORTO',                slug: 'neroli-porto',             description: 'Sun-drenched neroli blossom with bergamot, petitgrain, and a warm musk base. Mediterranean sunshine in a bottle for all.',                                      story: s('NEROLI PORTO — MEDITERRANEAN SUN','Neroli, Bergamot, Lemon, Mandarin','Petitgrain, White Flowers, Green Tea','White Musk, Cedarwood, Amber','100ML','Rs 11,500 / $41'), price_pkr: 11500, price_usd: 41 },
    { name: 'VETIVER SUPREME',             slug: 'vetiver-supreme',          description: 'Clean, smoky Haitian vetiver with fresh geranium and woody cedar. The ultimate unisex power neutral — no gender, pure sovereignty.',                             story: s('VETIVER SUPREME — PURE SOVEREIGNTY','Grapefruit, Geranium, Vetiver','Haitian Vetiver, Cedar, Guaiac Wood','Amber, Oakmoss, Grey Musks','100ML','Rs 12,800 / $45'), price_pkr: 12800, price_usd: 45 },
    { name: 'HINOKI CEDAR JAPAN',          slug: 'hinoki-cedar-japan',       description: 'Sacred Japanese hinoki cypress wood with soft yuzu citrus and white musk. Meditative, clean, and serenely unisex.',                                              story: s('HINOKI CEDAR JAPAN — SACRED FOREST','Yuzu, Green Tea, Bergamot','Hinoki Cypress, Cedarwood, Iris','White Musk, Sandalwood, Ambroxan','100ML','Rs 13,000 / $46'), price_pkr: 13000, price_usd: 46 },
    { name: 'SMOKY ROSE FUSION',           slug: 'smoky-rose-fusion',        description: 'Turkish rose absolute smoked with birch and oud. The boundary-less fragrance for those who defy all categories.',                                                story: s('SMOKY ROSE FUSION — NO BOUNDARIES','Turkish Rose, Black Pepper, Bergamot','Oud, Birch Smoke, Rose Absolute','Dark Amber, Patchouli, Musks','100ML','Rs 14,200 / $50'), price_pkr: 14200, price_usd: 50 },
    { name: 'GREY AMBER ACCORD',           slug: 'grey-amber-accord',        description: 'Ambroxan-forward accord with sea salt, sage, and clean musks. Skin-close intimacy for all. The ultimate modern luxury neutral.',                                  story: s('GREY AMBER ACCORD — INTIMATE LUXURY','Sea Salt, Bergamot, Lavender','Ambroxan, Grey Amber, Sage','Sandalwood, Musks, Cashmeran','100ML','Rs 13,500 / $48'), price_pkr: 13500, price_usd: 48 },
    { name: 'CITRUS PARADISO',             slug: 'citrus-paradiso',          description: 'Explosive Sicilian citrus with bergamot, grapefruit, and verbena over a woody amber dry-down. Pure energy, perfectly unisex.',                                   story: s('CITRUS PARADISO — EXPLOSIVE ENERGY','Bergamot, Grapefruit, Lemon Verbena','Petitgrain, Neroli, Green Accord','Woody Amber, White Musk, Cedar','100ML','Rs 9,800 / $35'), price_pkr: 9800, price_usd: 35 },
    { name: 'INCENSE & MUSK',              slug: 'incense-musk-unisex',      description: 'Sacred frankincense with clean white musk and warm cedarwood. A meditative blend for those who seek clarity and sovereignty.',                                    story: s('INCENSE & MUSK — MEDITATIVE CLARITY','Frankincense, Elemi, Bergamot','Myrrh, Cedarwood, Orris','White Musk, Sandalwood, Labdanum','100ML','Rs 11,500 / $41'), price_pkr: 11500, price_usd: 41 },
  ]

  // ── COSMETICS ──────────────────────────────────────────────────────────────
  // Male (20)
  const cosMale = [
    // Skin Prep (7)
    { name: 'Niacinamide 10% Serum',       slug: 'niacinamide-serum-him',    description: '10% niacinamide + 1% zinc serum that minimizes pores, controls oil, and brightens skin. The sovereign daily skin prep.', story: c('NIACINAMIDE 10% — SKIN PREP FOUNDATION', ['Minimizes pores','Controls oil','Brightens skin','Reduces blemishes'], 'Apply 3-5 drops to clean face morning and evening.'), price_pkr: 4800, price_usd: 17 },
    { name: 'AHA BHA Exfoliant',            slug: 'aha-bha-exfoliant-him',    description: '7% glycolic + 2% salicylic acid chemical exfoliant. Dissolves dead cells and unclogs pores without physical scrubbing.', story: c('AHA BHA EXFOLIANT — CLEAR SKIN', ['Dissolves dead skin','Unclogs pores','Prevents breakouts','Even tone'], 'Apply at night 2-3x per week. Always use SPF next morning.'), price_pkr: 5500, price_usd: 20 },
    { name: 'Peptide Firming Cream',        slug: 'peptide-firming-cream-him',description: 'Advanced peptide moisturizer that stimulates collagen, firms skin, and fills fine lines. Premium anti-aging for men.', story: c('PEPTIDE FIRMING CREAM — ANTI-AGING', ['Stimulates collagen','Firms and tightens','Fills fine lines','12-hour hydration'], 'Apply to face and neck morning and evening.'), price_pkr: 6800, price_usd: 24 },
    { name: 'Centella Recovery Toner',      slug: 'centella-toner-him',       description: 'Calming centella asiatica toner that repairs and hydrates sensitive, irritated, or post-shave skin. Zero-sting formula.', story: c('CENTELLA TONER — CALM & REPAIR', ['Calms irritation','Repairs barrier','Hydrates instantly','Prevents redness'], 'Apply with hands or cotton pad after cleanser.'), price_pkr: 3900, price_usd: 14 },
    { name: 'Retinol 0.5% Night Serum',     slug: 'retinol-night-serum-him',  description: 'Encapsulated 0.5% retinol serum for masculine skin — minimizes pores, reduces wrinkles, refines texture overnight.', story: c('RETINOL 0.5% NIGHT SERUM — OVERNIGHT POWER', ['Reduces wrinkles','Refines texture','Minimizes pores','Stimulates renewal'], 'Apply 3-4 drops every other evening to clean skin. Use SPF daily.'), price_pkr: 7200, price_usd: 26 },
    { name: 'Oil-Control Primer',           slug: 'oil-control-primer-him',   description: 'Matte silicone primer that fills pores and creates a smooth, oil-free canvas. Perfect for daily confidence under any conditions.', story: c('OIL-CONTROL PRIMER — SMOOTH CANVAS', ['Fills pores instantly','Controls oil 8 hours','Smooth texture','Extends makeup wear'], 'Apply thin layer to clean, moisturized face before any product.'), price_pkr: 4200, price_usd: 15 },
    { name: 'Hyaluron Booster Ampoule',     slug: 'hyaluron-booster-him',     description: 'Concentrated hyaluronic acid ampoule shot for instant deep hydration. Use as a weekly treatment or daily booster.', story: c('HYALURON BOOSTER — INSTANT HYDRATION', ['Instant deep hydration','Plumps fine lines','Strengthens barrier','Glowing skin'], 'Apply 1 ampoule to face and neck before moisturizer.'), price_pkr: 5800, price_usd: 21 },
    // Professional Treatments (7)
    { name: 'Salicylic Acne Spot Gel',      slug: 'salicylic-spot-gel',       description: 'Fast-acting 2% salicylic acid spot treatment that eliminates pimples and blackheads in 24-48 hours without scarring.', story: c('SALICYLIC SPOT GEL — FAST ELIMINATION', ['Works in 24-48 hours','No scarring','Unclogs pores','Reduces redness'], 'Apply directly to blemish with cotton swab. Do not rub.'), price_pkr: 2800, price_usd: 10 },
    { name: 'Kojic Acid Dark Spot Serum',   slug: 'kojic-dark-spot-him',      description: 'Kojic acid + vitamin C serum that fades post-acne marks, dark patches, and uneven skin tone. Medical-grade depigmentation.', story: c('KOJIC ACID SERUM — FADE DARK SPOTS', ['Fades post-acne marks','Brightens dark spots','Even skin tone','Medical-grade'], 'Apply 4-5 drops to dark areas morning and evening.'), price_pkr: 6500, price_usd: 23 },
    { name: 'Under-Eye Serum Patches',      slug: 'under-eye-patches',        description: 'Collagen-infused hydrogel eye patches with caffeine and gold. Eliminates puffiness and dark circles in 20 minutes.', story: c('EYE SERUM PATCHES — 20-MIN RESULTS', ['Eliminates puffiness','Brightens dark circles','Deep collagen boost','Gold infused'], 'Apply cold patches under eyes for 20 minutes.'), price_pkr: 3500, price_usd: 12 },
    { name: 'Microneedling Roller 0.3mm',   slug: 'derma-roller-0-3mm',       description: 'Medical-grade 0.3mm titanium microneedle roller for collagen induction. Improves skin texture, reduces scars, enhances product absorption.', story: c('DERMA ROLLER 0.3MM — COLLAGEN INDUCTION', ['Improves skin texture','Reduces scars','Boosts product absorption','Stimulates collagen'], 'Roll lightly over face 2x per week. Sanitize before and after.'), price_pkr: 3200, price_usd: 11 },
    { name: 'Glycolic Acid Toner 7%',       slug: 'glycolic-toner-7-him',     description: '7% glycolic acid liquid exfoliant that resurfaces skin, brightens complexion, and unclogs pores with daily use.', story: c('GLYCOLIC TONER 7% — RESURFACE', ['Resurfaces skin','Brightens dull complexion','Unclogs pores','Smooths texture'], 'Apply with cotton pad at night. Start 3x per week, build up.'), price_pkr: 4500, price_usd: 16 },
    { name: 'Bentonite Clay Mask',          slug: 'bentonite-clay-mask-him',  description: 'Deep-cleansing bentonite clay mask with apple cider vinegar that extracts impurities, tightens pores, and detoxifies.', story: c('BENTONITE CLAY MASK — DEEP DETOX', ['Extracts impurities','Tightens pores','Detoxifies skin','Controls sebum'], 'Apply thin layer. Leave 10-15 minutes. Rinse with warm water.'), price_pkr: 3800, price_usd: 14 },
    // Trendy Grooming (6)
    { name: 'Tinted SPF 50 Fluid',          slug: 'tinted-spf50-fluid-him',   description: 'Tinted mineral SPF 50 with a natural skin-tone finish. Covers imperfections, protects, and perfects — the modern man\'s secret.', story: c('TINTED SPF 50 — PROTECT & PERFECT', ['SPF 50 protection','Covers imperfections','Natural finish','Lightweight fluid'], 'Apply to face 15 min before sun. Reapply every 2 hours.'), price_pkr: 5200, price_usd: 18 },
    { name: 'Brightening Eye Cream',        slug: 'brightening-eye-cream-him',description: 'Vitamin K + retinol eye cream that banishes dark circles, firms eye area, and reduces crow\'s feet. Daily luxury.', story: c('BRIGHTENING EYE CREAM — AWAKE EYES', ['Banishes dark circles','Firms eye area','Reduces crow\'s feet','24-hour hydration'], 'Apply small amount morning and evening. Pat gently.'), price_pkr: 6200, price_usd: 22 },
    { name: 'Scalp Serum Biotin',           slug: 'scalp-serum-biotin',       description: 'Biotin, caffeine, and niacinamide scalp serum that strengthens hair roots and promotes new growth. Medical-grade results.', story: c('SCALP SERUM BIOTIN — HAIR GROWTH', ['Strengthens roots','Promotes new growth','Reduces hairfall','Medical-grade biotin'], 'Apply to dry scalp sections. Massage in. Do not rinse.'), price_pkr: 5800, price_usd: 21 },
    { name: 'BB Cream SPF 30',              slug: 'bb-cream-spf30-him',       description: 'Light BB cream with SPF 30 — covers redness and dark circles while hydrating and protecting. The modern man\'s daily essential.', story: c('BB CREAM SPF 30 — MODERN GROOMING', ['Covers redness','SPF 30 protection','Hydrates all day','Natural finish'], 'Apply evenly after skincare. Blend with fingers.'), price_pkr: 4400, price_usd: 16 },
    { name: 'Beard Conditioning Balm',      slug: 'beard-conditioning-balm',  description: 'Shea butter, argan, and vitamin E beard conditioning balm. Softens coarse beard hair, nourishes skin, and controls shape.', story: c('BEARD CONDITIONING BALM — SOVEREIGN GROOMING', ['Softens beard','Nourishes skin','Controls shape','Premium ingredients'], 'Warm small amount between palms, work through beard.'), price_pkr: 3600, price_usd: 13 },
    { name: 'Pomade High Shine',            slug: 'pomade-high-shine',        description: 'Water-based high-shine pomade with medium hold. Classic slicked-back look or modern wet-look styles. Washes out easily.', story: c('POMADE HIGH SHINE — CLASSIC STYLE', ['High shine finish','Medium hold','Water-based formula','Washes out easily'], 'Apply to damp hair. Comb into desired style.'), price_pkr: 3400, price_usd: 12 },
  ]

  // Female (40)
  const cosFemale = [
    // Skin Prep (10)
    { name: 'Tranexamic Acid Serum',        slug: 'tranexamic-serum',         description: 'Powerful tranexamic acid + niacinamide serum for dark spots and melasma. Clinical-strength brightening with zero irritation.', story: c('TRANEXAMIC ACID — CLINICAL BRIGHTENING', ['Fades melasma','Reduces dark spots','Even tone','Zero irritation'], 'Apply 3-5 drops morning and evening to problem areas.'), price_pkr: 8200, price_usd: 29 },
    { name: 'Double Cleanse Oil Balm',      slug: 'double-cleanse-oil-balm',  description: 'Japanese-inspired cleansing oil balm that melts away SPF and heavy makeup without stripping natural moisture.', story: c('CLEANSING OIL BALM — DEEP MELT', ['Melts all makeup','Removes SPF','Preserves moisture','Suits all skin'], 'Massage onto dry face, emulsify with water, rinse.'), price_pkr: 4800, price_usd: 17 },
    { name: 'Ceramide Barrier Cream',       slug: 'ceramide-barrier-cream',   description: '3 essential ceramides, hyaluronic acid, and niacinamide that restore, seal, and protect the skin barrier. Dermatologist-approved.', story: c('CERAMIDE BARRIER CREAM — SKIN SHIELD', ['Restores skin barrier','Seals moisture','Reduces sensitivity','Dermat-approved'], 'Apply generously to face and neck daily.'), price_pkr: 6500, price_usd: 23 },
    { name: 'Alpha Arbutin 2% Serum',       slug: 'alpha-arbutin-serum',      description: 'Alpha arbutin + vitamin C serum for safe daily brightening. Fades stubborn dark spots without irritation. Safe for all skin tones.', story: c('ALPHA ARBUTIN 2% — SAFE BRIGHTENING', ['Safe for all tones','Fades dark spots','Brightens daily','Hyaluronic acid blend'], 'Apply 4-5 drops to face morning and evening.'), price_pkr: 5800, price_usd: 21 },
    { name: 'Glow Toner with BHA',          slug: 'glow-toner-bha',           description: '1% BHA (salicylic) + botanical extracts toner. Exfoliates, unclogs, and brightens for a naturally radiant complexion.', story: c('GLOW TONER BHA — RADIANT SKIN', ['Exfoliates gently','Unclogs pores','Natural radiance','Brightening botanicals'], 'Apply with cotton pad after cleansing.'), price_pkr: 4200, price_usd: 15 },
    { name: 'Rose Hip Face Oil',            slug: 'rosehip-face-oil',         description: 'Cold-pressed rosehip seed oil — nature\'s most powerful anti-aging oil. Fades scars, brightens, and deeply nourishes dry skin.', story: c('ROSEHIP FACE OIL — NATURE\'S RETINOL', ['Fades scars','Brightens complexion','Deep nourishment','Anti-aging natural'], 'Apply 3-4 drops to face after serum. Can mix with moisturizer.'), price_pkr: 5500, price_usd: 20 },
    { name: 'Snail Mucin Essence',          slug: 'snail-mucin-essence',      description: 'K-beauty classic — 96% snail secretion filtrate that repairs, hydrates, and regenerates skin. Anti-aging without any irritation.', story: c('SNAIL MUCIN ESSENCE — K-BEAUTY SECRET', ['Repairs skin cells','Deep hydration','Anti-aging','Zero irritation'], 'Apply after toner, before serum. Pat gently to absorb.'), price_pkr: 6200, price_usd: 22 },
    { name: 'Vitamin C + E Brightener',     slug: 'vit-c-e-brightener',       description: '20% vitamin C with vitamin E and ferulic acid — the gold standard brightening serum. Morning glow guaranteed.', story: c('VITAMIN C + E — GLOW SERUM', ['Maximum brightening','Antioxidant protection','Fades dark spots','Glow guaranteed'], 'Apply 4-5 drops every morning. Follow with SPF.'), price_pkr: 7800, price_usd: 28 },
    { name: 'Retinol 1% Night Cream',       slug: 'retinol-1-night-cream',    description: 'Maximum strength 1% retinol in a cushioning cream base. Eliminates fine lines and wrinkles overnight. The gold standard anti-aging.', story: c('RETINOL 1% NIGHT CREAM — GOLD STANDARD', ['Maximum anti-aging','Eliminates fine lines','Smooths texture','Overnight renewal'], 'Apply pea-sized amount every other evening. Use SPF daily.'), price_pkr: 9800, price_usd: 35 },
    { name: 'Toning Face Mist',             slug: 'toning-face-mist',         description: 'Hyaluronic acid + rose water face mist that refreshes, sets makeup, and boosts hydration throughout the day. Sovereign freshness.', story: c('TONING FACE MIST — REFRESH & SET', ['Refreshes instantly','Sets makeup','Boosts hydration','All-day use'], 'Spray 20cm from face with eyes closed. Morning and afternoon.'), price_pkr: 3200, price_usd: 11 },
    // Trendy Color Makeup (15)
    { name: 'Glass Skin Foundation',        slug: 'glass-skin-foundation',    description: 'Ultra-dewy glass-finish liquid foundation with SPF 30 and hyaluronic acid. The K-beauty glass skin look in one bottle.', story: c('GLASS SKIN FOUNDATION — K-BEAUTY GLOW', ['Glass skin effect','SPF 30','Hyaluronic acid blend','24 shades'], 'Dot 5 points on face, blend with damp sponge.'), price_pkr: 8500, price_usd: 30 },
    { name: 'Blurring Primer SPF 20',       slug: 'blurring-primer-spf20',    description: 'Silicon-free pore-blurring primer with SPF 20 that smooths, perfects, and primes for 12-hour wear.', story: c('BLURRING PRIMER — PORE-FREE CANVAS', ['Blurs pores','SPF 20','12-hour wear','Silicon-free'], 'Apply to clean skin before foundation.'), price_pkr: 5200, price_usd: 18 },
    { name: 'Cushion Foundation Compact',   slug: 'cushion-foundation-compact', description: 'Korean cushion compact foundation with natural-glow finish. SPF 50, lightweight, buildable coverage with free refill.', story: c('CUSHION FOUNDATION — NATURAL GLOW', ['SPF 50','Natural glow finish','Buildable coverage','Refill included'], 'Dab applicator into cushion. Press onto skin, build up.'), price_pkr: 9200, price_usd: 33 },
    { name: 'Cream Contour & Highlight',    slug: 'cream-contour-highlight',  description: 'Cream contouring stick with highlight. Buildable, blendable, long-lasting. Sculpt and illuminate like a professional.', story: c('CREAM CONTOUR — SCULPT & GLOW', ['Easy to blend','Buildable formula','Long-lasting','Professional result'], 'Apply dark shade to hollows, highlight to high points. Blend.'), price_pkr: 5800, price_usd: 21 },
    { name: 'Glossy Lip Treatment',         slug: 'glossy-lip-treatment',     description: 'Plumping glossy lip treatment with peptides, hyaluronic acid, and vitamin E. Therapeutic luxury for perfect lips.', story: c('GLOSSY LIP TREATMENT — PERFECT LIPS', ['Plumps lips','Glossy finish','Therapeutic formula','5 shades'], 'Apply as desired. Layer over lipstick for ultimate gloss.'), price_pkr: 4200, price_usd: 15 },
    { name: 'Satin Blush Palette',          slug: 'satin-blush-palette',      description: '6 satin-finish blush shades from nude-pink to deep coral. Buildable, long-wearing, and incredibly flattering.', story: c('SATIN BLUSH PALETTE — 6 SHADES', ['6 flattering shades','Satin finish','Buildable color','Long-wearing'], 'Swirl brush in desired shade. Apply to apples of cheeks.'), price_pkr: 6800, price_usd: 24 },
    { name: 'Graphic Liner Duo',            slug: 'graphic-liner-duo',        description: 'Two-ended liner for creative graphic eye looks — one black felt tip, one white gel liner. Trendy artistry made easy.', story: c('GRAPHIC LINER DUO — CREATIVE ARTISTRY', ['Felt tip precision','Gel white liner','Waterproof formula','Trendy graphics'], 'Use black for graphic lines, white for highlights.'), price_pkr: 4500, price_usd: 16 },
    { name: 'Brow Pomade & Soap',           slug: 'brow-pomade-soap',         description: 'Two-in-one brow pomade and brow soap. Fill sparse brows with precision and set with soap-brow technique.', story: c('BROW POMADE & SOAP — PERFECT ARCHES', ['Fill sparse brows','Soap-brow technique','Waterproof hold','Natural finish'], 'Use spoolie on soap first for soap-brow. Fill with pomade.'), price_pkr: 3800, price_usd: 14 },
    { name: 'Lash Glue Liner',              slug: 'lash-glue-liner',          description: 'Revolutionary 2-in-1 liner and lash adhesive. Apply liner, press on lashes — no separate glue needed. Game-changing.', story: c('LASH GLUE LINER — NO GLUE NEEDED', ['No separate glue','Strong hold 24h','Black liner finish','Easy application'], 'Apply along lash line, wait 30s, press lashes firmly.'), price_pkr: 4800, price_usd: 17 },
    { name: 'Ombre Lip Kit',                slug: 'ombre-lip-kit',            description: 'Complete ombre lip kit with liner, two complementary liquid lipsticks, and a gloss for a professional gradient lip effect.', story: c('OMBRE LIP KIT — GRADIENT PERFECTION', ['Complete lip kit','2 liquid lipsticks','Gradient technique','Gloss finish'], 'Apply darker shade to outer corners, lighter to centre.'), price_pkr: 6500, price_usd: 23 },
    { name: 'HD Powder Compact',            slug: 'hd-powder-compact',        description: 'Ultra-fine HD setting powder that blurs imperfections, controls shine, and sets makeup for 16-hour wear. Camera-ready.', story: c('HD POWDER — CAMERA-READY', ['16-hour setting','Blurs imperfections','Zero flashback','All skin tones'], 'Dust over foundation with large fluffy brush.'), price_pkr: 5500, price_usd: 20 },
    { name: 'Gradient Eyeshadow Quad',      slug: 'gradient-eyeshadow-quad',  description: '4-shade gradient quad pre-designed for foolproof eye looks. Matte to shimmer in one progressive palette.', story: c('GRADIENT EYESHADOW QUAD — FOOLPROOF', ['4-step gradient','Matte to shimmer','Zero fallout','All-day wear'], 'Apply matte to lid, shimmer to centre, dark to crease, highlight to brow.'), price_pkr: 5800, price_usd: 21 },
    { name: 'Vinyl Lip Gloss',              slug: 'vinyl-lip-gloss',          description: 'Non-sticky high-gloss vinyl lip gloss with plumping peptides. The wettest, shiniest lip look with serious moisture.', story: c('VINYL LIP GLOSS — WET LOOK', ['Non-sticky formula','High-vinyl shine','Plumping peptides','8 shades'], 'Apply directly to lips or over lipstick.'), price_pkr: 3600, price_usd: 13 },
    { name: 'Laminated Brow Gel',           slug: 'laminated-brow-gel',       description: 'Soap-brow alternative — clear or tinted laminating brow gel that sets hairs upward for the feathered, laminated brow trend.', story: c('LAMINATED BROW GEL — FEATHERED TREND', ['Laminated brow effect','Clear or tinted','All-day hold','Flexible finish'], 'Brush brow hairs upward with spoolie. Allow to set 30s.'), price_pkr: 3900, price_usd: 14 },
    { name: 'Monochrome Makeup Set',        slug: 'monochrome-makeup-set',    description: 'Complete monochrome makeup kit — matching blush, eyeshadow, and lip colour in one cohesive shade family for a perfectly coordinated look.', story: c('MONOCHROME SET — COORDINATED BEAUTY', ['3-piece set','Matching shades','Eye, cheek, lip','Easy coordination'], 'Use eyeshadow on lid, blush on cheeks, lip on lips.'), price_pkr: 8800, price_usd: 31 },
    // Professional Treatments (15)
    { name: 'Chemical Peel Kit 30%',        slug: 'chemical-peel-kit',        description: '30% glycolic acid professional-strength chemical peel kit with neutralizer. Resurfaces, brightens, and renews in 5 minutes.', story: c('CHEMICAL PEEL 30% — PROFESSIONAL RENEW', ['Professional strength','Resurfaces skin','5-minute treatment','Includes neutralizer'], 'Apply to clean skin. Leave 3-5 min. Neutralize and rinse.'), price_pkr: 7800, price_usd: 28 },
    { name: 'Hyaluron Ampoule Set',         slug: 'hyaluron-ampoule-set',     description: '7-day hyaluronic acid ampoule treatment set for intensive hydration therapy. Each ampoule targets a different hydration layer.', story: c('HYALURON AMPOULE SET — 7-DAY THERAPY', ['7-day treatment','Multi-layer hydration','Intensive therapy','Anti-aging'], 'Apply 1 ampoule per day. Pat gently to absorb.'), price_pkr: 9500, price_usd: 34 },
    { name: 'Collagen Eye Mask Set',        slug: 'collagen-eye-mask-set',    description: 'Pack of 30 collagen + gold hydrogel eye masks. Eliminates puffiness and dark circles. Regular use firms and brightens eye area.', story: c('COLLAGEN EYE MASKS — 30 PACK', ['30-treatment pack','Eliminates puffiness','Gold and collagen','Firms eye area'], 'Apply cold masks under eyes for 20 minutes, 3x per week.'), price_pkr: 5500, price_usd: 20 },
    { name: 'LED Face Mask Red Light',      slug: 'led-face-mask',            description: 'Professional-grade red LED face mask with 660nm wavelength. Stimulates collagen production, reduces fine lines, and heals acne.', story: c('LED RED LIGHT FACE MASK — COLLAGEN BOOST', ['660nm red light','Stimulates collagen','Reduces acne','10-min treatment'], 'Use on clean face for 10 minutes, 5x per week.'), price_pkr: 15500, price_usd: 55 },
    { name: 'Vitamin C Brightening Kit',    slug: 'vitamin-c-kit',            description: 'Complete vitamin C routine: cleanser, serum, moisturizer, and SPF — the complete brightening protocol for sovereign skin.', story: c('VITAMIN C KIT — COMPLETE PROTOCOL', ['4-piece protocol','Morning routine','Maximum brightening','Includes SPF'], 'Use all 4 steps every morning for best results.'), price_pkr: 18500, price_usd: 66 },
    { name: 'Dermaplaning Tool Kit',        slug: 'dermaplaning-kit',         description: 'Professional dermaplaning kit with 10 medical-grade blades. Removes dead skin and peach fuzz, allows perfect product absorption.', story: c('DERMAPLANING KIT — PROFESSIONAL SMOOTH', ['10 blades included','Removes peach fuzz','Perfect absorption','Professional grade'], 'Use on dry skin at 45° angle. One use per blade.'), price_pkr: 5200, price_usd: 18 },
    { name: 'Blackhead Extraction Serum',   slug: 'blackhead-extraction-serum',description: 'BHA + green tea extraction serum that dissolves blackheads from the inside without squeezing. No damage, no scarring.', story: c('BLACKHEAD SERUM — NO SQUEEZE', ['Dissolves blackheads','No squeezing needed','No scarring','BHA formula'], 'Apply to nose and chin daily. Results in 2-4 weeks.'), price_pkr: 4200, price_usd: 15 },
    { name: 'Pro Gua Sha + Roller Set',     slug: 'gua-sha-roller-set',       description: 'Jade roller + rose quartz gua sha duo. Reduces puffiness, sculpts face, drains lymphatic fluid, and boosts serum absorption.', story: c('GUA SHA + ROLLER SET — SCULPT & DRAIN', ['Reduces puffiness','Sculpts jawline','Lymphatic drainage','Boosts absorption'], 'Use cold on clean face after serum. Always use upward strokes.'), price_pkr: 3800, price_usd: 14 },
    { name: 'Lactic Acid 10% Serum',        slug: 'lactic-acid-serum',        description: 'Gentle yet effective lactic acid serum with ceramides. Exfoliates, brightens, and intensely hydrates simultaneously.', story: c('LACTIC ACID 10% — GENTLE EXFOLIANT', ['Exfoliates gently','Brightens skin','Hydrates simultaneously','Ceramide-enriched'], 'Apply every other evening to clean skin.'), price_pkr: 5800, price_usd: 21 },
    { name: 'Microcurrent Face Massager',   slug: 'microcurrent-massager',    description: 'Portable microcurrent face massager that tones facial muscles, lifts sagging areas, and enhances product penetration.', story: c('MICROCURRENT MASSAGER — NON-INVASIVE LIFT', ['Tones muscles','Lifts and firms','Enhances absorption','Portable device'], 'Use with conducting gel on clean face for 5 minutes daily.'), price_pkr: 12500, price_usd: 44 },
    { name: 'Salicylic Face Wash Foam',     slug: 'salicylic-face-wash-foam', description: 'Foaming 2% salicylic face wash with niacinamide. Clears breakouts, controls oil, and prevents new blemishes.', story: c('SALICYLIC FOAM WASH — CLEAR SKIN', ['Clears breakouts','Controls oil','Prevents blemishes','Niacinamide blend'], 'Lather on wet face for 60 seconds, rinse thoroughly.'), price_pkr: 3900, price_usd: 14 },
    { name: 'Anti-Aging Face Mask Set',     slug: 'anti-aging-mask-set',      description: '5-mask anti-aging treatment set targeting fine lines, lifting, brightening, firming, and deep hydration in 5 sessions.', story: c('ANTI-AGING MASK SET — 5 TREATMENTS', ['5 targeted treatments','Lifts and firms','Brightens complexion','Deep hydration'], 'Use one mask per session, 2x per week.'), price_pkr: 6800, price_usd: 24 },
    { name: 'Professional Brush Set',       slug: 'professional-brush-set',   description: 'Complete 16-piece vegan makeup brush set with synthetic fibres. Foundation, contour, blending, and detail brushes for professional results.', story: c('PROFESSIONAL BRUSH SET — 16 PIECES', ['16 brushes','Vegan synthetic','All techniques','Travel case'], 'Clean brushes weekly with brush cleaner.'), price_pkr: 8200, price_usd: 29 },
    { name: 'Vitamin B3 Skin Booster',      slug: 'vitamin-b3-booster',       description: '20% niacinamide + zinc serum. Controls sebum, fades dark spots, minimizes pores, and strengthens the skin barrier.', story: c('VITAMIN B3 BOOSTER — MULTI-TASKER', ['Controls sebum','Fades dark spots','Minimizes pores','Strengthens barrier'], 'Apply 4-5 drops to face morning and evening.'), price_pkr: 5500, price_usd: 20 },
    { name: 'Collagen Firming Neck Cream',  slug: 'neck-firming-cream',       description: 'Targeted neck and décolletage firming cream with retinol and peptides. Lifts, tightens, and erases neck lines.', story: c('NECK FIRMING CREAM — LIFT & TIGHTEN', ['Targets neck and chest','Retinol and peptides','Lifts sagging','Erases lines'], 'Apply upward strokes to neck and chest daily.'), price_pkr: 7500, price_usd: 27 },
  ]

  // ── JEWELRY ────────────────────────────────────────────────────────────────
  // Male Jewelry (20) — Modern Aesthetics + Structural Metals
  // Sub: Streetwear Links + Minimalist Accents
  const jewMale = [
    // Streetwear Links (10)
    { name: 'Thick Figaro Chain Gold',      slug: 'thick-figaro-chain-gold',  description: 'Heavy 12mm figaro link chain in 18K gold-plated stainless steel. The iconic streetwear chain for ultimate visual dominance.', story: j('FIGARO CHAIN GOLD — STREETWEAR ICON', '18K Gold Plated Stainless Steel 316L', '12mm width, 24 inches. Box clasp with safety lock.'), price_pkr: 32000, price_usd: 113 },
    { name: 'Silver Franco Chain',          slug: 'silver-franco-chain',      description: '8mm diamond-cut franco chain in polished sterling silver. Brilliant faceted links that catch light from every angle.', story: j('SILVER FRANCO CHAIN — BRILLIANT LINKS', '925 Sterling Silver', '8mm diamond-cut franco links, 24 inches. Lobster clasp.'), price_pkr: 22000, price_usd: 78 },
    { name: 'Black Steel Wheat Chain',      slug: 'black-steel-wheat-chain',  description: 'Matte black wheat chain in gunmetal-coated stainless steel. Understated strength for the streetwear sovereign.', story: j('BLACK WHEAT CHAIN — UNDERSTATED STRENGTH', 'Gunmetal Coated Stainless Steel 316L', '6mm matte wheat link, 22 inches. Lobster clasp.'), price_pkr: 14500, price_usd: 51 },
    { name: 'Gold Rope Chain Thick',        slug: 'gold-rope-chain-thick',    description: '10mm twisted rope chain in 18K gold-plated brass. Classic luxury streetwear chain with a twisted DNA structure.', story: j('GOLD ROPE CHAIN — CLASSIC STREETWEAR', '18K Gold Plated Brass', '10mm twisted rope, 24 inches. Lobster clasp.'), price_pkr: 24000, price_usd: 85 },
    { name: 'Ball Chain Layering Set',      slug: 'ball-chain-layering',      description: 'Set of 3 ball chains in silver, gold, and gunmetal at 18", 20", 22". The complete streetwear layering starter set.', story: j('BALL CHAIN SET — LAYER UP', 'Stainless Steel 316L in 3 finishes', 'Set of 3: 18", 20", 22". 3mm ball diameter. Lobster clasps.'), price_pkr: 9500, price_usd: 34 },
    { name: 'Cross Pendant Chain',          slug: 'cross-pendant-chain',      description: 'Bold 35mm cross pendant on a 6mm box chain. High-polish 18K gold finish. The ultimate statement streetwear pendant.', story: j('CROSS PENDANT — STATEMENT STREETWEAR', '18K Gold Plated Stainless Steel', '35mm cross pendant, 6mm box chain, 24 inches.'), price_pkr: 16500, price_usd: 58 },
    { name: 'Iced Out Pendant Cuban',       slug: 'iced-out-pendant-cuban',   description: 'CZ-encrusted geometric pendant on a 10mm Cuban link chain. Iced out aesthetic for the sovereign streetwear connoisseur.', story: j('ICED OUT PENDANT — FROZEN AESTHETIC', '18K Gold Plated Brass with CZ Stones', '25mm pendant, 10mm Cuban chain, 24 inches.'), price_pkr: 28000, price_usd: 99 },
    { name: 'Chunky Box Chain Silver',      slug: 'chunky-box-chain-silver',  description: 'Heavy 12mm box chain in brushed sterling silver. The silver alternative to the classic Cuban. Weighty, powerful, sovereign.', story: j('CHUNKY BOX CHAIN — SILVER POWER', '925 Sterling Silver', '12mm box chain, 24 inches. Box clasp with safety lock.'), price_pkr: 26000, price_usd: 92 },
    { name: 'Dog Tag Chain Set',            slug: 'dog-tag-chain-set-male',   description: 'Military dog tag on a 6mm ball chain. Custom engravable — initials, coordinates, or date. The original masculine pendant.', story: j('DOG TAG SET — CUSTOM MILITARY', 'Stainless Steel 316L', '45mm × 27mm tag. Ball chain, 24 inches. Laser engrave 3 lines.'), price_pkr: 12500, price_usd: 44 },
    { name: 'Oversized Link Bracelet',      slug: 'oversized-link-bracelet',  description: 'Chunky 14mm Cuban link bracelet in 18K gold plate. Matches the iconic Cuban chain for complete streetwear coordination.', story: j('OVERSIZED CUBAN BRACELET — MATCH UP', '18K Gold Plated Stainless Steel 316L', '14mm links, 8 inches, box clasp with safety.'), price_pkr: 18500, price_usd: 65 },
    // Minimalist Accents (10)
    { name: 'Thin Satellite Chain',         slug: 'thin-satellite-chain-male',description: '1.5mm satellite chain with tiny beads in gold or silver. The ultimate minimalist daily chain — nearly invisible luxury.', story: j('SATELLITE CHAIN — MINIMALIST LUXURY', '18K Gold Plated or 925 Silver', '1.5mm chain with 2mm bead stations, 20 inches.'), price_pkr: 8500, price_usd: 30 },
    { name: 'Plain Band Set Stack',         slug: 'plain-band-stack-male',    description: 'Set of 3 ultra-thin 2mm stainless steel bands in silver, gold, and black for the minimalist stacking aesthetic.', story: j('PLAIN BAND STACK — MINIMALIST', 'Stainless Steel 316L in 3 finishes', 'Set of 3: 2mm width. Sizes 7-13. Comfort-fit curvature.'), price_pkr: 6500, price_usd: 23 },
    { name: 'Subtle Cross Ring',            slug: 'subtle-cross-ring',        description: 'Minimalist 3mm band with a small flush-set cross detail. Elegant religious statement in understated luxury.', story: j('SUBTLE CROSS RING — ELEGANT FAITH', 'Sterling Silver or 18K Gold Plated', '3mm width, flush-set cross. Sizes 7-13.'), price_pkr: 7500, price_usd: 27 },
    { name: 'Thin Bead Bracelet Pack',      slug: 'thin-bead-bracelet-pack',  description: 'Pack of 4 minimalist bead bracelets — onyx, lava, tiger eye, and wood. Stack together for a natural, grounded aesthetic.', story: j('BEAD BRACELET PACK — NATURAL STACK', 'Natural Semi-Precious Stones', 'Pack of 4. 4mm beads. Stretch cord. One size fits most.'), price_pkr: 8200, price_usd: 29 },
    { name: 'Open Circle Pendant',          slug: 'open-circle-pendant',      description: 'Simple open circle pendant on a thin 1mm chain. Geometric minimalism elevated to sovereign luxury.', story: j('OPEN CIRCLE PENDANT — GEOMETRIC MINIMAL', '18K Gold or 925 Silver', '15mm circle pendant, 1.5mm chain, 18 inches.'), price_pkr: 9800, price_usd: 35 },
    { name: 'Slim Cuff with Detail',        slug: 'slim-cuff-with-detail',    description: '5mm slim metal cuff with a single engraved accent line. The minimalist male bracelet — clean, architectural, sovereign.', story: j('SLIM CUFF WITH DETAIL — ARCHITECTURAL', 'Sterling Silver or Brass with Plating', '5mm width. Open-ended. One size fits most.'), price_pkr: 8500, price_usd: 30 },
    { name: 'Ear Stud Set 4 Pairs',         slug: 'ear-stud-set-4-pairs',     description: '4 pairs of minimalist ear studs — ball, flat disc, triangle, and bar. The complete modern man\'s ear wardrobe in one set.', story: j('EAR STUD SET 4 PAIRS — COMPLETE', '316L Stainless Steel or Silver', '4 pairs: 4mm ball, 5mm disc, 4mm triangle, 2mm×6mm bar.'), price_pkr: 5800, price_usd: 21 },
    { name: 'Herringbone Flat Chain',       slug: 'herringbone-flat-chain',   description: 'Ultra-flat 4mm herringbone chain — liquid-like movement, mirror shine. The most elegant minimalist chain for modern men.', story: j('HERRINGBONE CHAIN — LIQUID ELEGANCE', '925 Silver or 18K Gold Plated', '4mm herringbone, 20 inches. Lobster clasp.'), price_pkr: 15500, price_usd: 55 },
    { name: 'Ring With Brushed Centre',     slug: 'ring-brushed-centre',      description: '8mm band ring with a brushed steel centre flanked by polished edges. The most sophisticated minimalist ring design.', story: j('RING BRUSHED CENTRE — DUAL TEXTURE', 'Stainless Steel 316L', '8mm width. Brushed centre, mirror-polish edges. Sizes 8-14.'), price_pkr: 7200, price_usd: 26 },
    { name: 'Anchor Chain Bracelet',        slug: 'anchor-chain-bracelet',    description: 'Classic nautical anchor chain bracelet in 18K gold or silver. Lightweight, elegant, and sovereignly masculine.', story: j('ANCHOR CHAIN BRACELET — NAUTICAL ICON', '18K Gold Plated or 925 Silver', '4mm anchor links, 7.5 inches. Lobster clasp.'), price_pkr: 10500, price_usd: 37 },
  ]

  // Female Jewelry (30) — High Fashion + Classic Luxury + Daily Elegance
  // Sub: Pearls + Fine Crystals + Statement Essentials
  const jewFemale = [
    // Pearls (10)
    { name: 'Classic Pearl Strand',         slug: 'classic-pearl-strand',     description: 'Timeless freshwater pearl strand, 18 inches with 7-8mm AAA pearls on knotted silk. The epitome of classic feminine luxury.', story: j('CLASSIC PEARL STRAND — TIMELESS', 'AAA Freshwater Pearls on Silk', '7-8mm, 18 inches on knotted silk. Gold-filled lobster clasp.'), price_pkr: 48000, price_usd: 170 },
    { name: 'Pearl Huggie Hoops',           slug: 'pearl-huggie-hoops',       description: '14K gold huggie hoop earrings with single 8mm freshwater pearl drop. Modern pearl elegance for daily sovereign wear.', story: j('PEARL HUGGIE HOOPS — MODERN PEARLS', '14K Gold Filled with Freshwater Pearl', '12mm huggie hoop, 8mm pearl drop. Click-close.'), price_pkr: 22000, price_usd: 78 },
    { name: 'Baroque Pearl Necklace',       slug: 'baroque-pearl-necklace',   description: 'Freeform baroque freshwater pearls on a gold-filled chain. Artisan, organic beauty — no two necklaces are identical.', story: j('BAROQUE PEARL NECKLACE — ARTISAN', 'Baroque Freshwater Pearls with Gold Fill', 'Mixed 12-15mm baroque pearls, 18 inches. Unique organic shapes.'), price_pkr: 38000, price_usd: 135 },
    { name: 'Pearl Ear Studs Classic',      slug: 'pearl-ear-studs-classic',  description: '8mm single pearl studs in 18K white or yellow gold setting. The quintessential piece for every woman\'s jewelry wardrobe.', story: j('PEARL STUDS CLASSIC — QUINTESSENTIAL', '18K Gold with AAA Freshwater Pearl', '8mm pearl, push-back post. White or yellow gold option.'), price_pkr: 18500, price_usd: 65 },
    { name: 'Pearl Bracelet Strand',        slug: 'pearl-bracelet-strand',    description: 'Single strand freshwater pearl bracelet with gold-filled clasp. Elegant, wearable luxury for every occasion.', story: j('PEARL BRACELET STRAND — ELEGANT', 'Freshwater Pearls with Gold Fill', '7mm pearls, 7 inches. Gold-filled box clasp.'), price_pkr: 19500, price_usd: 69 },
    { name: 'Pearl Y-Necklace',             slug: 'pearl-y-necklace',         description: 'Delicate Y-drop necklace with a single 10mm South Sea pearl drop. Modern, structural, and sovereignly elegant.', story: j('PEARL Y-NECKLACE — MODERN STRUCTURE', '18K Gold Chain with South Sea Pearl', '18-inch chain with Y-drop, 10mm pearl drop. Total length 22 inches.'), price_pkr: 35000, price_usd: 124 },
    { name: 'Freshwater Pearl Ring',        slug: 'freshwater-pearl-ring',    description: '12mm baroque pearl set in a brushed 18K gold band. Wearable, modern pearl jewellery that suits every look.', story: j('FRESHWATER PEARL RING — WEARABLE LUXURY', '18K Gold with Baroque Pearl', '12mm oval baroque pearl. Open-band design. Sizes 5-10.'), price_pkr: 16500, price_usd: 58 },
    { name: 'Pearl Ear Cuff Chain',         slug: 'pearl-ear-cuff-chain',     description: 'Gold ear cuff connected by a delicate chain to a pearl drop stud. Effortless editorial jewellery for the sovereign modern woman.', story: j('PEARL EAR CUFF CHAIN — EDITORIAL', '18K Gold Filled with Freshwater Pearl', 'Ear cuff + chain + 7mm pearl stud. No piercing for cuff.'), price_pkr: 14500, price_usd: 51 },
    { name: 'Pearl Station Bracelet',       slug: 'pearl-station-bracelet',   description: 'Delicate gold chain with 5 pearl stations. The modern pearl bracelet — minimalist, elevated, and sovereignly feminine.', story: j('PEARL STATION BRACELET — MINIMALIST', '18K Gold Filled with Freshwater Pearls', '5 × 7mm pearl stations, 7.5-inch chain. Lobster clasp.'), price_pkr: 12500, price_usd: 44 },
    { name: 'Multi-Layer Pearl Set',        slug: 'multi-layer-pearl-set',    description: 'Three-layer pearl and gold chain necklace set — different lengths, textures, and pearl sizes pre-arranged for a curated layered look.', story: j('MULTI-LAYER PEARL SET — CURATED LAYERS', '18K Gold Filled with Mixed Freshwater Pearls', '3 necklaces: 16", 18", 20". Baroque and round pearl mix.'), price_pkr: 28000, price_usd: 99 },
    // Fine Crystals (10)
    { name: 'Crystal Chandelier Earrings',  slug: 'crystal-chandelier-earrings', description: 'Statement chandelier earrings with cascading Swarovski crystals in gold tone. For weddings, galas, and sovereign occasions.', story: j('CRYSTAL CHANDELIER — STATEMENT EVENT', '18K Gold Plated Brass with Swarovski', 'Three-tier drop, 65mm length. Shepherd hook closure. 48 crystals.'), price_pkr: 28000, price_usd: 99 },
    { name: 'Crystal Tennis Necklace',      slug: 'crystal-tennis-necklace',  description: 'Continuous CZ crystal line necklace in silver or gold. 4mm stones, 16 inches — the ultimate high-fashion sovereign statement.', story: j('CRYSTAL TENNIS NECKLACE — HIGH FASHION', '18K Gold or Silver Plated with 4mm CZ', '4mm CZ stones, 16 inches. Box clasp with safety.'), price_pkr: 22000, price_usd: 78 },
    { name: 'Sapphire CZ Statement Ring',   slug: 'sapphire-cz-statement-ring', description: 'Royal blue CZ sapphire-inspired statement ring in 18K white gold. 12ct equivalent emerald-cut stone. Bold, regal, sovereign.', story: j('SAPPHIRE CZ RING — ROYAL STATEMENT', '18K White Gold Plated Brass with CZ', '12mm × 15mm emerald-cut blue CZ. Prong setting. Sizes 5-10.'), price_pkr: 18500, price_usd: 65 },
    { name: 'Crystal Stud Earring Pack',    slug: 'crystal-stud-pack',        description: '6-pair Swarovski crystal stud set — clear, pink, sapphire, emerald, amethyst, and topaz. Complete ear wardrobe in one box.', story: j('CRYSTAL STUD PACK — 6 PAIRS', '18K Gold Plated with Swarovski Crystals', '6 × 6mm crystal studs. Push-back posts. Complete colour wardrobe.'), price_pkr: 12500, price_usd: 44 },
    { name: 'Rhinestone Body Chain',        slug: 'rhinestone-body-chain',    description: 'Body jewelry statement — crystal-encrusted body chain that drapes across the shoulder or waist. High-fashion sovereign confidence.', story: j('RHINESTONE BODY CHAIN — HIGH FASHION', 'Gold Plated Brass with Rhinestones', 'Adjustable 28-36 inches. Lobster clasp. 1200+ crystals.'), price_pkr: 15500, price_usd: 55 },
    { name: 'Crystal Pavé Bangle',          slug: 'crystal-pave-bangle',      description: 'Fully pavé-set crystal bangle bracelet with a hidden box clasp. Over 150 crystals creating an unbroken circle of light.', story: j('CRYSTAL PAVÉ BANGLE — CIRCLE OF LIGHT', '18K Gold Plated Brass with Cubic Zirconia', '8mm width, 65mm diameter. Hidden box clasp. 150+ CZ stones.'), price_pkr: 19500, price_usd: 69 },
    { name: 'Aurora Crystal Choker',        slug: 'aurora-crystal-choker',    description: 'Aurora borealis crystal choker necklace with iridescent multicolour crystals. High fashion editorial jewellery at its finest.', story: j('AURORA CRYSTAL CHOKER — EDITORIAL', 'Gold Plated Brass with AB (Aurora Borealis) Crystals', '12mm crystal band, 14-inch choker. Adjustable extender chain.'), price_pkr: 16500, price_usd: 58 },
    { name: 'Crystal Vine Hair Piece',      slug: 'crystal-vine-hair-piece',  description: 'Crystal-studded vine hair accessory — flexible and versatile. Weaves through braids, buns, or loose hair for bridal and evening looks.', story: j('CRYSTAL VINE HAIR PIECE — BRIDAL', 'Gold Plated Brass with CZ Crystals', 'Flexible 30cm wire. 45 CZ stones. Push pins included.'), price_pkr: 9500, price_usd: 34 },
    { name: 'Twin Drop Crystal Earrings',   slug: 'twin-drop-crystal-earrings', description: 'Twin teardrop crystal earrings — two connected drops in a diagonal fan arrangement. Modern, architectural, sovereignly feminine.', story: j('TWIN DROP CRYSTALS — MODERN ARCHITECTURE', '18K Gold Plated with Clear CZ', '2 × teardrop CZ drops, 40mm total length. Shepherd hook.'), price_pkr: 11500, price_usd: 41 },
    { name: 'Crystal Crown Tiara',          slug: 'crystal-crown-tiara',      description: 'Bridal and event crystal tiara with fine-point crown design. Fully adjustable, 120 CZ crystals. The sovereign\'s crown.', story: j('CRYSTAL CROWN TIARA — THE SOVEREIGN CROWN', 'Silver or Gold Plated Brass with CZ', 'Height: 40mm. Adjustable 140-180mm. 120 CZ stones.'), price_pkr: 18500, price_usd: 65 },
    // Statement Essentials (10)
    { name: 'Thick Hoop Earrings Large',    slug: 'thick-hoop-large',         description: '45mm thick 5mm hoop earrings in 18K gold. Bold, modern, and sovereignly statement. The essential thick-hoop look.', story: j('THICK HOOP LARGE — BOLD STATEMENT', '18K Gold Plated 925 Silver', '5mm tube, 45mm diameter. Click-close.'), price_pkr: 15500, price_usd: 55 },
    { name: 'Chain Link Statement Necklace', slug: 'chain-link-statement',    description: 'Chunky wide paperclip chain statement necklace in 18K gold. 15mm link width, 18 inches. The boldest sovereign fashion statement.', story: j('CHAIN LINK STATEMENT — BOLD FASHION', '18K Gold Plated Stainless Steel', '15mm paperclip links, 18 inches. Lobster clasp.'), price_pkr: 19500, price_usd: 69 },
    { name: 'Coin Charm Bracelet',          slug: 'coin-charm-bracelet',      description: '5 gold coin charms (moon, star, sun, eye, heart) on an 18K gold chain bracelet. Meaningful symbols for the sovereign woman.', story: j('COIN CHARM BRACELET — MEANINGFUL SYMBOLS', '18K Gold Plated Silver', '5 × 12mm coin charms. 7.5-inch chain. Lobster clasp.'), price_pkr: 14500, price_usd: 51 },
    { name: 'Snake Chain Necklace Set',     slug: 'snake-chain-set-female',   description: 'Set of 3 ultra-smooth snake chains in gold — 16", 18", and 20". Liquid-silk feel for the most elegant layered look.', story: j('SNAKE CHAIN SET — LIQUID ELEGANCE', '18K Gold Plated Silver', '3 × snake chains: 16", 18", 20". 1.5mm diameter. Lobster clasps.'), price_pkr: 16500, price_usd: 58 },
    { name: 'Lock Pendant Necklace',        slug: 'lock-pendant-necklace',    description: 'Classic padlock pendant on a 3mm box chain. Iconic fashion jewelry that has graced every global runway.', story: j('LOCK PENDANT — FASHION ICON', '18K Gold Plated Brass', '20mm padlock pendant, 3mm box chain, 18 inches.'), price_pkr: 12500, price_usd: 44 },
    { name: 'Initial Letter Necklace',      slug: 'initial-letter-necklace',  description: 'Personalised 18K gold initial letter pendant on a dainty chain. Custom-made for the sovereign woman who wears her identity.', story: j('INITIAL LETTER NECKLACE — PERSONALISED', '18K Gold Plated Silver', '18mm block letter pendant, 1.5mm chain, 18 inches. All 26 letters.'), price_pkr: 10500, price_usd: 37 },
    { name: 'Evil Eye Statement Ring',      slug: 'evil-eye-ring',            description: 'Blue enamel evil eye ring with micro-pavé CZ halo. Bold protection meets bold fashion. The sovereign woman\'s talismanic statement.', story: j('EVIL EYE RING — TALISMAN', '18K Gold Plated Brass with Enamel and CZ', '12mm evil eye stone, CZ halo. Adjustable open band.'), price_pkr: 8500, price_usd: 30 },
    { name: 'Mixed Metal Stack Set',        slug: 'mixed-metal-stack-set',    description: 'Curated set of 6 mixed-metal stacking rings — 2 gold, 2 silver, 2 rose gold. Pre-stacked for a perfectly styled modern look.', story: j('MIXED METAL STACK SET — CURATED', '18K Gold, Silver, and Rose Gold Plated', 'Set of 6 rings: 2mm each. Sizes 5-9. Pre-styled.'), price_pkr: 11500, price_usd: 41 },
    { name: 'Paperclip Chain Anklet',       slug: 'paperclip-chain-anklet',   description: '4mm paperclip link gold anklet. The most on-trend ankle accessory — minimal, modern, and sovereignly fashionable.', story: j('PAPERCLIP ANKLET — ON-TREND', '18K Gold Plated Silver', '4mm paperclip links, 9-11 inch adjustable. Lobster clasp.'), price_pkr: 8500, price_usd: 30 },
    { name: 'Heart Toggle Necklace',        slug: 'heart-toggle-necklace',    description: 'Dainty heart on a curb chain with a toggle bar clasp. Romantic, wearable, and effortlessly feminine every day.', story: j('HEART TOGGLE NECKLACE — ROMANTIC DAILY', '18K Gold Plated Silver', '10mm heart, curb chain 16 inches, toggle closure.'), price_pkr: 9500, price_usd: 34 },
  ]

  // Assign categories, sub_categories, inventory, images
  function build(arr: any[], catId: string, subId: string | null, img: string) {
    return arr.map(p => ({
      ...p,
      main_category_id: catId,
      sub_category_id: subId,
      images: [img],
      is_featured: false,
      is_active: true,
      inventory: Math.floor(Math.random() * 80) + 20,
    }))
  }

  const allProducts = [
    ...build(perfMale,   perfumeId,   maleId,   IMG_PM),
    ...build(perfFemale, perfumeId,   femaleId, IMG_PF),
    ...build(perfUnisex, perfumeId,   unisexId, IMG_PU),
    ...build(cosMale,    cosmeticsId, maleId,   IMG_C),
    ...build(cosFemale,  cosmeticsId, femaleId, IMG_C),
    ...build(jewMale,    jewelryId,   maleId,   IMG_J),
    ...build(jewFemale,  jewelryId,   femaleId, IMG_J),
  ]

  let inserted = 0
  const errors: string[] = []
  for (let i = 0; i < allProducts.length; i += 20) {
    const { data, error } = await supabase.from('products')
      .upsert(allProducts.slice(i, i + 20), { onConflict: 'slug', ignoreDuplicates: false })
      .select('id')
    if (error) errors.push(error.message.slice(0, 80))
    else inserted += data?.length ?? 0
  }

  return NextResponse.json({
    success: errors.length === 0,
    inserted,
    total: allProducts.length,
    breakdown: {
      perfumes: { male: perfMale.length, female: perfFemale.length, unisex: perfUnisex.length, total: perfMale.length+perfFemale.length+perfUnisex.length },
      cosmetics: { male: cosMale.length, female: cosFemale.length, total: cosMale.length+cosFemale.length },
      jewelry: { male: jewMale.length, female: jewFemale.length, total: jewMale.length+jewFemale.length },
    },
    errors: errors.length > 0 ? errors : undefined,
  })
}
