import type { Metadata } from 'next'
import SeoJsonLd from '@/components/SeoJsonLd'
import SovereignInfrastructureHub from '@/components/SovereignInfrastructureHub'
import { sovereignDomains, sovereignFaqs } from '@/lib/sovereign-infrastructure-content'
const url='https://www.shamimforever.com/learn/sovereign-infrastructure'
const description='Explore the Sovereign Infrastructure of Shamim Forever: authenticity systems, private client architecture, boutique operations, digital identity, heritage preservation, privacy, security, global coordination, governance, and long-term luxury continuity.'
export const metadata:Metadata={title:'Sovereign Infrastructure | The Architecture Behind Shamim Forever',description,keywords:['Sovereign Infrastructure','luxury infrastructure','luxury house infrastructure','digital luxury infrastructure','heritage preservation','luxury authentication','private client infrastructure','luxury data privacy','global luxury operations','luxury brand architecture','digital identity infrastructure'],alternates:{canonical:url},robots:{index:true,follow:true},openGraph:{type:'article',url,title:'Sovereign Infrastructure | The Architecture Behind Shamim Forever',description,siteName:'Shamim Forever',images:[{url:'https://www.shamimforever.com/og-heirloom.jpg',width:1200,height:630,alt:'Sovereign Infrastructure at Shamim Forever'}]},twitter:{card:'summary_large_image',title:'Sovereign Infrastructure | Shamim Forever',description,images:['https://www.shamimforever.com/og-heirloom.jpg']}}
const schema=[{'@context':'https://schema.org','@type':'Organization','@id':'https://www.shamimforever.com/#organization',name:'Shamim Forever',url:'https://www.shamimforever.com',description:'A sovereign luxury house connecting craftsmanship, authenticity, heritage, private service, and long-term continuity.',knowsAbout:['luxury infrastructure','authenticity','digital identity','heritage preservation','private client service','privacy architecture','security','governance','resilience']},{'@context':'https://schema.org','@type':'Article','@id':url+'#article',headline:'Sovereign Infrastructure | The Architecture Behind Shamim Forever',description,url,mainEntityOfPage:{'@id':url},author:{'@id':'https://www.shamimforever.com/#organization'},publisher:{'@id':'https://www.shamimforever.com/#organization'},datePublished:'2026-09-08',dateModified:'2026-09-08',inLanguage:'en',about:['luxury infrastructure','digital sovereignty','heritage architecture','private client infrastructure','authenticity systems']},{'@context':'https://schema.org','@type':'WebPage','@id':url+'#webpage',url,name:'Sovereign Infrastructure',isPartOf:{'@id':'https://www.shamimforever.com/#website'},about:{'@id':'https://www.shamimforever.com/#organization'},inLanguage:'en'},{'@context':'https://schema.org','@type':'ItemList','@id':url+'#domains',name:'Sovereign Infrastructure knowledge domains',itemListElement:sovereignDomains.map((d,i)=>({'@type':'ListItem',position:i+1,name:d[1],url:url+'/'+d[0]}))},{'@context':'https://schema.org','@type':'FAQPage','@id':url+'#faq',mainEntity:sovereignFaqs.map(f=>({'@type':'Question',name:f[0],acceptedAnswer:{'@type':'Answer',text:f[1]}}))},{'@context':'https://schema.org','@type':'BreadcrumbList',itemListElement:[{'@type':'ListItem',position:1,name:'Learn',item:'https://www.shamimforever.com/learn'},{'@type':'ListItem',position:2,name:'Sovereign Infrastructure',item:url}]}]
export default function SovereignInfrastructurePage(){return <SeoJsonLd schemas={schema}><SovereignInfrastructureHub/></SeoJsonLd>}
